/**
 * Synthwave '84 — Retro neon pink and cyan, from Synthwave '84. Generated by scripts/generate.mjs from
 * scripts/seeds.json; regenerate with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the eight tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through its
 * ramp references.
 */
import type { FoundationLayer } from "../types";

export default {
  id: "synthwave",
  name: "Synthwave '84",
  tokens: {
    "primary-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "primary-4": {
      colorSpace: "srgb",
      components: [0.13725, 0, 0.1098],
      hex: "#23001c",
    },
    "primary-6": {
      colorSpace: "srgb",
      components: [0.17255, 0, 0.14118],
      hex: "#2c0024",
    },
    "primary-10": {
      colorSpace: "srgb",
      components: [0.23137, 0, 0.18824],
      hex: "#3b0030",
    },
    "primary-12": {
      colorSpace: "srgb",
      components: [0.25882, 0, 0.21176],
      hex: "#420036",
    },
    "primary-17": {
      colorSpace: "srgb",
      components: [0.32941, 0, 0.27059],
      hex: "#540045",
    },
    "primary-20": {
      colorSpace: "srgb",
      components: [0.37255, 0, 0.3098],
      hex: "#5f004f",
    },
    "primary-22": {
      colorSpace: "srgb",
      components: [0.40392, 0, 0.33333],
      hex: "#670055",
    },
    "primary-24": {
      colorSpace: "srgb",
      components: [0.43137, 0, 0.36078],
      hex: "#6e005c",
    },
    "primary-25": {
      colorSpace: "srgb",
      components: [0.44706, 0, 0.37255],
      hex: "#72005f",
    },
    "primary-30": {
      colorSpace: "srgb",
      components: [0.51373, 0.05098, 0.43137],
      hex: "#830d6e",
    },
    "primary-35": {
      colorSpace: "srgb",
      components: [0.57255, 0.12157, 0.47843],
      hex: "#921f7a",
    },
    "primary-40": {
      colorSpace: "srgb",
      components: [0.63137, 0.17647, 0.52941],
      hex: "#a12d87",
    },
    "primary-50": {
      colorSpace: "srgb",
      components: [0.74902, 0.28235, 0.63529],
      hex: "#bf48a2",
    },
    "primary-60": {
      colorSpace: "srgb",
      components: [0.87059, 0.38824, 0.7451],
      hex: "#de63be",
    },
    "primary-70": {
      colorSpace: "srgb",
      components: [0.99608, 0.4902, 0.8549],
      hex: "#fe7dda",
    },
    "primary-80": {
      colorSpace: "srgb",
      components: [1, 0.67843, 0.8902],
      hex: "#ffade3",
    },
    "primary-87": {
      colorSpace: "srgb",
      components: [1, 0.79608, 0.91765],
      hex: "#ffcbea",
    },
    "primary-90": {
      colorSpace: "srgb",
      components: [1, 0.84706, 0.93333],
      hex: "#ffd8ee",
    },
    "primary-92": {
      colorSpace: "srgb",
      components: [1, 0.87843, 0.94118],
      hex: "#ffe0f0",
    },
    "primary-94": {
      colorSpace: "srgb",
      components: [1, 0.9098, 0.95294],
      hex: "#ffe8f3",
    },
    "primary-95": {
      colorSpace: "srgb",
      components: [1, 0.92549, 0.95686],
      hex: "#ffecf4",
    },
    "primary-96": {
      colorSpace: "srgb",
      components: [1, 0.94118, 0.96471],
      hex: "#fff0f6",
    },
    "primary-98": {
      colorSpace: "srgb",
      components: [1, 0.97255, 0.97647],
      hex: "#fff8f9",
    },
    "primary-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "secondary-0": {
      colorSpace: "srgb",
      components: [0, 0, 0],
      hex: "#000000",
    },
    "secondary-4": {
      colorSpace: "srgb",
      components: [0, 0.06667, 0.06667],
      hex: "#001111",
    },
    "secondary-6": {
      colorSpace: "srgb",
      components: [0, 0.0902, 0.08627],
      hex: "#001716",
    },
    "secondary-10": {
      colorSpace: "srgb",
      components: [0, 0.12549, 0.12157],
      hex: "#00201f",
    },
    "secondary-12": {
      colorSpace: "srgb",
      components: [0, 0.14118, 0.14118],
      hex: "#002424",
    },
    "secondary-17": {
      colorSpace: "srgb",
      components: [0, 0.18824, 0.18431],
      hex: "#00302f",
    },
    "secondary-20": {
      colorSpace: "srgb",
      components: [0, 0.21569, 0.21176],
      hex: "#003736",
    },
    "secondary-22": {
      colorSpace: "srgb",
      components: [0, 0.23529, 0.23137],
      hex: "#003c3b",
    },
    "secondary-24": {
      colorSpace: "srgb",
      components: [0, 0.2549, 0.25098],
      hex: "#004140",
    },
    "secondary-25": {
      colorSpace: "srgb",
      components: [0, 0.26275, 0.25882],
      hex: "#004342",
    },
    "secondary-30": {
      colorSpace: "srgb",
      components: [0, 0.31373, 0.3098],
      hex: "#00504f",
    },
    "secondary-35": {
      colorSpace: "srgb",
      components: [0, 0.36078, 0.35686],
      hex: "#005c5b",
    },
    "secondary-40": {
      colorSpace: "srgb",
      components: [0, 0.41569, 0.40784],
      hex: "#006a68",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0, 0.52157, 0.51373],
      hex: "#008583",
    },
    "secondary-60": {
      colorSpace: "srgb",
      components: [0, 0.63137, 0.62353],
      hex: "#00a19f",
    },
    "secondary-70": {
      colorSpace: "srgb",
      components: [0, 0.74902, 0.73725],
      hex: "#00bfbc",
    },
    "secondary-80": {
      colorSpace: "srgb",
      components: [0, 0.86667, 0.8549],
      hex: "#00ddda",
    },
    "secondary-87": {
      colorSpace: "srgb",
      components: [0.14902, 0.94902, 0.93725],
      hex: "#26f2ef",
    },
    "secondary-90": {
      colorSpace: "srgb",
      components: [0.22353, 0.98431, 0.97255],
      hex: "#39fbf8",
    },
    "secondary-92": {
      colorSpace: "srgb",
      components: [0.35294, 1, 0.98824],
      hex: "#5afffc",
    },
    "secondary-94": {
      colorSpace: "srgb",
      components: [0.59608, 1, 0.98824],
      hex: "#98fffc",
    },
    "secondary-95": {
      colorSpace: "srgb",
      components: [0.68235, 1, 0.98824],
      hex: "#aefffc",
    },
    "secondary-96": {
      colorSpace: "srgb",
      components: [0.76078, 1, 0.99216],
      hex: "#c2fffd",
    },
    "secondary-98": {
      colorSpace: "srgb",
      components: [0.8902, 1, 0.99216],
      hex: "#e3fffd",
    },
    "secondary-99": {
      colorSpace: "srgb",
      components: [0.9451, 1, 0.99608],
      hex: "#f1fffe",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "tertiary-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "tertiary-4": {
      colorSpace: "srgb",
      components: [0.07451, 0.0549, 0],
      hex: "#130e00",
    },
    "tertiary-6": {
      colorSpace: "srgb",
      components: [0.09804, 0.07451, 0],
      hex: "#191300",
    },
    "tertiary-10": {
      colorSpace: "srgb",
      components: [0.13333, 0.10588, 0],
      hex: "#221b00",
    },
    "tertiary-12": {
      colorSpace: "srgb",
      components: [0.15294, 0.12157, 0],
      hex: "#271f00",
    },
    "tertiary-17": {
      colorSpace: "srgb",
      components: [0.2, 0.16078, 0],
      hex: "#332900",
    },
    "tertiary-20": {
      colorSpace: "srgb",
      components: [0.22745, 0.18824, 0],
      hex: "#3a3000",
    },
    "tertiary-22": {
      colorSpace: "srgb",
      components: [0.24706, 0.20392, 0],
      hex: "#3f3400",
    },
    "tertiary-24": {
      colorSpace: "srgb",
      components: [0.26667, 0.21961, 0],
      hex: "#443800",
    },
    "tertiary-25": {
      colorSpace: "srgb",
      components: [0.27843, 0.22745, 0],
      hex: "#473a00",
    },
    "tertiary-30": {
      colorSpace: "srgb",
      components: [0.32941, 0.27451, 0],
      hex: "#544600",
    },
    "tertiary-35": {
      colorSpace: "srgb",
      components: [0.38431, 0.31765, 0],
      hex: "#625100",
    },
    "tertiary-40": {
      colorSpace: "srgb",
      components: [0.43922, 0.36471, 0],
      hex: "#705d00",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.54902, 0.45882, 0],
      hex: "#8c7500",
    },
    "tertiary-60": {
      colorSpace: "srgb",
      components: [0.66667, 0.56078, 0.03922],
      hex: "#aa8f0a",
    },
    "tertiary-70": {
      colorSpace: "srgb",
      components: [0.77647, 0.66275, 0.17255],
      hex: "#c6a92c",
    },
    "tertiary-80": {
      colorSpace: "srgb",
      components: [0.8902, 0.77255, 0.27451],
      hex: "#e3c546",
    },
    "tertiary-87": {
      colorSpace: "srgb",
      components: [0.97255, 0.84706, 0.3451],
      hex: "#f8d858",
    },
    "tertiary-90": {
      colorSpace: "srgb",
      components: [1, 0.88235, 0.42745],
      hex: "#ffe16d",
    },
    "tertiary-92": {
      colorSpace: "srgb",
      components: [1, 0.90588, 0.57255],
      hex: "#ffe792",
    },
    "tertiary-94": {
      colorSpace: "srgb",
      components: [1, 0.92941, 0.70196],
      hex: "#ffedb3",
    },
    "tertiary-95": {
      colorSpace: "srgb",
      components: [1, 0.94118, 0.76078],
      hex: "#fff0c2",
    },
    "tertiary-96": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.81961],
      hex: "#fff3d1",
    },
    "tertiary-98": {
      colorSpace: "srgb",
      components: [1, 0.97647, 0.93333],
      hex: "#fff9ee",
    },
    "tertiary-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "error-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "error-4": {
      colorSpace: "srgb",
      components: [0.15294, 0, 0.01176],
      hex: "#270003",
    },
    "error-6": {
      colorSpace: "srgb",
      components: [0.19216, 0, 0.01569],
      hex: "#310004",
    },
    "error-10": {
      colorSpace: "srgb",
      components: [0.2549, 0, 0.02745],
      hex: "#410007",
    },
    "error-12": {
      colorSpace: "srgb",
      components: [0.28235, 0, 0.03137],
      hex: "#480008",
    },
    "error-17": {
      colorSpace: "srgb",
      components: [0.36078, 0, 0.0549],
      hex: "#5c000e",
    },
    "error-20": {
      colorSpace: "srgb",
      components: [0.40784, 0, 0.06667],
      hex: "#680011",
    },
    "error-22": {
      colorSpace: "srgb",
      components: [0.43922, 0, 0.07451],
      hex: "#700013",
    },
    "error-24": {
      colorSpace: "srgb",
      components: [0.47451, 0, 0.08235],
      hex: "#790015",
    },
    "error-25": {
      colorSpace: "srgb",
      components: [0.4902, 0, 0.08627],
      hex: "#7d0016",
    },
    "error-30": {
      colorSpace: "srgb",
      components: [0.57255, 0, 0.1098],
      hex: "#92001c",
    },
    "error-35": {
      colorSpace: "srgb",
      components: [0.66275, 0, 0.13333],
      hex: "#a90022",
    },
    "error-40": {
      colorSpace: "srgb",
      components: [0.74118, 0.03922, 0.16078],
      hex: "#bd0a29",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [0.88627, 0.18039, 0.24706],
      hex: "#e22e3f",
    },
    "error-60": {
      colorSpace: "srgb",
      components: [1, 0.32549, 0.35294],
      hex: "#ff535a",
    },
    "error-70": {
      colorSpace: "srgb",
      components: [1, 0.53333, 0.52941],
      hex: "#ff8887",
    },
    "error-80": {
      colorSpace: "srgb",
      components: [1, 0.70196, 0.69412],
      hex: "#ffb3b1",
    },
    "error-87": {
      colorSpace: "srgb",
      components: [1, 0.80784, 0.8],
      hex: "#ffcecc",
    },
    "error-90": {
      colorSpace: "srgb",
      components: [1, 0.8549, 0.84706],
      hex: "#ffdad8",
    },
    "error-92": {
      colorSpace: "srgb",
      components: [1, 0.88235, 0.87843],
      hex: "#ffe1e0",
    },
    "error-94": {
      colorSpace: "srgb",
      components: [1, 0.91373, 0.90588],
      hex: "#ffe9e7",
    },
    "error-95": {
      colorSpace: "srgb",
      components: [1, 0.92941, 0.92157],
      hex: "#ffedeb",
    },
    "error-96": {
      colorSpace: "srgb",
      components: [1, 0.94118, 0.93725],
      hex: "#fff0ef",
    },
    "error-98": {
      colorSpace: "srgb",
      components: [1, 0.97255, 0.96863],
      hex: "#fff8f7",
    },
    "error-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "error-100": { colorSpace: "srgb", components: [1, 1, 1], hex: "#ffffff" },
    "success-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "success-4": {
      colorSpace: "srgb",
      components: [0, 0.07059, 0.03529],
      hex: "#001209",
    },
    "success-6": {
      colorSpace: "srgb",
      components: [0, 0.09412, 0.05098],
      hex: "#00180d",
    },
    "success-10": {
      colorSpace: "srgb",
      components: [0, 0.12941, 0.07843],
      hex: "#002114",
    },
    "success-12": {
      colorSpace: "srgb",
      components: [0, 0.1451, 0.0902],
      hex: "#002517",
    },
    "success-17": {
      colorSpace: "srgb",
      components: [0, 0.19216, 0.12157],
      hex: "#00311f",
    },
    "success-20": {
      colorSpace: "srgb",
      components: [0, 0.21961, 0.14118],
      hex: "#003824",
    },
    "success-22": {
      colorSpace: "srgb",
      components: [0, 0.23922, 0.15686],
      hex: "#003d28",
    },
    "success-24": {
      colorSpace: "srgb",
      components: [0, 0.25882, 0.16863],
      hex: "#00422b",
    },
    "success-25": {
      colorSpace: "srgb",
      components: [0, 0.27059, 0.17647],
      hex: "#00452d",
    },
    "success-30": {
      colorSpace: "srgb",
      components: [0, 0.32157, 0.21176],
      hex: "#005236",
    },
    "success-35": {
      colorSpace: "srgb",
      components: [0, 0.37255, 0.25098],
      hex: "#005f40",
    },
    "success-40": {
      colorSpace: "srgb",
      components: [0, 0.42353, 0.2902],
      hex: "#006c4a",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0, 0.53333, 0.36471],
      hex: "#00885d",
    },
    "success-60": {
      colorSpace: "srgb",
      components: [0.01569, 0.64706, 0.44706],
      hex: "#04a572",
    },
    "success-70": {
      colorSpace: "srgb",
      components: [0.23137, 0.75686, 0.5451],
      hex: "#3bc18b",
    },
    "success-80": {
      colorSpace: "srgb",
      components: [0.36471, 0.86667, 0.64706],
      hex: "#5ddda5",
    },
    "success-87": {
      colorSpace: "srgb",
      components: [0.44706, 0.9451, 0.72157],
      hex: "#72f1b8",
    },
    "success-90": {
      colorSpace: "srgb",
      components: [0.48235, 0.98039, 0.75294],
      hex: "#7bfac0",
    },
    "success-92": {
      colorSpace: "srgb",
      components: [0.52549, 1, 0.78039],
      hex: "#86ffc7",
    },
    "success-94": {
      colorSpace: "srgb",
      components: [0.68235, 1, 0.83529],
      hex: "#aeffd5",
    },
    "success-95": {
      colorSpace: "srgb",
      components: [0.7451, 1, 0.86275],
      hex: "#beffdc",
    },
    "success-96": {
      colorSpace: "srgb",
      components: [0.80392, 1, 0.88627],
      hex: "#cdffe2",
    },
    "success-98": {
      colorSpace: "srgb",
      components: [0.9098, 1, 0.93725],
      hex: "#e8ffef",
    },
    "success-99": {
      colorSpace: "srgb",
      components: [0.95686, 1, 0.96471],
      hex: "#f4fff6",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "warning-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "warning-4": {
      colorSpace: "srgb",
      components: [0.07451, 0.0549, 0],
      hex: "#130e00",
    },
    "warning-6": {
      colorSpace: "srgb",
      components: [0.09804, 0.07451, 0],
      hex: "#191300",
    },
    "warning-10": {
      colorSpace: "srgb",
      components: [0.13333, 0.10588, 0],
      hex: "#221b00",
    },
    "warning-12": {
      colorSpace: "srgb",
      components: [0.15294, 0.12157, 0],
      hex: "#271f00",
    },
    "warning-17": {
      colorSpace: "srgb",
      components: [0.2, 0.16078, 0],
      hex: "#332900",
    },
    "warning-20": {
      colorSpace: "srgb",
      components: [0.22745, 0.18824, 0],
      hex: "#3a3000",
    },
    "warning-22": {
      colorSpace: "srgb",
      components: [0.24706, 0.20392, 0],
      hex: "#3f3400",
    },
    "warning-24": {
      colorSpace: "srgb",
      components: [0.26667, 0.21961, 0],
      hex: "#443800",
    },
    "warning-25": {
      colorSpace: "srgb",
      components: [0.27843, 0.22745, 0],
      hex: "#473a00",
    },
    "warning-30": {
      colorSpace: "srgb",
      components: [0.32941, 0.27451, 0],
      hex: "#544600",
    },
    "warning-35": {
      colorSpace: "srgb",
      components: [0.38431, 0.31765, 0],
      hex: "#625100",
    },
    "warning-40": {
      colorSpace: "srgb",
      components: [0.43922, 0.36471, 0],
      hex: "#705d00",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [0.54902, 0.45882, 0],
      hex: "#8c7500",
    },
    "warning-60": {
      colorSpace: "srgb",
      components: [0.66667, 0.56078, 0.03922],
      hex: "#aa8f0a",
    },
    "warning-70": {
      colorSpace: "srgb",
      components: [0.77647, 0.66275, 0.17255],
      hex: "#c6a92c",
    },
    "warning-80": {
      colorSpace: "srgb",
      components: [0.8902, 0.77255, 0.27451],
      hex: "#e3c546",
    },
    "warning-87": {
      colorSpace: "srgb",
      components: [0.97255, 0.84706, 0.3451],
      hex: "#f8d858",
    },
    "warning-90": {
      colorSpace: "srgb",
      components: [1, 0.88235, 0.42745],
      hex: "#ffe16d",
    },
    "warning-92": {
      colorSpace: "srgb",
      components: [1, 0.90588, 0.57255],
      hex: "#ffe792",
    },
    "warning-94": {
      colorSpace: "srgb",
      components: [1, 0.92941, 0.70196],
      hex: "#ffedb3",
    },
    "warning-95": {
      colorSpace: "srgb",
      components: [1, 0.94118, 0.76078],
      hex: "#fff0c2",
    },
    "warning-96": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.81961],
      hex: "#fff3d1",
    },
    "warning-98": {
      colorSpace: "srgb",
      components: [1, 0.97647, 0.93333],
      hex: "#fff9ee",
    },
    "warning-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "neutral-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "neutral-4": {
      colorSpace: "srgb",
      components: [0.05882, 0.04706, 0.11373],
      hex: "#0f0c1d",
    },
    "neutral-6": {
      colorSpace: "srgb",
      components: [0.07843, 0.06667, 0.13333],
      hex: "#141122",
    },
    "neutral-10": {
      colorSpace: "srgb",
      components: [0.1098, 0.09804, 0.16863],
      hex: "#1c192b",
    },
    "neutral-12": {
      colorSpace: "srgb",
      components: [0.12549, 0.11373, 0.18431],
      hex: "#201d2f",
    },
    "neutral-17": {
      colorSpace: "srgb",
      components: [0.16863, 0.15686, 0.22745],
      hex: "#2b283a",
    },
    "neutral-20": {
      colorSpace: "srgb",
      components: [0.19216, 0.18039, 0.2549],
      hex: "#312e41",
    },
    "neutral-22": {
      colorSpace: "srgb",
      components: [0.21176, 0.19608, 0.27059],
      hex: "#363245",
    },
    "neutral-24": {
      colorSpace: "srgb",
      components: [0.22745, 0.21569, 0.2902],
      hex: "#3a374a",
    },
    "neutral-25": {
      colorSpace: "srgb",
      components: [0.23529, 0.22353, 0.29804],
      hex: "#3c394c",
    },
    "neutral-30": {
      colorSpace: "srgb",
      components: [0.28235, 0.26667, 0.3451],
      hex: "#484458",
    },
    "neutral-35": {
      colorSpace: "srgb",
      components: [0.32941, 0.31373, 0.39216],
      hex: "#545064",
    },
    "neutral-40": {
      colorSpace: "srgb",
      components: [0.37647, 0.36078, 0.43922],
      hex: "#605c70",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.47451, 0.4549, 0.54118],
      hex: "#79748a",
    },
    "neutral-60": {
      colorSpace: "srgb",
      components: [0.57647, 0.55686, 0.64314],
      hex: "#938ea4",
    },
    "neutral-70": {
      colorSpace: "srgb",
      components: [0.68235, 0.65882, 0.74902],
      hex: "#aea8bf",
    },
    "neutral-80": {
      colorSpace: "srgb",
      components: [0.78824, 0.76471, 0.85882],
      hex: "#c9c3db",
    },
    "neutral-87": {
      colorSpace: "srgb",
      components: [0.86667, 0.84314, 0.93725],
      hex: "#ddd7ef",
    },
    "neutral-90": {
      colorSpace: "srgb",
      components: [0.90196, 0.87451, 0.97255],
      hex: "#e6dff8",
    },
    "neutral-92": {
      colorSpace: "srgb",
      components: [0.92157, 0.89804, 0.99608],
      hex: "#ebe5fe",
    },
    "neutral-94": {
      colorSpace: "srgb",
      components: [0.9451, 0.92157, 1],
      hex: "#f1ebff",
    },
    "neutral-95": {
      colorSpace: "srgb",
      components: [0.95686, 0.93333, 1],
      hex: "#f4eeff",
    },
    "neutral-96": {
      colorSpace: "srgb",
      components: [0.96863, 0.9451, 1],
      hex: "#f7f1ff",
    },
    "neutral-98": {
      colorSpace: "srgb",
      components: [0.99216, 0.97255, 1],
      hex: "#fdf8ff",
    },
    "neutral-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "neutral-variant-0": {
      colorSpace: "srgb",
      components: [0, 0, 0],
      hex: "#000000",
    },
    "neutral-variant-4": {
      colorSpace: "srgb",
      components: [0.00784, 0.03137, 0.21176],
      hex: "#020836",
    },
    "neutral-variant-6": {
      colorSpace: "srgb",
      components: [0.02353, 0.0549, 0.22745],
      hex: "#060e3a",
    },
    "neutral-variant-10": {
      colorSpace: "srgb",
      components: [0.06275, 0.0902, 0.26275],
      hex: "#101743",
    },
    "neutral-variant-12": {
      colorSpace: "srgb",
      components: [0.07843, 0.10588, 0.27843],
      hex: "#141b47",
    },
    "neutral-variant-17": {
      colorSpace: "srgb",
      components: [0.12157, 0.14902, 0.32157],
      hex: "#1f2652",
    },
    "neutral-variant-20": {
      colorSpace: "srgb",
      components: [0.14902, 0.17647, 0.34902],
      hex: "#262d59",
    },
    "neutral-variant-22": {
      colorSpace: "srgb",
      components: [0.16471, 0.19216, 0.36471],
      hex: "#2a315d",
    },
    "neutral-variant-24": {
      colorSpace: "srgb",
      components: [0.18431, 0.21176, 0.38431],
      hex: "#2f3662",
    },
    "neutral-variant-25": {
      colorSpace: "srgb",
      components: [0.19216, 0.21961, 0.39608],
      hex: "#313865",
    },
    "neutral-variant-30": {
      colorSpace: "srgb",
      components: [0.23529, 0.26667, 0.44314],
      hex: "#3c4471",
    },
    "neutral-variant-35": {
      colorSpace: "srgb",
      components: [0.28235, 0.3098, 0.4902],
      hex: "#484f7d",
    },
    "neutral-variant-40": {
      colorSpace: "srgb",
      components: [0.32941, 0.35686, 0.54118],
      hex: "#545b8a",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.42745, 0.4549, 0.64314],
      hex: "#6d74a4",
    },
    "neutral-variant-60": {
      colorSpace: "srgb",
      components: [0.52941, 0.55686, 0.75294],
      hex: "#878ec0",
    },
    "neutral-variant-70": {
      colorSpace: "srgb",
      components: [0.63137, 0.65882, 0.86275],
      hex: "#a1a8dc",
    },
    "neutral-variant-80": {
      colorSpace: "srgb",
      components: [0.73725, 0.76471, 0.97647],
      hex: "#bcc3f9",
    },
    "neutral-variant-87": {
      colorSpace: "srgb",
      components: [0.83137, 0.84314, 1],
      hex: "#d4d7ff",
    },
    "neutral-variant-90": {
      colorSpace: "srgb",
      components: [0.87059, 0.87843, 1],
      hex: "#dee0ff",
    },
    "neutral-variant-92": {
      colorSpace: "srgb",
      components: [0.89804, 0.90196, 1],
      hex: "#e5e6ff",
    },
    "neutral-variant-94": {
      colorSpace: "srgb",
      components: [0.92941, 0.92549, 1],
      hex: "#edecff",
    },
    "neutral-variant-95": {
      colorSpace: "srgb",
      components: [0.94118, 0.93725, 1],
      hex: "#f0efff",
    },
    "neutral-variant-96": {
      colorSpace: "srgb",
      components: [0.95686, 0.94902, 1],
      hex: "#f4f2ff",
    },
    "neutral-variant-98": {
      colorSpace: "srgb",
      components: [0.98431, 0.97255, 1],
      hex: "#fbf8ff",
    },
    "neutral-variant-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
  },
} satisfies FoundationLayer;
