/**
 * Vesper — Peach and mint on near-black, from Vesper. Generated by scripts/generate.mjs from
 * scripts/seeds.json; regenerate with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the eight tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through its
 * ramp references.
 */
import type { FoundationLayer } from "../types";

export default {
  id: "vesper",
  name: "Vesper",
  tokens: {
    "primary-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "primary-4": {
      colorSpace: "srgb",
      components: [0.10588, 0.03922, 0],
      hex: "#1b0a00",
    },
    "primary-6": {
      colorSpace: "srgb",
      components: [0.13333, 0.0549, 0],
      hex: "#220e00",
    },
    "primary-10": {
      colorSpace: "srgb",
      components: [0.18039, 0.08235, 0],
      hex: "#2e1500",
    },
    "primary-12": {
      colorSpace: "srgb",
      components: [0.20392, 0.09804, 0],
      hex: "#341900",
    },
    "primary-17": {
      colorSpace: "srgb",
      components: [0.25882, 0.13333, 0.00784],
      hex: "#422202",
    },
    "primary-20": {
      colorSpace: "srgb",
      components: [0.28627, 0.15686, 0.02745],
      hex: "#492807",
    },
    "primary-22": {
      colorSpace: "srgb",
      components: [0.3098, 0.17647, 0.04314],
      hex: "#4f2d0b",
    },
    "primary-24": {
      colorSpace: "srgb",
      components: [0.32941, 0.19216, 0.05882],
      hex: "#54310f",
    },
    "primary-25": {
      colorSpace: "srgb",
      components: [0.33725, 0.2, 0.06667],
      hex: "#563311",
    },
    "primary-30": {
      colorSpace: "srgb",
      components: [0.39216, 0.24314, 0.10588],
      hex: "#643e1b",
    },
    "primary-35": {
      colorSpace: "srgb",
      components: [0.44314, 0.2902, 0.14902],
      hex: "#714a26",
    },
    "primary-40": {
      colorSpace: "srgb",
      components: [0.49804, 0.33333, 0.18824],
      hex: "#7f5530",
    },
    "primary-50": {
      colorSpace: "srgb",
      components: [0.60784, 0.42745, 0.27451],
      hex: "#9b6d46",
    },
    "primary-60": {
      colorSpace: "srgb",
      components: [0.71765, 0.52941, 0.36471],
      hex: "#b7875d",
    },
    "primary-70": {
      colorSpace: "srgb",
      components: [0.83137, 0.63137, 0.45882],
      hex: "#d4a175",
    },
    "primary-80": {
      colorSpace: "srgb",
      components: [0.94902, 0.73725, 0.55686],
      hex: "#f2bc8e",
    },
    "primary-87": {
      colorSpace: "srgb",
      components: [1, 0.81961, 0.67843],
      hex: "#ffd1ad",
    },
    "primary-90": {
      colorSpace: "srgb",
      components: [1, 0.86275, 0.75686],
      hex: "#ffdcc1",
    },
    "primary-92": {
      colorSpace: "srgb",
      components: [1, 0.8902, 0.81176],
      hex: "#ffe3cf",
    },
    "primary-94": {
      colorSpace: "srgb",
      components: [1, 0.91765, 0.86275],
      hex: "#ffeadc",
    },
    "primary-95": {
      colorSpace: "srgb",
      components: [1, 0.93333, 0.88627],
      hex: "#ffeee2",
    },
    "primary-96": {
      colorSpace: "srgb",
      components: [1, 0.9451, 0.9098],
      hex: "#fff1e8",
    },
    "primary-98": {
      colorSpace: "srgb",
      components: [1, 0.97255, 0.96078],
      hex: "#fff8f5",
    },
    "primary-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "secondary-0": {
      colorSpace: "srgb",
      components: [0, 0, 0],
      hex: "#000000",
    },
    "secondary-4": {
      colorSpace: "srgb",
      components: [0, 0.06667, 0.05098],
      hex: "#00110d",
    },
    "secondary-6": {
      colorSpace: "srgb",
      components: [0, 0.0902, 0.07059],
      hex: "#001712",
    },
    "secondary-10": {
      colorSpace: "srgb",
      components: [0, 0.12549, 0.09804],
      hex: "#002019",
    },
    "secondary-12": {
      colorSpace: "srgb",
      components: [0, 0.1451, 0.11373],
      hex: "#00251d",
    },
    "secondary-17": {
      colorSpace: "srgb",
      components: [0, 0.18824, 0.15294],
      hex: "#003027",
    },
    "secondary-20": {
      colorSpace: "srgb",
      components: [0, 0.21961, 0.17647],
      hex: "#00382d",
    },
    "secondary-22": {
      colorSpace: "srgb",
      components: [0, 0.23922, 0.19216],
      hex: "#003d31",
    },
    "secondary-24": {
      colorSpace: "srgb",
      components: [0, 0.2549, 0.21176],
      hex: "#004136",
    },
    "secondary-25": {
      colorSpace: "srgb",
      components: [0, 0.26667, 0.21961],
      hex: "#004438",
    },
    "secondary-30": {
      colorSpace: "srgb",
      components: [0, 0.31765, 0.26275],
      hex: "#005143",
    },
    "secondary-35": {
      colorSpace: "srgb",
      components: [0, 0.36863, 0.30588],
      hex: "#005e4e",
    },
    "secondary-40": {
      colorSpace: "srgb",
      components: [0, 0.41961, 0.34902],
      hex: "#006b59",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.01961, 0.52941, 0.44314],
      hex: "#058771",
    },
    "secondary-60": {
      colorSpace: "srgb",
      components: [0.21176, 0.63137, 0.54118],
      hex: "#36a18a",
    },
    "secondary-70": {
      colorSpace: "srgb",
      components: [0.33333, 0.73725, 0.64314],
      hex: "#55bca4",
    },
    "secondary-80": {
      colorSpace: "srgb",
      components: [0.45098, 0.84706, 0.74902],
      hex: "#73d8bf",
    },
    "secondary-87": {
      colorSpace: "srgb",
      components: [0.52941, 0.92549, 0.82353],
      hex: "#87ecd2",
    },
    "secondary-90": {
      colorSpace: "srgb",
      components: [0.56078, 0.96078, 0.8549],
      hex: "#8ff5da",
    },
    "secondary-92": {
      colorSpace: "srgb",
      components: [0.58431, 0.98431, 0.87843],
      hex: "#95fbe0",
    },
    "secondary-94": {
      colorSpace: "srgb",
      components: [0.64706, 1, 0.90196],
      hex: "#a5ffe6",
    },
    "secondary-95": {
      colorSpace: "srgb",
      components: [0.72157, 1, 0.91765],
      hex: "#b8ffea",
    },
    "secondary-96": {
      colorSpace: "srgb",
      components: [0.78431, 1, 0.93333],
      hex: "#c8ffee",
    },
    "secondary-98": {
      colorSpace: "srgb",
      components: [0.90196, 1, 0.96471],
      hex: "#e6fff6",
    },
    "secondary-99": {
      colorSpace: "srgb",
      components: [0.95294, 1, 0.97647],
      hex: "#f3fff9",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "tertiary-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "tertiary-4": {
      colorSpace: "srgb",
      components: [0.15294, 0, 0.01176],
      hex: "#270003",
    },
    "tertiary-6": {
      colorSpace: "srgb",
      components: [0.19216, 0, 0.01569],
      hex: "#310004",
    },
    "tertiary-10": {
      colorSpace: "srgb",
      components: [0.2549, 0, 0.02745],
      hex: "#410007",
    },
    "tertiary-12": {
      colorSpace: "srgb",
      components: [0.28235, 0, 0.03529],
      hex: "#480009",
    },
    "tertiary-17": {
      colorSpace: "srgb",
      components: [0.35686, 0.00784, 0.05882],
      hex: "#5b020f",
    },
    "tertiary-20": {
      colorSpace: "srgb",
      components: [0.39216, 0.03922, 0.08235],
      hex: "#640a15",
    },
    "tertiary-22": {
      colorSpace: "srgb",
      components: [0.41961, 0.05882, 0.09412],
      hex: "#6b0f18",
    },
    "tertiary-24": {
      colorSpace: "srgb",
      components: [0.44314, 0.08235, 0.1098],
      hex: "#71151c",
    },
    "tertiary-25": {
      colorSpace: "srgb",
      components: [0.4549, 0.0902, 0.11765],
      hex: "#74171e",
    },
    "tertiary-30": {
      colorSpace: "srgb",
      components: [0.51765, 0.13725, 0.15686],
      hex: "#842328",
    },
    "tertiary-35": {
      colorSpace: "srgb",
      components: [0.57647, 0.18431, 0.2],
      hex: "#932f33",
    },
    "tertiary-40": {
      colorSpace: "srgb",
      components: [0.63922, 0.23137, 0.24314],
      hex: "#a33b3e",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.76471, 0.32549, 0.32941],
      hex: "#c35354",
    },
    "tertiary-60": {
      colorSpace: "srgb",
      components: [0.89412, 0.41961, 0.42353],
      hex: "#e46b6c",
    },
    "tertiary-70": {
      colorSpace: "srgb",
      components: [1, 0.53333, 0.53333],
      hex: "#ff8888",
    },
    "tertiary-80": {
      colorSpace: "srgb",
      components: [1, 0.70196, 0.69412],
      hex: "#ffb3b1",
    },
    "tertiary-87": {
      colorSpace: "srgb",
      components: [1, 0.80784, 0.80392],
      hex: "#ffcecd",
    },
    "tertiary-90": {
      colorSpace: "srgb",
      components: [1, 0.8549, 0.84706],
      hex: "#ffdad8",
    },
    "tertiary-92": {
      colorSpace: "srgb",
      components: [1, 0.88235, 0.87843],
      hex: "#ffe1e0",
    },
    "tertiary-94": {
      colorSpace: "srgb",
      components: [1, 0.91373, 0.9098],
      hex: "#ffe9e8",
    },
    "tertiary-95": {
      colorSpace: "srgb",
      components: [1, 0.92941, 0.92157],
      hex: "#ffedeb",
    },
    "tertiary-96": {
      colorSpace: "srgb",
      components: [1, 0.94118, 0.93725],
      hex: "#fff0ef",
    },
    "tertiary-98": {
      colorSpace: "srgb",
      components: [1, 0.97255, 0.96863],
      hex: "#fff8f7",
    },
    "tertiary-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "error-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "error-4": {
      colorSpace: "srgb",
      components: [0.15294, 0, 0.01176],
      hex: "#270003",
    },
    "error-6": {
      colorSpace: "srgb",
      components: [0.19216, 0, 0.01569],
      hex: "#310004",
    },
    "error-10": {
      colorSpace: "srgb",
      components: [0.2549, 0, 0.02745],
      hex: "#410007",
    },
    "error-12": {
      colorSpace: "srgb",
      components: [0.28235, 0, 0.03529],
      hex: "#480009",
    },
    "error-17": {
      colorSpace: "srgb",
      components: [0.35686, 0.00784, 0.05882],
      hex: "#5b020f",
    },
    "error-20": {
      colorSpace: "srgb",
      components: [0.39216, 0.03922, 0.08235],
      hex: "#640a15",
    },
    "error-22": {
      colorSpace: "srgb",
      components: [0.41961, 0.05882, 0.09412],
      hex: "#6b0f18",
    },
    "error-24": {
      colorSpace: "srgb",
      components: [0.44314, 0.08235, 0.1098],
      hex: "#71151c",
    },
    "error-25": {
      colorSpace: "srgb",
      components: [0.4549, 0.0902, 0.11765],
      hex: "#74171e",
    },
    "error-30": {
      colorSpace: "srgb",
      components: [0.51765, 0.13725, 0.15686],
      hex: "#842328",
    },
    "error-35": {
      colorSpace: "srgb",
      components: [0.57647, 0.18431, 0.2],
      hex: "#932f33",
    },
    "error-40": {
      colorSpace: "srgb",
      components: [0.63922, 0.23137, 0.24314],
      hex: "#a33b3e",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [0.76471, 0.32549, 0.32941],
      hex: "#c35354",
    },
    "error-60": {
      colorSpace: "srgb",
      components: [0.89412, 0.41961, 0.42353],
      hex: "#e46b6c",
    },
    "error-70": {
      colorSpace: "srgb",
      components: [1, 0.53333, 0.53333],
      hex: "#ff8888",
    },
    "error-80": {
      colorSpace: "srgb",
      components: [1, 0.70196, 0.69412],
      hex: "#ffb3b1",
    },
    "error-87": {
      colorSpace: "srgb",
      components: [1, 0.80784, 0.80392],
      hex: "#ffcecd",
    },
    "error-90": {
      colorSpace: "srgb",
      components: [1, 0.8549, 0.84706],
      hex: "#ffdad8",
    },
    "error-92": {
      colorSpace: "srgb",
      components: [1, 0.88235, 0.87843],
      hex: "#ffe1e0",
    },
    "error-94": {
      colorSpace: "srgb",
      components: [1, 0.91373, 0.9098],
      hex: "#ffe9e8",
    },
    "error-95": {
      colorSpace: "srgb",
      components: [1, 0.92941, 0.92157],
      hex: "#ffedeb",
    },
    "error-96": {
      colorSpace: "srgb",
      components: [1, 0.94118, 0.93725],
      hex: "#fff0ef",
    },
    "error-98": {
      colorSpace: "srgb",
      components: [1, 0.97255, 0.96863],
      hex: "#fff8f7",
    },
    "error-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "error-100": { colorSpace: "srgb", components: [1, 1, 1], hex: "#ffffff" },
    "success-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "success-4": {
      colorSpace: "srgb",
      components: [0, 0.06667, 0.05098],
      hex: "#00110d",
    },
    "success-6": {
      colorSpace: "srgb",
      components: [0, 0.0902, 0.07059],
      hex: "#001712",
    },
    "success-10": {
      colorSpace: "srgb",
      components: [0, 0.12549, 0.09804],
      hex: "#002019",
    },
    "success-12": {
      colorSpace: "srgb",
      components: [0, 0.1451, 0.11373],
      hex: "#00251d",
    },
    "success-17": {
      colorSpace: "srgb",
      components: [0, 0.18824, 0.15294],
      hex: "#003027",
    },
    "success-20": {
      colorSpace: "srgb",
      components: [0, 0.21961, 0.17647],
      hex: "#00382d",
    },
    "success-22": {
      colorSpace: "srgb",
      components: [0, 0.23922, 0.19216],
      hex: "#003d31",
    },
    "success-24": {
      colorSpace: "srgb",
      components: [0, 0.2549, 0.21176],
      hex: "#004136",
    },
    "success-25": {
      colorSpace: "srgb",
      components: [0, 0.26667, 0.21961],
      hex: "#004438",
    },
    "success-30": {
      colorSpace: "srgb",
      components: [0, 0.31765, 0.26275],
      hex: "#005143",
    },
    "success-35": {
      colorSpace: "srgb",
      components: [0, 0.36863, 0.30588],
      hex: "#005e4e",
    },
    "success-40": {
      colorSpace: "srgb",
      components: [0, 0.41961, 0.34902],
      hex: "#006b59",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.01961, 0.52941, 0.44314],
      hex: "#058771",
    },
    "success-60": {
      colorSpace: "srgb",
      components: [0.21176, 0.63137, 0.54118],
      hex: "#36a18a",
    },
    "success-70": {
      colorSpace: "srgb",
      components: [0.33333, 0.73725, 0.64314],
      hex: "#55bca4",
    },
    "success-80": {
      colorSpace: "srgb",
      components: [0.45098, 0.84706, 0.74902],
      hex: "#73d8bf",
    },
    "success-87": {
      colorSpace: "srgb",
      components: [0.52941, 0.92549, 0.82353],
      hex: "#87ecd2",
    },
    "success-90": {
      colorSpace: "srgb",
      components: [0.56078, 0.96078, 0.8549],
      hex: "#8ff5da",
    },
    "success-92": {
      colorSpace: "srgb",
      components: [0.58431, 0.98431, 0.87843],
      hex: "#95fbe0",
    },
    "success-94": {
      colorSpace: "srgb",
      components: [0.64706, 1, 0.90196],
      hex: "#a5ffe6",
    },
    "success-95": {
      colorSpace: "srgb",
      components: [0.72157, 1, 0.91765],
      hex: "#b8ffea",
    },
    "success-96": {
      colorSpace: "srgb",
      components: [0.78431, 1, 0.93333],
      hex: "#c8ffee",
    },
    "success-98": {
      colorSpace: "srgb",
      components: [0.90196, 1, 0.96471],
      hex: "#e6fff6",
    },
    "success-99": {
      colorSpace: "srgb",
      components: [0.95294, 1, 0.97647],
      hex: "#f3fff9",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "warning-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "warning-4": {
      colorSpace: "srgb",
      components: [0.10588, 0.03922, 0],
      hex: "#1b0a00",
    },
    "warning-6": {
      colorSpace: "srgb",
      components: [0.13333, 0.0549, 0],
      hex: "#220e00",
    },
    "warning-10": {
      colorSpace: "srgb",
      components: [0.18039, 0.08235, 0],
      hex: "#2e1500",
    },
    "warning-12": {
      colorSpace: "srgb",
      components: [0.20392, 0.09804, 0],
      hex: "#341900",
    },
    "warning-17": {
      colorSpace: "srgb",
      components: [0.25882, 0.13333, 0.00784],
      hex: "#422202",
    },
    "warning-20": {
      colorSpace: "srgb",
      components: [0.28627, 0.15686, 0.02745],
      hex: "#492807",
    },
    "warning-22": {
      colorSpace: "srgb",
      components: [0.3098, 0.17647, 0.04314],
      hex: "#4f2d0b",
    },
    "warning-24": {
      colorSpace: "srgb",
      components: [0.32941, 0.19216, 0.05882],
      hex: "#54310f",
    },
    "warning-25": {
      colorSpace: "srgb",
      components: [0.33725, 0.2, 0.06667],
      hex: "#563311",
    },
    "warning-30": {
      colorSpace: "srgb",
      components: [0.39216, 0.24314, 0.10588],
      hex: "#643e1b",
    },
    "warning-35": {
      colorSpace: "srgb",
      components: [0.44314, 0.2902, 0.14902],
      hex: "#714a26",
    },
    "warning-40": {
      colorSpace: "srgb",
      components: [0.49804, 0.33333, 0.18824],
      hex: "#7f5530",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [0.60784, 0.42745, 0.27451],
      hex: "#9b6d46",
    },
    "warning-60": {
      colorSpace: "srgb",
      components: [0.71765, 0.52941, 0.36471],
      hex: "#b7875d",
    },
    "warning-70": {
      colorSpace: "srgb",
      components: [0.83137, 0.63137, 0.45882],
      hex: "#d4a175",
    },
    "warning-80": {
      colorSpace: "srgb",
      components: [0.94902, 0.73725, 0.55686],
      hex: "#f2bc8e",
    },
    "warning-87": {
      colorSpace: "srgb",
      components: [1, 0.81961, 0.67843],
      hex: "#ffd1ad",
    },
    "warning-90": {
      colorSpace: "srgb",
      components: [1, 0.86275, 0.75686],
      hex: "#ffdcc1",
    },
    "warning-92": {
      colorSpace: "srgb",
      components: [1, 0.8902, 0.81176],
      hex: "#ffe3cf",
    },
    "warning-94": {
      colorSpace: "srgb",
      components: [1, 0.91765, 0.86275],
      hex: "#ffeadc",
    },
    "warning-95": {
      colorSpace: "srgb",
      components: [1, 0.93333, 0.88627],
      hex: "#ffeee2",
    },
    "warning-96": {
      colorSpace: "srgb",
      components: [1, 0.9451, 0.9098],
      hex: "#fff1e8",
    },
    "warning-98": {
      colorSpace: "srgb",
      components: [1, 0.97255, 0.96078],
      hex: "#fff8f5",
    },
    "warning-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "neutral-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "neutral-4": {
      colorSpace: "srgb",
      components: [0.0549, 0.0549, 0.0549],
      hex: "#0e0e0e",
    },
    "neutral-6": {
      colorSpace: "srgb",
      components: [0.07451, 0.07451, 0.07451],
      hex: "#131313",
    },
    "neutral-10": {
      colorSpace: "srgb",
      components: [0.1098, 0.10588, 0.10588],
      hex: "#1c1b1b",
    },
    "neutral-12": {
      colorSpace: "srgb",
      components: [0.12549, 0.12157, 0.12157],
      hex: "#201f1f",
    },
    "neutral-17": {
      colorSpace: "srgb",
      components: [0.16471, 0.16471, 0.16471],
      hex: "#2a2a2a",
    },
    "neutral-20": {
      colorSpace: "srgb",
      components: [0.19216, 0.18824, 0.18824],
      hex: "#313030",
    },
    "neutral-22": {
      colorSpace: "srgb",
      components: [0.20784, 0.20784, 0.20392],
      hex: "#353534",
    },
    "neutral-24": {
      colorSpace: "srgb",
      components: [0.22745, 0.22353, 0.22353],
      hex: "#3a3939",
    },
    "neutral-25": {
      colorSpace: "srgb",
      components: [0.23529, 0.23137, 0.23137],
      hex: "#3c3b3b",
    },
    "neutral-30": {
      colorSpace: "srgb",
      components: [0.27843, 0.27451, 0.27451],
      hex: "#474646",
    },
    "neutral-35": {
      colorSpace: "srgb",
      components: [0.32549, 0.32157, 0.32157],
      hex: "#535252",
    },
    "neutral-40": {
      colorSpace: "srgb",
      components: [0.37255, 0.36863, 0.36863],
      hex: "#5f5e5e",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.47059, 0.46667, 0.46275],
      hex: "#787776",
    },
    "neutral-60": {
      colorSpace: "srgb",
      components: [0.57255, 0.56471, 0.56471],
      hex: "#929090",
    },
    "neutral-70": {
      colorSpace: "srgb",
      components: [0.67843, 0.67059, 0.66667],
      hex: "#adabaa",
    },
    "neutral-80": {
      colorSpace: "srgb",
      components: [0.78431, 0.77647, 0.77255],
      hex: "#c8c6c5",
    },
    "neutral-87": {
      colorSpace: "srgb",
      components: [0.86275, 0.85098, 0.85098],
      hex: "#dcd9d9",
    },
    "neutral-90": {
      colorSpace: "srgb",
      components: [0.89804, 0.88627, 0.88235],
      hex: "#e5e2e1",
    },
    "neutral-92": {
      colorSpace: "srgb",
      components: [0.92157, 0.90588, 0.90588],
      hex: "#ebe7e7",
    },
    "neutral-94": {
      colorSpace: "srgb",
      components: [0.94118, 0.92941, 0.92549],
      hex: "#f0edec",
    },
    "neutral-95": {
      colorSpace: "srgb",
      components: [0.95294, 0.94118, 0.93725],
      hex: "#f3f0ef",
    },
    "neutral-96": {
      colorSpace: "srgb",
      components: [0.96471, 0.95294, 0.94902],
      hex: "#f6f3f2",
    },
    "neutral-98": {
      colorSpace: "srgb",
      components: [0.98824, 0.97647, 0.97255],
      hex: "#fcf9f8",
    },
    "neutral-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 0.98431],
      hex: "#fffbfb",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "neutral-variant-0": {
      colorSpace: "srgb",
      components: [0, 0, 0],
      hex: "#000000",
    },
    "neutral-variant-4": {
      colorSpace: "srgb",
      components: [0.05098, 0.0549, 0.05882],
      hex: "#0d0e0f",
    },
    "neutral-variant-6": {
      colorSpace: "srgb",
      components: [0.07059, 0.07843, 0.07843],
      hex: "#121414",
    },
    "neutral-variant-10": {
      colorSpace: "srgb",
      components: [0.10196, 0.1098, 0.1098],
      hex: "#1a1c1c",
    },
    "neutral-variant-12": {
      colorSpace: "srgb",
      components: [0.11765, 0.12549, 0.12549],
      hex: "#1e2020",
    },
    "neutral-variant-17": {
      colorSpace: "srgb",
      components: [0.16078, 0.16471, 0.16471],
      hex: "#292a2a",
    },
    "neutral-variant-20": {
      colorSpace: "srgb",
      components: [0.18431, 0.19216, 0.19216],
      hex: "#2f3131",
    },
    "neutral-variant-22": {
      colorSpace: "srgb",
      components: [0.20392, 0.20784, 0.20784],
      hex: "#343535",
    },
    "neutral-variant-24": {
      colorSpace: "srgb",
      components: [0.21961, 0.22353, 0.22353],
      hex: "#383939",
    },
    "neutral-variant-25": {
      colorSpace: "srgb",
      components: [0.22745, 0.23529, 0.23529],
      hex: "#3a3c3c",
    },
    "neutral-variant-30": {
      colorSpace: "srgb",
      components: [0.27451, 0.27843, 0.27843],
      hex: "#464747",
    },
    "neutral-variant-35": {
      colorSpace: "srgb",
      components: [0.32157, 0.32157, 0.32549],
      hex: "#525253",
    },
    "neutral-variant-40": {
      colorSpace: "srgb",
      components: [0.36863, 0.36863, 0.37255],
      hex: "#5e5e5f",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.46667, 0.46667, 0.46667],
      hex: "#777777",
    },
    "neutral-variant-60": {
      colorSpace: "srgb",
      components: [0.56471, 0.56863, 0.56863],
      hex: "#909191",
    },
    "neutral-variant-70": {
      colorSpace: "srgb",
      components: [0.67059, 0.67059, 0.67059],
      hex: "#ababab",
    },
    "neutral-variant-80": {
      colorSpace: "srgb",
      components: [0.78039, 0.77647, 0.77647],
      hex: "#c7c6c6",
    },
    "neutral-variant-87": {
      colorSpace: "srgb",
      components: [0.8549, 0.8549, 0.8549],
      hex: "#dadada",
    },
    "neutral-variant-90": {
      colorSpace: "srgb",
      components: [0.8902, 0.88627, 0.88627],
      hex: "#e3e2e2",
    },
    "neutral-variant-92": {
      colorSpace: "srgb",
      components: [0.91373, 0.9098, 0.9098],
      hex: "#e9e8e8",
    },
    "neutral-variant-94": {
      colorSpace: "srgb",
      components: [0.93333, 0.93333, 0.92941],
      hex: "#eeeeed",
    },
    "neutral-variant-95": {
      colorSpace: "srgb",
      components: [0.9451, 0.94118, 0.94118],
      hex: "#f1f0f0",
    },
    "neutral-variant-96": {
      colorSpace: "srgb",
      components: [0.95686, 0.95294, 0.95294],
      hex: "#f4f3f3",
    },
    "neutral-variant-98": {
      colorSpace: "srgb",
      components: [0.98039, 0.97647, 0.97647],
      hex: "#faf9f9",
    },
    "neutral-variant-99": {
      colorSpace: "srgb",
      components: [0.99216, 0.98824, 0.98824],
      hex: "#fdfcfc",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
  },
} satisfies FoundationLayer;
