/**
 * Catppuccin Mocha — Soothing lavender and blue pastels, from Catppuccin Mocha.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "catppuccin",
  name: "Catppuccin Mocha",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.96078, 1],
      hex: "#f9f5ff",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.9098, 1],
      hex: "#f1e8ff",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [0.8902, 0.80784, 1],
      hex: "#e3ceff",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.80392, 0.6902, 0.95294],
      hex: "#cdb0f3",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.70196, 0.56863, 0.86275],
      hex: "#b391dc",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.58824, 0.45098, 0.75294],
      hex: "#9673c0",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.48235, 0.3451, 0.63922],
      hex: "#7b58a3",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0.38824, 0.26275, 0.52941],
      hex: "#634387",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0.30196, 0.19216, 0.41961],
      hex: "#4d316b",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0.21569, 0.12941, 0.3098],
      hex: "#37214f",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0.15294, 0.0902, 0.22353],
      hex: "#271739",
    },
    "primary-muted-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.96078, 0.99216],
      hex: "#f8f5fd",
    },
    "primary-muted-100": {
      colorSpace: "srgb",
      components: [0.94118, 0.91765, 0.97255],
      hex: "#f0eaf8",
    },
    "primary-muted-200": {
      colorSpace: "srgb",
      components: [0.86667, 0.83137, 0.92157],
      hex: "#ddd4eb",
    },
    "primary-muted-300": {
      colorSpace: "srgb",
      components: [0.77255, 0.72549, 0.84314],
      hex: "#c5b9d7",
    },
    "primary-muted-400": {
      colorSpace: "srgb",
      components: [0.66667, 0.61176, 0.74118],
      hex: "#aa9cbd",
    },
    "primary-muted-500": {
      colorSpace: "srgb",
      components: [0.55294, 0.49804, 0.63137],
      hex: "#8d7fa1",
    },
    "primary-muted-600": {
      colorSpace: "srgb",
      components: [0.44706, 0.39216, 0.52157],
      hex: "#726485",
    },
    "primary-muted-700": {
      colorSpace: "srgb",
      components: [0.35686, 0.30588, 0.42353],
      hex: "#5b4e6c",
    },
    "primary-muted-800": {
      colorSpace: "srgb",
      components: [0.27451, 0.23137, 0.33333],
      hex: "#463b55",
    },
    "primary-muted-900": {
      colorSpace: "srgb",
      components: [0.19608, 0.16078, 0.23922],
      hex: "#32293d",
    },
    "primary-muted-950": {
      colorSpace: "srgb",
      components: [0.13725, 0.11373, 0.17255],
      hex: "#231d2c",
    },
    "primary-vivid-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.96078, 1],
      hex: "#f9f5ff",
    },
    "primary-vivid-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.9098, 1],
      hex: "#f1e8ff",
    },
    "primary-vivid-200": {
      colorSpace: "srgb",
      components: [0.8902, 0.80784, 1],
      hex: "#e3ceff",
    },
    "primary-vivid-300": {
      colorSpace: "srgb",
      components: [0.81569, 0.67059, 1],
      hex: "#d0abff",
    },
    "primary-vivid-400": {
      colorSpace: "srgb",
      components: [0.72549, 0.52941, 0.94902],
      hex: "#b987f2",
    },
    "primary-vivid-500": {
      colorSpace: "srgb",
      components: [0.61569, 0.40784, 0.83922],
      hex: "#9d68d6",
    },
    "primary-vivid-600": {
      colorSpace: "srgb",
      components: [0.5098, 0.29804, 0.72157],
      hex: "#824cb8",
    },
    "primary-vivid-700": {
      colorSpace: "srgb",
      components: [0.41176, 0.21569, 0.60392],
      hex: "#69379a",
    },
    "primary-vivid-800": {
      colorSpace: "srgb",
      components: [0.32157, 0.14902, 0.48235],
      hex: "#52267b",
    },
    "primary-vivid-900": {
      colorSpace: "srgb",
      components: [0.23137, 0.09412, 0.36078],
      hex: "#3b185c",
    },
    "primary-vivid-950": {
      colorSpace: "srgb",
      components: [0.16471, 0.06275, 0.26275],
      hex: "#2a1043",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.96863, 1],
      hex: "#f2f7ff",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.88627, 0.93333, 1],
      hex: "#e2eeff",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.76078, 0.85882, 1],
      hex: "#c2dbff",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.60392, 0.75686, 0.98824],
      hex: "#9ac1fc",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.47059, 0.64706, 0.90196],
      hex: "#78a5e6",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.34902, 0.52941, 0.79216],
      hex: "#5987ca",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0.24706, 0.42353, 0.67843],
      hex: "#3f6cad",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0.17255, 0.33333, 0.56471],
      hex: "#2c5590",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0.11373, 0.25098, 0.45098],
      hex: "#1d4073",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0.06667, 0.17647, 0.33333],
      hex: "#112d55",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0.04314, 0.12549, 0.24314],
      hex: "#0b203e",
    },
    "secondary-muted-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.96863, 1],
      hex: "#f2f7ff",
    },
    "secondary-muted-100": {
      colorSpace: "srgb",
      components: [0.89804, 0.93333, 0.98039],
      hex: "#e5eefa",
    },
    "secondary-muted-200": {
      colorSpace: "srgb",
      components: [0.80392, 0.8549, 0.93333],
      hex: "#cddaee",
    },
    "secondary-muted-300": {
      colorSpace: "srgb",
      components: [0.68627, 0.75686, 0.85882],
      hex: "#afc1db",
    },
    "secondary-muted-400": {
      colorSpace: "srgb",
      components: [0.56471, 0.64706, 0.76078],
      hex: "#90a5c2",
    },
    "secondary-muted-500": {
      colorSpace: "srgb",
      components: [0.45098, 0.53333, 0.64706],
      hex: "#7388a5",
    },
    "secondary-muted-600": {
      colorSpace: "srgb",
      components: [0.34902, 0.42745, 0.54118],
      hex: "#596d8a",
    },
    "secondary-muted-700": {
      colorSpace: "srgb",
      components: [0.27059, 0.33725, 0.43922],
      hex: "#455670",
    },
    "secondary-muted-800": {
      colorSpace: "srgb",
      components: [0.2, 0.25882, 0.3451],
      hex: "#334258",
    },
    "secondary-muted-900": {
      colorSpace: "srgb",
      components: [0.13333, 0.18039, 0.25098],
      hex: "#222e40",
    },
    "secondary-muted-950": {
      colorSpace: "srgb",
      components: [0.09412, 0.12941, 0.18039],
      hex: "#18212e",
    },
    "secondary-vivid-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.96863, 1],
      hex: "#f2f7ff",
    },
    "secondary-vivid-100": {
      colorSpace: "srgb",
      components: [0.88627, 0.93333, 1],
      hex: "#e2eeff",
    },
    "secondary-vivid-200": {
      colorSpace: "srgb",
      components: [0.76078, 0.85882, 1],
      hex: "#c2dbff",
    },
    "secondary-vivid-300": {
      colorSpace: "srgb",
      components: [0.59216, 0.75686, 1],
      hex: "#97c1ff",
    },
    "secondary-vivid-400": {
      colorSpace: "srgb",
      components: [0.39608, 0.63922, 1],
      hex: "#65a3ff",
    },
    "secondary-vivid-500": {
      colorSpace: "srgb",
      components: [0.26275, 0.52157, 0.89412],
      hex: "#4385e4",
    },
    "secondary-vivid-600": {
      colorSpace: "srgb",
      components: [0.15294, 0.41176, 0.77647],
      hex: "#2769c6",
    },
    "secondary-vivid-700": {
      colorSpace: "srgb",
      components: [0.07059, 0.31765, 0.65098],
      hex: "#1251a6",
    },
    "secondary-vivid-800": {
      colorSpace: "srgb",
      components: [0.01176, 0.23922, 0.52549],
      hex: "#033d86",
    },
    "secondary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.16471, 0.39216],
      hex: "#002a64",
    },
    "secondary-vivid-950": {
      colorSpace: "srgb",
      components: [0.00392, 0.11765, 0.28627],
      hex: "#011e49",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.98824, 0.96078, 0.96078],
      hex: "#fcf5f5",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.96471, 0.91373, 0.91373],
      hex: "#f6e9e9",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.9098, 0.82745, 0.82745],
      hex: "#e8d3d3",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.82745, 0.72157, 0.72157],
      hex: "#d3b8b8",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.72549, 0.60392, 0.60392],
      hex: "#b99a9a",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.61176, 0.4902, 0.4902],
      hex: "#9c7d7d",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.50588, 0.38824, 0.38824],
      hex: "#816363",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0.40784, 0.30196, 0.30588],
      hex: "#684d4e",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0.31765, 0.22745, 0.22745],
      hex: "#513a3a",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0.22745, 0.16078, 0.16078],
      hex: "#3a2929",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0.16471, 0.1098, 0.11373],
      hex: "#2a1c1d",
    },
    "tertiary-muted-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.96471, 0.96471],
      hex: "#f9f6f6",
    },
    "tertiary-muted-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.92157, 0.92157],
      hex: "#f1ebeb",
    },
    "tertiary-muted-200": {
      colorSpace: "srgb",
      components: [0.87843, 0.83922, 0.83922],
      hex: "#e0d6d6",
    },
    "tertiary-muted-300": {
      colorSpace: "srgb",
      components: [0.78431, 0.73725, 0.73725],
      hex: "#c8bcbc",
    },
    "tertiary-muted-400": {
      colorSpace: "srgb",
      components: [0.67843, 0.62353, 0.62353],
      hex: "#ad9f9f",
    },
    "tertiary-muted-500": {
      colorSpace: "srgb",
      components: [0.56471, 0.5098, 0.5098],
      hex: "#908282",
    },
    "tertiary-muted-600": {
      colorSpace: "srgb",
      components: [0.45882, 0.40784, 0.40784],
      hex: "#756868",
    },
    "tertiary-muted-700": {
      colorSpace: "srgb",
      components: [0.36863, 0.32157, 0.32157],
      hex: "#5e5252",
    },
    "tertiary-muted-800": {
      colorSpace: "srgb",
      components: [0.28235, 0.24314, 0.24314],
      hex: "#483e3e",
    },
    "tertiary-muted-900": {
      colorSpace: "srgb",
      components: [0.20392, 0.16863, 0.16863],
      hex: "#342b2b",
    },
    "tertiary-muted-950": {
      colorSpace: "srgb",
      components: [0.1451, 0.12157, 0.12157],
      hex: "#251f1f",
    },
    "tertiary-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95686],
      hex: "#fff4f4",
    },
    "tertiary-vivid-100": {
      colorSpace: "srgb",
      components: [0.98039, 0.9098, 0.9098],
      hex: "#fae8e8",
    },
    "tertiary-vivid-200": {
      colorSpace: "srgb",
      components: [0.93333, 0.81961, 0.81961],
      hex: "#eed1d1",
    },
    "tertiary-vivid-300": {
      colorSpace: "srgb",
      components: [0.8549, 0.7098, 0.7098],
      hex: "#dab5b5",
    },
    "tertiary-vivid-400": {
      colorSpace: "srgb",
      components: [0.75686, 0.59216, 0.59216],
      hex: "#c19797",
    },
    "tertiary-vivid-500": {
      colorSpace: "srgb",
      components: [0.64314, 0.47843, 0.47843],
      hex: "#a47a7a",
    },
    "tertiary-vivid-600": {
      colorSpace: "srgb",
      components: [0.53333, 0.37255, 0.37647],
      hex: "#885f60",
    },
    "tertiary-vivid-700": {
      colorSpace: "srgb",
      components: [0.43529, 0.2902, 0.29412],
      hex: "#6f4a4b",
    },
    "tertiary-vivid-800": {
      colorSpace: "srgb",
      components: [0.33725, 0.21569, 0.21961],
      hex: "#563738",
    },
    "tertiary-vivid-900": {
      colorSpace: "srgb",
      components: [0.24706, 0.14902, 0.15294],
      hex: "#3f2627",
    },
    "tertiary-vivid-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.10588, 0.10588],
      hex: "#2d1b1b",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96471],
      hex: "#fff3f6",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.92157],
      hex: "#ffe5eb",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [1, 0.78431, 0.83529],
      hex: "#ffc8d5",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [0.96863, 0.64314, 0.72549],
      hex: "#f7a4b9",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [0.87451, 0.51373, 0.61176],
      hex: "#df839c",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.76078, 0.39216, 0.49804],
      hex: "#c2647f",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.64314, 0.28627, 0.39608],
      hex: "#a44965",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.52941, 0.20392, 0.3098],
      hex: "#87344f",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.41961, 0.14118, 0.23529],
      hex: "#6b243c",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.3098, 0.08627, 0.16471],
      hex: "#4f162a",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.22353, 0.05882, 0.11373],
      hex: "#390f1d",
    },
    "error-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.96471],
      hex: "#fff4f6",
    },
    "error-muted-100": {
      colorSpace: "srgb",
      components: [0.98039, 0.90588, 0.92157],
      hex: "#fae7eb",
    },
    "error-muted-200": {
      colorSpace: "srgb",
      components: [0.92941, 0.81569, 0.84314],
      hex: "#edd0d7",
    },
    "error-muted-300": {
      colorSpace: "srgb",
      components: [0.8549, 0.70588, 0.74118],
      hex: "#dab4bd",
    },
    "error-muted-400": {
      colorSpace: "srgb",
      components: [0.75294, 0.58824, 0.62745],
      hex: "#c096a0",
    },
    "error-muted-500": {
      colorSpace: "srgb",
      components: [0.64314, 0.47059, 0.51373],
      hex: "#a47883",
    },
    "error-muted-600": {
      colorSpace: "srgb",
      components: [0.53333, 0.36863, 0.41176],
      hex: "#885e69",
    },
    "error-muted-700": {
      colorSpace: "srgb",
      components: [0.43137, 0.28627, 0.32549],
      hex: "#6e4953",
    },
    "error-muted-800": {
      colorSpace: "srgb",
      components: [0.33725, 0.21569, 0.24706],
      hex: "#56373f",
    },
    "error-muted-900": {
      colorSpace: "srgb",
      components: [0.24314, 0.1451, 0.17255],
      hex: "#3e252c",
    },
    "error-muted-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.10196, 0.12157],
      hex: "#2d1a1f",
    },
    "error-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96471],
      hex: "#fff3f6",
    },
    "error-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.92157],
      hex: "#ffe5eb",
    },
    "error-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.78431, 0.83529],
      hex: "#ffc8d5",
    },
    "error-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.61961, 0.72157],
      hex: "#ff9eb8",
    },
    "error-vivid-400": {
      colorSpace: "srgb",
      components: [0.95686, 0.44314, 0.60392],
      hex: "#f4719a",
    },
    "error-vivid-500": {
      colorSpace: "srgb",
      components: [0.83922, 0.3098, 0.4902],
      hex: "#d64f7d",
    },
    "error-vivid-600": {
      colorSpace: "srgb",
      components: [0.71373, 0.19216, 0.38824],
      hex: "#b63163",
    },
    "error-vivid-700": {
      colorSpace: "srgb",
      components: [0.59216, 0.10196, 0.30196],
      hex: "#971a4d",
    },
    "error-vivid-800": {
      colorSpace: "srgb",
      components: [0.47451, 0.02745, 0.22745],
      hex: "#79073a",
    },
    "error-vivid-900": {
      colorSpace: "srgb",
      components: [0.34902, 0, 0.15686],
      hex: "#590028",
    },
    "error-vivid-950": {
      colorSpace: "srgb",
      components: [0.2549, 0.00784, 0.1098],
      hex: "#41021c",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.93333, 0.98431, 0.92941],
      hex: "#eefbed",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.87059, 0.95686, 0.86275],
      hex: "#def4dc",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.75686, 0.89804, 0.74902],
      hex: "#c1e5bf",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.61961, 0.80784, 0.61176],
      hex: "#9ece9c",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.4902, 0.70196, 0.48235],
      hex: "#7db37b",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.36863, 0.58824, 0.36078],
      hex: "#5e965c",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0.26275, 0.48235, 0.26275],
      hex: "#437b43",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0.18431, 0.38824, 0.18431],
      hex: "#2f632f",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0.12549, 0.30196, 0.12549],
      hex: "#204d20",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0.07451, 0.21569, 0.07451],
      hex: "#133713",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0.05098, 0.15294, 0.05098],
      hex: "#0d270d",
    },
    "success-muted-50": {
      colorSpace: "srgb",
      components: [0.95294, 0.97647, 0.94902],
      hex: "#f3f9f2",
    },
    "success-muted-100": {
      colorSpace: "srgb",
      components: [0.90196, 0.94118, 0.89804],
      hex: "#e6f0e5",
    },
    "success-muted-200": {
      colorSpace: "srgb",
      components: [0.81176, 0.87059, 0.80784],
      hex: "#cfdece",
    },
    "success-muted-300": {
      colorSpace: "srgb",
      components: [0.69412, 0.77647, 0.6902],
      hex: "#b1c6b0",
    },
    "success-muted-400": {
      colorSpace: "srgb",
      components: [0.57647, 0.67059, 0.57255],
      hex: "#93ab92",
    },
    "success-muted-500": {
      colorSpace: "srgb",
      components: [0.46275, 0.55686, 0.4549],
      hex: "#768e74",
    },
    "success-muted-600": {
      colorSpace: "srgb",
      components: [0.36078, 0.45098, 0.35686],
      hex: "#5c735b",
    },
    "success-muted-700": {
      colorSpace: "srgb",
      components: [0.27843, 0.36078, 0.27451],
      hex: "#475c46",
    },
    "success-muted-800": {
      colorSpace: "srgb",
      components: [0.20392, 0.27843, 0.20392],
      hex: "#344734",
    },
    "success-muted-900": {
      colorSpace: "srgb",
      components: [0.14118, 0.19608, 0.13725],
      hex: "#243223",
    },
    "success-muted-950": {
      colorSpace: "srgb",
      components: [0.09804, 0.14118, 0.09804],
      hex: "#192419",
    },
    "success-vivid-50": {
      colorSpace: "srgb",
      components: [0.92157, 0.99216, 0.91373],
      hex: "#ebfde9",
    },
    "success-vivid-100": {
      colorSpace: "srgb",
      components: [0.84314, 0.96863, 0.83922],
      hex: "#d7f7d6",
    },
    "success-vivid-200": {
      colorSpace: "srgb",
      components: [0.71765, 0.91373, 0.70588],
      hex: "#b7e9b4",
    },
    "success-vivid-300": {
      colorSpace: "srgb",
      components: [0.56078, 0.83137, 0.55294],
      hex: "#8fd48d",
    },
    "success-vivid-400": {
      colorSpace: "srgb",
      components: [0.41176, 0.72549, 0.40784],
      hex: "#69b968",
    },
    "success-vivid-500": {
      colorSpace: "srgb",
      components: [0.27843, 0.61176, 0.28235],
      hex: "#479c48",
    },
    "success-vivid-600": {
      colorSpace: "srgb",
      components: [0.16078, 0.50196, 0.17255],
      hex: "#29802c",
    },
    "success-vivid-700": {
      colorSpace: "srgb",
      components: [0.06667, 0.40392, 0.09412],
      hex: "#116718",
    },
    "success-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.31373, 0.03529],
      hex: "#005009",
    },
    "success-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.01569],
      hex: "#003904",
    },
    "success-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.00784],
      hex: "#002902",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.93333],
      hex: "#fff4ee",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [1, 0.9098, 0.8549],
      hex: "#ffe8da",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.97255, 0.81569, 0.72157],
      hex: "#f8d0b8",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.90588, 0.69804, 0.57255],
      hex: "#e7b292",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.81176, 0.58039, 0.43529],
      hex: "#cf946f",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.69804, 0.46275, 0.31373],
      hex: "#b27650",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.58431, 0.36078, 0.21176],
      hex: "#955c36",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.47843, 0.27451, 0.13725],
      hex: "#7a4623",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.37647, 0.20392, 0.08235],
      hex: "#603415",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.27451, 0.13725, 0.03922],
      hex: "#46230a",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.2, 0.09804, 0.02745],
      hex: "#331907",
    },
    "warning-muted-50": {
      colorSpace: "srgb",
      components: [0.98824, 0.96078, 0.9451],
      hex: "#fcf5f1",
    },
    "warning-muted-100": {
      colorSpace: "srgb",
      components: [0.96471, 0.91765, 0.8902],
      hex: "#f6eae3",
    },
    "warning-muted-200": {
      colorSpace: "srgb",
      components: [0.90588, 0.83529, 0.79216],
      hex: "#e7d5ca",
    },
    "warning-muted-300": {
      colorSpace: "srgb",
      components: [0.82353, 0.72941, 0.67451],
      hex: "#d2baac",
    },
    "warning-muted-400": {
      colorSpace: "srgb",
      components: [0.72157, 0.61569, 0.55294],
      hex: "#b89d8d",
    },
    "warning-muted-500": {
      colorSpace: "srgb",
      components: [0.60784, 0.50196, 0.43529],
      hex: "#9b806f",
    },
    "warning-muted-600": {
      colorSpace: "srgb",
      components: [0.50196, 0.39608, 0.33725],
      hex: "#806556",
    },
    "warning-muted-700": {
      colorSpace: "srgb",
      components: [0.40392, 0.3098, 0.2549],
      hex: "#674f41",
    },
    "warning-muted-800": {
      colorSpace: "srgb",
      components: [0.31373, 0.23529, 0.18824],
      hex: "#503c30",
    },
    "warning-muted-900": {
      colorSpace: "srgb",
      components: [0.22745, 0.16471, 0.12549],
      hex: "#3a2a20",
    },
    "warning-muted-950": {
      colorSpace: "srgb",
      components: [0.16078, 0.11373, 0.08627],
      hex: "#291d16",
    },
    "warning-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.93333],
      hex: "#fff4ee",
    },
    "warning-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.9098, 0.8549],
      hex: "#ffe8da",
    },
    "warning-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.80392, 0.68627],
      hex: "#ffcdaf",
    },
    "warning-vivid-300": {
      colorSpace: "srgb",
      components: [0.96471, 0.67451, 0.49412],
      hex: "#f6ac7e",
    },
    "warning-vivid-400": {
      colorSpace: "srgb",
      components: [0.87451, 0.54902, 0.33725],
      hex: "#df8c56",
    },
    "warning-vivid-500": {
      colorSpace: "srgb",
      components: [0.76078, 0.42745, 0.19608],
      hex: "#c26d32",
    },
    "warning-vivid-600": {
      colorSpace: "srgb",
      components: [0.64314, 0.32157, 0.0549],
      hex: "#a4520e",
    },
    "warning-vivid-700": {
      colorSpace: "srgb",
      components: [0.52157, 0.24706, 0],
      hex: "#853f00",
    },
    "warning-vivid-800": {
      colorSpace: "srgb",
      components: [0.40392, 0.18431, 0],
      hex: "#672f00",
    },
    "warning-vivid-900": {
      colorSpace: "srgb",
      components: [0.2902, 0.12549, 0],
      hex: "#4a2000",
    },
    "warning-vivid-950": {
      colorSpace: "srgb",
      components: [0.21569, 0.08627, 0],
      hex: "#371600",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.96471, 0.96471, 0.98431],
      hex: "#f6f6fb",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.92549, 0.92549, 0.95686],
      hex: "#ececf4",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.84706, 0.84314, 0.89804],
      hex: "#d8d7e5",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.7451, 0.74118, 0.81176],
      hex: "#bebdcf",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.63529, 0.63137, 0.7098],
      hex: "#a2a1b5",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.52157, 0.51765, 0.59608],
      hex: "#858498",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.41569, 0.41176, 0.4902],
      hex: "#6a697d",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.32941, 0.32549, 0.39608],
      hex: "#545365",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.25098, 0.24706, 0.30588],
      hex: "#403f4e",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.17647, 0.17255, 0.21961],
      hex: "#2d2c38",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.12549, 0.12157, 0.15686],
      hex: "#201f28",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.96078, 0.96471, 0.98824],
      hex: "#f5f6fc",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.92157, 0.92549, 0.96471],
      hex: "#ebecf6",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.83922, 0.84706, 0.90588],
      hex: "#d6d8e7",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.73333, 0.7451, 0.82353],
      hex: "#bbbed2",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.61961, 0.63137, 0.72157],
      hex: "#9ea1b8",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.50588, 0.51765, 0.60784],
      hex: "#81849b",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.40392, 0.41569, 0.50196],
      hex: "#676a80",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.31765, 0.32941, 0.40392],
      hex: "#515467",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.24314, 0.25098, 0.31373],
      hex: "#3e4050",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.16863, 0.17647, 0.22745],
      hex: "#2b2d3a",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.11765, 0.12549, 0.16078],
      hex: "#1e2029",
    },
  },
} satisfies AuroraLayer;
