/**
 * Cyberdream — Neon blue and violet on graphite, from the Cyberdream colorscheme.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "cyberdream",
  name: "Cyberdream",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.96863, 1],
      hex: "#f2f7ff",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.93333, 1],
      hex: "#e1eeff",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [0.75686, 0.86275, 1],
      hex: "#c1dcff",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.58039, 0.76078, 1],
      hex: "#94c2ff",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.36863, 0.64706, 1],
      hex: "#5ea5ff",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.23137, 0.52549, 0.8902],
      hex: "#3b86e3",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.1098, 0.41569, 0.76863],
      hex: "#1c6ac4",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0.00784, 0.32549, 0.64706],
      hex: "#0253a5",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0, 0.24706, 0.50588],
      hex: "#003f81",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0, 0.17255, 0.36863],
      hex: "#002c5e",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0, 0.12157, 0.27451],
      hex: "#001f46",
    },
    "primary-muted-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.96863, 1],
      hex: "#f2f7ff",
    },
    "primary-muted-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.93333, 1],
      hex: "#e1eeff",
    },
    "primary-muted-200": {
      colorSpace: "srgb",
      components: [0.78039, 0.85882, 0.96471],
      hex: "#c7dbf6",
    },
    "primary-muted-300": {
      colorSpace: "srgb",
      components: [0.6549, 0.76078, 0.89804],
      hex: "#a7c2e5",
    },
    "primary-muted-400": {
      colorSpace: "srgb",
      components: [0.52941, 0.64706, 0.80392],
      hex: "#87a5cd",
    },
    "primary-muted-500": {
      colorSpace: "srgb",
      components: [0.41176, 0.53333, 0.69412],
      hex: "#6988b1",
    },
    "primary-muted-600": {
      colorSpace: "srgb",
      components: [0.31373, 0.43137, 0.58431],
      hex: "#506e95",
    },
    "primary-muted-700": {
      colorSpace: "srgb",
      components: [0.23529, 0.34118, 0.47843],
      hex: "#3c577a",
    },
    "primary-muted-800": {
      colorSpace: "srgb",
      components: [0.16863, 0.25882, 0.37647],
      hex: "#2b4260",
    },
    "primary-muted-900": {
      colorSpace: "srgb",
      components: [0.1098, 0.18431, 0.27451],
      hex: "#1c2f46",
    },
    "primary-muted-950": {
      colorSpace: "srgb",
      components: [0.07451, 0.12941, 0.2],
      hex: "#132133",
    },
    "primary-vivid-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.96863, 1],
      hex: "#f2f7ff",
    },
    "primary-vivid-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.93333, 1],
      hex: "#e1eeff",
    },
    "primary-vivid-200": {
      colorSpace: "srgb",
      components: [0.75686, 0.86275, 1],
      hex: "#c1dcff",
    },
    "primary-vivid-300": {
      colorSpace: "srgb",
      components: [0.58039, 0.76078, 1],
      hex: "#94c2ff",
    },
    "primary-vivid-400": {
      colorSpace: "srgb",
      components: [0.36863, 0.64706, 1],
      hex: "#5ea5ff",
    },
    "primary-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.51373, 0.99608],
      hex: "#0083fe",
    },
    "primary-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.41176, 0.80784],
      hex: "#0069ce",
    },
    "primary-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.32549, 0.65098],
      hex: "#0053a6",
    },
    "primary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.24706, 0.50588],
      hex: "#003f81",
    },
    "primary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.17255, 0.36863],
      hex: "#002c5e",
    },
    "primary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.12157, 0.27451],
      hex: "#001f46",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.95686, 1],
      hex: "#f9f4ff",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.95294, 0.90588, 1],
      hex: "#f3e7ff",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.90196, 0.80392, 1],
      hex: "#e6cdff",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.83922, 0.66275, 1],
      hex: "#d6a9ff",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.76863, 0.48627, 1],
      hex: "#c47cff",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.67843, 0.3098, 0.94118],
      hex: "#ad4ff0",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0.56863, 0.17647, 0.81961],
      hex: "#912dd1",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0.46667, 0.06667, 0.6902],
      hex: "#7711b0",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0.36471, 0, 0.54902],
      hex: "#5d008c",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0.26275, 0, 0.40392],
      hex: "#430067",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0.19216, 0, 0.30196],
      hex: "#31004d",
    },
    "secondary-muted-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.95686, 1],
      hex: "#f9f4ff",
    },
    "secondary-muted-100": {
      colorSpace: "srgb",
      components: [0.95294, 0.90588, 1],
      hex: "#f3e7ff",
    },
    "secondary-muted-200": {
      colorSpace: "srgb",
      components: [0.89412, 0.81176, 0.98039],
      hex: "#e4cffa",
    },
    "secondary-muted-300": {
      colorSpace: "srgb",
      components: [0.81176, 0.69412, 0.92157],
      hex: "#cfb1eb",
    },
    "secondary-muted-400": {
      colorSpace: "srgb",
      components: [0.70588, 0.57255, 0.83137],
      hex: "#b492d4",
    },
    "secondary-muted-500": {
      colorSpace: "srgb",
      components: [0.59608, 0.4549, 0.71765],
      hex: "#9874b7",
    },
    "secondary-muted-600": {
      colorSpace: "srgb",
      components: [0.48627, 0.35294, 0.60784],
      hex: "#7c5a9b",
    },
    "secondary-muted-700": {
      colorSpace: "srgb",
      components: [0.39216, 0.27059, 0.49804],
      hex: "#64457f",
    },
    "secondary-muted-800": {
      colorSpace: "srgb",
      components: [0.30588, 0.2, 0.39608],
      hex: "#4e3365",
    },
    "secondary-muted-900": {
      colorSpace: "srgb",
      components: [0.21961, 0.13333, 0.2902],
      hex: "#38224a",
    },
    "secondary-muted-950": {
      colorSpace: "srgb",
      components: [0.15686, 0.09412, 0.21176],
      hex: "#281836",
    },
    "secondary-vivid-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.95686, 1],
      hex: "#f9f4ff",
    },
    "secondary-vivid-100": {
      colorSpace: "srgb",
      components: [0.95294, 0.90588, 1],
      hex: "#f3e7ff",
    },
    "secondary-vivid-200": {
      colorSpace: "srgb",
      components: [0.90196, 0.80392, 1],
      hex: "#e6cdff",
    },
    "secondary-vivid-300": {
      colorSpace: "srgb",
      components: [0.83922, 0.66275, 1],
      hex: "#d6a9ff",
    },
    "secondary-vivid-400": {
      colorSpace: "srgb",
      components: [0.76863, 0.48627, 1],
      hex: "#c47cff",
    },
    "secondary-vivid-500": {
      colorSpace: "srgb",
      components: [0.70196, 0.23529, 1],
      hex: "#b33cff",
    },
    "secondary-vivid-600": {
      colorSpace: "srgb",
      components: [0.59216, 0, 0.87843],
      hex: "#9700e0",
    },
    "secondary-vivid-700": {
      colorSpace: "srgb",
      components: [0.47059, 0, 0.70588],
      hex: "#7800b4",
    },
    "secondary-vivid-800": {
      colorSpace: "srgb",
      components: [0.36471, 0, 0.54902],
      hex: "#5d008c",
    },
    "secondary-vivid-900": {
      colorSpace: "srgb",
      components: [0.26275, 0, 0.40392],
      hex: "#430067",
    },
    "secondary-vivid-950": {
      colorSpace: "srgb",
      components: [0.19216, 0, 0.30196],
      hex: "#31004d",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.90588, 0.98431, 0.99216],
      hex: "#e7fbfd",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.82353, 0.96078, 0.97255],
      hex: "#d2f5f8",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.67843, 0.89804, 0.91765],
      hex: "#ade5ea",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.50196, 0.81176, 0.83922],
      hex: "#80cfd6",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.32941, 0.70588, 0.73725],
      hex: "#54b4bc",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.16078, 0.59216, 0.62745],
      hex: "#2997a0",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0, 0.48235, 0.51373],
      hex: "#007b83",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0, 0.38039, 0.40784],
      hex: "#006168",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0, 0.29412, 0.31373],
      hex: "#004b50",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0, 0.20784, 0.22353],
      hex: "#003539",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0, 0.14902, 0.16078],
      hex: "#002629",
    },
    "tertiary-muted-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.97647, 0.98039],
      hex: "#f0f9fa",
    },
    "tertiary-muted-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.94118, 0.94902],
      hex: "#e1f0f2",
    },
    "tertiary-muted-200": {
      colorSpace: "srgb",
      components: [0.77647, 0.87059, 0.88235],
      hex: "#c6dee1",
    },
    "tertiary-muted-300": {
      colorSpace: "srgb",
      components: [0.65098, 0.77647, 0.78824],
      hex: "#a6c6c9",
    },
    "tertiary-muted-400": {
      colorSpace: "srgb",
      components: [0.52549, 0.67059, 0.68235],
      hex: "#86abae",
    },
    "tertiary-muted-500": {
      colorSpace: "srgb",
      components: [0.40784, 0.55686, 0.57255],
      hex: "#688e92",
    },
    "tertiary-muted-600": {
      colorSpace: "srgb",
      components: [0.30588, 0.45098, 0.46667],
      hex: "#4e7377",
    },
    "tertiary-muted-700": {
      colorSpace: "srgb",
      components: [0.22745, 0.36078, 0.37255],
      hex: "#3a5c5f",
    },
    "tertiary-muted-800": {
      colorSpace: "srgb",
      components: [0.16078, 0.27843, 0.2902],
      hex: "#29474a",
    },
    "tertiary-muted-900": {
      colorSpace: "srgb",
      components: [0.10588, 0.19608, 0.20784],
      hex: "#1b3235",
    },
    "tertiary-muted-950": {
      colorSpace: "srgb",
      components: [0.07059, 0.14118, 0.1451],
      hex: "#122425",
    },
    "tertiary-vivid-50": {
      colorSpace: "srgb",
      components: [0.8902, 0.99216, 1],
      hex: "#e3fdff",
    },
    "tertiary-vivid-100": {
      colorSpace: "srgb",
      components: [0.77647, 0.97255, 0.98824],
      hex: "#c6f8fc",
    },
    "tertiary-vivid-200": {
      colorSpace: "srgb",
      components: [0.59608, 0.91373, 0.9451],
      hex: "#98e9f1",
    },
    "tertiary-vivid-300": {
      colorSpace: "srgb",
      components: [0.34902, 0.83137, 0.87451],
      hex: "#59d4df",
    },
    "tertiary-vivid-400": {
      colorSpace: "srgb",
      components: [0, 0.72549, 0.77255],
      hex: "#00b9c5",
    },
    "tertiary-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.59608, 0.63529],
      hex: "#0098a2",
    },
    "tertiary-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.48235, 0.51373],
      hex: "#007b83",
    },
    "tertiary-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.38039, 0.40784],
      hex: "#006168",
    },
    "tertiary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.29412, 0.31373],
      hex: "#004b50",
    },
    "tertiary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.20784, 0.22353],
      hex: "#003539",
    },
    "tertiary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.14902, 0.16078],
      hex: "#002629",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.88627],
      hex: "#ffe6e2",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [1, 0.79608, 0.76078],
      hex: "#ffcbc2",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [1, 0.63922, 0.58824],
      hex: "#ffa396",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [0.96863, 0.46275, 0.4],
      hex: "#f77666",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.85098, 0.32941, 0.27451],
      hex: "#d95446",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.72941, 0.21569, 0.17255],
      hex: "#ba372c",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.60392, 0.12549, 0.09412],
      hex: "#9a2018",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.48235, 0.0549, 0.03922],
      hex: "#7b0e0a",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.35686, 0.01569, 0.01176],
      hex: "#5b0403",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.26275, 0.01569, 0.01176],
      hex: "#430403",
    },
    "error-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-muted-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.88627],
      hex: "#ffe6e2",
    },
    "error-muted-200": {
      colorSpace: "srgb",
      components: [0.96471, 0.80784, 0.78431],
      hex: "#f6cec8",
    },
    "error-muted-300": {
      colorSpace: "srgb",
      components: [0.89804, 0.69412, 0.65882],
      hex: "#e5b1a8",
    },
    "error-muted-400": {
      colorSpace: "srgb",
      components: [0.80392, 0.57255, 0.53725],
      hex: "#cd9289",
    },
    "error-muted-500": {
      colorSpace: "srgb",
      components: [0.6902, 0.45882, 0.42353],
      hex: "#b0756c",
    },
    "error-muted-600": {
      colorSpace: "srgb",
      components: [0.57647, 0.35294, 0.32157],
      hex: "#935a52",
    },
    "error-muted-700": {
      colorSpace: "srgb",
      components: [0.47059, 0.27059, 0.24314],
      hex: "#78453e",
    },
    "error-muted-800": {
      colorSpace: "srgb",
      components: [0.37255, 0.2, 0.17647],
      hex: "#5f332d",
    },
    "error-muted-900": {
      colorSpace: "srgb",
      components: [0.27059, 0.13725, 0.11765],
      hex: "#45231e",
    },
    "error-muted-950": {
      colorSpace: "srgb",
      components: [0.19608, 0.09412, 0.08235],
      hex: "#321815",
    },
    "error-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.88627],
      hex: "#ffe6e2",
    },
    "error-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.79608, 0.76078],
      hex: "#ffcbc2",
    },
    "error-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.63922, 0.58824],
      hex: "#ffa396",
    },
    "error-vivid-400": {
      colorSpace: "srgb",
      components: [1, 0.43529, 0.37255],
      hex: "#ff6f5f",
    },
    "error-vivid-500": {
      colorSpace: "srgb",
      components: [0.95686, 0.1451, 0.11373],
      hex: "#f4251d",
    },
    "error-vivid-600": {
      colorSpace: "srgb",
      components: [0.8, 0, 0.01569],
      hex: "#cc0004",
    },
    "error-vivid-700": {
      colorSpace: "srgb",
      components: [0.63922, 0, 0.01176],
      hex: "#a30003",
    },
    "error-vivid-800": {
      colorSpace: "srgb",
      components: [0.49804, 0, 0.00392],
      hex: "#7f0001",
    },
    "error-vivid-900": {
      colorSpace: "srgb",
      components: [0.36471, 0, 0.00392],
      hex: "#5d0001",
    },
    "error-vivid-950": {
      colorSpace: "srgb",
      components: [0.27059, 0, 0],
      hex: "#450000",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.9098, 0.99608, 0.9098],
      hex: "#e8fee8",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.82353, 0.97647, 0.82745],
      hex: "#d2f9d3",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.68235, 0.92549, 0.6902],
      hex: "#aeecb0",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.50588, 0.84314, 0.52549],
      hex: "#81d786",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.33725, 0.74118, 0.37255],
      hex: "#56bd5f",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.17255, 0.62745, 0.23922],
      hex: "#2ca03d",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0, 0.51373, 0.14118],
      hex: "#008324",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0, 0.40784, 0.10196],
      hex: "#00681a",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0, 0.31373, 0.07059],
      hex: "#005012",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.03922],
      hex: "#00390a",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.02353],
      hex: "#002906",
    },
    "success-muted-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.98039, 0.94118],
      hex: "#f0faf0",
    },
    "success-muted-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.94902, 0.88235],
      hex: "#e1f2e1",
    },
    "success-muted-200": {
      colorSpace: "srgb",
      components: [0.78039, 0.88627, 0.78039],
      hex: "#c7e2c7",
    },
    "success-muted-300": {
      colorSpace: "srgb",
      components: [0.65098, 0.79608, 0.6549],
      hex: "#a6cba7",
    },
    "success-muted-400": {
      colorSpace: "srgb",
      components: [0.52549, 0.6902, 0.52941],
      hex: "#86b087",
    },
    "success-muted-500": {
      colorSpace: "srgb",
      components: [0.40784, 0.57647, 0.41569],
      hex: "#68936a",
    },
    "success-muted-600": {
      colorSpace: "srgb",
      components: [0.30588, 0.47059, 0.31373],
      hex: "#4e7850",
    },
    "success-muted-700": {
      colorSpace: "srgb",
      components: [0.22745, 0.37647, 0.23529],
      hex: "#3a603c",
    },
    "success-muted-800": {
      colorSpace: "srgb",
      components: [0.16078, 0.2902, 0.16863],
      hex: "#294a2b",
    },
    "success-muted-900": {
      colorSpace: "srgb",
      components: [0.10588, 0.20784, 0.1098],
      hex: "#1b351c",
    },
    "success-muted-950": {
      colorSpace: "srgb",
      components: [0.07059, 0.14902, 0.07843],
      hex: "#122614",
    },
    "success-vivid-50": {
      colorSpace: "srgb",
      components: [0.90196, 1, 0.90196],
      hex: "#e6ffe6",
    },
    "success-vivid-100": {
      colorSpace: "srgb",
      components: [0.78039, 0.99608, 0.78431],
      hex: "#c7fec8",
    },
    "success-vivid-200": {
      colorSpace: "srgb",
      components: [0.6, 0.94902, 0.61569],
      hex: "#99f29d",
    },
    "success-vivid-300": {
      colorSpace: "srgb",
      components: [0.35686, 0.87451, 0.41569],
      hex: "#5bdf6a",
    },
    "success-vivid-400": {
      colorSpace: "srgb",
      components: [0, 0.77255, 0.22745],
      hex: "#00c53a",
    },
    "success-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.63529, 0.18039],
      hex: "#00a22e",
    },
    "success-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.51373, 0.14118],
      hex: "#008324",
    },
    "success-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.40784, 0.10196],
      hex: "#00681a",
    },
    "success-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.31373, 0.07059],
      hex: "#005012",
    },
    "success-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.03922],
      hex: "#00390a",
    },
    "success-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.02353],
      hex: "#002906",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.91373],
      hex: "#fff5e9",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [1, 0.91373, 0.80392],
      hex: "#ffe9cd",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.96471, 0.82745, 0.65098],
      hex: "#f6d3a6",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.89804, 0.71373, 0.47059],
      hex: "#e5b678",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.80392, 0.59608, 0.30588],
      hex: "#cd984e",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.6902, 0.47843, 0.14902],
      hex: "#b07a26",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.57255, 0.37647, 0],
      hex: "#926000",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.4549, 0.29804, 0],
      hex: "#744c00",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.35294, 0.22353, 0],
      hex: "#5a3900",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.2549, 0.15686, 0],
      hex: "#412800",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.18431, 0.1098, 0],
      hex: "#2f1c00",
    },
    "warning-muted-50": {
      colorSpace: "srgb",
      components: [0.98824, 0.96471, 0.93333],
      hex: "#fcf6ee",
    },
    "warning-muted-100": {
      colorSpace: "srgb",
      components: [0.96078, 0.92157, 0.87451],
      hex: "#f5ebdf",
    },
    "warning-muted-200": {
      colorSpace: "srgb",
      components: [0.90196, 0.83922, 0.76471],
      hex: "#e6d6c3",
    },
    "warning-muted-300": {
      colorSpace: "srgb",
      components: [0.81961, 0.73725, 0.63137],
      hex: "#d1bca1",
    },
    "warning-muted-400": {
      colorSpace: "srgb",
      components: [0.71373, 0.62353, 0.50588],
      hex: "#b69f81",
    },
    "warning-muted-500": {
      colorSpace: "srgb",
      components: [0.60392, 0.5098, 0.38824],
      hex: "#9a8263",
    },
    "warning-muted-600": {
      colorSpace: "srgb",
      components: [0.49412, 0.40392, 0.28627],
      hex: "#7e6749",
    },
    "warning-muted-700": {
      colorSpace: "srgb",
      components: [0.4, 0.31765, 0.21176],
      hex: "#665136",
    },
    "warning-muted-800": {
      colorSpace: "srgb",
      components: [0.3098, 0.24314, 0.14902],
      hex: "#4f3e26",
    },
    "warning-muted-900": {
      colorSpace: "srgb",
      components: [0.22353, 0.16863, 0.09412],
      hex: "#392b18",
    },
    "warning-muted-950": {
      colorSpace: "srgb",
      components: [0.16078, 0.11765, 0.06275],
      hex: "#291e10",
    },
    "warning-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.91373],
      hex: "#fff5e9",
    },
    "warning-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.91373, 0.80392],
      hex: "#ffe9cd",
    },
    "warning-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.81569, 0.57647],
      hex: "#ffd093",
    },
    "warning-vivid-300": {
      colorSpace: "srgb",
      components: [0.95294, 0.69412, 0.32157],
      hex: "#f3b152",
    },
    "warning-vivid-400": {
      colorSpace: "srgb",
      components: [0.85882, 0.57255, 0],
      hex: "#db9200",
    },
    "warning-vivid-500": {
      colorSpace: "srgb",
      components: [0.7098, 0.47059, 0],
      hex: "#b57800",
    },
    "warning-vivid-600": {
      colorSpace: "srgb",
      components: [0.57255, 0.37647, 0],
      hex: "#926000",
    },
    "warning-vivid-700": {
      colorSpace: "srgb",
      components: [0.4549, 0.29804, 0],
      hex: "#744c00",
    },
    "warning-vivid-800": {
      colorSpace: "srgb",
      components: [0.35294, 0.22353, 0],
      hex: "#5a3900",
    },
    "warning-vivid-900": {
      colorSpace: "srgb",
      components: [0.2549, 0.15686, 0],
      hex: "#412800",
    },
    "warning-vivid-950": {
      colorSpace: "srgb",
      components: [0.18431, 0.1098, 0],
      hex: "#2f1c00",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.96471, 0.96863, 0.97255],
      hex: "#f6f7f8",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.92549, 0.92941, 0.93333],
      hex: "#ecedee",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.84706, 0.85098, 0.86275],
      hex: "#d8d9dc",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.74118, 0.74902, 0.76471],
      hex: "#bdbfc3",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.63137, 0.63922, 0.6549],
      hex: "#a1a3a7",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.51765, 0.52549, 0.54118],
      hex: "#84868a",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.41569, 0.42353, 0.43922],
      hex: "#6a6c70",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.32549, 0.33333, 0.34902],
      hex: "#535559",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.24706, 0.2549, 0.26667],
      hex: "#3f4144",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.17647, 0.18039, 0.18824],
      hex: "#2d2e30",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.12549, 0.12549, 0.13333],
      hex: "#202022",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.96863, 0.98431],
      hex: "#f4f7fb",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.91373, 0.92941, 0.96078],
      hex: "#e9edf5",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.82745, 0.85098, 0.89804],
      hex: "#d3d9e5",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.71765, 0.75294, 0.81569],
      hex: "#b7c0d0",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.60392, 0.63922, 0.7098],
      hex: "#9aa3b5",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.4902, 0.52549, 0.6],
      hex: "#7d8699",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.38824, 0.42353, 0.49412],
      hex: "#636c7e",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.30196, 0.33333, 0.39608],
      hex: "#4d5565",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.22745, 0.2549, 0.3098],
      hex: "#3a414f",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.16078, 0.18039, 0.22353],
      hex: "#292e39",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.1098, 0.12549, 0.15686],
      hex: "#1c2028",
    },
  },
} satisfies AuroraLayer;
