/**
 * Cyberdream — Neon blue and violet on graphite, from the Cyberdream colorscheme. Generated by scripts/generate.mjs from
 * scripts/seeds.json; regenerate with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the eight tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through its
 * ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "cyberdream",
  name: "Cyberdream",
  tokens: {
    "primary-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "primary-4": {
      colorSpace: "srgb",
      components: [0, 0.0549, 0.14118],
      hex: "#000e24",
    },
    "primary-6": {
      colorSpace: "srgb",
      components: [0, 0.07451, 0.17647],
      hex: "#00132d",
    },
    "primary-10": {
      colorSpace: "srgb",
      components: [0, 0.10588, 0.23529],
      hex: "#001b3c",
    },
    "primary-12": {
      colorSpace: "srgb",
      components: [0, 0.12157, 0.26275],
      hex: "#001f43",
    },
    "primary-17": {
      colorSpace: "srgb",
      components: [0, 0.16471, 0.33333],
      hex: "#002a55",
    },
    "primary-20": {
      colorSpace: "srgb",
      components: [0, 0.18824, 0.38039],
      hex: "#003061",
    },
    "primary-22": {
      colorSpace: "srgb",
      components: [0, 0.20784, 0.41176],
      hex: "#003569",
    },
    "primary-24": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.44314],
      hex: "#003971",
    },
    "primary-25": {
      colorSpace: "srgb",
      components: [0, 0.23137, 0.45882],
      hex: "#003b75",
    },
    "primary-30": {
      colorSpace: "srgb",
      components: [0, 0.27451, 0.53725],
      hex: "#004689",
    },
    "primary-35": {
      colorSpace: "srgb",
      components: [0, 0.32157, 0.61961],
      hex: "#00529e",
    },
    "primary-40": {
      colorSpace: "srgb",
      components: [0, 0.36863, 0.70196],
      hex: "#005eb3",
    },
    "primary-50": {
      colorSpace: "srgb",
      components: [0.16863, 0.46667, 0.82353],
      hex: "#2b77d2",
    },
    "primary-60": {
      colorSpace: "srgb",
      components: [0.29804, 0.56863, 0.93333],
      hex: "#4c91ee",
    },
    "primary-70": {
      colorSpace: "srgb",
      components: [0.46275, 0.67843, 1],
      hex: "#76adff",
    },
    "primary-80": {
      colorSpace: "srgb",
      components: [0.6549, 0.78431, 1],
      hex: "#a7c8ff",
    },
    "primary-87": {
      colorSpace: "srgb",
      components: [0.78431, 0.85882, 1],
      hex: "#c8dbff",
    },
    "primary-90": {
      colorSpace: "srgb",
      components: [0.83529, 0.8902, 1],
      hex: "#d5e3ff",
    },
    "primary-92": {
      colorSpace: "srgb",
      components: [0.87059, 0.9098, 1],
      hex: "#dee8ff",
    },
    "primary-94": {
      colorSpace: "srgb",
      components: [0.90588, 0.93333, 1],
      hex: "#e7eeff",
    },
    "primary-95": {
      colorSpace: "srgb",
      components: [0.92549, 0.9451, 1],
      hex: "#ecf1ff",
    },
    "primary-96": {
      colorSpace: "srgb",
      components: [0.94118, 0.95294, 1],
      hex: "#f0f3ff",
    },
    "primary-98": {
      colorSpace: "srgb",
      components: [0.97647, 0.97647, 1],
      hex: "#f9f9ff",
    },
    "primary-99": {
      colorSpace: "srgb",
      components: [0.99216, 0.98431, 1],
      hex: "#fdfbff",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "secondary-0": {
      colorSpace: "srgb",
      components: [0, 0, 0],
      hex: "#000000",
    },
    "secondary-4": {
      colorSpace: "srgb",
      components: [0.10588, 0, 0.18431],
      hex: "#1b002f",
    },
    "secondary-6": {
      colorSpace: "srgb",
      components: [0.13725, 0, 0.22745],
      hex: "#23003a",
    },
    "secondary-10": {
      colorSpace: "srgb",
      components: [0.18431, 0, 0.29804],
      hex: "#2f004c",
    },
    "secondary-12": {
      colorSpace: "srgb",
      components: [0.20784, 0, 0.33333],
      hex: "#350055",
    },
    "secondary-17": {
      colorSpace: "srgb",
      components: [0.26667, 0, 0.42353],
      hex: "#44006c",
    },
    "secondary-20": {
      colorSpace: "srgb",
      components: [0.30196, 0, 0.47843],
      hex: "#4d007a",
    },
    "secondary-22": {
      colorSpace: "srgb",
      components: [0.32941, 0, 0.51373],
      hex: "#540083",
    },
    "secondary-24": {
      colorSpace: "srgb",
      components: [0.35294, 0, 0.55294],
      hex: "#5a008d",
    },
    "secondary-25": {
      colorSpace: "srgb",
      components: [0.36471, 0, 0.57255],
      hex: "#5d0092",
    },
    "secondary-30": {
      colorSpace: "srgb",
      components: [0.43137, 0, 0.66667],
      hex: "#6e00aa",
    },
    "secondary-35": {
      colorSpace: "srgb",
      components: [0.49412, 0.04706, 0.75294],
      hex: "#7e0cc0",
    },
    "secondary-40": {
      colorSpace: "srgb",
      components: [0.5451, 0.1451, 0.80392],
      hex: "#8b25cd",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.65098, 0.27843, 0.9098],
      hex: "#a647e8",
    },
    "secondary-60": {
      colorSpace: "srgb",
      components: [0.75294, 0.40392, 1],
      hex: "#c067ff",
    },
    "secondary-70": {
      colorSpace: "srgb",
      components: [0.82353, 0.56471, 1],
      hex: "#d290ff",
    },
    "secondary-80": {
      colorSpace: "srgb",
      components: [0.8902, 0.7098, 1],
      hex: "#e3b5ff",
    },
    "secondary-87": {
      colorSpace: "srgb",
      components: [0.93333, 0.81176, 1],
      hex: "#eecfff",
    },
    "secondary-90": {
      colorSpace: "srgb",
      components: [0.95294, 0.8549, 1],
      hex: "#f3daff",
    },
    "secondary-92": {
      colorSpace: "srgb",
      components: [0.96863, 0.88235, 1],
      hex: "#f7e1ff",
    },
    "secondary-94": {
      colorSpace: "srgb",
      components: [0.98039, 0.9098, 1],
      hex: "#fae8ff",
    },
    "secondary-95": {
      colorSpace: "srgb",
      components: [0.98431, 0.92549, 1],
      hex: "#fbecff",
    },
    "secondary-96": {
      colorSpace: "srgb",
      components: [0.99216, 0.93725, 1],
      hex: "#fdefff",
    },
    "secondary-98": {
      colorSpace: "srgb",
      components: [1, 0.96863, 0.99216],
      hex: "#fff7fd",
    },
    "secondary-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "tertiary-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "tertiary-4": {
      colorSpace: "srgb",
      components: [0, 0.06667, 0.07451],
      hex: "#001113",
    },
    "tertiary-6": {
      colorSpace: "srgb",
      components: [0, 0.0902, 0.09804],
      hex: "#001719",
    },
    "tertiary-10": {
      colorSpace: "srgb",
      components: [0, 0.12549, 0.13333],
      hex: "#002022",
    },
    "tertiary-12": {
      colorSpace: "srgb",
      components: [0, 0.14118, 0.15294],
      hex: "#002427",
    },
    "tertiary-17": {
      colorSpace: "srgb",
      components: [0, 0.18431, 0.2],
      hex: "#002f33",
    },
    "tertiary-20": {
      colorSpace: "srgb",
      components: [0, 0.21176, 0.23137],
      hex: "#00363b",
    },
    "tertiary-22": {
      colorSpace: "srgb",
      components: [0, 0.23137, 0.25098],
      hex: "#003b40",
    },
    "tertiary-24": {
      colorSpace: "srgb",
      components: [0, 0.25098, 0.27059],
      hex: "#004045",
    },
    "tertiary-25": {
      colorSpace: "srgb",
      components: [0, 0.25882, 0.28235],
      hex: "#004248",
    },
    "tertiary-30": {
      colorSpace: "srgb",
      components: [0, 0.3098, 0.33333],
      hex: "#004f55",
    },
    "tertiary-35": {
      colorSpace: "srgb",
      components: [0, 0.36078, 0.38824],
      hex: "#005c63",
    },
    "tertiary-40": {
      colorSpace: "srgb",
      components: [0, 0.41176, 0.44314],
      hex: "#006971",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0, 0.51765, 0.55294],
      hex: "#00848d",
    },
    "tertiary-60": {
      colorSpace: "srgb",
      components: [0, 0.62745, 0.67059],
      hex: "#00a0ab",
    },
    "tertiary-70": {
      colorSpace: "srgb",
      components: [0, 0.74118, 0.79216],
      hex: "#00bdca",
    },
    "tertiary-80": {
      colorSpace: "srgb",
      components: [0.24314, 0.85098, 0.90588],
      hex: "#3ed9e7",
    },
    "tertiary-87": {
      colorSpace: "srgb",
      components: [0.35294, 0.93333, 0.98431],
      hex: "#5aeefb",
    },
    "tertiary-90": {
      colorSpace: "srgb",
      components: [0.51373, 0.95294, 1],
      hex: "#83f3ff",
    },
    "tertiary-92": {
      colorSpace: "srgb",
      components: [0.63529, 0.96471, 1],
      hex: "#a2f6ff",
    },
    "tertiary-94": {
      colorSpace: "srgb",
      components: [0.73725, 0.97255, 1],
      hex: "#bcf8ff",
    },
    "tertiary-95": {
      colorSpace: "srgb",
      components: [0.78431, 0.97647, 1],
      hex: "#c8f9ff",
    },
    "tertiary-96": {
      colorSpace: "srgb",
      components: [0.83137, 0.98431, 1],
      hex: "#d4fbff",
    },
    "tertiary-98": {
      colorSpace: "srgb",
      components: [0.91765, 0.99216, 1],
      hex: "#eafdff",
    },
    "tertiary-99": {
      colorSpace: "srgb",
      components: [0.95686, 0.99608, 1],
      hex: "#f4feff",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "error-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "error-4": {
      colorSpace: "srgb",
      components: [0.15686, 0, 0],
      hex: "#280000",
    },
    "error-6": {
      colorSpace: "srgb",
      components: [0.19216, 0, 0.00392],
      hex: "#310001",
    },
    "error-10": {
      colorSpace: "srgb",
      components: [0.2549, 0, 0.00392],
      hex: "#410001",
    },
    "error-12": {
      colorSpace: "srgb",
      components: [0.28627, 0, 0.00392],
      hex: "#490001",
    },
    "error-17": {
      colorSpace: "srgb",
      components: [0.36078, 0, 0.00784],
      hex: "#5c0002",
    },
    "error-20": {
      colorSpace: "srgb",
      components: [0.41176, 0, 0.01176],
      hex: "#690003",
    },
    "error-22": {
      colorSpace: "srgb",
      components: [0.43922, 0.00784, 0.01569],
      hex: "#700204",
    },
    "error-24": {
      colorSpace: "srgb",
      components: [0.46667, 0.03137, 0.02745],
      hex: "#770807",
    },
    "error-25": {
      colorSpace: "srgb",
      components: [0.47843, 0.04314, 0.03529],
      hex: "#7a0b09",
    },
    "error-30": {
      colorSpace: "srgb",
      components: [0.5451, 0.09804, 0.07451],
      hex: "#8b1913",
    },
    "error-35": {
      colorSpace: "srgb",
      components: [0.61176, 0.14902, 0.11765],
      hex: "#9c261e",
    },
    "error-40": {
      colorSpace: "srgb",
      components: [0.67451, 0.19608, 0.15686],
      hex: "#ac3228",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [0.80784, 0.2902, 0.23922],
      hex: "#ce4a3d",
    },
    "error-60": {
      colorSpace: "srgb",
      components: [0.94118, 0.38824, 0.32941],
      hex: "#f06354",
    },
    "error-70": {
      colorSpace: "srgb",
      components: [1, 0.54118, 0.48235],
      hex: "#ff8a7b",
    },
    "error-80": {
      colorSpace: "srgb",
      components: [1, 0.70588, 0.66667],
      hex: "#ffb4aa",
    },
    "error-87": {
      colorSpace: "srgb",
      components: [1, 0.81176, 0.78431],
      hex: "#ffcfc8",
    },
    "error-90": {
      colorSpace: "srgb",
      components: [1, 0.8549, 0.83529],
      hex: "#ffdad5",
    },
    "error-92": {
      colorSpace: "srgb",
      components: [1, 0.88627, 0.86667],
      hex: "#ffe2dd",
    },
    "error-94": {
      colorSpace: "srgb",
      components: [1, 0.91373, 0.90196],
      hex: "#ffe9e6",
    },
    "error-95": {
      colorSpace: "srgb",
      components: [1, 0.92941, 0.91765],
      hex: "#ffedea",
    },
    "error-96": {
      colorSpace: "srgb",
      components: [1, 0.94118, 0.93333],
      hex: "#fff0ee",
    },
    "error-98": {
      colorSpace: "srgb",
      components: [1, 0.97255, 0.96863],
      hex: "#fff8f7",
    },
    "error-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "error-100": { colorSpace: "srgb", components: [1, 1, 1], hex: "#ffffff" },
    "success-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "success-4": {
      colorSpace: "srgb",
      components: [0, 0.07059, 0.00784],
      hex: "#001202",
    },
    "success-6": {
      colorSpace: "srgb",
      components: [0, 0.09412, 0.00784],
      hex: "#001802",
    },
    "success-10": {
      colorSpace: "srgb",
      components: [0, 0.13333, 0.01569],
      hex: "#002204",
    },
    "success-12": {
      colorSpace: "srgb",
      components: [0, 0.14902, 0.01961],
      hex: "#002605",
    },
    "success-17": {
      colorSpace: "srgb",
      components: [0, 0.19608, 0.03137],
      hex: "#003208",
    },
    "success-20": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.03922],
      hex: "#00390a",
    },
    "success-22": {
      colorSpace: "srgb",
      components: [0, 0.24314, 0.04706],
      hex: "#003e0c",
    },
    "success-24": {
      colorSpace: "srgb",
      components: [0, 0.26275, 0.0549],
      hex: "#00430e",
    },
    "success-25": {
      colorSpace: "srgb",
      components: [0, 0.27451, 0.05882],
      hex: "#00460f",
    },
    "success-30": {
      colorSpace: "srgb",
      components: [0, 0.32549, 0.07451],
      hex: "#005313",
    },
    "success-35": {
      colorSpace: "srgb",
      components: [0, 0.37647, 0.09412],
      hex: "#006018",
    },
    "success-40": {
      colorSpace: "srgb",
      components: [0, 0.43137, 0.11373],
      hex: "#006e1d",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0, 0.54118, 0.14902],
      hex: "#008a26",
    },
    "success-60": {
      colorSpace: "srgb",
      components: [0, 0.65882, 0.19216],
      hex: "#00a831",
    },
    "success-70": {
      colorSpace: "srgb",
      components: [0, 0.77647, 0.23137],
      hex: "#00c63b",
    },
    "success-80": {
      colorSpace: "srgb",
      components: [0.23922, 0.8902, 0.32941],
      hex: "#3de354",
    },
    "success-87": {
      colorSpace: "srgb",
      components: [0.33725, 0.97255, 0.4],
      hex: "#56f866",
    },
    "success-90": {
      colorSpace: "srgb",
      components: [0.43922, 1, 0.46667],
      hex: "#70ff77",
    },
    "success-92": {
      colorSpace: "srgb",
      components: [0.60784, 1, 0.59216],
      hex: "#9bff97",
    },
    "success-94": {
      colorSpace: "srgb",
      components: [0.72941, 1, 0.70196],
      hex: "#baffb3",
    },
    "success-95": {
      colorSpace: "srgb",
      components: [0.78431, 1, 0.75294],
      hex: "#c8ffc0",
    },
    "success-96": {
      colorSpace: "srgb",
      components: [0.83529, 1, 0.8],
      hex: "#d5ffcc",
    },
    "success-98": {
      colorSpace: "srgb",
      components: [0.92549, 1, 0.89412],
      hex: "#ecffe4",
    },
    "success-99": {
      colorSpace: "srgb",
      components: [0.96471, 1, 0.94118],
      hex: "#f6fff0",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "warning-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "warning-4": {
      colorSpace: "srgb",
      components: [0.0902, 0.04706, 0],
      hex: "#170c00",
    },
    "warning-6": {
      colorSpace: "srgb",
      components: [0.11765, 0.06275, 0],
      hex: "#1e1000",
    },
    "warning-10": {
      colorSpace: "srgb",
      components: [0.16078, 0.09412, 0],
      hex: "#291800",
    },
    "warning-12": {
      colorSpace: "srgb",
      components: [0.18431, 0.1098, 0],
      hex: "#2f1c00",
    },
    "warning-17": {
      colorSpace: "srgb",
      components: [0.23529, 0.1451, 0],
      hex: "#3c2500",
    },
    "warning-20": {
      colorSpace: "srgb",
      components: [0.27059, 0.16863, 0],
      hex: "#452b00",
    },
    "warning-22": {
      colorSpace: "srgb",
      components: [0.29412, 0.18431, 0],
      hex: "#4b2f00",
    },
    "warning-24": {
      colorSpace: "srgb",
      components: [0.31765, 0.2, 0],
      hex: "#513300",
    },
    "warning-25": {
      colorSpace: "srgb",
      components: [0.32941, 0.20784, 0],
      hex: "#543500",
    },
    "warning-30": {
      colorSpace: "srgb",
      components: [0.38824, 0.24706, 0],
      hex: "#633f00",
    },
    "warning-35": {
      colorSpace: "srgb",
      components: [0.44706, 0.2902, 0],
      hex: "#724a00",
    },
    "warning-40": {
      colorSpace: "srgb",
      components: [0.5098, 0.33333, 0],
      hex: "#825500",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [0.63137, 0.42353, 0.06275],
      hex: "#a16c10",
    },
    "warning-60": {
      colorSpace: "srgb",
      components: [0.74902, 0.52157, 0.16863],
      hex: "#bf852b",
    },
    "warning-70": {
      colorSpace: "srgb",
      components: [0.86667, 0.62353, 0.26275],
      hex: "#dd9f43",
    },
    "warning-80": {
      colorSpace: "srgb",
      components: [0.98824, 0.72941, 0.36078],
      hex: "#fcba5c",
    },
    "warning-87": {
      colorSpace: "srgb",
      components: [1, 0.82745, 0.6],
      hex: "#ffd399",
    },
    "warning-90": {
      colorSpace: "srgb",
      components: [1, 0.86667, 0.70588],
      hex: "#ffddb4",
    },
    "warning-92": {
      colorSpace: "srgb",
      components: [1, 0.89412, 0.76863],
      hex: "#ffe4c4",
    },
    "warning-94": {
      colorSpace: "srgb",
      components: [1, 0.92157, 0.83137],
      hex: "#ffebd4",
    },
    "warning-95": {
      colorSpace: "srgb",
      components: [1, 0.93333, 0.86275],
      hex: "#ffeedc",
    },
    "warning-96": {
      colorSpace: "srgb",
      components: [1, 0.9451, 0.89412],
      hex: "#fff1e4",
    },
    "warning-98": {
      colorSpace: "srgb",
      components: [1, 0.97255, 0.95686],
      hex: "#fff8f4",
    },
    "warning-99": {
      colorSpace: "srgb",
      components: [1, 0.98431, 1],
      hex: "#fffbff",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "neutral-0": { colorSpace: "srgb", components: [0, 0, 0], hex: "#000000" },
    "neutral-4": {
      colorSpace: "srgb",
      components: [0.04314, 0.05882, 0.06667],
      hex: "#0b0f11",
    },
    "neutral-6": {
      colorSpace: "srgb",
      components: [0.06667, 0.07843, 0.0902],
      hex: "#111417",
    },
    "neutral-10": {
      colorSpace: "srgb",
      components: [0.09804, 0.1098, 0.12157],
      hex: "#191c1f",
    },
    "neutral-12": {
      colorSpace: "srgb",
      components: [0.11373, 0.12549, 0.13725],
      hex: "#1d2023",
    },
    "neutral-17": {
      colorSpace: "srgb",
      components: [0.15294, 0.16471, 0.17647],
      hex: "#272a2d",
    },
    "neutral-20": {
      colorSpace: "srgb",
      components: [0.18039, 0.19216, 0.20392],
      hex: "#2e3134",
    },
    "neutral-22": {
      colorSpace: "srgb",
      components: [0.19608, 0.20784, 0.21961],
      hex: "#323538",
    },
    "neutral-24": {
      colorSpace: "srgb",
      components: [0.21569, 0.22353, 0.23922],
      hex: "#37393d",
    },
    "neutral-25": {
      colorSpace: "srgb",
      components: [0.22353, 0.23529, 0.24706],
      hex: "#393c3f",
    },
    "neutral-30": {
      colorSpace: "srgb",
      components: [0.26667, 0.27843, 0.2902],
      hex: "#44474a",
    },
    "neutral-35": {
      colorSpace: "srgb",
      components: [0.31373, 0.32549, 0.33725],
      hex: "#505356",
    },
    "neutral-40": {
      colorSpace: "srgb",
      components: [0.36078, 0.37255, 0.38431],
      hex: "#5c5f62",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.45882, 0.46667, 0.48235],
      hex: "#75777b",
    },
    "neutral-60": {
      colorSpace: "srgb",
      components: [0.55686, 0.56863, 0.58039],
      hex: "#8e9194",
    },
    "neutral-70": {
      colorSpace: "srgb",
      components: [0.66275, 0.67059, 0.68627],
      hex: "#a9abaf",
    },
    "neutral-80": {
      colorSpace: "srgb",
      components: [0.77255, 0.77647, 0.79216],
      hex: "#c5c6ca",
    },
    "neutral-87": {
      colorSpace: "srgb",
      components: [0.84706, 0.8549, 0.87059],
      hex: "#d8dade",
    },
    "neutral-90": {
      colorSpace: "srgb",
      components: [0.88235, 0.88627, 0.90196],
      hex: "#e1e2e6",
    },
    "neutral-92": {
      colorSpace: "srgb",
      components: [0.90588, 0.9098, 0.92549],
      hex: "#e7e8ec",
    },
    "neutral-94": {
      colorSpace: "srgb",
      components: [0.92549, 0.93333, 0.94902],
      hex: "#eceef2",
    },
    "neutral-95": {
      colorSpace: "srgb",
      components: [0.93725, 0.9451, 0.96078],
      hex: "#eff1f5",
    },
    "neutral-96": {
      colorSpace: "srgb",
      components: [0.94902, 0.95294, 0.96863],
      hex: "#f2f3f7",
    },
    "neutral-98": {
      colorSpace: "srgb",
      components: [0.97255, 0.97647, 0.99216],
      hex: "#f8f9fd",
    },
    "neutral-99": {
      colorSpace: "srgb",
      components: [0.98824, 0.98824, 1],
      hex: "#fcfcff",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
    "neutral-variant-0": {
      colorSpace: "srgb",
      components: [0, 0, 0],
      hex: "#000000",
    },
    "neutral-variant-4": {
      colorSpace: "srgb",
      components: [0.01961, 0.0549, 0.1098],
      hex: "#050e1c",
    },
    "neutral-variant-6": {
      colorSpace: "srgb",
      components: [0.03922, 0.07843, 0.13333],
      hex: "#0a1422",
    },
    "neutral-variant-10": {
      colorSpace: "srgb",
      components: [0.07451, 0.1098, 0.16471],
      hex: "#131c2a",
    },
    "neutral-variant-12": {
      colorSpace: "srgb",
      components: [0.0902, 0.12549, 0.18039],
      hex: "#17202e",
    },
    "neutral-variant-17": {
      colorSpace: "srgb",
      components: [0.12941, 0.16471, 0.22353],
      hex: "#212a39",
    },
    "neutral-variant-20": {
      colorSpace: "srgb",
      components: [0.15686, 0.19216, 0.25098],
      hex: "#283140",
    },
    "neutral-variant-22": {
      colorSpace: "srgb",
      components: [0.17255, 0.20784, 0.26667],
      hex: "#2c3544",
    },
    "neutral-variant-24": {
      colorSpace: "srgb",
      components: [0.19216, 0.22353, 0.28627],
      hex: "#313949",
    },
    "neutral-variant-25": {
      colorSpace: "srgb",
      components: [0.2, 0.23529, 0.29412],
      hex: "#333c4b",
    },
    "neutral-variant-30": {
      colorSpace: "srgb",
      components: [0.24314, 0.27843, 0.34118],
      hex: "#3e4757",
    },
    "neutral-variant-35": {
      colorSpace: "srgb",
      components: [0.2902, 0.32549, 0.38824],
      hex: "#4a5363",
    },
    "neutral-variant-40": {
      colorSpace: "srgb",
      components: [0.33725, 0.37255, 0.43922],
      hex: "#565f70",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.43137, 0.46667, 0.53725],
      hex: "#6e7789",
    },
    "neutral-variant-60": {
      colorSpace: "srgb",
      components: [0.53333, 0.56863, 0.63922],
      hex: "#8891a3",
    },
    "neutral-variant-70": {
      colorSpace: "srgb",
      components: [0.63529, 0.67059, 0.7451],
      hex: "#a2abbe",
    },
    "neutral-variant-80": {
      colorSpace: "srgb",
      components: [0.7451, 0.78039, 0.8549],
      hex: "#bec7da",
    },
    "neutral-variant-87": {
      colorSpace: "srgb",
      components: [0.81961, 0.8549, 0.93333],
      hex: "#d1daee",
    },
    "neutral-variant-90": {
      colorSpace: "srgb",
      components: [0.8549, 0.8902, 0.96863],
      hex: "#dae3f7",
    },
    "neutral-variant-92": {
      colorSpace: "srgb",
      components: [0.87451, 0.9098, 0.99216],
      hex: "#dfe8fd",
    },
    "neutral-variant-94": {
      colorSpace: "srgb",
      components: [0.90588, 0.93333, 1],
      hex: "#e7eeff",
    },
    "neutral-variant-95": {
      colorSpace: "srgb",
      components: [0.92549, 0.9451, 1],
      hex: "#ecf1ff",
    },
    "neutral-variant-96": {
      colorSpace: "srgb",
      components: [0.94118, 0.95294, 1],
      hex: "#f0f3ff",
    },
    "neutral-variant-98": {
      colorSpace: "srgb",
      components: [0.97647, 0.97647, 1],
      hex: "#f9f9ff",
    },
    "neutral-variant-99": {
      colorSpace: "srgb",
      components: [0.99216, 0.98431, 1],
      hex: "#fdfbff",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [1, 1, 1],
      hex: "#ffffff",
    },
  },
} satisfies AuroraLayer;
