/**
 * Dune — Terracotta, sand, and dusk mauve over sandstone grays.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "dune",
  name: "Dune",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.93333],
      hex: "#fff5ee",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [1, 0.9098, 0.84706],
      hex: "#ffe8d8",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [1, 0.80784, 0.67451],
      hex: "#ffceac",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.94902, 0.68235, 0.49804],
      hex: "#f2ae7f",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.85882, 0.56078, 0.34118],
      hex: "#db8f57",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.7451, 0.43922, 0.20392],
      hex: "#be7034",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.62745, 0.33333, 0.06667],
      hex: "#a05511",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0.5098, 0.2549, 0],
      hex: "#824100",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0.39608, 0.19216, 0],
      hex: "#653100",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0.28627, 0.13333, 0],
      hex: "#492200",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0.20784, 0.0902, 0],
      hex: "#351700",
    },
    "primary-muted-50": {
      colorSpace: "srgb",
      components: [0.99608, 0.96078, 0.93725],
      hex: "#fef5ef",
    },
    "primary-muted-100": {
      colorSpace: "srgb",
      components: [0.97647, 0.91765, 0.87843],
      hex: "#f9eae0",
    },
    "primary-muted-200": {
      colorSpace: "srgb",
      components: [0.92157, 0.83137, 0.77255],
      hex: "#ebd4c5",
    },
    "primary-muted-300": {
      colorSpace: "srgb",
      components: [0.84314, 0.72157, 0.64314],
      hex: "#d7b8a4",
    },
    "primary-muted-400": {
      colorSpace: "srgb",
      components: [0.7451, 0.60784, 0.51765],
      hex: "#be9b84",
    },
    "primary-muted-500": {
      colorSpace: "srgb",
      components: [0.63137, 0.49412, 0.4],
      hex: "#a17e66",
    },
    "primary-muted-600": {
      colorSpace: "srgb",
      components: [0.52157, 0.39216, 0.30196],
      hex: "#85644d",
    },
    "primary-muted-700": {
      colorSpace: "srgb",
      components: [0.42353, 0.30588, 0.22353],
      hex: "#6c4e39",
    },
    "primary-muted-800": {
      colorSpace: "srgb",
      components: [0.32941, 0.23137, 0.16078],
      hex: "#543b29",
    },
    "primary-muted-900": {
      colorSpace: "srgb",
      components: [0.23922, 0.16078, 0.10196],
      hex: "#3d291a",
    },
    "primary-muted-950": {
      colorSpace: "srgb",
      components: [0.17255, 0.11373, 0.07059],
      hex: "#2c1d12",
    },
    "primary-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.93333],
      hex: "#fff5ee",
    },
    "primary-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.9098, 0.84706],
      hex: "#ffe8d8",
    },
    "primary-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.80784, 0.67451],
      hex: "#ffceac",
    },
    "primary-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.65882, 0.41176],
      hex: "#ffa869",
    },
    "primary-vivid-400": {
      colorSpace: "srgb",
      components: [0.93333, 0.51373, 0.14118],
      hex: "#ee8324",
    },
    "primary-vivid-500": {
      colorSpace: "srgb",
      components: [0.78824, 0.41176, 0],
      hex: "#c96900",
    },
    "primary-vivid-600": {
      colorSpace: "srgb",
      components: [0.63922, 0.32549, 0],
      hex: "#a35300",
    },
    "primary-vivid-700": {
      colorSpace: "srgb",
      components: [0.5098, 0.2549, 0],
      hex: "#824100",
    },
    "primary-vivid-800": {
      colorSpace: "srgb",
      components: [0.39608, 0.19216, 0],
      hex: "#653100",
    },
    "primary-vivid-900": {
      colorSpace: "srgb",
      components: [0.28627, 0.13333, 0],
      hex: "#492200",
    },
    "primary-vivid-950": {
      colorSpace: "srgb",
      components: [0.20784, 0.0902, 0],
      hex: "#351700",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.99608, 0.96471, 0.90588],
      hex: "#fef6e7",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.97647, 0.92157, 0.82353],
      hex: "#f9ebd2",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.92157, 0.84314, 0.68627],
      hex: "#ebd7af",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.84314, 0.73725, 0.52157],
      hex: "#d7bc85",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.7451, 0.61961, 0.36863],
      hex: "#be9e5e",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.63137, 0.50588, 0.23922],
      hex: "#a1813d",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0.52549, 0.4, 0.12157],
      hex: "#86661f",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0.42745, 0.31373, 0.02353],
      hex: "#6d5006",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0.32941, 0.23922, 0],
      hex: "#543d00",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0.23529, 0.16863, 0],
      hex: "#3c2b00",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0.17255, 0.11765, 0],
      hex: "#2c1e00",
    },
    "secondary-muted-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.96471, 0.94118],
      hex: "#faf6f0",
    },
    "secondary-muted-100": {
      colorSpace: "srgb",
      components: [0.94902, 0.92549, 0.88235],
      hex: "#f2ece1",
    },
    "secondary-muted-200": {
      colorSpace: "srgb",
      components: [0.88235, 0.84706, 0.77647],
      hex: "#e1d8c6",
    },
    "secondary-muted-300": {
      colorSpace: "srgb",
      components: [0.79216, 0.7451, 0.65098],
      hex: "#cabea6",
    },
    "secondary-muted-400": {
      colorSpace: "srgb",
      components: [0.68627, 0.63137, 0.52941],
      hex: "#afa187",
    },
    "secondary-muted-500": {
      colorSpace: "srgb",
      components: [0.57647, 0.51765, 0.41176],
      hex: "#938469",
    },
    "secondary-muted-600": {
      colorSpace: "srgb",
      components: [0.47059, 0.41569, 0.3098],
      hex: "#786a4f",
    },
    "secondary-muted-700": {
      colorSpace: "srgb",
      components: [0.37647, 0.32941, 0.23137],
      hex: "#60543b",
    },
    "secondary-muted-800": {
      colorSpace: "srgb",
      components: [0.2902, 0.25098, 0.16863],
      hex: "#4a402b",
    },
    "secondary-muted-900": {
      colorSpace: "srgb",
      components: [0.20784, 0.17647, 0.1098],
      hex: "#352d1c",
    },
    "secondary-muted-950": {
      colorSpace: "srgb",
      components: [0.14902, 0.12549, 0.07451],
      hex: "#262013",
    },
    "secondary-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.96471, 0.89412],
      hex: "#fff6e4",
    },
    "secondary-vivid-100": {
      colorSpace: "srgb",
      components: [0.99216, 0.92157, 0.78039],
      hex: "#fdebc7",
    },
    "secondary-vivid-200": {
      colorSpace: "srgb",
      components: [0.94902, 0.83529, 0.61176],
      hex: "#f2d59c",
    },
    "secondary-vivid-300": {
      colorSpace: "srgb",
      components: [0.88235, 0.72549, 0.41176],
      hex: "#e1b969",
    },
    "secondary-vivid-400": {
      colorSpace: "srgb",
      components: [0.78431, 0.60784, 0.21176],
      hex: "#c89b36",
    },
    "secondary-vivid-500": {
      colorSpace: "srgb",
      components: [0.66667, 0.49412, 0],
      hex: "#aa7e00",
    },
    "secondary-vivid-600": {
      colorSpace: "srgb",
      components: [0.53725, 0.39608, 0],
      hex: "#896500",
    },
    "secondary-vivid-700": {
      colorSpace: "srgb",
      components: [0.42745, 0.31373, 0],
      hex: "#6d5000",
    },
    "secondary-vivid-800": {
      colorSpace: "srgb",
      components: [0.32941, 0.23922, 0],
      hex: "#543d00",
    },
    "secondary-vivid-900": {
      colorSpace: "srgb",
      components: [0.23529, 0.16863, 0],
      hex: "#3c2b00",
    },
    "secondary-vivid-950": {
      colorSpace: "srgb",
      components: [0.17255, 0.11765, 0],
      hex: "#2c1e00",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [1, 0.94902, 0.98824],
      hex: "#fff2fc",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.98431, 0.89804, 0.96471],
      hex: "#fbe5f6",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.93333, 0.80392, 0.90588],
      hex: "#eecde7",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.85882, 0.68627, 0.82353],
      hex: "#dbafd2",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.76078, 0.56863, 0.72157],
      hex: "#c291b8",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.64706, 0.45098, 0.61176],
      hex: "#a5739c",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.53725, 0.34902, 0.50196],
      hex: "#895980",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0.43529, 0.26667, 0.40784],
      hex: "#6f4468",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0.34118, 0.19608, 0.31765],
      hex: "#573251",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0.24706, 0.13333, 0.22745],
      hex: "#3f223a",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.09412, 0.16471],
      hex: "#2d182a",
    },
    "tertiary-muted-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.96078, 0.97647],
      hex: "#faf5f9",
    },
    "tertiary-muted-100": {
      colorSpace: "srgb",
      components: [0.95294, 0.91373, 0.9451],
      hex: "#f3e9f1",
    },
    "tertiary-muted-200": {
      colorSpace: "srgb",
      components: [0.8902, 0.83137, 0.87451],
      hex: "#e3d4df",
    },
    "tertiary-muted-300": {
      colorSpace: "srgb",
      components: [0.8, 0.72157, 0.78431],
      hex: "#ccb8c8",
    },
    "tertiary-muted-400": {
      colorSpace: "srgb",
      components: [0.69412, 0.60784, 0.67843],
      hex: "#b19bad",
    },
    "tertiary-muted-500": {
      colorSpace: "srgb",
      components: [0.58431, 0.49412, 0.56471],
      hex: "#957e90",
    },
    "tertiary-muted-600": {
      colorSpace: "srgb",
      components: [0.47843, 0.39216, 0.45882],
      hex: "#7a6475",
    },
    "tertiary-muted-700": {
      colorSpace: "srgb",
      components: [0.38431, 0.30588, 0.36863],
      hex: "#624e5e",
    },
    "tertiary-muted-800": {
      colorSpace: "srgb",
      components: [0.29804, 0.23137, 0.28235],
      hex: "#4c3b48",
    },
    "tertiary-muted-900": {
      colorSpace: "srgb",
      components: [0.21176, 0.16078, 0.2],
      hex: "#362933",
    },
    "tertiary-muted-950": {
      colorSpace: "srgb",
      components: [0.15294, 0.11373, 0.1451],
      hex: "#271d25",
    },
    "tertiary-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.94902, 0.98824],
      hex: "#fff2fc",
    },
    "tertiary-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.8902, 0.97647],
      hex: "#ffe3f9",
    },
    "tertiary-vivid-200": {
      colorSpace: "srgb",
      components: [0.96471, 0.78824, 0.92941],
      hex: "#f6c9ed",
    },
    "tertiary-vivid-300": {
      colorSpace: "srgb",
      components: [0.89804, 0.65882, 0.8549],
      hex: "#e5a8da",
    },
    "tertiary-vivid-400": {
      colorSpace: "srgb",
      components: [0.80392, 0.53333, 0.75294],
      hex: "#cd88c0",
    },
    "tertiary-vivid-500": {
      colorSpace: "srgb",
      components: [0.6902, 0.41569, 0.64314],
      hex: "#b06aa4",
    },
    "tertiary-vivid-600": {
      colorSpace: "srgb",
      components: [0.57647, 0.31373, 0.53333],
      hex: "#935088",
    },
    "tertiary-vivid-700": {
      colorSpace: "srgb",
      components: [0.47059, 0.23137, 0.43529],
      hex: "#783b6f",
    },
    "tertiary-vivid-800": {
      colorSpace: "srgb",
      components: [0.37255, 0.16471, 0.34118],
      hex: "#5f2a57",
    },
    "tertiary-vivid-900": {
      colorSpace: "srgb",
      components: [0.27059, 0.1098, 0.24706],
      hex: "#451c3f",
    },
    "tertiary-vivid-950": {
      colorSpace: "srgb",
      components: [0.19608, 0.07451, 0.17647],
      hex: "#32132d",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.88627],
      hex: "#ffe6e2",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [1, 0.79608, 0.76078],
      hex: "#ffcbc2",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [1, 0.64314, 0.58431],
      hex: "#ffa495",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [0.96471, 0.47059, 0.4],
      hex: "#f67866",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.84706, 0.33725, 0.27451],
      hex: "#d85646",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.72549, 0.21961, 0.16863],
      hex: "#b9382b",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.6, 0.13333, 0.09412],
      hex: "#992218",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.48235, 0.06667, 0.03529],
      hex: "#7b1109",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.35686, 0.02353, 0.00784],
      hex: "#5b0602",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.25882, 0.01961, 0.01176],
      hex: "#420503",
    },
    "error-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-muted-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.88627],
      hex: "#ffe6e2",
    },
    "error-muted-200": {
      colorSpace: "srgb",
      components: [0.96471, 0.81176, 0.78431],
      hex: "#f6cfc8",
    },
    "error-muted-300": {
      colorSpace: "srgb",
      components: [0.89412, 0.69412, 0.65882],
      hex: "#e4b1a8",
    },
    "error-muted-400": {
      colorSpace: "srgb",
      components: [0.8, 0.57647, 0.53725],
      hex: "#cc9389",
    },
    "error-muted-500": {
      colorSpace: "srgb",
      components: [0.68627, 0.45882, 0.42353],
      hex: "#af756c",
    },
    "error-muted-600": {
      colorSpace: "srgb",
      components: [0.57255, 0.35686, 0.32157],
      hex: "#925b52",
    },
    "error-muted-700": {
      colorSpace: "srgb",
      components: [0.47059, 0.27451, 0.24314],
      hex: "#78463e",
    },
    "error-muted-800": {
      colorSpace: "srgb",
      components: [0.36863, 0.2, 0.17647],
      hex: "#5e332d",
    },
    "error-muted-900": {
      colorSpace: "srgb",
      components: [0.27059, 0.13725, 0.11765],
      hex: "#45231e",
    },
    "error-muted-950": {
      colorSpace: "srgb",
      components: [0.19608, 0.09412, 0.08235],
      hex: "#321815",
    },
    "error-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.88627],
      hex: "#ffe6e2",
    },
    "error-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.79608, 0.76078],
      hex: "#ffcbc2",
    },
    "error-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.64314, 0.58431],
      hex: "#ffa495",
    },
    "error-vivid-400": {
      colorSpace: "srgb",
      components: [1, 0.43529, 0.36471],
      hex: "#ff6f5d",
    },
    "error-vivid-500": {
      colorSpace: "srgb",
      components: [0.95294, 0.16471, 0.1098],
      hex: "#f32a1c",
    },
    "error-vivid-600": {
      colorSpace: "srgb",
      components: [0.79608, 0.02745, 0],
      hex: "#cb0700",
    },
    "error-vivid-700": {
      colorSpace: "srgb",
      components: [0.63922, 0.01569, 0],
      hex: "#a30400",
    },
    "error-vivid-800": {
      colorSpace: "srgb",
      components: [0.49804, 0.00784, 0],
      hex: "#7f0200",
    },
    "error-vivid-900": {
      colorSpace: "srgb",
      components: [0.36078, 0.00392, 0],
      hex: "#5c0100",
    },
    "error-vivid-950": {
      colorSpace: "srgb",
      components: [0.27059, 0.00392, 0],
      hex: "#450100",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.98431, 0.9098],
      hex: "#f0fbe8",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.95686, 0.83137],
      hex: "#e1f4d4",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.78039, 0.89412, 0.69804],
      hex: "#c7e4b2",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.65098, 0.80784, 0.53725],
      hex: "#a6ce89",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.52941, 0.70196, 0.39216],
      hex: "#87b364",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.41176, 0.58431, 0.26275],
      hex: "#699543",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0.3098, 0.47843, 0.14902],
      hex: "#4f7a26",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0.23137, 0.38431, 0.06275],
      hex: "#3b6210",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0.16471, 0.29804, 0.00392],
      hex: "#2a4c01",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0.1098, 0.21176, 0],
      hex: "#1c3600",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0.07451, 0.15294, 0],
      hex: "#132700",
    },
    "success-muted-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.97647, 0.94118],
      hex: "#f4f9f0",
    },
    "success-muted-100": {
      colorSpace: "srgb",
      components: [0.90588, 0.94118, 0.88627],
      hex: "#e7f0e2",
    },
    "success-muted-200": {
      colorSpace: "srgb",
      components: [0.81961, 0.87059, 0.78431],
      hex: "#d1dec8",
    },
    "success-muted-300": {
      colorSpace: "srgb",
      components: [0.70588, 0.77647, 0.65882],
      hex: "#b4c6a8",
    },
    "success-muted-400": {
      colorSpace: "srgb",
      components: [0.59216, 0.67059, 0.53725],
      hex: "#97ab89",
    },
    "success-muted-500": {
      colorSpace: "srgb",
      components: [0.47843, 0.55686, 0.41961],
      hex: "#7a8e6b",
    },
    "success-muted-600": {
      colorSpace: "srgb",
      components: [0.37647, 0.45098, 0.31765],
      hex: "#607351",
    },
    "success-muted-700": {
      colorSpace: "srgb",
      components: [0.2902, 0.36078, 0.23922],
      hex: "#4a5c3d",
    },
    "success-muted-800": {
      colorSpace: "srgb",
      components: [0.21961, 0.27451, 0.17255],
      hex: "#38462c",
    },
    "success-muted-900": {
      colorSpace: "srgb",
      components: [0.14902, 0.19608, 0.11373],
      hex: "#26321d",
    },
    "success-muted-950": {
      colorSpace: "srgb",
      components: [0.10588, 0.14118, 0.07843],
      hex: "#1b2414",
    },
    "success-vivid-50": {
      colorSpace: "srgb",
      components: [0.92941, 0.99216, 0.8902],
      hex: "#edfde3",
    },
    "success-vivid-100": {
      colorSpace: "srgb",
      components: [0.86275, 0.96863, 0.79216],
      hex: "#dcf7ca",
    },
    "success-vivid-200": {
      colorSpace: "srgb",
      components: [0.74902, 0.9098, 0.63137],
      hex: "#bfe8a1",
    },
    "success-vivid-300": {
      colorSpace: "srgb",
      components: [0.61176, 0.82353, 0.43529],
      hex: "#9cd26f",
    },
    "success-vivid-400": {
      colorSpace: "srgb",
      components: [0.47843, 0.72157, 0.25098],
      hex: "#7ab840",
    },
    "success-vivid-500": {
      colorSpace: "srgb",
      components: [0.35686, 0.60392, 0.00784],
      hex: "#5b9a02",
    },
    "success-vivid-600": {
      colorSpace: "srgb",
      components: [0.28235, 0.48627, 0],
      hex: "#487c00",
    },
    "success-vivid-700": {
      colorSpace: "srgb",
      components: [0.21961, 0.38824, 0],
      hex: "#386300",
    },
    "success-vivid-800": {
      colorSpace: "srgb",
      components: [0.16471, 0.29804, 0],
      hex: "#2a4c00",
    },
    "success-vivid-900": {
      colorSpace: "srgb",
      components: [0.1098, 0.21176, 0],
      hex: "#1c3600",
    },
    "success-vivid-950": {
      colorSpace: "srgb",
      components: [0.07451, 0.15294, 0],
      hex: "#132700",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.90588],
      hex: "#fff5e7",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [1, 0.91765, 0.78431],
      hex: "#ffeac8",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.96863, 0.82745, 0.60784],
      hex: "#f7d39b",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.90196, 0.71765, 0.40392],
      hex: "#e6b767",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.80784, 0.59608, 0.2],
      hex: "#ce9833",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.68627, 0.48235, 0],
      hex: "#af7b00",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.55294, 0.38824, 0],
      hex: "#8d6300",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.44314, 0.30588, 0],
      hex: "#714e00",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.34118, 0.23137, 0],
      hex: "#573b00",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.24314, 0.16078, 0],
      hex: "#3e2900",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.11373, 0],
      hex: "#2d1d00",
    },
    "warning-muted-50": {
      colorSpace: "srgb",
      components: [0.98824, 0.96471, 0.92941],
      hex: "#fcf6ed",
    },
    "warning-muted-100": {
      colorSpace: "srgb",
      components: [0.96078, 0.92157, 0.86275],
      hex: "#f5ebdc",
    },
    "warning-muted-200": {
      colorSpace: "srgb",
      components: [0.90196, 0.84314, 0.7451],
      hex: "#e6d7be",
    },
    "warning-muted-300": {
      colorSpace: "srgb",
      components: [0.81961, 0.73725, 0.60784],
      hex: "#d1bc9b",
    },
    "warning-muted-400": {
      colorSpace: "srgb",
      components: [0.71765, 0.62353, 0.47843],
      hex: "#b79f7a",
    },
    "warning-muted-500": {
      colorSpace: "srgb",
      components: [0.60392, 0.5098, 0.35686],
      hex: "#9a825b",
    },
    "warning-muted-600": {
      colorSpace: "srgb",
      components: [0.49804, 0.40784, 0.25882],
      hex: "#7f6842",
    },
    "warning-muted-700": {
      colorSpace: "srgb",
      components: [0.40392, 0.32157, 0.18431],
      hex: "#67522f",
    },
    "warning-muted-800": {
      colorSpace: "srgb",
      components: [0.31373, 0.24314, 0.12157],
      hex: "#503e1f",
    },
    "warning-muted-900": {
      colorSpace: "srgb",
      components: [0.22353, 0.16863, 0.07451],
      hex: "#392b13",
    },
    "warning-muted-950": {
      colorSpace: "srgb",
      components: [0.16078, 0.11765, 0.05098],
      hex: "#291e0d",
    },
    "warning-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.90588],
      hex: "#fff5e7",
    },
    "warning-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.91765, 0.78431],
      hex: "#ffeac8",
    },
    "warning-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.81961, 0.52549],
      hex: "#ffd186",
    },
    "warning-vivid-300": {
      colorSpace: "srgb",
      components: [0.96078, 0.69804, 0.16078],
      hex: "#f5b229",
    },
    "warning-vivid-400": {
      colorSpace: "srgb",
      components: [0.83137, 0.58824, 0],
      hex: "#d49600",
    },
    "warning-vivid-500": {
      colorSpace: "srgb",
      components: [0.68627, 0.48235, 0],
      hex: "#af7b00",
    },
    "warning-vivid-600": {
      colorSpace: "srgb",
      components: [0.55294, 0.38824, 0],
      hex: "#8d6300",
    },
    "warning-vivid-700": {
      colorSpace: "srgb",
      components: [0.44314, 0.30588, 0],
      hex: "#714e00",
    },
    "warning-vivid-800": {
      colorSpace: "srgb",
      components: [0.34118, 0.23137, 0],
      hex: "#573b00",
    },
    "warning-vivid-900": {
      colorSpace: "srgb",
      components: [0.24314, 0.16078, 0],
      hex: "#3e2900",
    },
    "warning-vivid-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.11373, 0],
      hex: "#2d1d00",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.96471, 0.94902],
      hex: "#f9f6f2",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.94118, 0.92549, 0.89804],
      hex: "#f0ece5",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.87451, 0.84706, 0.80784],
      hex: "#dfd8ce",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.78039, 0.7451, 0.6902],
      hex: "#c7beb0",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.67059, 0.63529, 0.57255],
      hex: "#aba292",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.56078, 0.52157, 0.45882],
      hex: "#8f8575",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.4549, 0.41569, 0.35686],
      hex: "#746a5b",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.36471, 0.32941, 0.27451],
      hex: "#5d5446",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.27843, 0.25098, 0.20392],
      hex: "#474034",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.2, 0.17647, 0.13725],
      hex: "#332d23",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.14118, 0.12549, 0.09804],
      hex: "#242019",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.96471, 0.9451],
      hex: "#f9f6f1",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.92549, 0.8902],
      hex: "#f1ece3",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.87843, 0.84706, 0.79608],
      hex: "#e0d8cb",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.78431, 0.7451, 0.67451],
      hex: "#c8beac",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.67843, 0.63529, 0.55294],
      hex: "#ada28d",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.56471, 0.52157, 0.43922],
      hex: "#908570",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.46275, 0.41569, 0.33725],
      hex: "#766a56",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.36863, 0.32941, 0.25882],
      hex: "#5e5442",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.28627, 0.25098, 0.18824],
      hex: "#494030",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.20392, 0.17647, 0.12549],
      hex: "#342d20",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.1451, 0.12549, 0.08627],
      hex: "#252016",
    },
  },
} satisfies AuroraLayer;
