/**
 * Glacier — Ice blues and periwinkle over frosted grays, light and cold.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "glacier",
  name: "Glacier",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.97255, 1],
      hex: "#f0f8ff",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [0.86667, 0.94118, 1],
      hex: "#ddf0ff",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [0.71373, 0.87451, 1],
      hex: "#b6dfff",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.51765, 0.78039, 0.98039],
      hex: "#84c7fa",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.35686, 0.67059, 0.89804],
      hex: "#5babe5",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.21176, 0.55686, 0.78431],
      hex: "#368ec8",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.05882, 0.44706, 0.67059],
      hex: "#0f72ab",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0, 0.35686, 0.5451],
      hex: "#005b8b",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0, 0.27059, 0.42353],
      hex: "#00456c",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0, 0.19216, 0.30588],
      hex: "#00314e",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0, 0.13725, 0.22353],
      hex: "#002339",
    },
    "primary-muted-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.97255, 0.99608],
      hex: "#f0f8fe",
    },
    "primary-muted-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.93725, 0.98039],
      hex: "#e1effa",
    },
    "primary-muted-200": {
      colorSpace: "srgb",
      components: [0.78039, 0.86275, 0.92941],
      hex: "#c7dced",
    },
    "primary-muted-300": {
      colorSpace: "srgb",
      components: [0.6549, 0.76863, 0.8549],
      hex: "#a7c4da",
    },
    "primary-muted-400": {
      colorSpace: "srgb",
      components: [0.52941, 0.65882, 0.75686],
      hex: "#87a8c1",
    },
    "primary-muted-500": {
      colorSpace: "srgb",
      components: [0.41176, 0.5451, 0.64706],
      hex: "#698ba5",
    },
    "primary-muted-600": {
      colorSpace: "srgb",
      components: [0.3098, 0.43922, 0.53725],
      hex: "#4f7089",
    },
    "primary-muted-700": {
      colorSpace: "srgb",
      components: [0.23137, 0.34902, 0.43529],
      hex: "#3b596f",
    },
    "primary-muted-800": {
      colorSpace: "srgb",
      components: [0.16471, 0.26667, 0.34118],
      hex: "#2a4457",
    },
    "primary-muted-900": {
      colorSpace: "srgb",
      components: [0.1098, 0.18824, 0.24706],
      hex: "#1c303f",
    },
    "primary-muted-950": {
      colorSpace: "srgb",
      components: [0.07451, 0.13333, 0.18039],
      hex: "#13222e",
    },
    "primary-vivid-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.97255, 1],
      hex: "#f0f8ff",
    },
    "primary-vivid-100": {
      colorSpace: "srgb",
      components: [0.86667, 0.94118, 1],
      hex: "#ddf0ff",
    },
    "primary-vivid-200": {
      colorSpace: "srgb",
      components: [0.71373, 0.87451, 1],
      hex: "#b6dfff",
    },
    "primary-vivid-300": {
      colorSpace: "srgb",
      components: [0.49412, 0.78431, 1],
      hex: "#7ec8ff",
    },
    "primary-vivid-400": {
      colorSpace: "srgb",
      components: [0.12941, 0.67843, 0.99608],
      hex: "#21adfe",
    },
    "primary-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.55686, 0.83922],
      hex: "#008ed6",
    },
    "primary-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.44706, 0.67843],
      hex: "#0072ad",
    },
    "primary-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.35686, 0.5451],
      hex: "#005b8b",
    },
    "primary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.27059, 0.42353],
      hex: "#00456c",
    },
    "primary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.19216, 0.30588],
      hex: "#00314e",
    },
    "primary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.13725, 0.22353],
      hex: "#002339",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.92549, 0.98039, 0.98824],
      hex: "#ecfafc",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.8549, 0.94902, 0.96471],
      hex: "#daf2f6",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.73725, 0.88235, 0.90588],
      hex: "#bce1e7",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.58824, 0.79216, 0.82353],
      hex: "#96cad2",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.45098, 0.68235, 0.72157],
      hex: "#73aeb8",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.32549, 0.57255, 0.60784],
      hex: "#53929b",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0.21569, 0.46667, 0.50196],
      hex: "#377780",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0.13725, 0.37255, 0.40784],
      hex: "#235f68",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0.07451, 0.28627, 0.31765],
      hex: "#134951",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0.03137, 0.20392, 0.22745],
      hex: "#08343a",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0.02353, 0.1451, 0.16471],
      hex: "#06252a",
    },
    "secondary-muted-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.97255, 0.97647],
      hex: "#f2f8f9",
    },
    "secondary-muted-100": {
      colorSpace: "srgb",
      components: [0.89804, 0.93725, 0.9451],
      hex: "#e5eff1",
    },
    "secondary-muted-200": {
      colorSpace: "srgb",
      components: [0.8, 0.86667, 0.87451],
      hex: "#ccdddf",
    },
    "secondary-muted-300": {
      colorSpace: "srgb",
      components: [0.68235, 0.76863, 0.78431],
      hex: "#aec4c8",
    },
    "secondary-muted-400": {
      colorSpace: "srgb",
      components: [0.56078, 0.65882, 0.67451],
      hex: "#8fa8ac",
    },
    "secondary-muted-500": {
      colorSpace: "srgb",
      components: [0.44706, 0.54902, 0.56471],
      hex: "#728c90",
    },
    "secondary-muted-600": {
      colorSpace: "srgb",
      components: [0.3451, 0.44314, 0.45882],
      hex: "#587175",
    },
    "secondary-muted-700": {
      colorSpace: "srgb",
      components: [0.26275, 0.35294, 0.36863],
      hex: "#435a5e",
    },
    "secondary-muted-800": {
      colorSpace: "srgb",
      components: [0.19216, 0.27059, 0.28235],
      hex: "#314548",
    },
    "secondary-muted-900": {
      colorSpace: "srgb",
      components: [0.12941, 0.19216, 0.2],
      hex: "#213133",
    },
    "secondary-muted-950": {
      colorSpace: "srgb",
      components: [0.0902, 0.13725, 0.1451],
      hex: "#172325",
    },
    "secondary-vivid-50": {
      colorSpace: "srgb",
      components: [0.9098, 0.98431, 0.99608],
      hex: "#e8fbfe",
    },
    "secondary-vivid-100": {
      colorSpace: "srgb",
      components: [0.82745, 0.95686, 0.97647],
      hex: "#d3f4f9",
    },
    "secondary-vivid-200": {
      colorSpace: "srgb",
      components: [0.68627, 0.89412, 0.92941],
      hex: "#afe4ed",
    },
    "secondary-vivid-300": {
      colorSpace: "srgb",
      components: [0.5098, 0.80392, 0.85098],
      hex: "#82cdd9",
    },
    "secondary-vivid-400": {
      colorSpace: "srgb",
      components: [0.3451, 0.70196, 0.75294],
      hex: "#58b3c0",
    },
    "secondary-vivid-500": {
      colorSpace: "srgb",
      components: [0.18431, 0.58431, 0.64314],
      hex: "#2f95a4",
    },
    "secondary-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.47843, 0.53333],
      hex: "#007a88",
    },
    "secondary-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.38039, 0.42353],
      hex: "#00616c",
    },
    "secondary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.2902, 0.32549],
      hex: "#004a53",
    },
    "secondary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.20784, 0.23137],
      hex: "#00353b",
    },
    "secondary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.14902, 0.16863],
      hex: "#00262b",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.96471, 1],
      hex: "#f4f6ff",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.90588, 0.92549, 1],
      hex: "#e7ecff",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.81176, 0.84706, 0.97647],
      hex: "#cfd8f9",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.69412, 0.74118, 0.91765],
      hex: "#b1bdea",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.58039, 0.62745, 0.82353],
      hex: "#94a0d2",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.46667, 0.51373, 0.71373],
      hex: "#7783b6",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.36471, 0.40784, 0.6],
      hex: "#5d6899",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0.28235, 0.32157, 0.49412],
      hex: "#48527e",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0.21176, 0.24314, 0.39216],
      hex: "#363e64",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0.1451, 0.16863, 0.28627],
      hex: "#252b49",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0.10196, 0.12157, 0.20784],
      hex: "#1a1f35",
    },
    "tertiary-muted-50": {
      colorSpace: "srgb",
      components: [0.96078, 0.96471, 0.98824],
      hex: "#f5f6fc",
    },
    "tertiary-muted-100": {
      colorSpace: "srgb",
      components: [0.91765, 0.92549, 0.96471],
      hex: "#eaecf6",
    },
    "tertiary-muted-200": {
      colorSpace: "srgb",
      components: [0.83137, 0.84706, 0.9098],
      hex: "#d4d8e8",
    },
    "tertiary-muted-300": {
      colorSpace: "srgb",
      components: [0.72549, 0.74902, 0.82745],
      hex: "#b9bfd3",
    },
    "tertiary-muted-400": {
      colorSpace: "srgb",
      components: [0.61176, 0.63529, 0.72549],
      hex: "#9ca2b9",
    },
    "tertiary-muted-500": {
      colorSpace: "srgb",
      components: [0.49804, 0.52157, 0.61176],
      hex: "#7f859c",
    },
    "tertiary-muted-600": {
      colorSpace: "srgb",
      components: [0.39608, 0.41961, 0.50588],
      hex: "#656b81",
    },
    "tertiary-muted-700": {
      colorSpace: "srgb",
      components: [0.3098, 0.32941, 0.40784],
      hex: "#4f5468",
    },
    "tertiary-muted-800": {
      colorSpace: "srgb",
      components: [0.23529, 0.25098, 0.31765],
      hex: "#3c4051",
    },
    "tertiary-muted-900": {
      colorSpace: "srgb",
      components: [0.16471, 0.17647, 0.22745],
      hex: "#2a2d3a",
    },
    "tertiary-muted-950": {
      colorSpace: "srgb",
      components: [0.11373, 0.12549, 0.16471],
      hex: "#1d202a",
    },
    "tertiary-vivid-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.96471, 1],
      hex: "#f4f6ff",
    },
    "tertiary-vivid-100": {
      colorSpace: "srgb",
      components: [0.90588, 0.92549, 1],
      hex: "#e7ecff",
    },
    "tertiary-vivid-200": {
      colorSpace: "srgb",
      components: [0.80392, 0.84314, 1],
      hex: "#cdd7ff",
    },
    "tertiary-vivid-300": {
      colorSpace: "srgb",
      components: [0.67451, 0.73725, 0.98039],
      hex: "#acbcfa",
    },
    "tertiary-vivid-400": {
      colorSpace: "srgb",
      components: [0.55686, 0.61961, 0.89804],
      hex: "#8e9ee5",
    },
    "tertiary-vivid-500": {
      colorSpace: "srgb",
      components: [0.44314, 0.50588, 0.78431],
      hex: "#7181c8",
    },
    "tertiary-vivid-600": {
      colorSpace: "srgb",
      components: [0.3451, 0.4, 0.67059],
      hex: "#5866ab",
    },
    "tertiary-vivid-700": {
      colorSpace: "srgb",
      components: [0.26275, 0.3098, 0.55686],
      hex: "#434f8e",
    },
    "tertiary-vivid-800": {
      colorSpace: "srgb",
      components: [0.19608, 0.23529, 0.44314],
      hex: "#323c71",
    },
    "tertiary-vivid-900": {
      colorSpace: "srgb",
      components: [0.13333, 0.16078, 0.32941],
      hex: "#222954",
    },
    "tertiary-vivid-950": {
      colorSpace: "srgb",
      components: [0.0902, 0.11373, 0.23922],
      hex: "#171d3d",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95686],
      hex: "#fff4f4",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.90196],
      hex: "#ffe6e6",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [1, 0.79216, 0.79216],
      hex: "#ffcaca",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [1, 0.63137, 0.64706],
      hex: "#ffa1a5",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [0.96471, 0.45882, 0.49412],
      hex: "#f6757e",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.84706, 0.32549, 0.37647],
      hex: "#d85360",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.72157, 0.20784, 0.27843],
      hex: "#b83547",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.6, 0.12157, 0.2],
      hex: "#991f33",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.47843, 0.05098, 0.14118],
      hex: "#7a0d24",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.35294, 0.01176, 0.0902],
      hex: "#5a0317",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.25882, 0.01569, 0.05882],
      hex: "#42040f",
    },
    "error-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95686],
      hex: "#fff4f4",
    },
    "error-muted-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.90196],
      hex: "#ffe6e6",
    },
    "error-muted-200": {
      colorSpace: "srgb",
      components: [0.96471, 0.80784, 0.80784],
      hex: "#f6cece",
    },
    "error-muted-300": {
      colorSpace: "srgb",
      components: [0.89412, 0.6902, 0.69412],
      hex: "#e4b0b1",
    },
    "error-muted-400": {
      colorSpace: "srgb",
      components: [0.8, 0.56863, 0.57647],
      hex: "#cc9193",
    },
    "error-muted-500": {
      colorSpace: "srgb",
      components: [0.68627, 0.4549, 0.45882],
      hex: "#af7475",
    },
    "error-muted-600": {
      colorSpace: "srgb",
      components: [0.57255, 0.35294, 0.36078],
      hex: "#925a5c",
    },
    "error-muted-700": {
      colorSpace: "srgb",
      components: [0.47059, 0.26667, 0.27843],
      hex: "#784447",
    },
    "error-muted-800": {
      colorSpace: "srgb",
      components: [0.36863, 0.19608, 0.20784],
      hex: "#5e3235",
    },
    "error-muted-900": {
      colorSpace: "srgb",
      components: [0.27059, 0.13333, 0.14118],
      hex: "#452224",
    },
    "error-muted-950": {
      colorSpace: "srgb",
      components: [0.19216, 0.09412, 0.09804],
      hex: "#311819",
    },
    "error-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95686],
      hex: "#fff4f4",
    },
    "error-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.90196],
      hex: "#ffe6e6",
    },
    "error-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.79216, 0.79216],
      hex: "#ffcaca",
    },
    "error-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.63137, 0.64706],
      hex: "#ffa1a5",
    },
    "error-vivid-400": {
      colorSpace: "srgb",
      components: [1, 0.42353, 0.47059],
      hex: "#ff6c78",
    },
    "error-vivid-500": {
      colorSpace: "srgb",
      components: [0.94902, 0.13333, 0.3098],
      hex: "#f2224f",
    },
    "error-vivid-600": {
      colorSpace: "srgb",
      components: [0.78824, 0, 0.23137],
      hex: "#c9003b",
    },
    "error-vivid-700": {
      colorSpace: "srgb",
      components: [0.63137, 0, 0.17647],
      hex: "#a1002d",
    },
    "error-vivid-800": {
      colorSpace: "srgb",
      components: [0.49412, 0, 0.12941],
      hex: "#7e0021",
    },
    "error-vivid-900": {
      colorSpace: "srgb",
      components: [0.36078, 0, 0.08627],
      hex: "#5c0016",
    },
    "error-vivid-950": {
      colorSpace: "srgb",
      components: [0.26667, 0, 0.0549],
      hex: "#44000e",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.91765, 0.98824, 0.93725],
      hex: "#eafcef",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.84314, 0.96471, 0.87843],
      hex: "#d7f6e0",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.71373, 0.90588, 0.77255],
      hex: "#b6e7c5",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.55294, 0.82353, 0.64706],
      hex: "#8dd2a5",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.40392, 0.71765, 0.51765],
      hex: "#67b784",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.26667, 0.60392, 0.40392],
      hex: "#449a67",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0.14118, 0.49804, 0.30196],
      hex: "#247f4d",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0.03529, 0.4, 0.22353],
      hex: "#096639",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0, 0.3098, 0.16471],
      hex: "#004f2a",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0, 0.21961, 0.1098],
      hex: "#00381c",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.07451],
      hex: "#002913",
    },
    "success-muted-50": {
      colorSpace: "srgb",
      components: [0.9451, 0.97647, 0.95294],
      hex: "#f1f9f3",
    },
    "success-muted-100": {
      colorSpace: "srgb",
      components: [0.8902, 0.9451, 0.90588],
      hex: "#e3f1e7",
    },
    "success-muted-200": {
      colorSpace: "srgb",
      components: [0.79216, 0.87843, 0.81569],
      hex: "#cae0d0",
    },
    "success-muted-300": {
      colorSpace: "srgb",
      components: [0.67059, 0.78431, 0.70196],
      hex: "#abc8b3",
    },
    "success-muted-400": {
      colorSpace: "srgb",
      components: [0.5451, 0.67843, 0.58824],
      hex: "#8bad96",
    },
    "success-muted-500": {
      colorSpace: "srgb",
      components: [0.43137, 0.56471, 0.47059],
      hex: "#6e9078",
    },
    "success-muted-600": {
      colorSpace: "srgb",
      components: [0.32941, 0.45882, 0.37255],
      hex: "#54755f",
    },
    "success-muted-700": {
      colorSpace: "srgb",
      components: [0.24706, 0.36471, 0.28627],
      hex: "#3f5d49",
    },
    "success-muted-800": {
      colorSpace: "srgb",
      components: [0.18039, 0.28235, 0.21569],
      hex: "#2e4837",
    },
    "success-muted-900": {
      colorSpace: "srgb",
      components: [0.12157, 0.2, 0.14902],
      hex: "#1f3326",
    },
    "success-muted-950": {
      colorSpace: "srgb",
      components: [0.08235, 0.1451, 0.10196],
      hex: "#15251a",
    },
    "success-vivid-50": {
      colorSpace: "srgb",
      components: [0.89804, 0.99608, 0.92549],
      hex: "#e5feec",
    },
    "success-vivid-100": {
      colorSpace: "srgb",
      components: [0.80784, 0.98039, 0.85882],
      hex: "#cefadb",
    },
    "success-vivid-200": {
      colorSpace: "srgb",
      components: [0.64706, 0.92941, 0.74118],
      hex: "#a5edbd",
    },
    "success-vivid-300": {
      colorSpace: "srgb",
      components: [0.45098, 0.84706, 0.6],
      hex: "#73d899",
    },
    "success-vivid-400": {
      colorSpace: "srgb",
      components: [0.24314, 0.7451, 0.46667],
      hex: "#3ebe77",
    },
    "success-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.62745, 0.35294],
      hex: "#00a05a",
    },
    "success-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.50588, 0.28235],
      hex: "#008148",
    },
    "success-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.40392, 0.21961],
      hex: "#006738",
    },
    "success-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.3098, 0.16471],
      hex: "#004f2a",
    },
    "success-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.21961, 0.1098],
      hex: "#00381c",
    },
    "success-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.07451],
      hex: "#002913",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.9098],
      hex: "#fff5e8",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [0.99216, 0.91765, 0.81176],
      hex: "#fdeacf",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.94902, 0.83137, 0.67059],
      hex: "#f2d4ab",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.87843, 0.72157, 0.49804],
      hex: "#e0b87f",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.78431, 0.60392, 0.34118],
      hex: "#c89a57",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.67059, 0.48627, 0.2],
      hex: "#ab7c33",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.56078, 0.38431, 0.05882],
      hex: "#8f620f",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.45098, 0.29804, 0],
      hex: "#734c00",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.34902, 0.22745, 0],
      hex: "#593a00",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.25098, 0.15686, 0],
      hex: "#402800",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.18039, 0.1098, 0],
      hex: "#2e1c00",
    },
    "warning-muted-50": {
      colorSpace: "srgb",
      components: [0.98431, 0.96471, 0.93725],
      hex: "#fbf6ef",
    },
    "warning-muted-100": {
      colorSpace: "srgb",
      components: [0.95686, 0.92157, 0.87843],
      hex: "#f4ebe0",
    },
    "warning-muted-200": {
      colorSpace: "srgb",
      components: [0.89412, 0.84314, 0.77255],
      hex: "#e4d7c5",
    },
    "warning-muted-300": {
      colorSpace: "srgb",
      components: [0.80784, 0.73725, 0.64314],
      hex: "#cebca4",
    },
    "warning-muted-400": {
      colorSpace: "srgb",
      components: [0.70588, 0.62745, 0.51765],
      hex: "#b4a084",
    },
    "warning-muted-500": {
      colorSpace: "srgb",
      components: [0.59216, 0.51373, 0.4],
      hex: "#978366",
    },
    "warning-muted-600": {
      colorSpace: "srgb",
      components: [0.48627, 0.40784, 0.29804],
      hex: "#7c684c",
    },
    "warning-muted-700": {
      colorSpace: "srgb",
      components: [0.39216, 0.32157, 0.22353],
      hex: "#645239",
    },
    "warning-muted-800": {
      colorSpace: "srgb",
      components: [0.30588, 0.24314, 0.15686],
      hex: "#4e3e28",
    },
    "warning-muted-900": {
      colorSpace: "srgb",
      components: [0.21961, 0.16863, 0.10196],
      hex: "#382b1a",
    },
    "warning-muted-950": {
      colorSpace: "srgb",
      components: [0.15686, 0.12157, 0.07059],
      hex: "#281f12",
    },
    "warning-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.9098],
      hex: "#fff5e8",
    },
    "warning-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.91373, 0.8],
      hex: "#ffe9cc",
    },
    "warning-vivid-200": {
      colorSpace: "srgb",
      components: [0.98824, 0.81961, 0.58824],
      hex: "#fcd196",
    },
    "warning-vivid-300": {
      colorSpace: "srgb",
      components: [0.92941, 0.70588, 0.36863],
      hex: "#edb45e",
    },
    "warning-vivid-400": {
      colorSpace: "srgb",
      components: [0.83922, 0.58431, 0.12941],
      hex: "#d69521",
    },
    "warning-vivid-500": {
      colorSpace: "srgb",
      components: [0.70196, 0.47451, 0],
      hex: "#b37900",
    },
    "warning-vivid-600": {
      colorSpace: "srgb",
      components: [0.56471, 0.38039, 0],
      hex: "#906100",
    },
    "warning-vivid-700": {
      colorSpace: "srgb",
      components: [0.45098, 0.29804, 0],
      hex: "#734c00",
    },
    "warning-vivid-800": {
      colorSpace: "srgb",
      components: [0.34902, 0.22745, 0],
      hex: "#593a00",
    },
    "warning-vivid-900": {
      colorSpace: "srgb",
      components: [0.25098, 0.15686, 0],
      hex: "#402800",
    },
    "warning-vivid-950": {
      colorSpace: "srgb",
      components: [0.18039, 0.1098, 0],
      hex: "#2e1c00",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.96078, 0.96863, 0.97647],
      hex: "#f5f7f9",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.91765, 0.92941, 0.9451],
      hex: "#eaedf1",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.83137, 0.8549, 0.87843],
      hex: "#d4dae0",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.72549, 0.75294, 0.78824],
      hex: "#b9c0c9",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.61176, 0.64314, 0.68235],
      hex: "#9ca4ae",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.49804, 0.52941, 0.56863],
      hex: "#7f8791",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.39608, 0.42745, 0.46275],
      hex: "#656d76",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.3098, 0.33725, 0.36863],
      hex: "#4f565e",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.23529, 0.25882, 0.28627],
      hex: "#3c4249",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.16471, 0.18039, 0.20392],
      hex: "#2a2e34",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.11373, 0.12941, 0.1451],
      hex: "#1d2125",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.96863, 0.98824],
      hex: "#f4f7fc",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.9098, 0.92941, 0.96078],
      hex: "#e8edf5",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.82353, 0.8549, 0.90196],
      hex: "#d2dae6",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.71373, 0.75294, 0.81569],
      hex: "#b6c0d0",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.59608, 0.64314, 0.71373],
      hex: "#98a4b6",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.48235, 0.52941, 0.60392],
      hex: "#7b879a",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.38039, 0.42353, 0.49412],
      hex: "#616c7e",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.29804, 0.33725, 0.4],
      hex: "#4c5666",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.22353, 0.25882, 0.3098],
      hex: "#39424f",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.15294, 0.18039, 0.22353],
      hex: "#272e39",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.1098, 0.12941, 0.16078],
      hex: "#1c2129",
    },
  },
} satisfies AuroraLayer;
