/**
 * Horizon — Coral pink and violet dusk tones, from Horizon.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "horizon",
  name: "Horizon",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [0.99216, 0.96471, 0.96863],
      hex: "#fdf6f7",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [0.98431, 0.92549, 0.94118],
      hex: "#fbecf0",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [0.95686, 0.81569, 0.85098],
      hex: "#f4d0d9",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.92941, 0.70196, 0.76078],
      hex: "#edb3c2",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.87843, 0.47843, 0.58431],
      hex: "#e07a95",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.82353, 0.2549, 0.40392],
      hex: "#d24167",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.74118, 0.23137, 0.36471],
      hex: "#bd3b5d",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0.49412, 0.15294, 0.24314],
      hex: "#7e273e",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0.37255, 0.11373, 0.18039],
      hex: "#5f1d2e",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0.24706, 0.07843, 0.12157],
      hex: "#3f141f",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0.16471, 0.05098, 0.08235],
      hex: "#2a0d15",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.96863, 0.98824],
      hex: "#faf7fc",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.96078, 0.93725, 0.97647],
      hex: "#f5eff9",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.90196, 0.83922, 0.93725],
      hex: "#e6d6ef",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.84314, 0.7451, 0.89804],
      hex: "#d7bee5",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.72549, 0.55294, 0.82353],
      hex: "#b98dd2",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.60784, 0.36078, 0.7451],
      hex: "#9b5cbe",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0.54902, 0.32549, 0.67059],
      hex: "#8c53ab",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0.36471, 0.21569, 0.44706],
      hex: "#5d3772",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0.27451, 0.16078, 0.33725],
      hex: "#462956",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0.18431, 0.1098, 0.22353],
      hex: "#2f1c39",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0.12157, 0.07059, 0.14902],
      hex: "#1f1226",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.97647, 0.97647],
      hex: "#f2f9f9",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.90196, 0.95294, 0.95686],
      hex: "#e6f3f4",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.74902, 0.87843, 0.8902],
      hex: "#bfe0e3",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.6, 0.80784, 0.82353],
      hex: "#99ced2",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.30196, 0.66275, 0.6902],
      hex: "#4da9b0",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0, 0.51765, 0.55686],
      hex: "#00848e",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0, 0.46667, 0.50196],
      hex: "#007780",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0, 0.3098, 0.33333],
      hex: "#004f55",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0, 0.23137, 0.25098],
      hex: "#003b40",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0, 0.15686, 0.16863],
      hex: "#00282b",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0, 0.10196, 0.1098],
      hex: "#001a1c",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [0.99216, 0.96078, 0.96471],
      hex: "#fdf5f6",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [0.98824, 0.91765, 0.92941],
      hex: "#fceaed",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [0.96863, 0.79608, 0.82745],
      hex: "#f7cbd3",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [0.95294, 0.67059, 0.72549],
      hex: "#f3abb9",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [0.91373, 0.42745, 0.51765],
      hex: "#e96d84",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.87843, 0.18039, 0.3098],
      hex: "#e02e4f",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.79216, 0.16078, 0.27843],
      hex: "#ca2947",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.52549, 0.1098, 0.18431],
      hex: "#861c2f",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.39608, 0.08235, 0.14118],
      hex: "#651524",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.26275, 0.0549, 0.09412],
      hex: "#430e18",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.03529, 0.06275],
      hex: "#2d0910",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.97647, 0.96863],
      hex: "#f2f9f7",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.90196, 0.95294, 0.93725],
      hex: "#e6f3ef",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.74902, 0.88235, 0.84314],
      hex: "#bfe1d7",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.6, 0.81176, 0.7451],
      hex: "#99cfbe",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.30196, 0.67451, 0.55686],
      hex: "#4dac8e",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0, 0.53333, 0.36471],
      hex: "#00885d",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0, 0.47843, 0.32941],
      hex: "#007a54",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0, 0.32157, 0.21961],
      hex: "#005238",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0, 0.23922, 0.16471],
      hex: "#003d2a",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.1098],
      hex: "#00291c",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0, 0.10588, 0.07451],
      hex: "#001b13",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.97255, 0.96471],
      hex: "#faf8f6",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [0.96078, 0.94118, 0.92941],
      hex: "#f5f0ed",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.90196, 0.85882, 0.82353],
      hex: "#e6dbd2",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.84314, 0.77255, 0.71765],
      hex: "#d7c5b7",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.72549, 0.6, 0.50588],
      hex: "#b99981",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.60784, 0.42745, 0.29412],
      hex: "#9b6d4b",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.54902, 0.38431, 0.26667],
      hex: "#8c6244",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.36471, 0.2549, 0.17647],
      hex: "#5d412d",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.27451, 0.19216, 0.13333],
      hex: "#463122",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.18431, 0.12941, 0.0902],
      hex: "#2f2117",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.12157, 0.08627, 0.05882],
      hex: "#1f160f",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.97255, 0.97647],
      hex: "#f8f8f9",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.9451, 0.94902],
      hex: "#f1f1f2",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.86667, 0.86667, 0.87451],
      hex: "#dddddf",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.78431, 0.78431, 0.8],
      hex: "#c8c8cc",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.61961, 0.62353, 0.65098],
      hex: "#9e9fa6",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.45882, 0.46275, 0.50196],
      hex: "#757680",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.41176, 0.41569, 0.45098],
      hex: "#696a73",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.27451, 0.27843, 0.30196],
      hex: "#46474d",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.20784, 0.20784, 0.22745],
      hex: "#35353a",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.13725, 0.13725, 0.14902],
      hex: "#232326",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.0902, 0.09412, 0.10196],
      hex: "#17181a",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.97255, 0.98039],
      hex: "#f8f8fa",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.9451, 0.96078],
      hex: "#f1f1f5",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.86275, 0.86275, 0.90196],
      hex: "#dcdce6",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.77647, 0.78039, 0.83922],
      hex: "#c6c7d6",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.61176, 0.61961, 0.72157],
      hex: "#9c9eb8",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.44314, 0.4549, 0.6],
      hex: "#717499",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.4, 0.40784, 0.54118],
      hex: "#66688a",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.26667, 0.27451, 0.36078],
      hex: "#44465c",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.2, 0.20392, 0.27059],
      hex: "#333445",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.13333, 0.13725, 0.18039],
      hex: "#22232e",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.0902, 0.0902, 0.12157],
      hex: "#17171f",
    },
  },
} satisfies AuroraLayer;
