/**
 * Monokai — Hot magenta and cyan on olive darks, from Monokai.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "monokai",
  name: "Monokai",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96078],
      hex: "#fff3f5",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.91373],
      hex: "#ffe5e9",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [1, 0.78824, 0.81961],
      hex: "#ffc9d1",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [1, 0.62353, 0.69804],
      hex: "#ff9fb2",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [1, 0.40784, 0.55294],
      hex: "#ff688d",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.93725, 0.12157, 0.42353],
      hex: "#ef1f6c",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.77647, 0, 0.33333],
      hex: "#c60055",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0.62353, 0, 0.25882],
      hex: "#9f0042",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0.48627, 0, 0.19608],
      hex: "#7c0032",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0.35294, 0, 0.13333],
      hex: "#5a0022",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0.26275, 0, 0.09412],
      hex: "#430018",
    },
    "primary-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96078],
      hex: "#fff3f5",
    },
    "primary-muted-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.91373],
      hex: "#ffe5e9",
    },
    "primary-muted-200": {
      colorSpace: "srgb",
      components: [1, 0.78824, 0.81961],
      hex: "#ffc9d1",
    },
    "primary-muted-300": {
      colorSpace: "srgb",
      components: [0.9451, 0.65882, 0.7098],
      hex: "#f1a8b5",
    },
    "primary-muted-400": {
      colorSpace: "srgb",
      components: [0.85098, 0.53333, 0.59216],
      hex: "#d98897",
    },
    "primary-muted-500": {
      colorSpace: "srgb",
      components: [0.73725, 0.41569, 0.47843],
      hex: "#bc6a7a",
    },
    "primary-muted-600": {
      colorSpace: "srgb",
      components: [0.61961, 0.3098, 0.37647],
      hex: "#9e4f60",
    },
    "primary-muted-700": {
      colorSpace: "srgb",
      components: [0.5098, 0.23137, 0.29412],
      hex: "#823b4b",
    },
    "primary-muted-800": {
      colorSpace: "srgb",
      components: [0.40392, 0.16471, 0.21961],
      hex: "#672a38",
    },
    "primary-muted-900": {
      colorSpace: "srgb",
      components: [0.29412, 0.10588, 0.15294],
      hex: "#4b1b27",
    },
    "primary-muted-950": {
      colorSpace: "srgb",
      components: [0.21569, 0.07451, 0.10588],
      hex: "#37131b",
    },
    "primary-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96078],
      hex: "#fff3f5",
    },
    "primary-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.91373],
      hex: "#ffe5e9",
    },
    "primary-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.78824, 0.81961],
      hex: "#ffc9d1",
    },
    "primary-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.62353, 0.69804],
      hex: "#ff9fb2",
    },
    "primary-vivid-400": {
      colorSpace: "srgb",
      components: [1, 0.40784, 0.55294],
      hex: "#ff688d",
    },
    "primary-vivid-500": {
      colorSpace: "srgb",
      components: [0.95686, 0, 0.41569],
      hex: "#f4006a",
    },
    "primary-vivid-600": {
      colorSpace: "srgb",
      components: [0.77647, 0, 0.33333],
      hex: "#c60055",
    },
    "primary-vivid-700": {
      colorSpace: "srgb",
      components: [0.62353, 0, 0.25882],
      hex: "#9f0042",
    },
    "primary-vivid-800": {
      colorSpace: "srgb",
      components: [0.48627, 0, 0.19608],
      hex: "#7c0032",
    },
    "primary-vivid-900": {
      colorSpace: "srgb",
      components: [0.35294, 0, 0.13333],
      hex: "#5a0022",
    },
    "primary-vivid-950": {
      colorSpace: "srgb",
      components: [0.26275, 0, 0.09412],
      hex: "#430018",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.9098, 0.98431, 1],
      hex: "#e8fbff",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.82353, 0.95686, 0.98431],
      hex: "#d2f4fb",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.67843, 0.89412, 0.93725],
      hex: "#ade4ef",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.50196, 0.80784, 0.86667],
      hex: "#80cedd",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.32941, 0.70196, 0.76863],
      hex: "#54b3c4",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.15686, 0.58431, 0.65882],
      hex: "#2895a8",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0, 0.47451, 0.54118],
      hex: "#00798a",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0, 0.37647, 0.43137],
      hex: "#00606e",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0, 0.2902, 0.33333],
      hex: "#004a55",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0, 0.20784, 0.23922],
      hex: "#00353d",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0, 0.14902, 0.17255],
      hex: "#00262c",
    },
    "secondary-muted-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.97647, 0.98039],
      hex: "#f0f9fa",
    },
    "secondary-muted-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.94118, 0.95294],
      hex: "#e1f0f3",
    },
    "secondary-muted-200": {
      colorSpace: "srgb",
      components: [0.77647, 0.87059, 0.8902],
      hex: "#c6dee3",
    },
    "secondary-muted-300": {
      colorSpace: "srgb",
      components: [0.65098, 0.77647, 0.80392],
      hex: "#a6c6cd",
    },
    "secondary-muted-400": {
      colorSpace: "srgb",
      components: [0.52549, 0.67059, 0.69804],
      hex: "#86abb2",
    },
    "secondary-muted-500": {
      colorSpace: "srgb",
      components: [0.40392, 0.55686, 0.58431],
      hex: "#678e95",
    },
    "secondary-muted-600": {
      colorSpace: "srgb",
      components: [0.30196, 0.45098, 0.47843],
      hex: "#4d737a",
    },
    "secondary-muted-700": {
      colorSpace: "srgb",
      components: [0.22353, 0.36078, 0.38431],
      hex: "#395c62",
    },
    "secondary-muted-800": {
      colorSpace: "srgb",
      components: [0.16078, 0.27451, 0.29804],
      hex: "#29464c",
    },
    "secondary-muted-900": {
      colorSpace: "srgb",
      components: [0.10196, 0.19608, 0.21569],
      hex: "#1a3237",
    },
    "secondary-muted-950": {
      colorSpace: "srgb",
      components: [0.07059, 0.14118, 0.15294],
      hex: "#122427",
    },
    "secondary-vivid-50": {
      colorSpace: "srgb",
      components: [0.9098, 0.98431, 1],
      hex: "#e8fbff",
    },
    "secondary-vivid-100": {
      colorSpace: "srgb",
      components: [0.79216, 0.96471, 1],
      hex: "#caf6ff",
    },
    "secondary-vivid-200": {
      colorSpace: "srgb",
      components: [0.59216, 0.9098, 0.97255],
      hex: "#97e8f8",
    },
    "secondary-vivid-300": {
      colorSpace: "srgb",
      components: [0.3451, 0.82353, 0.91373],
      hex: "#58d2e9",
    },
    "secondary-vivid-400": {
      colorSpace: "srgb",
      components: [0, 0.71765, 0.81176],
      hex: "#00b7cf",
    },
    "secondary-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.59216, 0.67059],
      hex: "#0097ab",
    },
    "secondary-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.47451, 0.54118],
      hex: "#00798a",
    },
    "secondary-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.37647, 0.43137],
      hex: "#00606e",
    },
    "secondary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.2902, 0.33333],
      hex: "#004a55",
    },
    "secondary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.20784, 0.23922],
      hex: "#00353d",
    },
    "secondary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.14902, 0.17255],
      hex: "#00262c",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.96863, 0.96078, 1],
      hex: "#f7f5ff",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.93333, 0.91373, 1],
      hex: "#eee9ff",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.86667, 0.81961, 1],
      hex: "#ddd1ff",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.78039, 0.6902, 1],
      hex: "#c7b0ff",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.68627, 0.53725, 1],
      hex: "#af89ff",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.58039, 0.40784, 0.89412],
      hex: "#9468e4",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.47451, 0.29804, 0.77647],
      hex: "#794cc6",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0.38431, 0.21176, 0.65098],
      hex: "#6236a6",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0.29804, 0.1451, 0.52549],
      hex: "#4c2586",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0.21569, 0.0902, 0.39216],
      hex: "#371764",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0.15294, 0.06275, 0.28627],
      hex: "#271049",
    },
    "tertiary-muted-50": {
      colorSpace: "srgb",
      components: [0.96863, 0.96078, 1],
      hex: "#f7f5ff",
    },
    "tertiary-muted-100": {
      colorSpace: "srgb",
      components: [0.93333, 0.91373, 1],
      hex: "#eee9ff",
    },
    "tertiary-muted-200": {
      colorSpace: "srgb",
      components: [0.86275, 0.82745, 0.96471],
      hex: "#dcd3f6",
    },
    "tertiary-muted-300": {
      colorSpace: "srgb",
      components: [0.76471, 0.71765, 0.90196],
      hex: "#c3b7e6",
    },
    "tertiary-muted-400": {
      colorSpace: "srgb",
      components: [0.65882, 0.6, 0.80784],
      hex: "#a899ce",
    },
    "tertiary-muted-500": {
      colorSpace: "srgb",
      components: [0.5451, 0.48627, 0.69804],
      hex: "#8b7cb2",
    },
    "tertiary-muted-600": {
      colorSpace: "srgb",
      components: [0.44314, 0.38039, 0.58431],
      hex: "#716195",
    },
    "tertiary-muted-700": {
      colorSpace: "srgb",
      components: [0.35294, 0.29804, 0.48235],
      hex: "#5a4c7b",
    },
    "tertiary-muted-800": {
      colorSpace: "srgb",
      components: [0.27059, 0.22353, 0.38039],
      hex: "#453961",
    },
    "tertiary-muted-900": {
      colorSpace: "srgb",
      components: [0.19216, 0.15294, 0.27843],
      hex: "#312747",
    },
    "tertiary-muted-950": {
      colorSpace: "srgb",
      components: [0.13725, 0.1098, 0.2],
      hex: "#231c33",
    },
    "tertiary-vivid-50": {
      colorSpace: "srgb",
      components: [0.96863, 0.96078, 1],
      hex: "#f7f5ff",
    },
    "tertiary-vivid-100": {
      colorSpace: "srgb",
      components: [0.93333, 0.91373, 1],
      hex: "#eee9ff",
    },
    "tertiary-vivid-200": {
      colorSpace: "srgb",
      components: [0.86667, 0.81961, 1],
      hex: "#ddd1ff",
    },
    "tertiary-vivid-300": {
      colorSpace: "srgb",
      components: [0.78039, 0.6902, 1],
      hex: "#c7b0ff",
    },
    "tertiary-vivid-400": {
      colorSpace: "srgb",
      components: [0.68627, 0.53725, 1],
      hex: "#af89ff",
    },
    "tertiary-vivid-500": {
      colorSpace: "srgb",
      components: [0.6, 0.3451, 1],
      hex: "#9958ff",
    },
    "tertiary-vivid-600": {
      colorSpace: "srgb",
      components: [0.50588, 0.17255, 0.9098],
      hex: "#812ce8",
    },
    "tertiary-vivid-700": {
      colorSpace: "srgb",
      components: [0.41569, 0.04314, 0.77255],
      hex: "#6a0bc5",
    },
    "tertiary-vivid-800": {
      colorSpace: "srgb",
      components: [0.32157, 0, 0.61176],
      hex: "#52009c",
    },
    "tertiary-vivid-900": {
      colorSpace: "srgb",
      components: [0.22745, 0, 0.45098],
      hex: "#3a0073",
    },
    "tertiary-vivid-950": {
      colorSpace: "srgb",
      components: [0.16471, 0, 0.33725],
      hex: "#2a0056",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96078],
      hex: "#fff3f5",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.91373],
      hex: "#ffe5e9",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [1, 0.78824, 0.81961],
      hex: "#ffc9d1",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [1, 0.62353, 0.69804],
      hex: "#ff9fb2",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [1, 0.40784, 0.55294],
      hex: "#ff688d",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.93725, 0.12157, 0.42353],
      hex: "#ef1f6c",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.77647, 0, 0.33333],
      hex: "#c60055",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.62353, 0, 0.25882],
      hex: "#9f0042",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.48627, 0, 0.19608],
      hex: "#7c0032",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.35294, 0, 0.13333],
      hex: "#5a0022",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.26275, 0, 0.09412],
      hex: "#430018",
    },
    "error-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96078],
      hex: "#fff3f5",
    },
    "error-muted-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.91373],
      hex: "#ffe5e9",
    },
    "error-muted-200": {
      colorSpace: "srgb",
      components: [1, 0.78824, 0.81961],
      hex: "#ffc9d1",
    },
    "error-muted-300": {
      colorSpace: "srgb",
      components: [0.9451, 0.65882, 0.7098],
      hex: "#f1a8b5",
    },
    "error-muted-400": {
      colorSpace: "srgb",
      components: [0.85098, 0.53333, 0.59216],
      hex: "#d98897",
    },
    "error-muted-500": {
      colorSpace: "srgb",
      components: [0.73725, 0.41569, 0.47843],
      hex: "#bc6a7a",
    },
    "error-muted-600": {
      colorSpace: "srgb",
      components: [0.61961, 0.3098, 0.37647],
      hex: "#9e4f60",
    },
    "error-muted-700": {
      colorSpace: "srgb",
      components: [0.5098, 0.23137, 0.29412],
      hex: "#823b4b",
    },
    "error-muted-800": {
      colorSpace: "srgb",
      components: [0.40392, 0.16471, 0.21961],
      hex: "#672a38",
    },
    "error-muted-900": {
      colorSpace: "srgb",
      components: [0.29412, 0.10588, 0.15294],
      hex: "#4b1b27",
    },
    "error-muted-950": {
      colorSpace: "srgb",
      components: [0.21569, 0.07451, 0.10588],
      hex: "#37131b",
    },
    "error-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96078],
      hex: "#fff3f5",
    },
    "error-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.91373],
      hex: "#ffe5e9",
    },
    "error-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.78824, 0.81961],
      hex: "#ffc9d1",
    },
    "error-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.62353, 0.69804],
      hex: "#ff9fb2",
    },
    "error-vivid-400": {
      colorSpace: "srgb",
      components: [1, 0.40784, 0.55294],
      hex: "#ff688d",
    },
    "error-vivid-500": {
      colorSpace: "srgb",
      components: [0.95686, 0, 0.41569],
      hex: "#f4006a",
    },
    "error-vivid-600": {
      colorSpace: "srgb",
      components: [0.77647, 0, 0.33333],
      hex: "#c60055",
    },
    "error-vivid-700": {
      colorSpace: "srgb",
      components: [0.62353, 0, 0.25882],
      hex: "#9f0042",
    },
    "error-vivid-800": {
      colorSpace: "srgb",
      components: [0.48627, 0, 0.19608],
      hex: "#7c0032",
    },
    "error-vivid-900": {
      colorSpace: "srgb",
      components: [0.35294, 0, 0.13333],
      hex: "#5a0022",
    },
    "error-vivid-950": {
      colorSpace: "srgb",
      components: [0.26275, 0, 0.09412],
      hex: "#430018",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.9451, 0.98431, 0.89804],
      hex: "#f1fbe5",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.88627, 0.95686, 0.80392],
      hex: "#e2f4cd",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.78824, 0.89804, 0.65098],
      hex: "#c9e5a6",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.66667, 0.80784, 0.47059],
      hex: "#aace78",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.5451, 0.70196, 0.30196],
      hex: "#8bb34d",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.42745, 0.58824, 0.14118],
      hex: "#6d9624",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0.33333, 0.47451, 0],
      hex: "#557900",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0.26275, 0.37647, 0],
      hex: "#436000",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0.19608, 0.2902, 0],
      hex: "#324a00",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0.13725, 0.20392, 0],
      hex: "#233400",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0.09412, 0.14902, 0],
      hex: "#182600",
    },
    "success-muted-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.97647, 0.93725],
      hex: "#f4f9ef",
    },
    "success-muted-100": {
      colorSpace: "srgb",
      components: [0.9098, 0.94118, 0.87451],
      hex: "#e8f0df",
    },
    "success-muted-200": {
      colorSpace: "srgb",
      components: [0.82353, 0.87059, 0.76471],
      hex: "#d2dec3",
    },
    "success-muted-300": {
      colorSpace: "srgb",
      components: [0.71373, 0.77647, 0.63529],
      hex: "#b6c6a2",
    },
    "success-muted-400": {
      colorSpace: "srgb",
      components: [0.59608, 0.67059, 0.50588],
      hex: "#98ab81",
    },
    "success-muted-500": {
      colorSpace: "srgb",
      components: [0.48235, 0.55686, 0.38824],
      hex: "#7b8e63",
    },
    "success-muted-600": {
      colorSpace: "srgb",
      components: [0.38039, 0.45098, 0.2902],
      hex: "#61734a",
    },
    "success-muted-700": {
      colorSpace: "srgb",
      components: [0.29804, 0.36078, 0.21176],
      hex: "#4c5c36",
    },
    "success-muted-800": {
      colorSpace: "srgb",
      components: [0.22353, 0.27843, 0.14902],
      hex: "#394726",
    },
    "success-muted-900": {
      colorSpace: "srgb",
      components: [0.15294, 0.19608, 0.09412],
      hex: "#273218",
    },
    "success-muted-950": {
      colorSpace: "srgb",
      components: [0.1098, 0.14118, 0.06275],
      hex: "#1c2410",
    },
    "success-vivid-50": {
      colorSpace: "srgb",
      components: [0.93333, 0.99216, 0.86667],
      hex: "#eefddd",
    },
    "success-vivid-100": {
      colorSpace: "srgb",
      components: [0.87059, 0.96863, 0.75294],
      hex: "#def7c0",
    },
    "success-vivid-200": {
      colorSpace: "srgb",
      components: [0.76078, 0.91373, 0.56078],
      hex: "#c2e98f",
    },
    "success-vivid-300": {
      colorSpace: "srgb",
      components: [0.63137, 0.82745, 0.31765],
      hex: "#a1d351",
    },
    "success-vivid-400": {
      colorSpace: "srgb",
      components: [0.5098, 0.71765, 0],
      hex: "#82b700",
    },
    "success-vivid-500": {
      colorSpace: "srgb",
      components: [0.41569, 0.59216, 0],
      hex: "#6a9700",
    },
    "success-vivid-600": {
      colorSpace: "srgb",
      components: [0.33333, 0.47451, 0],
      hex: "#557900",
    },
    "success-vivid-700": {
      colorSpace: "srgb",
      components: [0.26275, 0.37647, 0],
      hex: "#436000",
    },
    "success-vivid-800": {
      colorSpace: "srgb",
      components: [0.19608, 0.2902, 0],
      hex: "#324a00",
    },
    "success-vivid-900": {
      colorSpace: "srgb",
      components: [0.13725, 0.20392, 0],
      hex: "#233400",
    },
    "success-vivid-950": {
      colorSpace: "srgb",
      components: [0.09412, 0.14902, 0],
      hex: "#182600",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.97255, 0.90196],
      hex: "#f9f8e6",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.93725, 0.81176],
      hex: "#f1efcf",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.87843, 0.86275, 0.66667],
      hex: "#e0dcaa",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.78431, 0.76471, 0.4902],
      hex: "#c8c37d",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.67843, 0.65098, 0.33333],
      hex: "#ada655",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.56863, 0.53725, 0.18824],
      hex: "#918930",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.46275, 0.43137, 0.02745],
      hex: "#766e07",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.36863, 0.34118, 0],
      hex: "#5e5700",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.28235, 0.26275, 0],
      hex: "#484300",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.2, 0.18431, 0],
      hex: "#332f00",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.1451, 0.12941, 0],
      hex: "#252100",
    },
    "warning-muted-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.96863, 0.93725],
      hex: "#f8f7ef",
    },
    "warning-muted-100": {
      colorSpace: "srgb",
      components: [0.93333, 0.93333, 0.87843],
      hex: "#eeeee0",
    },
    "warning-muted-200": {
      colorSpace: "srgb",
      components: [0.86275, 0.85882, 0.76863],
      hex: "#dcdbc4",
    },
    "warning-muted-300": {
      colorSpace: "srgb",
      components: [0.76471, 0.75686, 0.63922],
      hex: "#c3c1a3",
    },
    "warning-muted-400": {
      colorSpace: "srgb",
      components: [0.6549, 0.64706, 0.51373],
      hex: "#a7a583",
    },
    "warning-muted-500": {
      colorSpace: "srgb",
      components: [0.5451, 0.53333, 0.39608],
      hex: "#8b8865",
    },
    "warning-muted-600": {
      colorSpace: "srgb",
      components: [0.43922, 0.43137, 0.29804],
      hex: "#706e4c",
    },
    "warning-muted-700": {
      colorSpace: "srgb",
      components: [0.34902, 0.34118, 0.21961],
      hex: "#595738",
    },
    "warning-muted-800": {
      colorSpace: "srgb",
      components: [0.26667, 0.25882, 0.15686],
      hex: "#444228",
    },
    "warning-muted-900": {
      colorSpace: "srgb",
      components: [0.18824, 0.18431, 0.10196],
      hex: "#302f1a",
    },
    "warning-muted-950": {
      colorSpace: "srgb",
      components: [0.13333, 0.12941, 0.07059],
      hex: "#222112",
    },
    "warning-vivid-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.97647, 0.87451],
      hex: "#faf9df",
    },
    "warning-vivid-100": {
      colorSpace: "srgb",
      components: [0.95294, 0.94118, 0.76471],
      hex: "#f3f0c3",
    },
    "warning-vivid-200": {
      colorSpace: "srgb",
      components: [0.88627, 0.86667, 0.58431],
      hex: "#e2dd95",
    },
    "warning-vivid-300": {
      colorSpace: "srgb",
      components: [0.8, 0.76471, 0.35686],
      hex: "#ccc35b",
    },
    "warning-vivid-400": {
      colorSpace: "srgb",
      components: [0.69804, 0.6549, 0.0902],
      hex: "#b2a717",
    },
    "warning-vivid-500": {
      colorSpace: "srgb",
      components: [0.57647, 0.53725, 0],
      hex: "#938900",
    },
    "warning-vivid-600": {
      colorSpace: "srgb",
      components: [0.46667, 0.43137, 0],
      hex: "#776e00",
    },
    "warning-vivid-700": {
      colorSpace: "srgb",
      components: [0.36863, 0.34118, 0],
      hex: "#5e5700",
    },
    "warning-vivid-800": {
      colorSpace: "srgb",
      components: [0.28235, 0.26275, 0],
      hex: "#484300",
    },
    "warning-vivid-900": {
      colorSpace: "srgb",
      components: [0.2, 0.18431, 0],
      hex: "#332f00",
    },
    "warning-vivid-950": {
      colorSpace: "srgb",
      components: [0.1451, 0.12941, 0],
      hex: "#252100",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.96863, 0.96863, 0.96078],
      hex: "#f7f7f5",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.92941, 0.92941, 0.91765],
      hex: "#ededea",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.85098, 0.85098, 0.83529],
      hex: "#d9d9d5",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.75294, 0.75294, 0.72549],
      hex: "#c0c0b9",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.63922, 0.63922, 0.61176],
      hex: "#a3a39c",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.52941, 0.52941, 0.49804],
      hex: "#87877f",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.42353, 0.42353, 0.39608],
      hex: "#6c6c65",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.33725, 0.33725, 0.3098],
      hex: "#56564f",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.2549, 0.2549, 0.23529],
      hex: "#41413c",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.18039, 0.18039, 0.16471],
      hex: "#2e2e2a",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.12941, 0.12941, 0.11373],
      hex: "#21211d",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.96863, 0.94902],
      hex: "#f8f7f2",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.93725, 0.92941, 0.89804],
      hex: "#efede5",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.86275, 0.85098, 0.80392],
      hex: "#dcd9cd",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.76471, 0.75294, 0.68627],
      hex: "#c3c0af",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.6549, 0.63922, 0.56471],
      hex: "#a7a390",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.5451, 0.52941, 0.45098],
      hex: "#8b8773",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.43922, 0.42353, 0.34902],
      hex: "#706c59",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.34902, 0.33725, 0.27059],
      hex: "#595645",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.26667, 0.2549, 0.2],
      hex: "#444133",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.18824, 0.18039, 0.13725],
      hex: "#302e23",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.13333, 0.12941, 0.09412],
      hex: "#222118",
    },
  },
} satisfies AuroraLayer;
