/**
 * Oxocarbon — IBM blue, teal, and purple on carbon grays, after oxocarbon.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "oxocarbon",
  name: "Oxocarbon",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.96863, 1],
      hex: "#f2f7ff",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [0.8902, 0.92941, 1],
      hex: "#e3edff",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [0.77255, 0.8549, 1],
      hex: "#c5daff",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.61569, 0.75294, 1],
      hex: "#9dc0ff",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.43529, 0.63137, 1],
      hex: "#6fa1ff",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.23137, 0.4902, 1],
      hex: "#3b7dff",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.00392, 0.34902, 0.96078],
      hex: "#0159f5",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0, 0.27451, 0.77255],
      hex: "#0046c5",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0, 0.20784, 0.60392],
      hex: "#00359a",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0, 0.14118, 0.44314],
      hex: "#002471",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0, 0.09804, 0.33333],
      hex: "#001955",
    },
    "primary-muted-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.96863, 1],
      hex: "#f2f7ff",
    },
    "primary-muted-100": {
      colorSpace: "srgb",
      components: [0.8902, 0.92941, 1],
      hex: "#e3edff",
    },
    "primary-muted-200": {
      colorSpace: "srgb",
      components: [0.77255, 0.8549, 1],
      hex: "#c5daff",
    },
    "primary-muted-300": {
      colorSpace: "srgb",
      components: [0.62745, 0.75294, 0.98039],
      hex: "#a0c0fa",
    },
    "primary-muted-400": {
      colorSpace: "srgb",
      components: [0.49804, 0.63922, 0.89412],
      hex: "#7fa3e4",
    },
    "primary-muted-500": {
      colorSpace: "srgb",
      components: [0.38039, 0.52157, 0.78431],
      hex: "#6185c8",
    },
    "primary-muted-600": {
      colorSpace: "srgb",
      components: [0.28235, 0.41569, 0.67059],
      hex: "#486aab",
    },
    "primary-muted-700": {
      colorSpace: "srgb",
      components: [0.20784, 0.32941, 0.55686],
      hex: "#35548e",
    },
    "primary-muted-800": {
      colorSpace: "srgb",
      components: [0.1451, 0.24706, 0.44314],
      hex: "#253f71",
    },
    "primary-muted-900": {
      colorSpace: "srgb",
      components: [0.0902, 0.17255, 0.32941],
      hex: "#172c54",
    },
    "primary-muted-950": {
      colorSpace: "srgb",
      components: [0.06275, 0.12157, 0.23922],
      hex: "#101f3d",
    },
    "primary-vivid-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.96863, 1],
      hex: "#f2f7ff",
    },
    "primary-vivid-100": {
      colorSpace: "srgb",
      components: [0.8902, 0.92941, 1],
      hex: "#e3edff",
    },
    "primary-vivid-200": {
      colorSpace: "srgb",
      components: [0.77255, 0.8549, 1],
      hex: "#c5daff",
    },
    "primary-vivid-300": {
      colorSpace: "srgb",
      components: [0.61569, 0.75294, 1],
      hex: "#9dc0ff",
    },
    "primary-vivid-400": {
      colorSpace: "srgb",
      components: [0.43529, 0.63137, 1],
      hex: "#6fa1ff",
    },
    "primary-vivid-500": {
      colorSpace: "srgb",
      components: [0.23137, 0.4902, 1],
      hex: "#3b7dff",
    },
    "primary-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.34902, 0.96078],
      hex: "#0059f5",
    },
    "primary-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.27451, 0.77255],
      hex: "#0046c5",
    },
    "primary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.20784, 0.60392],
      hex: "#00359a",
    },
    "primary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.14118, 0.44314],
      hex: "#002471",
    },
    "primary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.09804, 0.33333],
      hex: "#001955",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.90196, 0.98824, 0.98431],
      hex: "#e6fcfb",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.80784, 0.96471, 0.95686],
      hex: "#cef6f4",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.6549, 0.90588, 0.89412],
      hex: "#a7e7e4",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.46275, 0.82353, 0.80784],
      hex: "#76d2ce",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.26275, 0.71765, 0.70588],
      hex: "#43b7b4",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0, 0.60392, 0.59216],
      hex: "#009a97",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0, 0.48627, 0.47843],
      hex: "#007c7a",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0, 0.38431, 0.38039],
      hex: "#006261",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0, 0.29804, 0.2902],
      hex: "#004c4a",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0, 0.21176, 0.20784],
      hex: "#003635",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0, 0.15294, 0.14902],
      hex: "#002726",
    },
    "secondary-muted-50": {
      colorSpace: "srgb",
      components: [0.93725, 0.97647, 0.97647],
      hex: "#eff9f9",
    },
    "secondary-muted-100": {
      colorSpace: "srgb",
      components: [0.87843, 0.9451, 0.94118],
      hex: "#e0f1f0",
    },
    "secondary-muted-200": {
      colorSpace: "srgb",
      components: [0.76863, 0.87843, 0.87059],
      hex: "#c4e0de",
    },
    "secondary-muted-300": {
      colorSpace: "srgb",
      components: [0.63922, 0.78431, 0.77647],
      hex: "#a3c8c6",
    },
    "secondary-muted-400": {
      colorSpace: "srgb",
      components: [0.5098, 0.67843, 0.67059],
      hex: "#82adab",
    },
    "secondary-muted-500": {
      colorSpace: "srgb",
      components: [0.38824, 0.56471, 0.55686],
      hex: "#63908e",
    },
    "secondary-muted-600": {
      colorSpace: "srgb",
      components: [0.28627, 0.45882, 0.45098],
      hex: "#497573",
    },
    "secondary-muted-700": {
      colorSpace: "srgb",
      components: [0.20784, 0.36471, 0.36078],
      hex: "#355d5c",
    },
    "secondary-muted-800": {
      colorSpace: "srgb",
      components: [0.1451, 0.28235, 0.27843],
      hex: "#254847",
    },
    "secondary-muted-900": {
      colorSpace: "srgb",
      components: [0.0902, 0.2, 0.19608],
      hex: "#173332",
    },
    "secondary-muted-950": {
      colorSpace: "srgb",
      components: [0.06275, 0.1451, 0.14118],
      hex: "#102524",
    },
    "secondary-vivid-50": {
      colorSpace: "srgb",
      components: [0.87059, 0.99608, 0.99216],
      hex: "#defefd",
    },
    "secondary-vivid-100": {
      colorSpace: "srgb",
      components: [0.75686, 0.98039, 0.96863],
      hex: "#c1faf7",
    },
    "secondary-vivid-200": {
      colorSpace: "srgb",
      components: [0.55686, 0.92941, 0.91373],
      hex: "#8eede9",
    },
    "secondary-vivid-300": {
      colorSpace: "srgb",
      components: [0.25098, 0.84706, 0.83137],
      hex: "#40d8d4",
    },
    "secondary-vivid-400": {
      colorSpace: "srgb",
      components: [0, 0.73333, 0.71765],
      hex: "#00bbb7",
    },
    "secondary-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.60392, 0.59216],
      hex: "#009a97",
    },
    "secondary-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.48627, 0.47843],
      hex: "#007c7a",
    },
    "secondary-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.38431, 0.38039],
      hex: "#006261",
    },
    "secondary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.29804, 0.2902],
      hex: "#004c4a",
    },
    "secondary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.21176, 0.20784],
      hex: "#003635",
    },
    "secondary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.15294, 0.14902],
      hex: "#002726",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.96078, 1],
      hex: "#f8f5ff",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.93725, 0.91373, 1],
      hex: "#efe9ff",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.87059, 0.81961, 1],
      hex: "#ded1ff",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.78431, 0.68627, 1],
      hex: "#c8afff",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.69412, 0.53333, 1],
      hex: "#b188ff",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.59608, 0.37647, 0.94118],
      hex: "#9860f0",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.49412, 0.25882, 0.81961],
      hex: "#7e42d1",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0.4, 0.17255, 0.6902],
      hex: "#662cb0",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0.31373, 0.10196, 0.56078],
      hex: "#501a8f",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0.22353, 0.05098, 0.41961],
      hex: "#390d6b",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0.16078, 0.03529, 0.30588],
      hex: "#29094e",
    },
    "tertiary-muted-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.96078, 1],
      hex: "#f8f5ff",
    },
    "tertiary-muted-100": {
      colorSpace: "srgb",
      components: [0.93725, 0.91373, 1],
      hex: "#efe9ff",
    },
    "tertiary-muted-200": {
      colorSpace: "srgb",
      components: [0.86667, 0.82353, 0.98039],
      hex: "#ddd2fa",
    },
    "tertiary-muted-300": {
      colorSpace: "srgb",
      components: [0.77255, 0.7098, 0.92157],
      hex: "#c5b5eb",
    },
    "tertiary-muted-400": {
      colorSpace: "srgb",
      components: [0.66667, 0.59216, 0.83137],
      hex: "#aa97d4",
    },
    "tertiary-muted-500": {
      colorSpace: "srgb",
      components: [0.55294, 0.47843, 0.71765],
      hex: "#8d7ab7",
    },
    "tertiary-muted-600": {
      colorSpace: "srgb",
      components: [0.44706, 0.37255, 0.60784],
      hex: "#725f9b",
    },
    "tertiary-muted-700": {
      colorSpace: "srgb",
      components: [0.35686, 0.2902, 0.49804],
      hex: "#5b4a7f",
    },
    "tertiary-muted-800": {
      colorSpace: "srgb",
      components: [0.27451, 0.21569, 0.39608],
      hex: "#463765",
    },
    "tertiary-muted-900": {
      colorSpace: "srgb",
      components: [0.19608, 0.14902, 0.2902],
      hex: "#32264a",
    },
    "tertiary-muted-950": {
      colorSpace: "srgb",
      components: [0.14118, 0.10196, 0.21176],
      hex: "#241a36",
    },
    "tertiary-vivid-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.96078, 1],
      hex: "#f8f5ff",
    },
    "tertiary-vivid-100": {
      colorSpace: "srgb",
      components: [0.93725, 0.91373, 1],
      hex: "#efe9ff",
    },
    "tertiary-vivid-200": {
      colorSpace: "srgb",
      components: [0.87059, 0.81961, 1],
      hex: "#ded1ff",
    },
    "tertiary-vivid-300": {
      colorSpace: "srgb",
      components: [0.78431, 0.68627, 1],
      hex: "#c8afff",
    },
    "tertiary-vivid-400": {
      colorSpace: "srgb",
      components: [0.69412, 0.53333, 1],
      hex: "#b188ff",
    },
    "tertiary-vivid-500": {
      colorSpace: "srgb",
      components: [0.61176, 0.33725, 1],
      hex: "#9c56ff",
    },
    "tertiary-vivid-600": {
      colorSpace: "srgb",
      components: [0.52941, 0, 0.96471],
      hex: "#8700f6",
    },
    "tertiary-vivid-700": {
      colorSpace: "srgb",
      components: [0.42353, 0, 0.77647],
      hex: "#6c00c6",
    },
    "tertiary-vivid-800": {
      colorSpace: "srgb",
      components: [0.32549, 0, 0.60784],
      hex: "#53009b",
    },
    "tertiary-vivid-900": {
      colorSpace: "srgb",
      components: [0.23137, 0, 0.44706],
      hex: "#3b0072",
    },
    "tertiary-vivid-950": {
      colorSpace: "srgb",
      components: [0.16863, 0, 0.33333],
      hex: "#2b0055",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.8902],
      hex: "#ffe6e3",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [1, 0.79216, 0.76863],
      hex: "#ffcac4",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [1, 0.63922, 0.60392],
      hex: "#ffa39a",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [1, 0.43137, 0.4],
      hex: "#ff6e66",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.92941, 0.21569, 0.21961],
      hex: "#ed3738",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.79608, 0, 0.10588],
      hex: "#cb001b",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.63922, 0, 0.07843],
      hex: "#a30014",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.49804, 0, 0.05098],
      hex: "#7f000d",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.36471, 0, 0.02745],
      hex: "#5d0007",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.27059, 0, 0.01569],
      hex: "#450004",
    },
    "error-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-muted-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.8902],
      hex: "#ffe6e3",
    },
    "error-muted-200": {
      colorSpace: "srgb",
      components: [0.99608, 0.79608, 0.77255],
      hex: "#fecbc5",
    },
    "error-muted-300": {
      colorSpace: "srgb",
      components: [0.93725, 0.67451, 0.64314],
      hex: "#efaca4",
    },
    "error-muted-400": {
      colorSpace: "srgb",
      components: [0.84314, 0.54902, 0.52157],
      hex: "#d78c85",
    },
    "error-muted-500": {
      colorSpace: "srgb",
      components: [0.72941, 0.43137, 0.40392],
      hex: "#ba6e67",
    },
    "error-muted-600": {
      colorSpace: "srgb",
      components: [0.61569, 0.32941, 0.30588],
      hex: "#9d544e",
    },
    "error-muted-700": {
      colorSpace: "srgb",
      components: [0.50588, 0.24706, 0.22745],
      hex: "#813f3a",
    },
    "error-muted-800": {
      colorSpace: "srgb",
      components: [0.4, 0.17647, 0.16078],
      hex: "#662d29",
    },
    "error-muted-900": {
      colorSpace: "srgb",
      components: [0.29412, 0.11765, 0.10588],
      hex: "#4b1e1b",
    },
    "error-muted-950": {
      colorSpace: "srgb",
      components: [0.21176, 0.08235, 0.07059],
      hex: "#361512",
    },
    "error-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.8902],
      hex: "#ffe6e3",
    },
    "error-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.79216, 0.76863],
      hex: "#ffcac4",
    },
    "error-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.63922, 0.60392],
      hex: "#ffa39a",
    },
    "error-vivid-400": {
      colorSpace: "srgb",
      components: [1, 0.43137, 0.4],
      hex: "#ff6e66",
    },
    "error-vivid-500": {
      colorSpace: "srgb",
      components: [0.98039, 0, 0.14118],
      hex: "#fa0024",
    },
    "error-vivid-600": {
      colorSpace: "srgb",
      components: [0.79608, 0, 0.10588],
      hex: "#cb001b",
    },
    "error-vivid-700": {
      colorSpace: "srgb",
      components: [0.63922, 0, 0.07843],
      hex: "#a30014",
    },
    "error-vivid-800": {
      colorSpace: "srgb",
      components: [0.49804, 0, 0.05098],
      hex: "#7f000d",
    },
    "error-vivid-900": {
      colorSpace: "srgb",
      components: [0.36471, 0, 0.02745],
      hex: "#5d0007",
    },
    "error-vivid-950": {
      colorSpace: "srgb",
      components: [0.27059, 0, 0.01569],
      hex: "#450004",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.90588, 0.99608, 0.91373],
      hex: "#e7fee9",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.81961, 0.97647, 0.83922],
      hex: "#d1f9d6",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.67451, 0.92549, 0.70588],
      hex: "#acecb4",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.49412, 0.84314, 0.54902],
      hex: "#7ed78c",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.31765, 0.74118, 0.40784],
      hex: "#51bd68",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.13333, 0.62745, 0.27843],
      hex: "#22a047",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0, 0.5098, 0.19608],
      hex: "#008232",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0, 0.40784, 0.14902],
      hex: "#006826",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0, 0.31373, 0.1098],
      hex: "#00501c",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.07059],
      hex: "#003912",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.03922],
      hex: "#00290a",
    },
    "success-muted-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.98039, 0.9451],
      hex: "#f0faf1",
    },
    "success-muted-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.94902, 0.88627],
      hex: "#e1f2e2",
    },
    "success-muted-200": {
      colorSpace: "srgb",
      components: [0.77647, 0.88627, 0.78824],
      hex: "#c6e2c9",
    },
    "success-muted-300": {
      colorSpace: "srgb",
      components: [0.64706, 0.79608, 0.66275],
      hex: "#a5cba9",
    },
    "success-muted-400": {
      colorSpace: "srgb",
      components: [0.52157, 0.6902, 0.54118],
      hex: "#85b08a",
    },
    "success-muted-500": {
      colorSpace: "srgb",
      components: [0.40392, 0.57647, 0.42745],
      hex: "#67936d",
    },
    "success-muted-600": {
      colorSpace: "srgb",
      components: [0.30196, 0.47059, 0.32549],
      hex: "#4d7853",
    },
    "success-muted-700": {
      colorSpace: "srgb",
      components: [0.22353, 0.37647, 0.24706],
      hex: "#39603f",
    },
    "success-muted-800": {
      colorSpace: "srgb",
      components: [0.15686, 0.2902, 0.18039],
      hex: "#284a2e",
    },
    "success-muted-900": {
      colorSpace: "srgb",
      components: [0.10196, 0.20784, 0.11765],
      hex: "#1a351e",
    },
    "success-muted-950": {
      colorSpace: "srgb",
      components: [0.07059, 0.14902, 0.08235],
      hex: "#122615",
    },
    "success-vivid-50": {
      colorSpace: "srgb",
      components: [0.89804, 1, 0.9098],
      hex: "#e5ffe8",
    },
    "success-vivid-100": {
      colorSpace: "srgb",
      components: [0.77255, 0.99608, 0.8],
      hex: "#c5fecc",
    },
    "success-vivid-200": {
      colorSpace: "srgb",
      components: [0.58824, 0.95294, 0.64314],
      hex: "#96f3a4",
    },
    "success-vivid-300": {
      colorSpace: "srgb",
      components: [0.32941, 0.87843, 0.4549],
      hex: "#54e074",
    },
    "success-vivid-400": {
      colorSpace: "srgb",
      components: [0, 0.76863, 0.31373],
      hex: "#00c450",
    },
    "success-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.63529, 0.25098],
      hex: "#00a240",
    },
    "success-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.5098, 0.19608],
      hex: "#008232",
    },
    "success-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.40784, 0.14902],
      hex: "#006826",
    },
    "success-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.31373, 0.1098],
      hex: "#00501c",
    },
    "success-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.07059],
      hex: "#003912",
    },
    "success-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.03922],
      hex: "#00290a",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [1, 0.96471, 0.8902],
      hex: "#fff6e3",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [0.98824, 0.92157, 0.78039],
      hex: "#fcebc7",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.9451, 0.83922, 0.61569],
      hex: "#f1d69d",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.87451, 0.72941, 0.41569],
      hex: "#dfba6a",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.78039, 0.61176, 0.21569],
      hex: "#c79c37",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.66275, 0.49804, 0],
      hex: "#a97f00",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.53333, 0.4, 0],
      hex: "#886600",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.42353, 0.31373, 0],
      hex: "#6c5000",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.32549, 0.23922, 0],
      hex: "#533d00",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.23529, 0.16863, 0],
      hex: "#3c2b00",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.16863, 0.11765, 0],
      hex: "#2b1e00",
    },
    "warning-muted-50": {
      colorSpace: "srgb",
      components: [0.98431, 0.96471, 0.92941],
      hex: "#fbf6ed",
    },
    "warning-muted-100": {
      colorSpace: "srgb",
      components: [0.95686, 0.92549, 0.86275],
      hex: "#f4ecdc",
    },
    "warning-muted-200": {
      colorSpace: "srgb",
      components: [0.89412, 0.84706, 0.74902],
      hex: "#e4d8bf",
    },
    "warning-muted-300": {
      colorSpace: "srgb",
      components: [0.80784, 0.7451, 0.61176],
      hex: "#cebe9c",
    },
    "warning-muted-400": {
      colorSpace: "srgb",
      components: [0.70196, 0.63137, 0.48235],
      hex: "#b3a17b",
    },
    "warning-muted-500": {
      colorSpace: "srgb",
      components: [0.59216, 0.51765, 0.36078],
      hex: "#97845c",
    },
    "warning-muted-600": {
      colorSpace: "srgb",
      components: [0.48627, 0.41176, 0.26275],
      hex: "#7c6943",
    },
    "warning-muted-700": {
      colorSpace: "srgb",
      components: [0.38824, 0.32549, 0.18824],
      hex: "#635330",
    },
    "warning-muted-800": {
      colorSpace: "srgb",
      components: [0.30196, 0.24706, 0.12549],
      hex: "#4d3f20",
    },
    "warning-muted-900": {
      colorSpace: "srgb",
      components: [0.21569, 0.17255, 0.07843],
      hex: "#372c14",
    },
    "warning-muted-950": {
      colorSpace: "srgb",
      components: [0.15686, 0.12157, 0.05098],
      hex: "#281f0d",
    },
    "warning-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.96471, 0.8902],
      hex: "#fff6e3",
    },
    "warning-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.92157, 0.75294],
      hex: "#ffebc0",
    },
    "warning-vivid-200": {
      colorSpace: "srgb",
      components: [0.98431, 0.83137, 0.50588],
      hex: "#fbd481",
    },
    "warning-vivid-300": {
      colorSpace: "srgb",
      components: [0.92549, 0.71765, 0.19216],
      hex: "#ecb731",
    },
    "warning-vivid-400": {
      colorSpace: "srgb",
      components: [0.8, 0.60392, 0],
      hex: "#cc9a00",
    },
    "warning-vivid-500": {
      colorSpace: "srgb",
      components: [0.66275, 0.49804, 0],
      hex: "#a97f00",
    },
    "warning-vivid-600": {
      colorSpace: "srgb",
      components: [0.53333, 0.4, 0],
      hex: "#886600",
    },
    "warning-vivid-700": {
      colorSpace: "srgb",
      components: [0.42353, 0.31373, 0],
      hex: "#6c5000",
    },
    "warning-vivid-800": {
      colorSpace: "srgb",
      components: [0.32549, 0.23922, 0],
      hex: "#533d00",
    },
    "warning-vivid-900": {
      colorSpace: "srgb",
      components: [0.23529, 0.16863, 0],
      hex: "#3c2b00",
    },
    "warning-vivid-950": {
      colorSpace: "srgb",
      components: [0.16863, 0.11765, 0],
      hex: "#2b1e00",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.96863, 0.96863, 0.96863],
      hex: "#f7f7f7",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.92941, 0.92941, 0.92941],
      hex: "#ededed",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.85098, 0.85098, 0.85098],
      hex: "#d9d9d9",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.74902, 0.74902, 0.74902],
      hex: "#bfbfbf",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.63922, 0.63922, 0.63922],
      hex: "#a3a3a3",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.52549, 0.52549, 0.52549],
      hex: "#868686",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.42353, 0.42353, 0.42353],
      hex: "#6c6c6c",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.33333, 0.33333, 0.33333],
      hex: "#555555",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.2549, 0.2549, 0.2549],
      hex: "#414141",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.18039, 0.18039, 0.18039],
      hex: "#2e2e2e",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.12549, 0.12549, 0.12549],
      hex: "#202020",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.96078, 0.96863, 0.97647],
      hex: "#f5f7f9",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.91765, 0.92941, 0.94118],
      hex: "#eaedf0",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.83529, 0.8549, 0.87059],
      hex: "#d5dade",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.72941, 0.75294, 0.77647],
      hex: "#bac0c6",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.61569, 0.64314, 0.67059],
      hex: "#9da4ab",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.50196, 0.52941, 0.55686],
      hex: "#80878e",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.4, 0.42745, 0.4549],
      hex: "#666d74",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.31373, 0.33725, 0.36078],
      hex: "#50565c",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.23529, 0.25882, 0.27843],
      hex: "#3c4247",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.16471, 0.18039, 0.2],
      hex: "#2a2e33",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.11765, 0.12941, 0.14118],
      hex: "#1e2124",
    },
  },
} satisfies AuroraLayer;
