/**
 * Material Palenight — Soft violet and indigo pastels, from Material Palenight.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "palenight",
  name: "Material Palenight",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.95686, 1],
      hex: "#faf4ff",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [0.95686, 0.90588, 1],
      hex: "#f4e7ff",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [0.91373, 0.8, 1],
      hex: "#e9ccff",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.83529, 0.67059, 0.95686],
      hex: "#d5abf4",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.73725, 0.5451, 0.87059],
      hex: "#bc8bde",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.62353, 0.42745, 0.76078],
      hex: "#9f6dc2",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.51765, 0.32157, 0.64706],
      hex: "#8452a5",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0.41961, 0.23922, 0.53333],
      hex: "#6b3d88",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0.32549, 0.17255, 0.42745],
      hex: "#532c6d",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0.23529, 0.11373, 0.31373],
      hex: "#3c1d50",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0.16863, 0.07843, 0.22745],
      hex: "#2b143a",
    },
    "primary-muted-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.95686, 0.99608],
      hex: "#faf4fe",
    },
    "primary-muted-100": {
      colorSpace: "srgb",
      components: [0.94902, 0.91373, 0.97647],
      hex: "#f2e9f9",
    },
    "primary-muted-200": {
      colorSpace: "srgb",
      components: [0.88235, 0.82745, 0.92157],
      hex: "#e1d3eb",
    },
    "primary-muted-300": {
      colorSpace: "srgb",
      components: [0.78824, 0.71765, 0.84706],
      hex: "#c9b7d8",
    },
    "primary-muted-400": {
      colorSpace: "srgb",
      components: [0.68235, 0.6, 0.7451],
      hex: "#ae99be",
    },
    "primary-muted-500": {
      colorSpace: "srgb",
      components: [0.57255, 0.48627, 0.63529],
      hex: "#927ca2",
    },
    "primary-muted-600": {
      colorSpace: "srgb",
      components: [0.46667, 0.38431, 0.52549],
      hex: "#776286",
    },
    "primary-muted-700": {
      colorSpace: "srgb",
      components: [0.37255, 0.29804, 0.42745],
      hex: "#5f4c6d",
    },
    "primary-muted-800": {
      colorSpace: "srgb",
      components: [0.28627, 0.22353, 0.33333],
      hex: "#493955",
    },
    "primary-muted-900": {
      colorSpace: "srgb",
      components: [0.20392, 0.15686, 0.24314],
      hex: "#34283e",
    },
    "primary-muted-950": {
      colorSpace: "srgb",
      components: [0.1451, 0.1098, 0.17255],
      hex: "#251c2c",
    },
    "primary-vivid-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.95686, 1],
      hex: "#faf4ff",
    },
    "primary-vivid-100": {
      colorSpace: "srgb",
      components: [0.95686, 0.90588, 1],
      hex: "#f4e7ff",
    },
    "primary-vivid-200": {
      colorSpace: "srgb",
      components: [0.91373, 0.8, 1],
      hex: "#e9ccff",
    },
    "primary-vivid-300": {
      colorSpace: "srgb",
      components: [0.8549, 0.65098, 1],
      hex: "#daa6ff",
    },
    "primary-vivid-400": {
      colorSpace: "srgb",
      components: [0.77255, 0.49804, 0.96078],
      hex: "#c57ff5",
    },
    "primary-vivid-500": {
      colorSpace: "srgb",
      components: [0.66275, 0.36863, 0.85098],
      hex: "#a95ed9",
    },
    "primary-vivid-600": {
      colorSpace: "srgb",
      components: [0.55294, 0.2549, 0.72941],
      hex: "#8d41ba",
    },
    "primary-vivid-700": {
      colorSpace: "srgb",
      components: [0.45098, 0.17255, 0.61176],
      hex: "#732c9c",
    },
    "primary-vivid-800": {
      colorSpace: "srgb",
      components: [0.35686, 0.10588, 0.4902],
      hex: "#5b1b7d",
    },
    "primary-vivid-900": {
      colorSpace: "srgb",
      components: [0.25882, 0.0549, 0.36471],
      hex: "#420e5d",
    },
    "primary-vivid-950": {
      colorSpace: "srgb",
      components: [0.18431, 0.03922, 0.26667],
      hex: "#2f0a44",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.95294, 0.96863, 1],
      hex: "#f3f7ff",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.89412, 0.92941, 1],
      hex: "#e4edff",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.77647, 0.8549, 1],
      hex: "#c6daff",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.61961, 0.75294, 1],
      hex: "#9ec0ff",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.47059, 0.63529, 0.94902],
      hex: "#78a2f2",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.35294, 0.51765, 0.83922],
      hex: "#5a84d6",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0.25098, 0.40784, 0.72157],
      hex: "#4068b8",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0.18039, 0.31765, 0.60392],
      hex: "#2e519a",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0.12157, 0.23922, 0.48627],
      hex: "#1f3d7c",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0.07451, 0.16863, 0.36078],
      hex: "#132b5c",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0.04706, 0.11765, 0.26275],
      hex: "#0c1e43",
    },
    "secondary-muted-50": {
      colorSpace: "srgb",
      components: [0.95294, 0.96863, 1],
      hex: "#f3f7ff",
    },
    "secondary-muted-100": {
      colorSpace: "srgb",
      components: [0.89804, 0.92941, 0.99216],
      hex: "#e5edfd",
    },
    "secondary-muted-200": {
      colorSpace: "srgb",
      components: [0.80392, 0.8549, 0.94902],
      hex: "#cddaf2",
    },
    "secondary-muted-300": {
      colorSpace: "srgb",
      components: [0.68627, 0.75294, 0.87843],
      hex: "#afc0e0",
    },
    "secondary-muted-400": {
      colorSpace: "srgb",
      components: [0.56471, 0.64314, 0.78431],
      hex: "#90a4c8",
    },
    "secondary-muted-500": {
      colorSpace: "srgb",
      components: [0.45098, 0.52941, 0.67059],
      hex: "#7387ab",
    },
    "secondary-muted-600": {
      colorSpace: "srgb",
      components: [0.34902, 0.42353, 0.56078],
      hex: "#596c8f",
    },
    "secondary-muted-700": {
      colorSpace: "srgb",
      components: [0.26667, 0.33333, 0.45882],
      hex: "#445575",
    },
    "secondary-muted-800": {
      colorSpace: "srgb",
      components: [0.2, 0.2549, 0.36078],
      hex: "#33415c",
    },
    "secondary-muted-900": {
      colorSpace: "srgb",
      components: [0.13333, 0.18039, 0.26275],
      hex: "#222e43",
    },
    "secondary-muted-950": {
      colorSpace: "srgb",
      components: [0.09412, 0.12549, 0.18824],
      hex: "#182030",
    },
    "secondary-vivid-50": {
      colorSpace: "srgb",
      components: [0.95294, 0.96863, 1],
      hex: "#f3f7ff",
    },
    "secondary-vivid-100": {
      colorSpace: "srgb",
      components: [0.89412, 0.92941, 1],
      hex: "#e4edff",
    },
    "secondary-vivid-200": {
      colorSpace: "srgb",
      components: [0.77647, 0.8549, 1],
      hex: "#c6daff",
    },
    "secondary-vivid-300": {
      colorSpace: "srgb",
      components: [0.61961, 0.75294, 1],
      hex: "#9ec0ff",
    },
    "secondary-vivid-400": {
      colorSpace: "srgb",
      components: [0.43922, 0.63137, 1],
      hex: "#70a1ff",
    },
    "secondary-vivid-500": {
      colorSpace: "srgb",
      components: [0.27059, 0.49804, 0.96078],
      hex: "#457ff5",
    },
    "secondary-vivid-600": {
      colorSpace: "srgb",
      components: [0.17255, 0.38431, 0.83922],
      hex: "#2c62d6",
    },
    "secondary-vivid-700": {
      colorSpace: "srgb",
      components: [0.10196, 0.29412, 0.7098],
      hex: "#1a4bb5",
    },
    "secondary-vivid-800": {
      colorSpace: "srgb",
      components: [0.05098, 0.21569, 0.57255],
      hex: "#0d3792",
    },
    "secondary-vivid-900": {
      colorSpace: "srgb",
      components: [0.01961, 0.1451, 0.43137],
      hex: "#05256e",
    },
    "secondary-vivid-950": {
      colorSpace: "srgb",
      components: [0.01569, 0.10588, 0.31373],
      hex: "#041b50",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.92549, 0.97647, 1],
      hex: "#ecf9ff",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.83137, 0.95294, 1],
      hex: "#d4f3ff",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.6902, 0.88627, 0.96471],
      hex: "#b0e2f6",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.51765, 0.79608, 0.90196],
      hex: "#84cbe6",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.35686, 0.6902, 0.80784],
      hex: "#5bb0ce",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.20784, 0.57255, 0.69804],
      hex: "#3592b2",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.03137, 0.46667, 0.58824],
      hex: "#087796",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0, 0.37255, 0.47059],
      hex: "#005f78",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0, 0.28235, 0.36471],
      hex: "#00485d",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0, 0.2, 0.26275],
      hex: "#003343",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0, 0.1451, 0.19216],
      hex: "#002531",
    },
    "tertiary-muted-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.97255, 0.98824],
      hex: "#f0f8fc",
    },
    "tertiary-muted-100": {
      colorSpace: "srgb",
      components: [0.88627, 0.94118, 0.96078],
      hex: "#e2f0f5",
    },
    "tertiary-muted-200": {
      colorSpace: "srgb",
      components: [0.78039, 0.86667, 0.90196],
      hex: "#c7dde6",
    },
    "tertiary-muted-300": {
      colorSpace: "srgb",
      components: [0.6549, 0.77255, 0.81961],
      hex: "#a7c5d1",
    },
    "tertiary-muted-400": {
      colorSpace: "srgb",
      components: [0.52941, 0.66275, 0.71765],
      hex: "#87a9b7",
    },
    "tertiary-muted-500": {
      colorSpace: "srgb",
      components: [0.41569, 0.54902, 0.60392],
      hex: "#6a8c9a",
    },
    "tertiary-muted-600": {
      colorSpace: "srgb",
      components: [0.31373, 0.44706, 0.49804],
      hex: "#50727f",
    },
    "tertiary-muted-700": {
      colorSpace: "srgb",
      components: [0.23137, 0.35294, 0.40392],
      hex: "#3b5a67",
    },
    "tertiary-muted-800": {
      colorSpace: "srgb",
      components: [0.16863, 0.27059, 0.31373],
      hex: "#2b4550",
    },
    "tertiary-muted-900": {
      colorSpace: "srgb",
      components: [0.1098, 0.19216, 0.22353],
      hex: "#1c3139",
    },
    "tertiary-muted-950": {
      colorSpace: "srgb",
      components: [0.07451, 0.13725, 0.16078],
      hex: "#132329",
    },
    "tertiary-vivid-50": {
      colorSpace: "srgb",
      components: [0.92549, 0.97647, 1],
      hex: "#ecf9ff",
    },
    "tertiary-vivid-100": {
      colorSpace: "srgb",
      components: [0.83137, 0.95294, 1],
      hex: "#d4f3ff",
    },
    "tertiary-vivid-200": {
      colorSpace: "srgb",
      components: [0.63137, 0.89804, 1],
      hex: "#a1e5ff",
    },
    "tertiary-vivid-300": {
      colorSpace: "srgb",
      components: [0.38824, 0.81176, 0.96078],
      hex: "#63cff5",
    },
    "tertiary-vivid-400": {
      colorSpace: "srgb",
      components: [0.10588, 0.70196, 0.87451],
      hex: "#1bb3df",
    },
    "tertiary-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.58039, 0.72941],
      hex: "#0094ba",
    },
    "tertiary-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.46667, 0.59216],
      hex: "#007797",
    },
    "tertiary-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.37255, 0.47059],
      hex: "#005f78",
    },
    "tertiary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.28235, 0.36471],
      hex: "#00485d",
    },
    "tertiary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.2, 0.26275],
      hex: "#003343",
    },
    "tertiary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.1451, 0.19216],
      hex: "#002531",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95686],
      hex: "#fff4f4",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.90588],
      hex: "#ffe6e7",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [1, 0.78824, 0.8],
      hex: "#ffc9cc",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [1, 0.63137, 0.65882],
      hex: "#ffa1a8",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [1, 0.41961, 0.49412],
      hex: "#ff6b7e",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.89412, 0.2549, 0.37255],
      hex: "#e4415f",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.76471, 0.10588, 0.27059],
      hex: "#c31b45",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.63137, 0, 0.20392],
      hex: "#a10034",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.4902, 0, 0.14902],
      hex: "#7d0026",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.35686, 0, 0.09804],
      hex: "#5b0019",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.26667, 0, 0.06667],
      hex: "#440011",
    },
    "error-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95686],
      hex: "#fff4f4",
    },
    "error-muted-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.90588],
      hex: "#ffe6e7",
    },
    "error-muted-200": {
      colorSpace: "srgb",
      components: [0.98431, 0.79608, 0.80784],
      hex: "#fbcbce",
    },
    "error-muted-300": {
      colorSpace: "srgb",
      components: [0.92157, 0.67843, 0.6902],
      hex: "#ebadb0",
    },
    "error-muted-400": {
      colorSpace: "srgb",
      components: [0.82745, 0.55294, 0.57255],
      hex: "#d38d92",
    },
    "error-muted-500": {
      colorSpace: "srgb",
      components: [0.7098, 0.43529, 0.45882],
      hex: "#b56f75",
    },
    "error-muted-600": {
      colorSpace: "srgb",
      components: [0.59608, 0.33333, 0.35686],
      hex: "#98555b",
    },
    "error-muted-700": {
      colorSpace: "srgb",
      components: [0.4902, 0.25098, 0.27451],
      hex: "#7d4046",
    },
    "error-muted-800": {
      colorSpace: "srgb",
      components: [0.38824, 0.18431, 0.20392],
      hex: "#632f34",
    },
    "error-muted-900": {
      colorSpace: "srgb",
      components: [0.28235, 0.12157, 0.14118],
      hex: "#481f24",
    },
    "error-muted-950": {
      colorSpace: "srgb",
      components: [0.20392, 0.08627, 0.09804],
      hex: "#341619",
    },
    "error-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95686],
      hex: "#fff4f4",
    },
    "error-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.90588],
      hex: "#ffe6e7",
    },
    "error-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.78824, 0.8],
      hex: "#ffc9cc",
    },
    "error-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.63137, 0.65882],
      hex: "#ffa1a8",
    },
    "error-vivid-400": {
      colorSpace: "srgb",
      components: [1, 0.41961, 0.49412],
      hex: "#ff6b7e",
    },
    "error-vivid-500": {
      colorSpace: "srgb",
      components: [0.96863, 0, 0.32941],
      hex: "#f70054",
    },
    "error-vivid-600": {
      colorSpace: "srgb",
      components: [0.78431, 0, 0.25882],
      hex: "#c80042",
    },
    "error-vivid-700": {
      colorSpace: "srgb",
      components: [0.63137, 0, 0.20392],
      hex: "#a10034",
    },
    "error-vivid-800": {
      colorSpace: "srgb",
      components: [0.4902, 0, 0.14902],
      hex: "#7d0026",
    },
    "error-vivid-900": {
      colorSpace: "srgb",
      components: [0.35686, 0, 0.09804],
      hex: "#5b0019",
    },
    "error-vivid-950": {
      colorSpace: "srgb",
      components: [0.26667, 0, 0.06667],
      hex: "#440011",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.98039, 0.91373],
      hex: "#f2fae9",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.89412, 0.95294, 0.83529],
      hex: "#e4f3d5",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.8, 0.88627, 0.70196],
      hex: "#cce2b3",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.68235, 0.79608, 0.5451],
      hex: "#aecb8b",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.56078, 0.6902, 0.4],
      hex: "#8fb066",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.44706, 0.57647, 0.27059],
      hex: "#729345",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0.3451, 0.47059, 0.16078],
      hex: "#587829",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0.26667, 0.37647, 0.08235],
      hex: "#446015",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0.19608, 0.2902, 0.01961],
      hex: "#324a05",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0.13333, 0.20784, 0],
      hex: "#223500",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0.0902, 0.14902, 0.00392],
      hex: "#172601",
    },
    "success-muted-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.97255, 0.94118],
      hex: "#f4f8f0",
    },
    "success-muted-100": {
      colorSpace: "srgb",
      components: [0.91373, 0.94118, 0.88627],
      hex: "#e9f0e2",
    },
    "success-muted-200": {
      colorSpace: "srgb",
      components: [0.82745, 0.86667, 0.78431],
      hex: "#d3ddc8",
    },
    "success-muted-300": {
      colorSpace: "srgb",
      components: [0.71765, 0.77255, 0.66275],
      hex: "#b7c5a9",
    },
    "success-muted-400": {
      colorSpace: "srgb",
      components: [0.60392, 0.66275, 0.53725],
      hex: "#9aa989",
    },
    "success-muted-500": {
      colorSpace: "srgb",
      components: [0.4902, 0.54902, 0.42353],
      hex: "#7d8c6c",
    },
    "success-muted-600": {
      colorSpace: "srgb",
      components: [0.38824, 0.44706, 0.32157],
      hex: "#637252",
    },
    "success-muted-700": {
      colorSpace: "srgb",
      components: [0.30196, 0.35686, 0.24314],
      hex: "#4d5b3e",
    },
    "success-muted-800": {
      colorSpace: "srgb",
      components: [0.22745, 0.27451, 0.17647],
      hex: "#3a462d",
    },
    "success-muted-900": {
      colorSpace: "srgb",
      components: [0.15686, 0.19216, 0.11765],
      hex: "#28311e",
    },
    "success-muted-950": {
      colorSpace: "srgb",
      components: [0.1098, 0.13725, 0.08235],
      hex: "#1c2315",
    },
    "success-vivid-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.98824, 0.8902],
      hex: "#f0fce3",
    },
    "success-vivid-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.96078, 0.79608],
      hex: "#e1f5cb",
    },
    "success-vivid-200": {
      colorSpace: "srgb",
      components: [0.78039, 0.90196, 0.63922],
      hex: "#c7e6a3",
    },
    "success-vivid-300": {
      colorSpace: "srgb",
      components: [0.6549, 0.81176, 0.44706],
      hex: "#a7cf72",
    },
    "success-vivid-400": {
      colorSpace: "srgb",
      components: [0.52941, 0.70588, 0.26667],
      hex: "#87b444",
    },
    "success-vivid-500": {
      colorSpace: "srgb",
      components: [0.41176, 0.59216, 0.07059],
      hex: "#699712",
    },
    "success-vivid-600": {
      colorSpace: "srgb",
      components: [0.32549, 0.47843, 0],
      hex: "#537a00",
    },
    "success-vivid-700": {
      colorSpace: "srgb",
      components: [0.2549, 0.38039, 0],
      hex: "#416100",
    },
    "success-vivid-800": {
      colorSpace: "srgb",
      components: [0.19216, 0.2902, 0],
      hex: "#314a00",
    },
    "success-vivid-900": {
      colorSpace: "srgb",
      components: [0.13333, 0.20784, 0],
      hex: "#223500",
    },
    "success-vivid-950": {
      colorSpace: "srgb",
      components: [0.0902, 0.14902, 0],
      hex: "#172600",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [1, 0.96471, 0.90196],
      hex: "#fff6e6",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [0.98824, 0.92157, 0.80784],
      hex: "#fcebce",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.94118, 0.83529, 0.65882],
      hex: "#f0d5a8",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.86667, 0.72941, 0.48235],
      hex: "#ddba7b",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.77255, 0.61176, 0.31765],
      hex: "#c59c51",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.65882, 0.49412, 0.16863],
      hex: "#a87e2b",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.54902, 0.39216, 0],
      hex: "#8c6400",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.43529, 0.3098, 0],
      hex: "#6f4f00",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.33725, 0.23529, 0],
      hex: "#563c00",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.23922, 0.16471, 0],
      hex: "#3d2a00",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.11373, 0],
      hex: "#2d1d00",
    },
    "warning-muted-50": {
      colorSpace: "srgb",
      components: [0.98431, 0.96471, 0.93725],
      hex: "#fbf6ef",
    },
    "warning-muted-100": {
      colorSpace: "srgb",
      components: [0.95294, 0.92549, 0.87451],
      hex: "#f3ecdf",
    },
    "warning-muted-200": {
      colorSpace: "srgb",
      components: [0.8902, 0.84706, 0.76863],
      hex: "#e3d8c4",
    },
    "warning-muted-300": {
      colorSpace: "srgb",
      components: [0.80392, 0.74118, 0.63529],
      hex: "#cdbda2",
    },
    "warning-muted-400": {
      colorSpace: "srgb",
      components: [0.69804, 0.63137, 0.5098],
      hex: "#b2a182",
    },
    "warning-muted-500": {
      colorSpace: "srgb",
      components: [0.58824, 0.51373, 0.39216],
      hex: "#968364",
    },
    "warning-muted-600": {
      colorSpace: "srgb",
      components: [0.48235, 0.41176, 0.29412],
      hex: "#7b694b",
    },
    "warning-muted-700": {
      colorSpace: "srgb",
      components: [0.38824, 0.32549, 0.21569],
      hex: "#635337",
    },
    "warning-muted-800": {
      colorSpace: "srgb",
      components: [0.29804, 0.24706, 0.15294],
      hex: "#4c3f27",
    },
    "warning-muted-900": {
      colorSpace: "srgb",
      components: [0.21569, 0.17255, 0.09804],
      hex: "#372c19",
    },
    "warning-muted-950": {
      colorSpace: "srgb",
      components: [0.15294, 0.12157, 0.06667],
      hex: "#271f11",
    },
    "warning-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.96471, 0.90196],
      hex: "#fff6e6",
    },
    "warning-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.91765, 0.77647],
      hex: "#ffeac6",
    },
    "warning-vivid-200": {
      colorSpace: "srgb",
      components: [0.97647, 0.82745, 0.57255],
      hex: "#f9d392",
    },
    "warning-vivid-300": {
      colorSpace: "srgb",
      components: [0.91373, 0.71373, 0.34118],
      hex: "#e9b657",
    },
    "warning-vivid-400": {
      colorSpace: "srgb",
      components: [0.81961, 0.59216, 0.01176],
      hex: "#d19703",
    },
    "warning-vivid-500": {
      colorSpace: "srgb",
      components: [0.67843, 0.48627, 0],
      hex: "#ad7c00",
    },
    "warning-vivid-600": {
      colorSpace: "srgb",
      components: [0.54902, 0.39216, 0],
      hex: "#8c6400",
    },
    "warning-vivid-700": {
      colorSpace: "srgb",
      components: [0.43529, 0.3098, 0],
      hex: "#6f4f00",
    },
    "warning-vivid-800": {
      colorSpace: "srgb",
      components: [0.33725, 0.23529, 0],
      hex: "#563c00",
    },
    "warning-vivid-900": {
      colorSpace: "srgb",
      components: [0.23922, 0.16471, 0],
      hex: "#3d2a00",
    },
    "warning-vivid-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.11373, 0],
      hex: "#2d1d00",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.96078, 0.96471, 0.98431],
      hex: "#f5f6fb",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.91765, 0.92549, 0.96078],
      hex: "#eaecf5",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.83529, 0.84706, 0.90196],
      hex: "#d5d8e6",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.73333, 0.7451, 0.81569],
      hex: "#bbbed0",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.61961, 0.63529, 0.71373],
      hex: "#9ea2b6",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.50588, 0.52157, 0.6],
      hex: "#818599",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.40392, 0.41961, 0.49412],
      hex: "#676b7e",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.31765, 0.32941, 0.4],
      hex: "#515466",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.23922, 0.25098, 0.3098],
      hex: "#3d404f",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.16863, 0.17647, 0.22353],
      hex: "#2b2d39",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.11765, 0.12549, 0.16078],
      hex: "#1e2029",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.96471, 1],
      hex: "#f4f6ff",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.9098, 0.92549, 0.99216],
      hex: "#e8ecfd",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.82353, 0.84706, 0.94902],
      hex: "#d2d8f2",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.71373, 0.74118, 0.87843],
      hex: "#b6bde0",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.6, 0.62745, 0.78431],
      hex: "#99a0c8",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.48627, 0.51373, 0.67059],
      hex: "#7c83ab",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.38431, 0.41176, 0.56078],
      hex: "#62698f",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.30196, 0.32549, 0.45882],
      hex: "#4d5375",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.22745, 0.24706, 0.36078],
      hex: "#3a3f5c",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.15686, 0.17255, 0.26275],
      hex: "#282c43",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.1098, 0.12157, 0.18824],
      hex: "#1c1f30",
    },
  },
} satisfies AuroraLayer;
