/**
 * Phosphor — CRT phosphor greens on green-cast grays.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "phosphor",
  name: "Phosphor",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [0.89804, 1, 0.90588],
      hex: "#e5ffe7",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [0.80784, 0.98431, 0.81961],
      hex: "#cefbd1",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [0.65098, 0.93333, 0.67451],
      hex: "#a6eeac",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.45882, 0.8549, 0.50588],
      hex: "#75da81",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.25882, 0.75294, 0.3451],
      hex: "#42c058",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0, 0.63529, 0.21569],
      hex: "#00a237",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0, 0.51373, 0.16471],
      hex: "#00832a",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0, 0.40784, 0.12549],
      hex: "#006820",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0, 0.31373, 0.0902],
      hex: "#005017",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.0549],
      hex: "#00390e",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.03137],
      hex: "#002908",
    },
    "primary-muted-50": {
      colorSpace: "srgb",
      components: [0.93725, 0.98039, 0.93725],
      hex: "#effaef",
    },
    "primary-muted-100": {
      colorSpace: "srgb",
      components: [0.87451, 0.95294, 0.87843],
      hex: "#dff3e0",
    },
    "primary-muted-200": {
      colorSpace: "srgb",
      components: [0.76863, 0.8902, 0.77255],
      hex: "#c4e3c5",
    },
    "primary-muted-300": {
      colorSpace: "srgb",
      components: [0.63529, 0.8, 0.64706],
      hex: "#a2cca5",
    },
    "primary-muted-400": {
      colorSpace: "srgb",
      components: [0.50588, 0.69412, 0.52157],
      hex: "#81b185",
    },
    "primary-muted-500": {
      colorSpace: "srgb",
      components: [0.38824, 0.58039, 0.40392],
      hex: "#639467",
    },
    "primary-muted-600": {
      colorSpace: "srgb",
      components: [0.28627, 0.47451, 0.30196],
      hex: "#49794d",
    },
    "primary-muted-700": {
      colorSpace: "srgb",
      components: [0.20784, 0.38039, 0.22745],
      hex: "#35613a",
    },
    "primary-muted-800": {
      colorSpace: "srgb",
      components: [0.1451, 0.29412, 0.16078],
      hex: "#254b29",
    },
    "primary-muted-900": {
      colorSpace: "srgb",
      components: [0.0902, 0.21176, 0.10588],
      hex: "#17361b",
    },
    "primary-muted-950": {
      colorSpace: "srgb",
      components: [0.06275, 0.14902, 0.07059],
      hex: "#102612",
    },
    "primary-vivid-50": {
      colorSpace: "srgb",
      components: [0.89804, 1, 0.90588],
      hex: "#e5ffe7",
    },
    "primary-vivid-100": {
      colorSpace: "srgb",
      components: [0.76471, 1, 0.78039],
      hex: "#c3ffc7",
    },
    "primary-vivid-200": {
      colorSpace: "srgb",
      components: [0.55294, 0.96078, 0.59608],
      hex: "#8df598",
    },
    "primary-vivid-300": {
      colorSpace: "srgb",
      components: [0.23922, 0.8902, 0.37647],
      hex: "#3de360",
    },
    "primary-vivid-400": {
      colorSpace: "srgb",
      components: [0, 0.76863, 0.26667],
      hex: "#00c444",
    },
    "primary-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.63529, 0.21569],
      hex: "#00a237",
    },
    "primary-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.51373, 0.16471],
      hex: "#00832a",
    },
    "primary-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.40784, 0.12549],
      hex: "#006820",
    },
    "primary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.31373, 0.0902],
      hex: "#005017",
    },
    "primary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.0549],
      hex: "#00390e",
    },
    "primary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.03137],
      hex: "#002908",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.9098, 0.99216, 0.9451],
      hex: "#e8fdf1",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.82745, 0.96863, 0.88627],
      hex: "#d3f7e2",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.68627, 0.91373, 0.78824],
      hex: "#afe9c9",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.5098, 0.83137, 0.66275],
      hex: "#82d4a9",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.34118, 0.72549, 0.54118],
      hex: "#57b98a",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.17647, 0.61176, 0.42745],
      hex: "#2d9c6d",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0, 0.50196, 0.32941],
      hex: "#008054",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0, 0.4, 0.25882],
      hex: "#006642",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0, 0.30588, 0.19216],
      hex: "#004e31",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0, 0.21961, 0.13333],
      hex: "#003822",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0, 0.15686, 0.0902],
      hex: "#002817",
    },
    "secondary-muted-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.97647, 0.95686],
      hex: "#f0f9f4",
    },
    "secondary-muted-100": {
      colorSpace: "srgb",
      components: [0.88235, 0.9451, 0.9098],
      hex: "#e1f1e8",
    },
    "secondary-muted-200": {
      colorSpace: "srgb",
      components: [0.78039, 0.87843, 0.82353],
      hex: "#c7e0d2",
    },
    "secondary-muted-300": {
      colorSpace: "srgb",
      components: [0.6549, 0.78824, 0.71373],
      hex: "#a7c9b6",
    },
    "secondary-muted-400": {
      colorSpace: "srgb",
      components: [0.52941, 0.68235, 0.59608],
      hex: "#87ae98",
    },
    "secondary-muted-500": {
      colorSpace: "srgb",
      components: [0.41176, 0.56863, 0.48235],
      hex: "#69917b",
    },
    "secondary-muted-600": {
      colorSpace: "srgb",
      components: [0.3098, 0.46275, 0.38039],
      hex: "#4f7661",
    },
    "secondary-muted-700": {
      colorSpace: "srgb",
      components: [0.22745, 0.36863, 0.29412],
      hex: "#3a5e4b",
    },
    "secondary-muted-800": {
      colorSpace: "srgb",
      components: [0.16471, 0.28627, 0.22353],
      hex: "#2a4939",
    },
    "secondary-muted-900": {
      colorSpace: "srgb",
      components: [0.10588, 0.20392, 0.15294],
      hex: "#1b3427",
    },
    "secondary-muted-950": {
      colorSpace: "srgb",
      components: [0.07451, 0.1451, 0.10588],
      hex: "#13251b",
    },
    "secondary-vivid-50": {
      colorSpace: "srgb",
      components: [0.88627, 1, 0.93725],
      hex: "#e2ffef",
    },
    "secondary-vivid-100": {
      colorSpace: "srgb",
      components: [0.78039, 0.98431, 0.87059],
      hex: "#c7fbde",
    },
    "secondary-vivid-200": {
      colorSpace: "srgb",
      components: [0.60392, 0.93725, 0.76078],
      hex: "#9aefc2",
    },
    "secondary-vivid-300": {
      colorSpace: "srgb",
      components: [0.36471, 0.85882, 0.62745],
      hex: "#5ddba0",
    },
    "secondary-vivid-400": {
      colorSpace: "srgb",
      components: [0, 0.75686, 0.50196],
      hex: "#00c180",
    },
    "secondary-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.62353, 0.41176],
      hex: "#009f69",
    },
    "secondary-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.50196, 0.32941],
      hex: "#008054",
    },
    "secondary-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.4, 0.25882],
      hex: "#006642",
    },
    "secondary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.30588, 0.19216],
      hex: "#004e31",
    },
    "secondary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.21961, 0.13333],
      hex: "#003822",
    },
    "secondary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.15686, 0.0902],
      hex: "#002817",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.92941, 0.99216, 0.8902],
      hex: "#edfde3",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.86275, 0.96863, 0.79608],
      hex: "#dcf7cb",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.7451, 0.9098, 0.63529],
      hex: "#bee8a2",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.60392, 0.82745, 0.44706],
      hex: "#9ad372",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.47059, 0.72157, 0.26275],
      hex: "#78b843",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.3451, 0.60784, 0.05882],
      hex: "#589b0f",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.27059, 0.4902, 0],
      hex: "#457d00",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0.21176, 0.38824, 0],
      hex: "#366300",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0.15686, 0.29804, 0],
      hex: "#284c00",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0.10588, 0.21176, 0],
      hex: "#1b3600",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0.07059, 0.15294, 0],
      hex: "#122700",
    },
    "tertiary-muted-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.98039, 0.93333],
      hex: "#f2faee",
    },
    "tertiary-muted-100": {
      colorSpace: "srgb",
      components: [0.89804, 0.94902, 0.87059],
      hex: "#e5f2de",
    },
    "tertiary-muted-200": {
      colorSpace: "srgb",
      components: [0.80392, 0.87843, 0.75686],
      hex: "#cde0c1",
    },
    "tertiary-muted-300": {
      colorSpace: "srgb",
      components: [0.68627, 0.78824, 0.62353],
      hex: "#afc99f",
    },
    "tertiary-muted-400": {
      colorSpace: "srgb",
      components: [0.56863, 0.67843, 0.49412],
      hex: "#91ad7e",
    },
    "tertiary-muted-500": {
      colorSpace: "srgb",
      components: [0.45098, 0.56863, 0.37647],
      hex: "#739160",
    },
    "tertiary-muted-600": {
      colorSpace: "srgb",
      components: [0.35294, 0.46275, 0.27843],
      hex: "#5a7647",
    },
    "tertiary-muted-700": {
      colorSpace: "srgb",
      components: [0.27059, 0.36863, 0.2],
      hex: "#455e33",
    },
    "tertiary-muted-800": {
      colorSpace: "srgb",
      components: [0.2, 0.28235, 0.13725],
      hex: "#334823",
    },
    "tertiary-muted-900": {
      colorSpace: "srgb",
      components: [0.13725, 0.20392, 0.08627],
      hex: "#233416",
    },
    "tertiary-muted-950": {
      colorSpace: "srgb",
      components: [0.09412, 0.1451, 0.05882],
      hex: "#18250f",
    },
    "tertiary-vivid-50": {
      colorSpace: "srgb",
      components: [0.91373, 1, 0.86275],
      hex: "#e9ffdc",
    },
    "tertiary-vivid-100": {
      colorSpace: "srgb",
      components: [0.83137, 0.98431, 0.73725],
      hex: "#d4fbbc",
    },
    "tertiary-vivid-200": {
      colorSpace: "srgb",
      components: [0.69804, 0.93333, 0.53725],
      hex: "#b2ee89",
    },
    "tertiary-vivid-300": {
      colorSpace: "srgb",
      components: [0.53725, 0.85098, 0.26275],
      hex: "#89d943",
    },
    "tertiary-vivid-400": {
      colorSpace: "srgb",
      components: [0.41961, 0.73725, 0],
      hex: "#6bbc00",
    },
    "tertiary-vivid-500": {
      colorSpace: "srgb",
      components: [0.34118, 0.60784, 0],
      hex: "#579b00",
    },
    "tertiary-vivid-600": {
      colorSpace: "srgb",
      components: [0.27059, 0.4902, 0],
      hex: "#457d00",
    },
    "tertiary-vivid-700": {
      colorSpace: "srgb",
      components: [0.21176, 0.38824, 0],
      hex: "#366300",
    },
    "tertiary-vivid-800": {
      colorSpace: "srgb",
      components: [0.15686, 0.29804, 0],
      hex: "#284c00",
    },
    "tertiary-vivid-900": {
      colorSpace: "srgb",
      components: [0.10588, 0.21176, 0],
      hex: "#1b3600",
    },
    "tertiary-vivid-950": {
      colorSpace: "srgb",
      components: [0.07059, 0.15294, 0],
      hex: "#122700",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.8902],
      hex: "#ffe6e3",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [1, 0.79608, 0.76471],
      hex: "#ffcbc3",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [1, 0.63922, 0.59216],
      hex: "#ffa397",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [0.98039, 0.4549, 0.39608],
      hex: "#fa7465",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.86275, 0.31765, 0.27059],
      hex: "#dc5145",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.73725, 0.2, 0.16471],
      hex: "#bc332a",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.61176, 0.10588, 0.0902],
      hex: "#9c1b17",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.4902, 0.03137, 0.03137],
      hex: "#7d0808",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.36471, 0, 0.00784],
      hex: "#5d0002",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.26667, 0.00784, 0.00784],
      hex: "#440202",
    },
    "error-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-muted-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.8902],
      hex: "#ffe6e3",
    },
    "error-muted-200": {
      colorSpace: "srgb",
      components: [0.96863, 0.80784, 0.78431],
      hex: "#f7cec8",
    },
    "error-muted-300": {
      colorSpace: "srgb",
      components: [0.90196, 0.6902, 0.65882],
      hex: "#e6b0a8",
    },
    "error-muted-400": {
      colorSpace: "srgb",
      components: [0.80784, 0.56863, 0.53725],
      hex: "#ce9189",
    },
    "error-muted-500": {
      colorSpace: "srgb",
      components: [0.69412, 0.4549, 0.41961],
      hex: "#b1746b",
    },
    "error-muted-600": {
      colorSpace: "srgb",
      components: [0.58039, 0.35294, 0.32157],
      hex: "#945a52",
    },
    "error-muted-700": {
      colorSpace: "srgb",
      components: [0.47451, 0.26667, 0.24314],
      hex: "#79443e",
    },
    "error-muted-800": {
      colorSpace: "srgb",
      components: [0.37255, 0.19608, 0.17647],
      hex: "#5f322d",
    },
    "error-muted-900": {
      colorSpace: "srgb",
      components: [0.27451, 0.13333, 0.11765],
      hex: "#46221e",
    },
    "error-muted-950": {
      colorSpace: "srgb",
      components: [0.19608, 0.09412, 0.07843],
      hex: "#321814",
    },
    "error-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.94902],
      hex: "#fff4f2",
    },
    "error-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.8902],
      hex: "#ffe6e3",
    },
    "error-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.79608, 0.76471],
      hex: "#ffcbc3",
    },
    "error-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.63922, 0.59216],
      hex: "#ffa397",
    },
    "error-vivid-400": {
      colorSpace: "srgb",
      components: [1, 0.43529, 0.37647],
      hex: "#ff6f60",
    },
    "error-vivid-500": {
      colorSpace: "srgb",
      components: [0.96863, 0.09412, 0.10196],
      hex: "#f7181a",
    },
    "error-vivid-600": {
      colorSpace: "srgb",
      components: [0.79608, 0, 0.04314],
      hex: "#cb000b",
    },
    "error-vivid-700": {
      colorSpace: "srgb",
      components: [0.63922, 0, 0.02745],
      hex: "#a30007",
    },
    "error-vivid-800": {
      colorSpace: "srgb",
      components: [0.49804, 0, 0.01569],
      hex: "#7f0004",
    },
    "error-vivid-900": {
      colorSpace: "srgb",
      components: [0.36471, 0, 0.00784],
      hex: "#5d0002",
    },
    "error-vivid-950": {
      colorSpace: "srgb",
      components: [0.27059, 0, 0.00392],
      hex: "#450001",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.90588, 0.99608, 0.92157],
      hex: "#e7feeb",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.81569, 0.97647, 0.84706],
      hex: "#d0f9d8",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.66667, 0.92549, 0.72157],
      hex: "#aaecb8",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.48235, 0.84314, 0.57255],
      hex: "#7bd792",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.29804, 0.74118, 0.43529],
      hex: "#4cbd6f",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.09412, 0.62745, 0.3098],
      hex: "#18a04f",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0, 0.5098, 0.23529],
      hex: "#00823c",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0, 0.40392, 0.18039],
      hex: "#00672e",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0, 0.3098, 0.13333],
      hex: "#004f22",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.08627],
      hex: "#003916",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.0549],
      hex: "#00290e",
    },
    "success-muted-50": {
      colorSpace: "srgb",
      components: [0.94118, 0.98039, 0.9451],
      hex: "#f0faf1",
    },
    "success-muted-100": {
      colorSpace: "srgb",
      components: [0.87843, 0.94902, 0.8902],
      hex: "#e0f2e3",
    },
    "success-muted-200": {
      colorSpace: "srgb",
      components: [0.77255, 0.88627, 0.79608],
      hex: "#c5e2cb",
    },
    "success-muted-300": {
      colorSpace: "srgb",
      components: [0.64314, 0.79608, 0.67451],
      hex: "#a4cbac",
    },
    "success-muted-400": {
      colorSpace: "srgb",
      components: [0.51765, 0.6902, 0.55294],
      hex: "#84b08d",
    },
    "success-muted-500": {
      colorSpace: "srgb",
      components: [0.4, 0.57647, 0.43529],
      hex: "#66936f",
    },
    "success-muted-600": {
      colorSpace: "srgb",
      components: [0.29412, 0.47059, 0.33725],
      hex: "#4b7856",
    },
    "success-muted-700": {
      colorSpace: "srgb",
      components: [0.21569, 0.37647, 0.2549],
      hex: "#376041",
    },
    "success-muted-800": {
      colorSpace: "srgb",
      components: [0.15294, 0.2902, 0.18824],
      hex: "#274a30",
    },
    "success-muted-900": {
      colorSpace: "srgb",
      components: [0.09804, 0.20784, 0.12549],
      hex: "#193520",
    },
    "success-muted-950": {
      colorSpace: "srgb",
      components: [0.06667, 0.14902, 0.08627],
      hex: "#112616",
    },
    "success-vivid-50": {
      colorSpace: "srgb",
      components: [0.89804, 1, 0.91373],
      hex: "#e5ffe9",
    },
    "success-vivid-100": {
      colorSpace: "srgb",
      components: [0.76863, 0.99608, 0.81176],
      hex: "#c4fecf",
    },
    "success-vivid-200": {
      colorSpace: "srgb",
      components: [0.57647, 0.95294, 0.66667],
      hex: "#93f3aa",
    },
    "success-vivid-300": {
      colorSpace: "srgb",
      components: [0.30196, 0.87843, 0.4902],
      hex: "#4de07d",
    },
    "success-vivid-400": {
      colorSpace: "srgb",
      components: [0, 0.76471, 0.36863],
      hex: "#00c35e",
    },
    "success-vivid-500": {
      colorSpace: "srgb",
      components: [0, 0.63137, 0.29804],
      hex: "#00a14c",
    },
    "success-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.5098, 0.23529],
      hex: "#00823c",
    },
    "success-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.40392, 0.18039],
      hex: "#00672e",
    },
    "success-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.3098, 0.13333],
      hex: "#004f22",
    },
    "success-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.08627],
      hex: "#003916",
    },
    "success-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.0549],
      hex: "#00290e",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [0.99608, 0.96863, 0.88235],
      hex: "#fef7e1",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [0.97647, 0.92941, 0.78039],
      hex: "#f9edc7",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.92549, 0.84706, 0.61176],
      hex: "#ecd89c",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.85098, 0.74118, 0.40784],
      hex: "#d9bd68",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.75294, 0.62745, 0.20392],
      hex: "#c0a034",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.63529, 0.51373, 0],
      hex: "#a28300",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.5098, 0.41176, 0],
      hex: "#826900",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.40784, 0.32549, 0],
      hex: "#685300",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.31373, 0.24706, 0],
      hex: "#503f00",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.22353, 0.17255, 0],
      hex: "#392c00",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.16078, 0.12157, 0],
      hex: "#291f00",
    },
    "warning-muted-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.96863, 0.92941],
      hex: "#faf7ed",
    },
    "warning-muted-100": {
      colorSpace: "srgb",
      components: [0.94902, 0.92941, 0.86275],
      hex: "#f2eddc",
    },
    "warning-muted-200": {
      colorSpace: "srgb",
      components: [0.88627, 0.85098, 0.74902],
      hex: "#e2d9bf",
    },
    "warning-muted-300": {
      colorSpace: "srgb",
      components: [0.79608, 0.74902, 0.60784],
      hex: "#cbbf9b",
    },
    "warning-muted-400": {
      colorSpace: "srgb",
      components: [0.6902, 0.63529, 0.47843],
      hex: "#b0a27a",
    },
    "warning-muted-500": {
      colorSpace: "srgb",
      components: [0.57647, 0.52157, 0.36078],
      hex: "#93855c",
    },
    "warning-muted-600": {
      colorSpace: "srgb",
      components: [0.47059, 0.41961, 0.25882],
      hex: "#786b42",
    },
    "warning-muted-700": {
      colorSpace: "srgb",
      components: [0.38039, 0.32941, 0.18431],
      hex: "#61542f",
    },
    "warning-muted-800": {
      colorSpace: "srgb",
      components: [0.29412, 0.25098, 0.12549],
      hex: "#4b4020",
    },
    "warning-muted-900": {
      colorSpace: "srgb",
      components: [0.20784, 0.17647, 0.07451],
      hex: "#352d13",
    },
    "warning-muted-950": {
      colorSpace: "srgb",
      components: [0.14902, 0.12549, 0.05098],
      hex: "#26200d",
    },
    "warning-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.96863, 0.86667],
      hex: "#fff7dd",
    },
    "warning-vivid-100": {
      colorSpace: "srgb",
      components: [0.99608, 0.92549, 0.71373],
      hex: "#feecb6",
    },
    "warning-vivid-200": {
      colorSpace: "srgb",
      components: [0.95686, 0.84314, 0.49804],
      hex: "#f4d77f",
    },
    "warning-vivid-300": {
      colorSpace: "srgb",
      components: [0.8902, 0.73333, 0.16471],
      hex: "#e3bb2a",
    },
    "warning-vivid-400": {
      colorSpace: "srgb",
      components: [0.76863, 0.62353, 0],
      hex: "#c49f00",
    },
    "warning-vivid-500": {
      colorSpace: "srgb",
      components: [0.63529, 0.51373, 0],
      hex: "#a28300",
    },
    "warning-vivid-600": {
      colorSpace: "srgb",
      components: [0.5098, 0.41176, 0],
      hex: "#826900",
    },
    "warning-vivid-700": {
      colorSpace: "srgb",
      components: [0.40784, 0.32549, 0],
      hex: "#685300",
    },
    "warning-vivid-800": {
      colorSpace: "srgb",
      components: [0.31373, 0.24706, 0],
      hex: "#503f00",
    },
    "warning-vivid-900": {
      colorSpace: "srgb",
      components: [0.22353, 0.17255, 0],
      hex: "#392c00",
    },
    "warning-vivid-950": {
      colorSpace: "srgb",
      components: [0.16078, 0.12157, 0],
      hex: "#291f00",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.97255, 0.96078],
      hex: "#f4f8f5",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.9098, 0.93725, 0.91765],
      hex: "#e8efea",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.82353, 0.86275, 0.83529],
      hex: "#d2dcd5",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.7098, 0.76471, 0.72941],
      hex: "#b5c3ba",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.59608, 0.65882, 0.61569],
      hex: "#98a89d",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.48235, 0.5451, 0.50196],
      hex: "#7b8b80",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.38039, 0.43922, 0.4],
      hex: "#617066",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.29412, 0.34902, 0.31373],
      hex: "#4b5950",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.21961, 0.27059, 0.23529],
      hex: "#38453c",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.15294, 0.19216, 0.16471],
      hex: "#27312a",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.10588, 0.13333, 0.11765],
      hex: "#1b221e",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.95294, 0.97255, 0.96078],
      hex: "#f3f8f5",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.90588, 0.93725, 0.91373],
      hex: "#e7efe9",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.81176, 0.86667, 0.83137],
      hex: "#cfddd4",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.69804, 0.77255, 0.72157],
      hex: "#b2c5b8",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.58039, 0.66275, 0.60784],
      hex: "#94a99b",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.46667, 0.54902, 0.49412],
      hex: "#778c7e",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.36471, 0.44706, 0.39216],
      hex: "#5d7264",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.28235, 0.35686, 0.30588],
      hex: "#485b4e",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.20784, 0.27451, 0.23137],
      hex: "#35463b",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.1451, 0.19216, 0.16078],
      hex: "#253129",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.10196, 0.13725, 0.11373],
      hex: "#1a231d",
    },
  },
} satisfies AuroraLayer;
