/**
 * Phosphor — CRT phosphor greens on green-cast grays.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "phosphor",
  name: "Phosphor",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.98431, 0.96471],
      hex: "#f4fbf6",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [0.91373, 0.97255, 0.92941],
      hex: "#e9f8ed",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [0.78824, 0.92941, 0.81961],
      hex: "#c9edd1",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.66275, 0.88627, 0.71373],
      hex: "#a9e2b6",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.40784, 0.8, 0.49804],
      hex: "#68cc7f",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.15294, 0.71373, 0.28235],
      hex: "#27b648",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.13725, 0.64314, 0.2549],
      hex: "#23a441",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0.0902, 0.42745, 0.16863],
      hex: "#176d2b",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0.07059, 0.32157, 0.12549],
      hex: "#125220",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0.04706, 0.21569, 0.08627],
      hex: "#0c3716",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0.03137, 0.14118, 0.0549],
      hex: "#08240e",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.96078, 0.98039, 0.97255],
      hex: "#f5faf8",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.91765, 0.96078, 0.9451],
      hex: "#eaf5f1",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.79608, 0.90588, 0.85882],
      hex: "#cbe7db",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.67451, 0.84706, 0.77255],
      hex: "#acd8c5",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.42745, 0.73333, 0.60392],
      hex: "#6dbb9a",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.18431, 0.61961, 0.43137],
      hex: "#2f9e6e",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0.16471, 0.55686, 0.38824],
      hex: "#2a8e63",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0.1098, 0.37255, 0.25882],
      hex: "#1c5f42",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0.08235, 0.27843, 0.19608],
      hex: "#154732",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0.0549, 0.18431, 0.12941],
      hex: "#0e2f21",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0.03529, 0.12549, 0.08627],
      hex: "#092016",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.98431, 0.96078],
      hex: "#f8fbf5",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.97255, 0.92157],
      hex: "#f1f8eb",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.86275, 0.92941, 0.80784],
      hex: "#dcedce",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.78039, 0.8902, 0.6902],
      hex: "#c7e3b0",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.61961, 0.80392, 0.45882],
      hex: "#9ecd75",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.4549, 0.72157, 0.22745],
      hex: "#74b83a",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.40784, 0.65098, 0.20392],
      hex: "#68a634",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0.27451, 0.43137, 0.13725],
      hex: "#466e23",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0.20392, 0.32549, 0.10196],
      hex: "#34531a",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0.13725, 0.21569, 0.06667],
      hex: "#233711",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0.0902, 0.1451, 0.04706],
      hex: "#17250c",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [0.99216, 0.96471, 0.96471],
      hex: "#fdf6f6",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [0.98431, 0.92941, 0.92549],
      hex: "#fbedec",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [0.96471, 0.82745, 0.81569],
      hex: "#f6d3d0",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [0.94118, 0.72549, 0.70588],
      hex: "#f0b9b4",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [0.89412, 0.51765, 0.48235],
      hex: "#e4847b",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.85098, 0.3098, 0.26275],
      hex: "#d94f43",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.76471, 0.27843, 0.23529],
      hex: "#c3473c",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.5098, 0.18431, 0.15686],
      hex: "#822f28",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.38431, 0.14118, 0.11765],
      hex: "#62241e",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.2549, 0.09412, 0.07843],
      hex: "#411814",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.16863, 0.06275, 0.05098],
      hex: "#2b100d",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.96078, 0.98431, 0.96863],
      hex: "#f5fbf7",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.91765, 0.96863, 0.93725],
      hex: "#eaf7ef",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.79608, 0.92157, 0.83922],
      hex: "#cbebd6",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.67451, 0.87451, 0.7451],
      hex: "#acdfbe",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.42745, 0.77647, 0.55294],
      hex: "#6dc68d",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.18431, 0.68235, 0.36078],
      hex: "#2fae5c",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0.16471, 0.61569, 0.32549],
      hex: "#2a9d53",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0.1098, 0.40784, 0.21569],
      hex: "#1c6837",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0.08235, 0.30588, 0.16078],
      hex: "#154e29",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0.0549, 0.20392, 0.1098],
      hex: "#0e341c",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0.03529, 0.13725, 0.07059],
      hex: "#092312",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [0.98824, 0.98039, 0.95686],
      hex: "#fcfaf4",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [0.97647, 0.96471, 0.91765],
      hex: "#f9f6ea",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.94118, 0.90588, 0.79216],
      hex: "#f0e7ca",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.90588, 0.85098, 0.66275],
      hex: "#e7d9a9",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.83137, 0.74118, 0.41176],
      hex: "#d4bd69",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.76078, 0.62745, 0.16078],
      hex: "#c2a029",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.68627, 0.56471, 0.1451],
      hex: "#af9025",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.4549, 0.37647, 0.09804],
      hex: "#746019",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.34118, 0.28235, 0.07059],
      hex: "#574812",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.22745, 0.18824, 0.04706],
      hex: "#3a300c",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.15294, 0.12549, 0.03137],
      hex: "#272008",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.97647, 0.97255],
      hex: "#f8f9f8",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.94902, 0.9451],
      hex: "#f1f2f1",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.85882, 0.87451, 0.86275],
      hex: "#dbdfdc",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.77255, 0.8, 0.78039],
      hex: "#c5ccc7",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.60392, 0.64706, 0.61961],
      hex: "#9aa59e",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.43529, 0.49804, 0.4549],
      hex: "#6f7f74",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.39216, 0.44706, 0.40784],
      hex: "#647268",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.26275, 0.29804, 0.27451],
      hex: "#434c46",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.19608, 0.22353, 0.20392],
      hex: "#323934",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.12941, 0.14902, 0.13725],
      hex: "#212623",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.08627, 0.09804, 0.0902],
      hex: "#161917",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.96863, 0.97255, 0.97255],
      hex: "#f7f8f8",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.94118, 0.94902, 0.94118],
      hex: "#f0f2f0",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.85098, 0.87059, 0.8549],
      hex: "#d9deda",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.75686, 0.79216, 0.76863],
      hex: "#c1cac4",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.57647, 0.63529, 0.59608],
      hex: "#93a298",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.39608, 0.47843, 0.42353],
      hex: "#657a6c",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.35686, 0.43137, 0.38039],
      hex: "#5b6e61",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.23922, 0.28627, 0.2549],
      hex: "#3d4941",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.17647, 0.21569, 0.19216],
      hex: "#2d3731",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.11765, 0.1451, 0.12549],
      hex: "#1e2520",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.07843, 0.09412, 0.08627],
      hex: "#141816",
    },
  },
} satisfies AuroraLayer;
