/**
 * Rosé Pine — Iris, foam, and rose over deep pine, from Rosé Pine.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "rose_pine",
  name: "Rosé Pine",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.96078, 1],
      hex: "#f9f5ff",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.9098, 1],
      hex: "#f1e8ff",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [0.88235, 0.81569, 0.97255],
      hex: "#e1d0f8",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.79216, 0.70196, 0.9098],
      hex: "#cab3e8",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.68627, 0.58431, 0.81961],
      hex: "#af95d1",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.57647, 0.47059, 0.70588],
      hex: "#9378b4",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.47059, 0.36471, 0.59608],
      hex: "#785d98",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0.37647, 0.28235, 0.4902],
      hex: "#60487d",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0.2902, 0.20784, 0.38824],
      hex: "#4a3563",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0.20784, 0.14118, 0.28235],
      hex: "#352448",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0.14902, 0.09804, 0.20392],
      hex: "#261934",
    },
    "primary-muted-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.96078, 0.98824],
      hex: "#f8f5fc",
    },
    "primary-muted-100": {
      colorSpace: "srgb",
      components: [0.93725, 0.91765, 0.96471],
      hex: "#efeaf6",
    },
    "primary-muted-200": {
      colorSpace: "srgb",
      components: [0.86667, 0.83529, 0.90588],
      hex: "#ddd5e7",
    },
    "primary-muted-300": {
      colorSpace: "srgb",
      components: [0.76863, 0.72941, 0.82353],
      hex: "#c4bad2",
    },
    "primary-muted-400": {
      colorSpace: "srgb",
      components: [0.65882, 0.61569, 0.72157],
      hex: "#a89db8",
    },
    "primary-muted-500": {
      colorSpace: "srgb",
      components: [0.54902, 0.50196, 0.60784],
      hex: "#8c809b",
    },
    "primary-muted-600": {
      colorSpace: "srgb",
      components: [0.44314, 0.4, 0.50196],
      hex: "#716680",
    },
    "primary-muted-700": {
      colorSpace: "srgb",
      components: [0.35294, 0.31373, 0.40784],
      hex: "#5a5068",
    },
    "primary-muted-800": {
      colorSpace: "srgb",
      components: [0.27059, 0.23529, 0.31765],
      hex: "#453c51",
    },
    "primary-muted-900": {
      colorSpace: "srgb",
      components: [0.19216, 0.16471, 0.22745],
      hex: "#312a3a",
    },
    "primary-muted-950": {
      colorSpace: "srgb",
      components: [0.13725, 0.11765, 0.16471],
      hex: "#231e2a",
    },
    "primary-vivid-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.96078, 1],
      hex: "#f9f5ff",
    },
    "primary-vivid-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.9098, 1],
      hex: "#f1e8ff",
    },
    "primary-vivid-200": {
      colorSpace: "srgb",
      components: [0.8902, 0.80784, 1],
      hex: "#e3ceff",
    },
    "primary-vivid-300": {
      colorSpace: "srgb",
      components: [0.81176, 0.68235, 0.97255],
      hex: "#cfaef8",
    },
    "primary-vivid-400": {
      colorSpace: "srgb",
      components: [0.70588, 0.55686, 0.8902],
      hex: "#b48ee3",
    },
    "primary-vivid-500": {
      colorSpace: "srgb",
      components: [0.59608, 0.43922, 0.77647],
      hex: "#9870c6",
    },
    "primary-vivid-600": {
      colorSpace: "srgb",
      components: [0.4902, 0.33333, 0.66275],
      hex: "#7d55a9",
    },
    "primary-vivid-700": {
      colorSpace: "srgb",
      components: [0.39608, 0.25098, 0.54902],
      hex: "#65408c",
    },
    "primary-vivid-800": {
      colorSpace: "srgb",
      components: [0.30588, 0.18039, 0.43922],
      hex: "#4e2e70",
    },
    "primary-vivid-900": {
      colorSpace: "srgb",
      components: [0.21961, 0.12157, 0.32549],
      hex: "#381f53",
    },
    "primary-vivid-950": {
      colorSpace: "srgb",
      components: [0.15686, 0.08235, 0.23529],
      hex: "#28153c",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.93333, 0.97647, 0.98431],
      hex: "#eef9fb",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.87059, 0.9451, 0.95686],
      hex: "#def1f4",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.75686, 0.87843, 0.89804],
      hex: "#c1e0e5",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.61961, 0.78431, 0.81176],
      hex: "#9ec8cf",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.48627, 0.67843, 0.7098],
      hex: "#7cadb5",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.36471, 0.56471, 0.59608],
      hex: "#5d9098",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0.26275, 0.45882, 0.4902],
      hex: "#43757d",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0.18431, 0.36471, 0.39608],
      hex: "#2f5d65",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0.12157, 0.28235, 0.30588],
      hex: "#1f484e",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0.07451, 0.2, 0.21961],
      hex: "#133338",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0.05098, 0.14118, 0.15686],
      hex: "#0d2428",
    },
    "secondary-muted-50": {
      colorSpace: "srgb",
      components: [0.95294, 0.97255, 0.97647],
      hex: "#f3f8f9",
    },
    "secondary-muted-100": {
      colorSpace: "srgb",
      components: [0.90196, 0.93725, 0.94118],
      hex: "#e6eff0",
    },
    "secondary-muted-200": {
      colorSpace: "srgb",
      components: [0.81176, 0.86275, 0.87059],
      hex: "#cfdcde",
    },
    "secondary-muted-300": {
      colorSpace: "srgb",
      components: [0.69412, 0.76471, 0.77647],
      hex: "#b1c3c6",
    },
    "secondary-muted-400": {
      colorSpace: "srgb",
      components: [0.57647, 0.6549, 0.67059],
      hex: "#93a7ab",
    },
    "secondary-muted-500": {
      colorSpace: "srgb",
      components: [0.46275, 0.5451, 0.55686],
      hex: "#768b8e",
    },
    "secondary-muted-600": {
      colorSpace: "srgb",
      components: [0.36078, 0.43922, 0.45098],
      hex: "#5c7073",
    },
    "secondary-muted-700": {
      colorSpace: "srgb",
      components: [0.27843, 0.34902, 0.36078],
      hex: "#47595c",
    },
    "secondary-muted-800": {
      colorSpace: "srgb",
      components: [0.20392, 0.26667, 0.27843],
      hex: "#344447",
    },
    "secondary-muted-900": {
      colorSpace: "srgb",
      components: [0.14118, 0.18824, 0.19608],
      hex: "#243032",
    },
    "secondary-muted-950": {
      colorSpace: "srgb",
      components: [0.09804, 0.13333, 0.14118],
      hex: "#192224",
    },
    "secondary-vivid-50": {
      colorSpace: "srgb",
      components: [0.91765, 0.98039, 0.99216],
      hex: "#eafafd",
    },
    "secondary-vivid-100": {
      colorSpace: "srgb",
      components: [0.84314, 0.95294, 0.96863],
      hex: "#d7f3f7",
    },
    "secondary-vivid-200": {
      colorSpace: "srgb",
      components: [0.71765, 0.88627, 0.91373],
      hex: "#b7e2e9",
    },
    "secondary-vivid-300": {
      colorSpace: "srgb",
      components: [0.56078, 0.79608, 0.83529],
      hex: "#8fcbd5",
    },
    "secondary-vivid-400": {
      colorSpace: "srgb",
      components: [0.41176, 0.6902, 0.73333],
      hex: "#69b0bb",
    },
    "secondary-vivid-500": {
      colorSpace: "srgb",
      components: [0.27843, 0.57647, 0.62353],
      hex: "#47939f",
    },
    "secondary-vivid-600": {
      colorSpace: "srgb",
      components: [0.15686, 0.47059, 0.51765],
      hex: "#287884",
    },
    "secondary-vivid-700": {
      colorSpace: "srgb",
      components: [0.06275, 0.37647, 0.41961],
      hex: "#10606b",
    },
    "secondary-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.2902, 0.32549],
      hex: "#004a53",
    },
    "secondary-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.20784, 0.23529],
      hex: "#00353c",
    },
    "secondary-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.14902, 0.16863],
      hex: "#00262b",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.99608, 0.95686, 0.95294],
      hex: "#fef4f3",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.98039, 0.9098, 0.90588],
      hex: "#fae8e7",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.92941, 0.82353, 0.81961],
      hex: "#edd2d1",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.85098, 0.7098, 0.70588],
      hex: "#d9b5b4",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.75294, 0.59216, 0.58824],
      hex: "#c09796",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.63922, 0.47843, 0.47451],
      hex: "#a37a79",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.52941, 0.37647, 0.37255],
      hex: "#87605f",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0.43137, 0.29412, 0.2902],
      hex: "#6e4b4a",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0.33725, 0.21961, 0.21569],
      hex: "#563837",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0.24314, 0.15294, 0.14902],
      hex: "#3e2726",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.10588, 0.10588],
      hex: "#2d1b1b",
    },
    "tertiary-muted-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.96078, 0.96078],
      hex: "#faf5f5",
    },
    "tertiary-muted-100": {
      colorSpace: "srgb",
      components: [0.95294, 0.92157, 0.91765],
      hex: "#f3ebea",
    },
    "tertiary-muted-200": {
      colorSpace: "srgb",
      components: [0.88627, 0.83922, 0.83529],
      hex: "#e2d6d5",
    },
    "tertiary-muted-300": {
      colorSpace: "srgb",
      components: [0.79608, 0.73333, 0.72941],
      hex: "#cbbbba",
    },
    "tertiary-muted-400": {
      colorSpace: "srgb",
      components: [0.69412, 0.61961, 0.61569],
      hex: "#b19e9d",
    },
    "tertiary-muted-500": {
      colorSpace: "srgb",
      components: [0.58039, 0.50588, 0.50196],
      hex: "#948180",
    },
    "tertiary-muted-600": {
      colorSpace: "srgb",
      components: [0.47451, 0.40392, 0.4],
      hex: "#796766",
    },
    "tertiary-muted-700": {
      colorSpace: "srgb",
      components: [0.38039, 0.31765, 0.31373],
      hex: "#615150",
    },
    "tertiary-muted-800": {
      colorSpace: "srgb",
      components: [0.29412, 0.23922, 0.23922],
      hex: "#4b3d3d",
    },
    "tertiary-muted-900": {
      colorSpace: "srgb",
      components: [0.21176, 0.16863, 0.16471],
      hex: "#362b2a",
    },
    "tertiary-muted-950": {
      colorSpace: "srgb",
      components: [0.14902, 0.11765, 0.11765],
      hex: "#261e1e",
    },
    "tertiary-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95294],
      hex: "#fff4f3",
    },
    "tertiary-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.89804],
      hex: "#ffe6e5",
    },
    "tertiary-vivid-200": {
      colorSpace: "srgb",
      components: [0.96078, 0.81176, 0.80392],
      hex: "#f5cfcd",
    },
    "tertiary-vivid-300": {
      colorSpace: "srgb",
      components: [0.8902, 0.69412, 0.68627],
      hex: "#e3b1af",
    },
    "tertiary-vivid-400": {
      colorSpace: "srgb",
      components: [0.79216, 0.57255, 0.56863],
      hex: "#ca9291",
    },
    "tertiary-vivid-500": {
      colorSpace: "srgb",
      components: [0.67843, 0.45882, 0.4549],
      hex: "#ad7574",
    },
    "tertiary-vivid-600": {
      colorSpace: "srgb",
      components: [0.56863, 0.35686, 0.35294],
      hex: "#915b5a",
    },
    "tertiary-vivid-700": {
      colorSpace: "srgb",
      components: [0.46275, 0.27451, 0.27059],
      hex: "#764645",
    },
    "tertiary-vivid-800": {
      colorSpace: "srgb",
      components: [0.36471, 0.2, 0.2],
      hex: "#5d3333",
    },
    "tertiary-vivid-900": {
      colorSpace: "srgb",
      components: [0.26667, 0.13725, 0.13725],
      hex: "#442323",
    },
    "tertiary-vivid-950": {
      colorSpace: "srgb",
      components: [0.19216, 0.09412, 0.09412],
      hex: "#311818",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96471],
      hex: "#fff3f6",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.91765],
      hex: "#ffe5ea",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [1, 0.78431, 0.83137],
      hex: "#ffc8d4",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [1, 0.62353, 0.71373],
      hex: "#ff9fb6",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [0.92549, 0.47451, 0.59608],
      hex: "#ec7998",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.80784, 0.34902, 0.48235],
      hex: "#ce597b",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.68627, 0.23922, 0.38039],
      hex: "#af3d61",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.56863, 0.15686, 0.29804],
      hex: "#91284c",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.45098, 0.09412, 0.22353],
      hex: "#731839",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.33333, 0.04706, 0.15294],
      hex: "#550c27",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.24314, 0.03137, 0.1098],
      hex: "#3e081c",
    },
    "error-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96471],
      hex: "#fff3f6",
    },
    "error-muted-100": {
      colorSpace: "srgb",
      components: [0.99216, 0.90196, 0.92157],
      hex: "#fde6eb",
    },
    "error-muted-200": {
      colorSpace: "srgb",
      components: [0.94902, 0.81176, 0.83922],
      hex: "#f2cfd6",
    },
    "error-muted-300": {
      colorSpace: "srgb",
      components: [0.87843, 0.69412, 0.73333],
      hex: "#e0b1bb",
    },
    "error-muted-400": {
      colorSpace: "srgb",
      components: [0.78039, 0.57647, 0.61961],
      hex: "#c7939e",
    },
    "error-muted-500": {
      colorSpace: "srgb",
      components: [0.66667, 0.45882, 0.50588],
      hex: "#aa7581",
    },
    "error-muted-600": {
      colorSpace: "srgb",
      components: [0.55686, 0.35686, 0.40392],
      hex: "#8e5b67",
    },
    "error-muted-700": {
      colorSpace: "srgb",
      components: [0.45098, 0.27451, 0.31765],
      hex: "#734651",
    },
    "error-muted-800": {
      colorSpace: "srgb",
      components: [0.35686, 0.20392, 0.23922],
      hex: "#5b343d",
    },
    "error-muted-900": {
      colorSpace: "srgb",
      components: [0.25882, 0.13725, 0.16863],
      hex: "#42232b",
    },
    "error-muted-950": {
      colorSpace: "srgb",
      components: [0.18431, 0.09804, 0.11765],
      hex: "#2f191e",
    },
    "error-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96471],
      hex: "#fff3f6",
    },
    "error-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.91765],
      hex: "#ffe5ea",
    },
    "error-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.78431, 0.83137],
      hex: "#ffc8d4",
    },
    "error-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.62353, 0.71373],
      hex: "#ff9fb6",
    },
    "error-vivid-400": {
      colorSpace: "srgb",
      components: [1, 0.4, 0.58431],
      hex: "#ff6695",
    },
    "error-vivid-500": {
      colorSpace: "srgb",
      components: [0.89804, 0.21569, 0.46667],
      hex: "#e53777",
    },
    "error-vivid-600": {
      colorSpace: "srgb",
      components: [0.77255, 0.01176, 0.36471],
      hex: "#c5035d",
    },
    "error-vivid-700": {
      colorSpace: "srgb",
      components: [0.61961, 0, 0.28627],
      hex: "#9e0049",
    },
    "error-vivid-800": {
      colorSpace: "srgb",
      components: [0.48235, 0, 0.21569],
      hex: "#7b0037",
    },
    "error-vivid-900": {
      colorSpace: "srgb",
      components: [0.35294, 0, 0.15294],
      hex: "#5a0027",
    },
    "error-vivid-950": {
      colorSpace: "srgb",
      components: [0.25882, 0, 0.10588],
      hex: "#42001b",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.93333, 0.97647, 0.98431],
      hex: "#eef9fb",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.87059, 0.9451, 0.95686],
      hex: "#def1f4",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.75686, 0.87843, 0.89804],
      hex: "#c1e0e5",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.61961, 0.78431, 0.81176],
      hex: "#9ec8cf",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.48627, 0.67843, 0.7098],
      hex: "#7cadb5",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.36471, 0.56471, 0.59608],
      hex: "#5d9098",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0.26275, 0.45882, 0.4902],
      hex: "#43757d",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0.18431, 0.36471, 0.39608],
      hex: "#2f5d65",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0.12157, 0.28235, 0.30588],
      hex: "#1f484e",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0.07451, 0.2, 0.21961],
      hex: "#133338",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0.05098, 0.14118, 0.15686],
      hex: "#0d2428",
    },
    "success-muted-50": {
      colorSpace: "srgb",
      components: [0.95294, 0.97255, 0.97647],
      hex: "#f3f8f9",
    },
    "success-muted-100": {
      colorSpace: "srgb",
      components: [0.90196, 0.93725, 0.94118],
      hex: "#e6eff0",
    },
    "success-muted-200": {
      colorSpace: "srgb",
      components: [0.81176, 0.86275, 0.87059],
      hex: "#cfdcde",
    },
    "success-muted-300": {
      colorSpace: "srgb",
      components: [0.69412, 0.76471, 0.77647],
      hex: "#b1c3c6",
    },
    "success-muted-400": {
      colorSpace: "srgb",
      components: [0.57647, 0.6549, 0.67059],
      hex: "#93a7ab",
    },
    "success-muted-500": {
      colorSpace: "srgb",
      components: [0.46275, 0.5451, 0.55686],
      hex: "#768b8e",
    },
    "success-muted-600": {
      colorSpace: "srgb",
      components: [0.36078, 0.43922, 0.45098],
      hex: "#5c7073",
    },
    "success-muted-700": {
      colorSpace: "srgb",
      components: [0.27843, 0.34902, 0.36078],
      hex: "#47595c",
    },
    "success-muted-800": {
      colorSpace: "srgb",
      components: [0.20392, 0.26667, 0.27843],
      hex: "#344447",
    },
    "success-muted-900": {
      colorSpace: "srgb",
      components: [0.14118, 0.18824, 0.19608],
      hex: "#243032",
    },
    "success-muted-950": {
      colorSpace: "srgb",
      components: [0.09804, 0.13333, 0.14118],
      hex: "#192224",
    },
    "success-vivid-50": {
      colorSpace: "srgb",
      components: [0.91765, 0.98039, 0.99216],
      hex: "#eafafd",
    },
    "success-vivid-100": {
      colorSpace: "srgb",
      components: [0.84314, 0.95294, 0.96863],
      hex: "#d7f3f7",
    },
    "success-vivid-200": {
      colorSpace: "srgb",
      components: [0.71765, 0.88627, 0.91373],
      hex: "#b7e2e9",
    },
    "success-vivid-300": {
      colorSpace: "srgb",
      components: [0.56078, 0.79608, 0.83529],
      hex: "#8fcbd5",
    },
    "success-vivid-400": {
      colorSpace: "srgb",
      components: [0.41176, 0.6902, 0.73333],
      hex: "#69b0bb",
    },
    "success-vivid-500": {
      colorSpace: "srgb",
      components: [0.27843, 0.57647, 0.62353],
      hex: "#47939f",
    },
    "success-vivid-600": {
      colorSpace: "srgb",
      components: [0.15686, 0.47059, 0.51765],
      hex: "#287884",
    },
    "success-vivid-700": {
      colorSpace: "srgb",
      components: [0.06275, 0.37647, 0.41961],
      hex: "#10606b",
    },
    "success-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.2902, 0.32549],
      hex: "#004a53",
    },
    "success-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.20784, 0.23529],
      hex: "#00353c",
    },
    "success-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.14902, 0.16863],
      hex: "#00262b",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.9098],
      hex: "#fff5e8",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [0.98824, 0.91765, 0.82353],
      hex: "#fcead2",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.9451, 0.83137, 0.68235],
      hex: "#f1d4ae",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.87059, 0.72157, 0.51765],
      hex: "#deb884",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.77255, 0.60784, 0.36863],
      hex: "#c59b5e",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.66275, 0.4902, 0.23529],
      hex: "#a97d3c",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.55294, 0.38431, 0.11765],
      hex: "#8d621e",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.45098, 0.29804, 0.02353],
      hex: "#734c06",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.34902, 0.22745, 0],
      hex: "#593a00",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.25098, 0.15686, 0],
      hex: "#402800",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.18431, 0.1098, 0],
      hex: "#2f1c00",
    },
    "warning-muted-50": {
      colorSpace: "srgb",
      components: [0.98431, 0.96471, 0.94118],
      hex: "#fbf6f0",
    },
    "warning-muted-100": {
      colorSpace: "srgb",
      components: [0.95686, 0.92157, 0.88235],
      hex: "#f4ebe1",
    },
    "warning-muted-200": {
      colorSpace: "srgb",
      components: [0.89412, 0.84314, 0.77647],
      hex: "#e4d7c6",
    },
    "warning-muted-300": {
      colorSpace: "srgb",
      components: [0.80392, 0.74118, 0.65098],
      hex: "#cdbda6",
    },
    "warning-muted-400": {
      colorSpace: "srgb",
      components: [0.70196, 0.62745, 0.52549],
      hex: "#b3a086",
    },
    "warning-muted-500": {
      colorSpace: "srgb",
      components: [0.58824, 0.51373, 0.41176],
      hex: "#968369",
    },
    "warning-muted-600": {
      colorSpace: "srgb",
      components: [0.48235, 0.40784, 0.3098],
      hex: "#7b684f",
    },
    "warning-muted-700": {
      colorSpace: "srgb",
      components: [0.38824, 0.32157, 0.23137],
      hex: "#63523b",
    },
    "warning-muted-800": {
      colorSpace: "srgb",
      components: [0.30196, 0.24314, 0.16863],
      hex: "#4d3e2b",
    },
    "warning-muted-900": {
      colorSpace: "srgb",
      components: [0.21569, 0.17255, 0.1098],
      hex: "#372c1c",
    },
    "warning-muted-950": {
      colorSpace: "srgb",
      components: [0.15294, 0.12157, 0.07451],
      hex: "#271f13",
    },
    "warning-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.9098],
      hex: "#fff5e8",
    },
    "warning-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.91373, 0.8],
      hex: "#ffe9cc",
    },
    "warning-vivid-200": {
      colorSpace: "srgb",
      components: [0.98039, 0.82353, 0.61176],
      hex: "#fad29c",
    },
    "warning-vivid-300": {
      colorSpace: "srgb",
      components: [0.91765, 0.7098, 0.40784],
      hex: "#eab568",
    },
    "warning-vivid-400": {
      colorSpace: "srgb",
      components: [0.82353, 0.58824, 0.20784],
      hex: "#d29635",
    },
    "warning-vivid-500": {
      colorSpace: "srgb",
      components: [0.70196, 0.47451, 0],
      hex: "#b37900",
    },
    "warning-vivid-600": {
      colorSpace: "srgb",
      components: [0.56863, 0.38039, 0],
      hex: "#916100",
    },
    "warning-vivid-700": {
      colorSpace: "srgb",
      components: [0.4549, 0.29804, 0],
      hex: "#744c00",
    },
    "warning-vivid-800": {
      colorSpace: "srgb",
      components: [0.34902, 0.22745, 0],
      hex: "#593a00",
    },
    "warning-vivid-900": {
      colorSpace: "srgb",
      components: [0.25098, 0.15686, 0],
      hex: "#402800",
    },
    "warning-vivid-950": {
      colorSpace: "srgb",
      components: [0.18431, 0.1098, 0],
      hex: "#2f1c00",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.96863, 0.96471, 0.98039],
      hex: "#f7f6fa",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.92941, 0.92549, 0.94902],
      hex: "#edecf2",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.8549, 0.84314, 0.88627],
      hex: "#dad7e2",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.75294, 0.74118, 0.79608],
      hex: "#c0bdcb",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.64314, 0.62745, 0.6902],
      hex: "#a4a0b0",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.52941, 0.51373, 0.58039],
      hex: "#878394",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.42745, 0.41176, 0.47451],
      hex: "#6d6979",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.33725, 0.32549, 0.38039],
      hex: "#565361",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.25882, 0.24706, 0.29412],
      hex: "#423f4b",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.18431, 0.17255, 0.21176],
      hex: "#2f2c36",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.12941, 0.12157, 0.14902],
      hex: "#211f26",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.96863, 0.96471, 0.98824],
      hex: "#f7f6fc",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.92941, 0.92157, 0.96471],
      hex: "#edebf6",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.85098, 0.84314, 0.9098],
      hex: "#d9d7e8",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.74902, 0.73725, 0.82745],
      hex: "#bfbcd3",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.63922, 0.62353, 0.72549],
      hex: "#a39fb9",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.52549, 0.5098, 0.61569],
      hex: "#86829d",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.42353, 0.40784, 0.50588],
      hex: "#6c6881",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.33333, 0.32157, 0.41176],
      hex: "#555269",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.2549, 0.24314, 0.32157],
      hex: "#413e52",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.18039, 0.16863, 0.23137],
      hex: "#2e2b3b",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.12549, 0.12157, 0.16471],
      hex: "#201f2a",
    },
  },
} satisfies AuroraLayer;
