/**
 * Sakura — Blossom pink, wisteria, and peach on soft rosy grays.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "sakura",
  name: "Sakura",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96471],
      hex: "#fff3f6",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.92549],
      hex: "#ffe5ec",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [1, 0.78431, 0.84706],
      hex: "#ffc8d8",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.98039, 0.63137, 0.7451],
      hex: "#faa1be",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.8902, 0.49804, 0.63529],
      hex: "#e37fa2",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.77255, 0.37255, 0.52157],
      hex: "#c55f85",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.6549, 0.26667, 0.41569],
      hex: "#a7446a",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0.54118, 0.18824, 0.32941],
      hex: "#8a3054",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0.42745, 0.12549, 0.25098],
      hex: "#6d2040",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0.31765, 0.07451, 0.17647],
      hex: "#51132d",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0.23137, 0.05098, 0.12549],
      hex: "#3b0d20",
    },
    "primary-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96471],
      hex: "#fff3f6",
    },
    "primary-muted-100": {
      colorSpace: "srgb",
      components: [0.98431, 0.90588, 0.92549],
      hex: "#fbe7ec",
    },
    "primary-muted-200": {
      colorSpace: "srgb",
      components: [0.93725, 0.81569, 0.85098],
      hex: "#efd0d9",
    },
    "primary-muted-300": {
      colorSpace: "srgb",
      components: [0.86275, 0.69804, 0.74902],
      hex: "#dcb2bf",
    },
    "primary-muted-400": {
      colorSpace: "srgb",
      components: [0.76078, 0.58039, 0.63529],
      hex: "#c294a2",
    },
    "primary-muted-500": {
      colorSpace: "srgb",
      components: [0.64706, 0.46667, 0.52157],
      hex: "#a57785",
    },
    "primary-muted-600": {
      colorSpace: "srgb",
      components: [0.53725, 0.36471, 0.41961],
      hex: "#895d6b",
    },
    "primary-muted-700": {
      colorSpace: "srgb",
      components: [0.43922, 0.28235, 0.33333],
      hex: "#704855",
    },
    "primary-muted-800": {
      colorSpace: "srgb",
      components: [0.34118, 0.20784, 0.25098],
      hex: "#573540",
    },
    "primary-muted-900": {
      colorSpace: "srgb",
      components: [0.24706, 0.1451, 0.17647],
      hex: "#3f252d",
    },
    "primary-muted-950": {
      colorSpace: "srgb",
      components: [0.18039, 0.10196, 0.12549],
      hex: "#2e1a20",
    },
    "primary-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95294, 0.96471],
      hex: "#fff3f6",
    },
    "primary-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.89804, 0.92549],
      hex: "#ffe5ec",
    },
    "primary-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.78431, 0.84706],
      hex: "#ffc8d8",
    },
    "primary-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.61569, 0.7451],
      hex: "#ff9dbe",
    },
    "primary-vivid-400": {
      colorSpace: "srgb",
      components: [0.97255, 0.41961, 0.63137],
      hex: "#f86ba1",
    },
    "primary-vivid-500": {
      colorSpace: "srgb",
      components: [0.8549, 0.27843, 0.51765],
      hex: "#da4784",
    },
    "primary-vivid-600": {
      colorSpace: "srgb",
      components: [0.72941, 0.14902, 0.41569],
      hex: "#ba266a",
    },
    "primary-vivid-700": {
      colorSpace: "srgb",
      components: [0.60784, 0.03137, 0.32941],
      hex: "#9b0854",
    },
    "primary-vivid-800": {
      colorSpace: "srgb",
      components: [0.47843, 0, 0.25098],
      hex: "#7a0040",
    },
    "primary-vivid-900": {
      colorSpace: "srgb",
      components: [0.34902, 0, 0.17647],
      hex: "#59002d",
    },
    "primary-vivid-950": {
      colorSpace: "srgb",
      components: [0.25882, 0, 0.12549],
      hex: "#420020",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.98824, 0.95294, 1],
      hex: "#fcf3ff",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.97255, 0.89804, 1],
      hex: "#f8e5ff",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.91765, 0.80392, 0.96078],
      hex: "#eacdf5",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.83922, 0.68627, 0.89412],
      hex: "#d6afe4",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.73725, 0.56471, 0.8],
      hex: "#bc90cc",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.62745, 0.44706, 0.68627],
      hex: "#a072af",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0.51765, 0.3451, 0.57647],
      hex: "#845893",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0.41961, 0.25882, 0.47059],
      hex: "#6b4278",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0.32549, 0.19216, 0.37255],
      hex: "#53315f",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0.23529, 0.12941, 0.27059],
      hex: "#3c2145",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0.16863, 0.0902, 0.19608],
      hex: "#2b1732",
    },
    "secondary-muted-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.96078, 0.98431],
      hex: "#faf5fb",
    },
    "secondary-muted-100": {
      colorSpace: "srgb",
      components: [0.94902, 0.91373, 0.96078],
      hex: "#f2e9f5",
    },
    "secondary-muted-200": {
      colorSpace: "srgb",
      components: [0.88235, 0.83137, 0.90196],
      hex: "#e1d4e6",
    },
    "secondary-muted-300": {
      colorSpace: "srgb",
      components: [0.79216, 0.72157, 0.81569],
      hex: "#cab8d0",
    },
    "secondary-muted-400": {
      colorSpace: "srgb",
      components: [0.68627, 0.60784, 0.71373],
      hex: "#af9bb6",
    },
    "secondary-muted-500": {
      colorSpace: "srgb",
      components: [0.57255, 0.49412, 0.6],
      hex: "#927e99",
    },
    "secondary-muted-600": {
      colorSpace: "srgb",
      components: [0.46667, 0.39216, 0.49412],
      hex: "#77647e",
    },
    "secondary-muted-700": {
      colorSpace: "srgb",
      components: [0.37255, 0.30588, 0.39608],
      hex: "#5f4e65",
    },
    "secondary-muted-800": {
      colorSpace: "srgb",
      components: [0.2902, 0.23137, 0.3098],
      hex: "#4a3b4f",
    },
    "secondary-muted-900": {
      colorSpace: "srgb",
      components: [0.20784, 0.16078, 0.22353],
      hex: "#352939",
    },
    "secondary-muted-950": {
      colorSpace: "srgb",
      components: [0.14902, 0.11373, 0.16078],
      hex: "#261d29",
    },
    "secondary-vivid-50": {
      colorSpace: "srgb",
      components: [0.98824, 0.95294, 1],
      hex: "#fcf3ff",
    },
    "secondary-vivid-100": {
      colorSpace: "srgb",
      components: [0.97255, 0.89804, 1],
      hex: "#f8e5ff",
    },
    "secondary-vivid-200": {
      colorSpace: "srgb",
      components: [0.9451, 0.78431, 1],
      hex: "#f1c8ff",
    },
    "secondary-vivid-300": {
      colorSpace: "srgb",
      components: [0.87451, 0.6549, 0.94902],
      hex: "#dfa7f2",
    },
    "secondary-vivid-400": {
      colorSpace: "srgb",
      components: [0.77647, 0.52549, 0.85882],
      hex: "#c686db",
    },
    "secondary-vivid-500": {
      colorSpace: "srgb",
      components: [0.66275, 0.40392, 0.74902],
      hex: "#a967bf",
    },
    "secondary-vivid-600": {
      colorSpace: "srgb",
      components: [0.55294, 0.29804, 0.63529],
      hex: "#8d4ca2",
    },
    "secondary-vivid-700": {
      colorSpace: "srgb",
      components: [0.45098, 0.21961, 0.52549],
      hex: "#733886",
    },
    "secondary-vivid-800": {
      colorSpace: "srgb",
      components: [0.35294, 0.15294, 0.41569],
      hex: "#5a276a",
    },
    "secondary-vivid-900": {
      colorSpace: "srgb",
      components: [0.25882, 0.09804, 0.30588],
      hex: "#42194e",
    },
    "secondary-vivid-950": {
      colorSpace: "srgb",
      components: [0.18431, 0.06667, 0.22353],
      hex: "#2f1139",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.9451],
      hex: "#fff4f1",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [1, 0.90588, 0.87843],
      hex: "#ffe7e0",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [1, 0.79608, 0.7451],
      hex: "#ffcbbe",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.95294, 0.67059, 0.59608],
      hex: "#f3ab98",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.86275, 0.5451, 0.46275],
      hex: "#dc8b76",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.74902, 0.42353, 0.3451],
      hex: "#bf6c58",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.63137, 0.32157, 0.24314],
      hex: "#a1523e",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0.52157, 0.23922, 0.16863],
      hex: "#853d2b",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0.41176, 0.17255, 0.1098],
      hex: "#692c1c",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0.30196, 0.11373, 0.06667],
      hex: "#4d1d11",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0.21961, 0.07843, 0.04314],
      hex: "#38140b",
    },
    "tertiary-muted-50": {
      colorSpace: "srgb",
      components: [0.99608, 0.95686, 0.94902],
      hex: "#fef4f2",
    },
    "tertiary-muted-100": {
      colorSpace: "srgb",
      components: [0.97647, 0.91373, 0.89412],
      hex: "#f9e9e4",
    },
    "tertiary-muted-200": {
      colorSpace: "srgb",
      components: [0.92549, 0.82745, 0.8],
      hex: "#ecd3cc",
    },
    "tertiary-muted-300": {
      colorSpace: "srgb",
      components: [0.84706, 0.71765, 0.68235],
      hex: "#d8b7ae",
    },
    "tertiary-muted-400": {
      colorSpace: "srgb",
      components: [0.7451, 0.6, 0.56078],
      hex: "#be998f",
    },
    "tertiary-muted-500": {
      colorSpace: "srgb",
      components: [0.63529, 0.48627, 0.44706],
      hex: "#a27c72",
    },
    "tertiary-muted-600": {
      colorSpace: "srgb",
      components: [0.52549, 0.38431, 0.3451],
      hex: "#866258",
    },
    "tertiary-muted-700": {
      colorSpace: "srgb",
      components: [0.42745, 0.29804, 0.26667],
      hex: "#6d4c44",
    },
    "tertiary-muted-800": {
      colorSpace: "srgb",
      components: [0.33333, 0.22353, 0.19608],
      hex: "#553932",
    },
    "tertiary-muted-900": {
      colorSpace: "srgb",
      components: [0.23922, 0.15686, 0.13333],
      hex: "#3d2822",
    },
    "tertiary-muted-950": {
      colorSpace: "srgb",
      components: [0.17255, 0.1098, 0.09412],
      hex: "#2c1c18",
    },
    "tertiary-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.9451],
      hex: "#fff4f1",
    },
    "tertiary-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.90588, 0.87843],
      hex: "#ffe7e0",
    },
    "tertiary-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.79608, 0.7451],
      hex: "#ffcbbe",
    },
    "tertiary-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.64314, 0.55294],
      hex: "#ffa48d",
    },
    "tertiary-vivid-400": {
      colorSpace: "srgb",
      components: [0.93725, 0.49412, 0.38431],
      hex: "#ef7e62",
    },
    "tertiary-vivid-500": {
      colorSpace: "srgb",
      components: [0.82353, 0.36863, 0.2549],
      hex: "#d25e41",
    },
    "tertiary-vivid-600": {
      colorSpace: "srgb",
      components: [0.70196, 0.2549, 0.1451],
      hex: "#b34125",
    },
    "tertiary-vivid-700": {
      colorSpace: "srgb",
      components: [0.58039, 0.17255, 0.06275],
      hex: "#942c10",
    },
    "tertiary-vivid-800": {
      colorSpace: "srgb",
      components: [0.46275, 0.1098, 0.00784],
      hex: "#761c02",
    },
    "tertiary-vivid-900": {
      colorSpace: "srgb",
      components: [0.34118, 0.06275, 0],
      hex: "#571000",
    },
    "tertiary-vivid-950": {
      colorSpace: "srgb",
      components: [0.25098, 0.03922, 0],
      hex: "#400a00",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95686],
      hex: "#fff4f4",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.90196],
      hex: "#ffe6e6",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [1, 0.79216, 0.79608],
      hex: "#ffcacb",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [1, 0.63137, 0.6549],
      hex: "#ffa1a7",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [0.97255, 0.44706, 0.50196],
      hex: "#f87280",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.85098, 0.31373, 0.38431],
      hex: "#d95062",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.72941, 0.19608, 0.28235],
      hex: "#ba3248",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.60392, 0.10196, 0.20784],
      hex: "#9a1a35",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.48235, 0.03137, 0.1451],
      hex: "#7b0825",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.35686, 0, 0.09412],
      hex: "#5b0018",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.26275, 0.00784, 0.06275],
      hex: "#430210",
    },
    "error-muted-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95686],
      hex: "#fff4f4",
    },
    "error-muted-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.90196],
      hex: "#ffe6e6",
    },
    "error-muted-200": {
      colorSpace: "srgb",
      components: [0.96471, 0.80392, 0.81176],
      hex: "#f6cdcf",
    },
    "error-muted-300": {
      colorSpace: "srgb",
      components: [0.89804, 0.68627, 0.69412],
      hex: "#e5afb1",
    },
    "error-muted-400": {
      colorSpace: "srgb",
      components: [0.80392, 0.56863, 0.57647],
      hex: "#cd9193",
    },
    "error-muted-500": {
      colorSpace: "srgb",
      components: [0.6902, 0.45098, 0.46275],
      hex: "#b07376",
    },
    "error-muted-600": {
      colorSpace: "srgb",
      components: [0.57647, 0.34902, 0.36078],
      hex: "#93595c",
    },
    "error-muted-700": {
      colorSpace: "srgb",
      components: [0.47059, 0.26667, 0.27843],
      hex: "#784447",
    },
    "error-muted-800": {
      colorSpace: "srgb",
      components: [0.37255, 0.19608, 0.20784],
      hex: "#5f3235",
    },
    "error-muted-900": {
      colorSpace: "srgb",
      components: [0.27059, 0.13333, 0.14118],
      hex: "#452224",
    },
    "error-muted-950": {
      colorSpace: "srgb",
      components: [0.19608, 0.0902, 0.09804],
      hex: "#321719",
    },
    "error-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.95686, 0.95686],
      hex: "#fff4f4",
    },
    "error-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.90196, 0.90196],
      hex: "#ffe6e6",
    },
    "error-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.79216, 0.79608],
      hex: "#ffcacb",
    },
    "error-vivid-300": {
      colorSpace: "srgb",
      components: [1, 0.63137, 0.6549],
      hex: "#ffa1a7",
    },
    "error-vivid-400": {
      colorSpace: "srgb",
      components: [1, 0.41961, 0.48627],
      hex: "#ff6b7c",
    },
    "error-vivid-500": {
      colorSpace: "srgb",
      components: [0.95686, 0.0902, 0.32157],
      hex: "#f41752",
    },
    "error-vivid-600": {
      colorSpace: "srgb",
      components: [0.78824, 0, 0.24706],
      hex: "#c9003f",
    },
    "error-vivid-700": {
      colorSpace: "srgb",
      components: [0.63137, 0, 0.19216],
      hex: "#a10031",
    },
    "error-vivid-800": {
      colorSpace: "srgb",
      components: [0.4902, 0, 0.14118],
      hex: "#7d0024",
    },
    "error-vivid-900": {
      colorSpace: "srgb",
      components: [0.35686, 0, 0.09412],
      hex: "#5b0018",
    },
    "error-vivid-950": {
      colorSpace: "srgb",
      components: [0.26667, 0, 0.05882],
      hex: "#44000f",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.92549, 0.98824, 0.92941],
      hex: "#ecfced",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.85098, 0.96471, 0.86275],
      hex: "#d9f6dc",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.72941, 0.90588, 0.74902],
      hex: "#bae7bf",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.57647, 0.81961, 0.61176],
      hex: "#93d19c",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.43529, 0.71765, 0.48235],
      hex: "#6fb77b",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.30588, 0.60392, 0.36078],
      hex: "#4e9a5c",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0.19216, 0.49412, 0.26275],
      hex: "#317e43",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0.1098, 0.39608, 0.18431],
      hex: "#1c652f",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0.04314, 0.3098, 0.12549],
      hex: "#0b4f20",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0.01176, 0.22353, 0.07451],
      hex: "#033913",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0.01176, 0.15686, 0.05098],
      hex: "#03280d",
    },
    "success-muted-50": {
      colorSpace: "srgb",
      components: [0.94902, 0.97647, 0.94902],
      hex: "#f2f9f2",
    },
    "success-muted-100": {
      colorSpace: "srgb",
      components: [0.89412, 0.9451, 0.89804],
      hex: "#e4f1e5",
    },
    "success-muted-200": {
      colorSpace: "srgb",
      components: [0.79608, 0.87451, 0.80784],
      hex: "#cbdfce",
    },
    "success-muted-300": {
      colorSpace: "srgb",
      components: [0.67843, 0.78431, 0.6902],
      hex: "#adc8b0",
    },
    "success-muted-400": {
      colorSpace: "srgb",
      components: [0.55686, 0.67451, 0.57255],
      hex: "#8eac92",
    },
    "success-muted-500": {
      colorSpace: "srgb",
      components: [0.43922, 0.56078, 0.4549],
      hex: "#708f74",
    },
    "success-muted-600": {
      colorSpace: "srgb",
      components: [0.34118, 0.45882, 0.35686],
      hex: "#57755b",
    },
    "success-muted-700": {
      colorSpace: "srgb",
      components: [0.25882, 0.36471, 0.27451],
      hex: "#425d46",
    },
    "success-muted-800": {
      colorSpace: "srgb",
      components: [0.18824, 0.28235, 0.20392],
      hex: "#304834",
    },
    "success-muted-900": {
      colorSpace: "srgb",
      components: [0.12549, 0.2, 0.13725],
      hex: "#203323",
    },
    "success-muted-950": {
      colorSpace: "srgb",
      components: [0.0902, 0.14118, 0.09804],
      hex: "#172419",
    },
    "success-vivid-50": {
      colorSpace: "srgb",
      components: [0.90588, 0.99608, 0.91373],
      hex: "#e7fee9",
    },
    "success-vivid-100": {
      colorSpace: "srgb",
      components: [0.81961, 0.97647, 0.83922],
      hex: "#d1f9d6",
    },
    "success-vivid-200": {
      colorSpace: "srgb",
      components: [0.67059, 0.92549, 0.7098],
      hex: "#abecb5",
    },
    "success-vivid-300": {
      colorSpace: "srgb",
      components: [0.4902, 0.84314, 0.55294],
      hex: "#7dd78d",
    },
    "success-vivid-400": {
      colorSpace: "srgb",
      components: [0.31373, 0.74118, 0.40784],
      hex: "#50bd68",
    },
    "success-vivid-500": {
      colorSpace: "srgb",
      components: [0.12549, 0.62745, 0.28235],
      hex: "#20a048",
    },
    "success-vivid-600": {
      colorSpace: "srgb",
      components: [0, 0.5098, 0.20392],
      hex: "#008234",
    },
    "success-vivid-700": {
      colorSpace: "srgb",
      components: [0, 0.40784, 0.15686],
      hex: "#006828",
    },
    "success-vivid-800": {
      colorSpace: "srgb",
      components: [0, 0.31373, 0.11373],
      hex: "#00501d",
    },
    "success-vivid-900": {
      colorSpace: "srgb",
      components: [0, 0.22353, 0.07059],
      hex: "#003912",
    },
    "success-vivid-950": {
      colorSpace: "srgb",
      components: [0, 0.16078, 0.04314],
      hex: "#00290b",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.90588],
      hex: "#fff5e7",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [1, 0.91765, 0.78824],
      hex: "#ffeac9",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.96471, 0.82745, 0.61176],
      hex: "#f6d39c",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.90196, 0.71765, 0.40784],
      hex: "#e6b768",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.80784, 0.59608, 0.21176],
      hex: "#ce9836",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.68627, 0.48235, 0],
      hex: "#af7b00",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.55686, 0.38824, 0],
      hex: "#8e6300",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.44314, 0.30588, 0],
      hex: "#714e00",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.34118, 0.23137, 0],
      hex: "#573b00",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.24314, 0.16078, 0],
      hex: "#3e2900",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.11373, 0],
      hex: "#2d1d00",
    },
    "warning-muted-50": {
      colorSpace: "srgb",
      components: [0.98824, 0.96471, 0.92941],
      hex: "#fcf6ed",
    },
    "warning-muted-100": {
      colorSpace: "srgb",
      components: [0.96078, 0.92157, 0.86275],
      hex: "#f5ebdc",
    },
    "warning-muted-200": {
      colorSpace: "srgb",
      components: [0.90196, 0.84314, 0.74902],
      hex: "#e6d7bf",
    },
    "warning-muted-300": {
      colorSpace: "srgb",
      components: [0.81961, 0.73725, 0.61176],
      hex: "#d1bc9c",
    },
    "warning-muted-400": {
      colorSpace: "srgb",
      components: [0.71765, 0.62353, 0.47843],
      hex: "#b79f7a",
    },
    "warning-muted-500": {
      colorSpace: "srgb",
      components: [0.60392, 0.5098, 0.36078],
      hex: "#9a825c",
    },
    "warning-muted-600": {
      colorSpace: "srgb",
      components: [0.49804, 0.40784, 0.25882],
      hex: "#7f6842",
    },
    "warning-muted-700": {
      colorSpace: "srgb",
      components: [0.40392, 0.32157, 0.18431],
      hex: "#67522f",
    },
    "warning-muted-800": {
      colorSpace: "srgb",
      components: [0.31373, 0.24314, 0.12549],
      hex: "#503e20",
    },
    "warning-muted-900": {
      colorSpace: "srgb",
      components: [0.22353, 0.16863, 0.07451],
      hex: "#392b13",
    },
    "warning-muted-950": {
      colorSpace: "srgb",
      components: [0.16078, 0.11765, 0.05098],
      hex: "#291e0d",
    },
    "warning-vivid-50": {
      colorSpace: "srgb",
      components: [1, 0.96078, 0.90588],
      hex: "#fff5e7",
    },
    "warning-vivid-100": {
      colorSpace: "srgb",
      components: [1, 0.91765, 0.78824],
      hex: "#ffeac9",
    },
    "warning-vivid-200": {
      colorSpace: "srgb",
      components: [1, 0.81961, 0.52941],
      hex: "#ffd187",
    },
    "warning-vivid-300": {
      colorSpace: "srgb",
      components: [0.96078, 0.69804, 0.18039],
      hex: "#f5b22e",
    },
    "warning-vivid-400": {
      colorSpace: "srgb",
      components: [0.83137, 0.58824, 0],
      hex: "#d49600",
    },
    "warning-vivid-500": {
      colorSpace: "srgb",
      components: [0.68627, 0.48235, 0],
      hex: "#af7b00",
    },
    "warning-vivid-600": {
      colorSpace: "srgb",
      components: [0.55686, 0.38824, 0],
      hex: "#8e6300",
    },
    "warning-vivid-700": {
      colorSpace: "srgb",
      components: [0.44314, 0.30588, 0],
      hex: "#714e00",
    },
    "warning-vivid-800": {
      colorSpace: "srgb",
      components: [0.34118, 0.23137, 0],
      hex: "#573b00",
    },
    "warning-vivid-900": {
      colorSpace: "srgb",
      components: [0.24314, 0.16078, 0],
      hex: "#3e2900",
    },
    "warning-vivid-950": {
      colorSpace: "srgb",
      components: [0.17647, 0.11373, 0],
      hex: "#2d1d00",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.96471, 0.96863],
      hex: "#f9f6f7",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.94118, 0.92157, 0.92941],
      hex: "#f0ebed",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.87059, 0.84314, 0.8549],
      hex: "#ded7da",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.77647, 0.73725, 0.75686],
      hex: "#c6bcc1",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.66667, 0.62745, 0.64314],
      hex: "#aaa0a4",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.55686, 0.51373, 0.53333],
      hex: "#8e8388",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.45098, 0.40784, 0.42745],
      hex: "#73686d",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.36078, 0.32157, 0.34118],
      hex: "#5c5257",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.27843, 0.24314, 0.25882],
      hex: "#473e42",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.19608, 0.17255, 0.18431],
      hex: "#322c2f",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.14118, 0.12157, 0.12941],
      hex: "#241f21",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.96078, 0.97255],
      hex: "#faf5f8",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.94902, 0.91765, 0.93333],
      hex: "#f2eaee",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.88627, 0.83529, 0.85882],
      hex: "#e2d5db",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.79216, 0.72941, 0.76471],
      hex: "#cabac3",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.6902, 0.61569, 0.6549],
      hex: "#b09da7",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.57647, 0.50196, 0.54118],
      hex: "#93808a",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.47059, 0.4, 0.43529],
      hex: "#78666f",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.37647, 0.31373, 0.3451],
      hex: "#605058",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.2902, 0.23529, 0.26667],
      hex: "#4a3c44",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.20784, 0.16471, 0.18824],
      hex: "#352a30",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.14902, 0.11765, 0.13333],
      hex: "#261e22",
    },
  },
} satisfies AuroraLayer;
