/**
 * Tokyo Night — City-light blue and purple, from Tokyo Night.
 * Generated by scripts/generate.mjs from scripts/seeds.json; regenerate
 * with `pnpm generate`, do not edit by hand.
 *
 * A theme rebinds only the tonal ramps: every role and every modifier
 * context lives in the base contract and reads the new values through
 * its ramp references.
 */
import type { AuroraLayer } from "../types";

export default {
  id: "tokyo_night",
  name: "Tokyo Night",
  tokens: {
    "primary-50": {
      colorSpace: "srgb",
      components: [0.96471, 0.97255, 0.98824],
      hex: "#f6f8fc",
    },
    "primary-100": {
      colorSpace: "srgb",
      components: [0.92941, 0.9451, 0.97647],
      hex: "#edf1f9",
    },
    "primary-200": {
      colorSpace: "srgb",
      components: [0.82353, 0.86667, 0.9451],
      hex: "#d2ddf1",
    },
    "primary-300": {
      colorSpace: "srgb",
      components: [0.71765, 0.78431, 0.91373],
      hex: "#b7c8e9",
    },
    "primary-400": {
      colorSpace: "srgb",
      components: [0.5098, 0.61961, 0.84706],
      hex: "#829ed8",
    },
    "primary-500": {
      colorSpace: "srgb",
      components: [0.29804, 0.45882, 0.78039],
      hex: "#4c75c7",
    },
    "primary-600": {
      colorSpace: "srgb",
      components: [0.26667, 0.41176, 0.70196],
      hex: "#4469b3",
    },
    "primary-700": {
      colorSpace: "srgb",
      components: [0.18039, 0.27451, 0.46667],
      hex: "#2e4677",
    },
    "primary-800": {
      colorSpace: "srgb",
      components: [0.13333, 0.20784, 0.35294],
      hex: "#22355a",
    },
    "primary-900": {
      colorSpace: "srgb",
      components: [0.0902, 0.13725, 0.23529],
      hex: "#17233c",
    },
    "primary-950": {
      colorSpace: "srgb",
      components: [0.05882, 0.0902, 0.15686],
      hex: "#0f1728",
    },
    "secondary-50": {
      colorSpace: "srgb",
      components: [0.97647, 0.96863, 0.98824],
      hex: "#f9f7fc",
    },
    "secondary-100": {
      colorSpace: "srgb",
      components: [0.95294, 0.94118, 0.97647],
      hex: "#f3f0f9",
    },
    "secondary-200": {
      colorSpace: "srgb",
      components: [0.88235, 0.85098, 0.93725],
      hex: "#e1d9ef",
    },
    "secondary-300": {
      colorSpace: "srgb",
      components: [0.81176, 0.76078, 0.89804],
      hex: "#cfc2e5",
    },
    "secondary-400": {
      colorSpace: "srgb",
      components: [0.66667, 0.58431, 0.82353],
      hex: "#aa95d2",
    },
    "secondary-500": {
      colorSpace: "srgb",
      components: [0.52549, 0.40392, 0.74902],
      hex: "#8667bf",
    },
    "secondary-600": {
      colorSpace: "srgb",
      components: [0.47451, 0.36471, 0.67451],
      hex: "#795dac",
    },
    "secondary-700": {
      colorSpace: "srgb",
      components: [0.31373, 0.24314, 0.45098],
      hex: "#503e73",
    },
    "secondary-800": {
      colorSpace: "srgb",
      components: [0.23529, 0.18039, 0.33725],
      hex: "#3c2e56",
    },
    "secondary-900": {
      colorSpace: "srgb",
      components: [0.15686, 0.12157, 0.22353],
      hex: "#281f39",
    },
    "secondary-950": {
      colorSpace: "srgb",
      components: [0.10588, 0.08235, 0.14902],
      hex: "#1b1526",
    },
    "tertiary-50": {
      colorSpace: "srgb",
      components: [0.95686, 0.97647, 0.98431],
      hex: "#f4f9fb",
    },
    "tertiary-100": {
      colorSpace: "srgb",
      components: [0.9098, 0.94902, 0.96863],
      hex: "#e8f2f7",
    },
    "tertiary-200": {
      colorSpace: "srgb",
      components: [0.78039, 0.87451, 0.91765],
      hex: "#c7dfea",
    },
    "tertiary-300": {
      colorSpace: "srgb",
      components: [0.64706, 0.8, 0.86667],
      hex: "#a5ccdd",
    },
    "tertiary-400": {
      colorSpace: "srgb",
      components: [0.38039, 0.64706, 0.76863],
      hex: "#61a5c4",
    },
    "tertiary-500": {
      colorSpace: "srgb",
      components: [0.11373, 0.49804, 0.67059],
      hex: "#1d7fab",
    },
    "tertiary-600": {
      colorSpace: "srgb",
      components: [0.10196, 0.44706, 0.60392],
      hex: "#1a729a",
    },
    "tertiary-700": {
      colorSpace: "srgb",
      components: [0.06667, 0.29804, 0.40392],
      hex: "#114c67",
    },
    "tertiary-800": {
      colorSpace: "srgb",
      components: [0.05098, 0.22353, 0.30196],
      hex: "#0d394d",
    },
    "tertiary-900": {
      colorSpace: "srgb",
      components: [0.03529, 0.14902, 0.2],
      hex: "#092633",
    },
    "tertiary-950": {
      colorSpace: "srgb",
      components: [0.02353, 0.09804, 0.13333],
      hex: "#061922",
    },
    "error-50": {
      colorSpace: "srgb",
      components: [0.98824, 0.96471, 0.96863],
      hex: "#fcf6f7",
    },
    "error-100": {
      colorSpace: "srgb",
      components: [0.97647, 0.92941, 0.94118],
      hex: "#f9edf0",
    },
    "error-200": {
      colorSpace: "srgb",
      components: [0.9451, 0.82745, 0.85098],
      hex: "#f1d3d9",
    },
    "error-300": {
      colorSpace: "srgb",
      components: [0.9098, 0.72549, 0.76078],
      hex: "#e8b9c2",
    },
    "error-400": {
      colorSpace: "srgb",
      components: [0.83922, 0.51765, 0.58431],
      hex: "#d68495",
    },
    "error-500": {
      colorSpace: "srgb",
      components: [0.77255, 0.3098, 0.40392],
      hex: "#c54f67",
    },
    "error-600": {
      colorSpace: "srgb",
      components: [0.69412, 0.27843, 0.36471],
      hex: "#b1475d",
    },
    "error-700": {
      colorSpace: "srgb",
      components: [0.46275, 0.18431, 0.24314],
      hex: "#762f3e",
    },
    "error-800": {
      colorSpace: "srgb",
      components: [0.34902, 0.14118, 0.18039],
      hex: "#59242e",
    },
    "error-900": {
      colorSpace: "srgb",
      components: [0.23137, 0.09412, 0.12157],
      hex: "#3b181f",
    },
    "error-950": {
      colorSpace: "srgb",
      components: [0.15294, 0.06275, 0.08235],
      hex: "#271015",
    },
    "success-50": {
      colorSpace: "srgb",
      components: [0.96863, 0.97647, 0.95686],
      hex: "#f7f9f4",
    },
    "success-100": {
      colorSpace: "srgb",
      components: [0.93333, 0.95294, 0.91765],
      hex: "#eef3ea",
    },
    "success-200": {
      colorSpace: "srgb",
      components: [0.83529, 0.87843, 0.78824],
      hex: "#d5e0c9",
    },
    "success-300": {
      colorSpace: "srgb",
      components: [0.73725, 0.80392, 0.66275],
      hex: "#bccda9",
    },
    "success-400": {
      colorSpace: "srgb",
      components: [0.54118, 0.65882, 0.41176],
      hex: "#8aa869",
    },
    "success-500": {
      colorSpace: "srgb",
      components: [0.3451, 0.51373, 0.15686],
      hex: "#588328",
    },
    "success-600": {
      colorSpace: "srgb",
      components: [0.3098, 0.46275, 0.14118],
      hex: "#4f7624",
    },
    "success-700": {
      colorSpace: "srgb",
      components: [0.20784, 0.3098, 0.09412],
      hex: "#354f18",
    },
    "success-800": {
      colorSpace: "srgb",
      components: [0.15686, 0.23137, 0.07059],
      hex: "#283b12",
    },
    "success-900": {
      colorSpace: "srgb",
      components: [0.10196, 0.15294, 0.04706],
      hex: "#1a270c",
    },
    "success-950": {
      colorSpace: "srgb",
      components: [0.07059, 0.10196, 0.03137],
      hex: "#121a08",
    },
    "warning-50": {
      colorSpace: "srgb",
      components: [0.98039, 0.97255, 0.96078],
      hex: "#faf8f5",
    },
    "warning-100": {
      colorSpace: "srgb",
      components: [0.96078, 0.9451, 0.91765],
      hex: "#f5f1ea",
    },
    "warning-200": {
      colorSpace: "srgb",
      components: [0.90196, 0.85882, 0.79608],
      hex: "#e6dbcb",
    },
    "warning-300": {
      colorSpace: "srgb",
      components: [0.83922, 0.77255, 0.67451],
      hex: "#d6c5ac",
    },
    "warning-400": {
      colorSpace: "srgb",
      components: [0.72157, 0.60392, 0.42745],
      hex: "#b89a6d",
    },
    "warning-500": {
      colorSpace: "srgb",
      components: [0.6, 0.43529, 0.18431],
      hex: "#996f2f",
    },
    "warning-600": {
      colorSpace: "srgb",
      components: [0.54118, 0.39216, 0.16471],
      hex: "#8a642a",
    },
    "warning-700": {
      colorSpace: "srgb",
      components: [0.36078, 0.26275, 0.1098],
      hex: "#5c431c",
    },
    "warning-800": {
      colorSpace: "srgb",
      components: [0.27059, 0.19608, 0.08235],
      hex: "#453215",
    },
    "warning-900": {
      colorSpace: "srgb",
      components: [0.18039, 0.12941, 0.0549],
      hex: "#2e210e",
    },
    "warning-950": {
      colorSpace: "srgb",
      components: [0.12157, 0.08627, 0.03529],
      hex: "#1f1609",
    },
    "neutral-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.97255, 0.97647],
      hex: "#f8f8f9",
    },
    "neutral-100": {
      colorSpace: "srgb",
      components: [0.9451, 0.9451, 0.95294],
      hex: "#f1f1f3",
    },
    "neutral-200": {
      colorSpace: "srgb",
      components: [0.86667, 0.86667, 0.87843],
      hex: "#dddde0",
    },
    "neutral-300": {
      colorSpace: "srgb",
      components: [0.78431, 0.78431, 0.80784],
      hex: "#c8c8ce",
    },
    "neutral-400": {
      colorSpace: "srgb",
      components: [0.62353, 0.62353, 0.66275],
      hex: "#9f9fa9",
    },
    "neutral-500": {
      colorSpace: "srgb",
      components: [0.46275, 0.46275, 0.51765],
      hex: "#767684",
    },
    "neutral-600": {
      colorSpace: "srgb",
      components: [0.41569, 0.41569, 0.46667],
      hex: "#6a6a77",
    },
    "neutral-700": {
      colorSpace: "srgb",
      components: [0.27843, 0.27843, 0.3098],
      hex: "#47474f",
    },
    "neutral-800": {
      colorSpace: "srgb",
      components: [0.20784, 0.20784, 0.23137],
      hex: "#35353b",
    },
    "neutral-900": {
      colorSpace: "srgb",
      components: [0.13725, 0.13725, 0.15686],
      hex: "#232328",
    },
    "neutral-950": {
      colorSpace: "srgb",
      components: [0.09412, 0.09412, 0.10196],
      hex: "#18181a",
    },
    "neutral-variant-50": {
      colorSpace: "srgb",
      components: [0.97255, 0.97255, 0.98039],
      hex: "#f8f8fa",
    },
    "neutral-variant-100": {
      colorSpace: "srgb",
      components: [0.94118, 0.9451, 0.96471],
      hex: "#f0f1f6",
    },
    "neutral-variant-200": {
      colorSpace: "srgb",
      components: [0.8549, 0.86667, 0.90588],
      hex: "#dadde7",
    },
    "neutral-variant-300": {
      colorSpace: "srgb",
      components: [0.76863, 0.78431, 0.85098],
      hex: "#c4c8d9",
    },
    "neutral-variant-400": {
      colorSpace: "srgb",
      components: [0.59608, 0.61961, 0.74118],
      hex: "#989ebd",
    },
    "neutral-variant-500": {
      colorSpace: "srgb",
      components: [0.42353, 0.45882, 0.62745],
      hex: "#6c75a0",
    },
    "neutral-variant-600": {
      colorSpace: "srgb",
      components: [0.38039, 0.41176, 0.56471],
      hex: "#616990",
    },
    "neutral-variant-700": {
      colorSpace: "srgb",
      components: [0.2549, 0.27451, 0.37647],
      hex: "#414660",
    },
    "neutral-variant-800": {
      colorSpace: "srgb",
      components: [0.19216, 0.20784, 0.28235],
      hex: "#313548",
    },
    "neutral-variant-900": {
      colorSpace: "srgb",
      components: [0.12549, 0.13725, 0.18824],
      hex: "#202330",
    },
    "neutral-variant-950": {
      colorSpace: "srgb",
      components: [0.08627, 0.0902, 0.12549],
      hex: "#161720",
    },
  },
} satisfies AuroraLayer;
