import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Ayu theme — M3 token variant.
 */
export default preset.define({
  id: "ayu",
  name: "Ayu",
  tokens: {
    // Chromatic palettes — Ayu Dark's clean, modern accents
    ...createM3ColorTokens("red", "#f07178"),
    ...createM3ColorTokens("orange", "#ff8f40"),
    ...createM3ColorTokens("amber", "#e6b450"),
    ...createM3ColorTokens("yellow", "#ffb454"),
    ...createM3ColorTokens("lime", "#aad94c"),
    ...createM3ColorTokens("green", "#aad94c"),
    ...createM3ColorTokens("emerald", "#95e6cb"),
    ...createM3ColorTokens("teal", "#95e6cb"),
    ...createM3ColorTokens("cyan", "#39bae6"),
    ...createM3ColorTokens("sky", "#59c2ff"),
    ...createM3ColorTokens("blue", "#59c2ff"),
    ...createM3ColorTokens("indigo", "#39bae6"),
    ...createM3ColorTokens("violet", "#d2a6ff"),
    ...createM3ColorTokens("purple", "#d2a6ff"),
    ...createM3ColorTokens("fuchsia", "#f29668"),
    ...createM3ColorTokens("pink", "#f07178"),
    ...createM3ColorTokens("rose", "#f07178"),
    // Neutral palettes — deep navy-black, cool and clean
    ...createM3ColorTokens("slate", "#5a6673"),
    ...createM3ColorTokens("gray", "#5a6673"),
    ...createM3ColorTokens("zinc", "#404953"),
    ...createM3ColorTokens("neutral", "#0b0e14"),
    ...createM3ColorTokens("stone", "#667381"),
    // Semantic roles — default to the light scheme
    // Primary — orange: Ayu's signature accent color
    primary: "{orange-40}",
    "on-primary": "{orange-100}",
    "primary-container": "{orange-90}",
    "on-primary-container": "{orange-10}",
    "inverse-primary": "{orange-80}",
    "primary-fixed": "{orange-90}",
    "primary-fixed-dim": "{orange-80}",
    "on-primary-fixed": "{orange-10}",
    "on-primary-fixed-variant": "{orange-30}",
    // Secondary — blue: functions, entities
    secondary: "{blue-40}",
    "on-secondary": "{blue-100}",
    "secondary-container": "{blue-90}",
    "on-secondary-container": "{blue-10}",
    "secondary-fixed": "{blue-90}",
    "secondary-fixed-dim": "{blue-80}",
    "on-secondary-fixed": "{blue-10}",
    "on-secondary-fixed-variant": "{blue-30}",
    // Tertiary — violet: constants, special
    tertiary: "{violet-40}",
    "on-tertiary": "{violet-100}",
    "tertiary-container": "{violet-90}",
    "on-tertiary-container": "{violet-10}",
    "tertiary-fixed": "{violet-90}",
    "tertiary-fixed-dim": "{violet-80}",
    "on-tertiary-fixed": "{violet-10}",
    "on-tertiary-fixed-variant": "{violet-30}",
    // Error — red
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — clean, minimal light
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{slate-90}",
    "on-surface-variant": "{slate-30}",
    "surface-tint": "{orange-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines
    outline: "{slate-50}",
    "outline-variant": "{slate-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — orange: warm accent on deep dark
        primary: "{orange-80}",
        "on-primary": "{orange-20}",
        "primary-container": "{orange-30}",
        "on-primary-container": "{orange-90}",
        "inverse-primary": "{orange-40}",
        "primary-fixed": "{orange-90}",
        "primary-fixed-dim": "{orange-80}",
        "on-primary-fixed": "{orange-10}",
        "on-primary-fixed-variant": "{orange-30}",
        // Secondary — blue: bright blue functions
        secondary: "{blue-80}",
        "on-secondary": "{blue-20}",
        "secondary-container": "{blue-30}",
        "on-secondary-container": "{blue-90}",
        "secondary-fixed": "{blue-90}",
        "secondary-fixed-dim": "{blue-80}",
        "on-secondary-fixed": "{blue-10}",
        "on-secondary-fixed-variant": "{blue-30}",
        // Tertiary — violet: purple constants
        tertiary: "{violet-80}",
        "on-tertiary": "{violet-20}",
        "tertiary-container": "{violet-30}",
        "on-tertiary-container": "{violet-90}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        // Error — red
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — deep navy-black (#0b0e14 territory)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{slate-80}",
        "surface-tint": "{orange-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — cool dark gray
        outline: "{slate-60}",
        "outline-variant": "{zinc-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
    },
  },
  order: ["color"],
});
