import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Catppuccin Mocha theme — M3 token variant.
 */
export default preset.define({
  id: "catppuccin",
  name: "Catppuccin Mocha",
  tokens: {
    // Chromatic palettes — mapped to Catppuccin Mocha's 14 accents
    ...createM3ColorTokens("red", "#f38ba8"),
    ...createM3ColorTokens("orange", "#fab387"),
    ...createM3ColorTokens("amber", "#fab387"),
    ...createM3ColorTokens("yellow", "#f9e2af"),
    ...createM3ColorTokens("lime", "#a6e3a1"),
    ...createM3ColorTokens("green", "#a6e3a1"),
    ...createM3ColorTokens("emerald", "#94e2d5"),
    ...createM3ColorTokens("teal", "#94e2d5"),
    ...createM3ColorTokens("cyan", "#89dceb"),
    ...createM3ColorTokens("sky", "#89dceb"),
    ...createM3ColorTokens("blue", "#89b4fa"),
    ...createM3ColorTokens("indigo", "#74c7ec"),
    ...createM3ColorTokens("violet", "#cba6f7"),
    ...createM3ColorTokens("purple", "#b4befe"),
    ...createM3ColorTokens("fuchsia", "#f5c2e7"),
    ...createM3ColorTokens("pink", "#f2cdcd"),
    ...createM3ColorTokens("rose", "#eba0ac"),
    // Neutral palettes — cool blue-purple tinted
    ...createM3ColorTokens("slate", "#585b70"),
    ...createM3ColorTokens("gray", "#6c7086"),
    ...createM3ColorTokens("zinc", "#7f849c"),
    ...createM3ColorTokens("neutral", "#1e1e2e"),
    ...createM3ColorTokens("stone", "#9399b2"),
    // Semantic roles — default to the light scheme
    // Primary — violet (Mauve): Catppuccin's brand purple
    primary: "{violet-40}",
    "on-primary": "{violet-100}",
    "primary-container": "{violet-90}",
    "on-primary-container": "{violet-10}",
    "inverse-primary": "{violet-80}",
    "primary-fixed": "{violet-90}",
    "primary-fixed-dim": "{violet-80}",
    "on-primary-fixed": "{violet-10}",
    "on-primary-fixed-variant": "{violet-30}",
    // Secondary — blue (Sapphire/Blue): cool complement
    secondary: "{blue-40}",
    "on-secondary": "{blue-100}",
    "secondary-container": "{blue-90}",
    "on-secondary-container": "{blue-10}",
    "secondary-fixed": "{blue-90}",
    "secondary-fixed-dim": "{blue-80}",
    "on-secondary-fixed": "{blue-10}",
    "on-secondary-fixed-variant": "{blue-30}",
    // Tertiary — pink (Flamingo): warm accent
    tertiary: "{pink-40}",
    "on-tertiary": "{pink-100}",
    "tertiary-container": "{pink-90}",
    "on-tertiary-container": "{pink-10}",
    "tertiary-fixed": "{pink-90}",
    "tertiary-fixed-dim": "{pink-80}",
    "on-tertiary-fixed": "{pink-10}",
    "on-tertiary-fixed-variant": "{pink-30}",
    // Error — red
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — cool blue-tinted neutral (Latte feel)
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{slate-90}",
    "on-surface-variant": "{slate-30}",
    "surface-tint": "{violet-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines — cool chromatic gray
    outline: "{slate-50}",
    "outline-variant": "{slate-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — violet (Mauve): the signature pastel purple
        primary: "{violet-80}",
        "on-primary": "{violet-20}",
        "primary-container": "{violet-30}",
        "on-primary-container": "{violet-90}",
        "inverse-primary": "{violet-40}",
        "primary-fixed": "{violet-90}",
        "primary-fixed-dim": "{violet-80}",
        "on-primary-fixed": "{violet-10}",
        "on-primary-fixed-variant": "{violet-30}",
        // Secondary — blue: soft blue accent
        secondary: "{blue-80}",
        "on-secondary": "{blue-20}",
        "secondary-container": "{blue-30}",
        "on-secondary-container": "{blue-90}",
        "secondary-fixed": "{blue-90}",
        "secondary-fixed-dim": "{blue-80}",
        "on-secondary-fixed": "{blue-10}",
        "on-secondary-fixed-variant": "{blue-30}",
        // Tertiary — pink (Flamingo): warm pastel counterpoint
        tertiary: "{pink-80}",
        "on-tertiary": "{pink-20}",
        "tertiary-container": "{pink-30}",
        "on-tertiary-container": "{pink-90}",
        "tertiary-fixed": "{pink-90}",
        "tertiary-fixed-dim": "{pink-80}",
        "on-tertiary-fixed": "{pink-10}",
        "on-tertiary-fixed-variant": "{pink-30}",
        // Error — red
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — deep blue-purple tinted darks
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-80}",
        "surface-tint": "{violet-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — cool gray with blue-purple character
        outline: "{zinc-60}",
        "outline-variant": "{slate-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{violet-22}",
        "primary-container": "{violet-50}",
        "on-primary-container": "{violet-100}",
        secondary: "{blue-22}",
        "secondary-container": "{blue-50}",
        "on-secondary-container": "{blue-100}",
        tertiary: "{pink-22}",
        "tertiary-container": "{pink-50}",
        "on-tertiary-container": "{pink-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{slate-22}",
        outline: "{slate-35}",
        "outline-variant": "{slate-50}",
      },
      "light-high-contrast": {
        primary: "{violet-17}",
        "primary-container": "{violet-30}",
        "on-primary-container": "{violet-100}",
        secondary: "{blue-17}",
        "secondary-container": "{blue-30}",
        "on-secondary-container": "{blue-100}",
        tertiary: "{pink-17}",
        "tertiary-container": "{pink-30}",
        "on-tertiary-container": "{pink-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{slate-0}",
        outline: "{slate-17}",
        "outline-variant": "{slate-30}",
      },
      "dark-medium-contrast": {
        primary: "{violet-87}",
        "on-primary": "{violet-17}",
        "primary-container": "{violet-60}",
        "on-primary-container": "{violet-0}",
        "inverse-primary": "{violet-30}",
        "primary-fixed": "{violet-90}",
        "primary-fixed-dim": "{violet-80}",
        "on-primary-fixed": "{violet-10}",
        "on-primary-fixed-variant": "{violet-30}",
        "surface-tint": "{violet-80}",
        secondary: "{blue-87}",
        "on-secondary": "{blue-17}",
        "secondary-container": "{blue-60}",
        "on-secondary-container": "{blue-0}",
        "secondary-fixed": "{blue-90}",
        "secondary-fixed-dim": "{blue-80}",
        "on-secondary-fixed": "{blue-10}",
        "on-secondary-fixed-variant": "{blue-30}",
        tertiary: "{pink-87}",
        "on-tertiary": "{pink-17}",
        "tertiary-container": "{pink-60}",
        "on-tertiary-container": "{pink-0}",
        "tertiary-fixed": "{pink-90}",
        "tertiary-fixed-dim": "{pink-80}",
        "on-tertiary-fixed": "{pink-10}",
        "on-tertiary-fixed-variant": "{pink-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-87}",
        outline: "{slate-70}",
        "outline-variant": "{slate-60}",
      },
      "dark-high-contrast": {
        primary: "{violet-95}",
        "on-primary": "{violet-0}",
        "primary-container": "{violet-80}",
        "on-primary-container": "{violet-4}",
        "inverse-primary": "{violet-30}",
        "primary-fixed": "{violet-90}",
        "primary-fixed-dim": "{violet-80}",
        "on-primary-fixed": "{violet-10}",
        "on-primary-fixed-variant": "{violet-30}",
        "surface-tint": "{violet-80}",
        secondary: "{blue-95}",
        "on-secondary": "{blue-0}",
        "secondary-container": "{blue-80}",
        "on-secondary-container": "{blue-4}",
        "secondary-fixed": "{blue-90}",
        "secondary-fixed-dim": "{blue-80}",
        "on-secondary-fixed": "{blue-10}",
        "on-secondary-fixed-variant": "{blue-30}",
        tertiary: "{pink-95}",
        "on-tertiary": "{pink-0}",
        "tertiary-container": "{pink-80}",
        "on-tertiary-container": "{pink-4}",
        "tertiary-fixed": "{pink-90}",
        "tertiary-fixed-dim": "{pink-80}",
        "on-tertiary-fixed": "{pink-10}",
        "on-tertiary-fixed-variant": "{pink-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-100}",
        outline: "{slate-95}",
        "outline-variant": "{slate-80}",
      },
    },
  },
  order: ["color"],
});
