import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Dracula theme — M3 token variant.
 */
export default preset.define({
  id: "dracula",
  name: "Dracula",
  tokens: {
    // Chromatic palettes — seeded from Dracula's vivid accents
    ...createM3ColorTokens("red", "#FF5555"),
    ...createM3ColorTokens("orange", "#FFB86C"),
    ...createM3ColorTokens("amber", "#FFB86C"),
    ...createM3ColorTokens("yellow", "#F1FA8C"),
    ...createM3ColorTokens("lime", "#50FA7B"),
    ...createM3ColorTokens("green", "#50FA7B"),
    ...createM3ColorTokens("emerald", "#50FA7B"),
    ...createM3ColorTokens("teal", "#8BE9FD"),
    ...createM3ColorTokens("cyan", "#8BE9FD"),
    ...createM3ColorTokens("sky", "#8BE9FD"),
    ...createM3ColorTokens("blue", "#6272A4"),
    ...createM3ColorTokens("indigo", "#6272A4"),
    ...createM3ColorTokens("violet", "#BD93F9"),
    ...createM3ColorTokens("purple", "#BD93F9"),
    ...createM3ColorTokens("fuchsia", "#FF79C6"),
    ...createM3ColorTokens("pink", "#FF79C6"),
    ...createM3ColorTokens("rose", "#FF5555"),
    // Neutral palettes — cool purple-blue tinted
    ...createM3ColorTokens("slate", "#44475A"),
    ...createM3ColorTokens("gray", "#44475A"),
    ...createM3ColorTokens("zinc", "#6272A4"),
    ...createM3ColorTokens("neutral", "#282A36"),
    ...createM3ColorTokens("stone", "#44475A"),
    // Semantic roles — default to the light scheme
    // Primary — violet (Dracula Purple)
    primary: "{violet-40}",
    "on-primary": "{violet-100}",
    "primary-container": "{violet-90}",
    "on-primary-container": "{violet-10}",
    "inverse-primary": "{violet-80}",
    "primary-fixed": "{violet-90}",
    "primary-fixed-dim": "{violet-80}",
    "on-primary-fixed": "{violet-10}",
    "on-primary-fixed-variant": "{violet-30}",
    // Secondary — pink (Dracula Pink)
    secondary: "{pink-40}",
    "on-secondary": "{pink-100}",
    "secondary-container": "{pink-90}",
    "on-secondary-container": "{pink-10}",
    "secondary-fixed": "{pink-90}",
    "secondary-fixed-dim": "{pink-80}",
    "on-secondary-fixed": "{pink-10}",
    "on-secondary-fixed-variant": "{pink-30}",
    // Tertiary — cyan (Dracula Cyan)
    tertiary: "{cyan-40}",
    "on-tertiary": "{cyan-100}",
    "tertiary-container": "{cyan-90}",
    "on-tertiary-container": "{cyan-10}",
    "tertiary-fixed": "{cyan-90}",
    "tertiary-fixed-dim": "{cyan-80}",
    "on-tertiary-fixed": "{cyan-10}",
    "on-tertiary-fixed-variant": "{cyan-30}",
    // Error — red (Dracula Red)
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — light mode with cool purple tint
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{slate-90}",
    "on-surface-variant": "{slate-30}",
    "surface-tint": "{violet-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines
    outline: "{zinc-50}",
    "outline-variant": "{slate-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — violet (Dracula Purple #BD93F9): the neon brand
        primary: "{violet-80}",
        "on-primary": "{violet-20}",
        "primary-container": "{violet-30}",
        "on-primary-container": "{violet-90}",
        "inverse-primary": "{violet-40}",
        "primary-fixed": "{violet-90}",
        "primary-fixed-dim": "{violet-80}",
        "on-primary-fixed": "{violet-10}",
        "on-primary-fixed-variant": "{violet-30}",
        // Secondary — pink (Dracula Pink #FF79C6): hot pink keywords
        secondary: "{pink-80}",
        "on-secondary": "{pink-20}",
        "secondary-container": "{pink-30}",
        "on-secondary-container": "{pink-90}",
        "secondary-fixed": "{pink-90}",
        "secondary-fixed-dim": "{pink-80}",
        "on-secondary-fixed": "{pink-10}",
        "on-secondary-fixed-variant": "{pink-30}",
        // Tertiary — cyan (Dracula Cyan #8BE9FD): bright cyan accent
        tertiary: "{cyan-80}",
        "on-tertiary": "{cyan-20}",
        "tertiary-container": "{cyan-30}",
        "on-tertiary-container": "{cyan-90}",
        "tertiary-fixed": "{cyan-90}",
        "tertiary-fixed-dim": "{cyan-80}",
        "on-tertiary-fixed": "{cyan-10}",
        "on-tertiary-fixed-variant": "{cyan-30}",
        // Error — red (Dracula Red #FF5555)
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — cool purple-tinted darks (from Background #282A36)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-80}",
        "surface-tint": "{violet-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — Comment blue for subdued structure
        outline: "{zinc-60}",
        "outline-variant": "{slate-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
    },
  },
  order: ["color"],
});
