import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Everforest theme — M3 token variant.
 */
export default preset.define({
  id: "everforest",
  name: "Everforest",
  tokens: {
    // Chromatic palettes — Everforest's warm, earthy nature tones
    ...createM3ColorTokens("red", "#e67e80"),
    ...createM3ColorTokens("orange", "#e69875"),
    ...createM3ColorTokens("amber", "#dbbc7f"),
    ...createM3ColorTokens("yellow", "#dbbc7f"),
    ...createM3ColorTokens("lime", "#a7c080"),
    ...createM3ColorTokens("green", "#a7c080"),
    ...createM3ColorTokens("emerald", "#83c092"),
    ...createM3ColorTokens("teal", "#83c092"),
    ...createM3ColorTokens("cyan", "#83c092"),
    ...createM3ColorTokens("sky", "#7fbbb3"),
    ...createM3ColorTokens("blue", "#7fbbb3"),
    ...createM3ColorTokens("indigo", "#7fbbb3"),
    ...createM3ColorTokens("violet", "#d699b6"),
    ...createM3ColorTokens("purple", "#d699b6"),
    ...createM3ColorTokens("fuchsia", "#d699b6"),
    ...createM3ColorTokens("pink", "#e67e80"),
    ...createM3ColorTokens("rose", "#e67e80"),
    // Neutral palettes — warm forest greens and grays
    ...createM3ColorTokens("slate", "#7a8478"),
    ...createM3ColorTokens("gray", "#859289"),
    ...createM3ColorTokens("zinc", "#56635f"),
    ...createM3ColorTokens("neutral", "#2d353b"),
    ...createM3ColorTokens("stone", "#9da9a0"),
    // Semantic roles — default to the light scheme
    // Primary — green: THE Everforest color — lush, natural
    primary: "{green-40}",
    "on-primary": "{green-100}",
    "primary-container": "{green-90}",
    "on-primary-container": "{green-10}",
    "inverse-primary": "{green-80}",
    "primary-fixed": "{green-90}",
    "primary-fixed-dim": "{green-80}",
    "on-primary-fixed": "{green-10}",
    "on-primary-fixed-variant": "{green-30}",
    // Secondary — blue (Everforest's soft teal-blue)
    secondary: "{blue-40}",
    "on-secondary": "{blue-100}",
    "secondary-container": "{blue-90}",
    "on-secondary-container": "{blue-10}",
    "secondary-fixed": "{blue-90}",
    "secondary-fixed-dim": "{blue-80}",
    "on-secondary-fixed": "{blue-10}",
    "on-secondary-fixed-variant": "{blue-30}",
    // Tertiary — violet: soft purple warmth
    tertiary: "{violet-40}",
    "on-tertiary": "{violet-100}",
    "tertiary-container": "{violet-90}",
    "on-tertiary-container": "{violet-10}",
    "tertiary-fixed": "{violet-90}",
    "tertiary-fixed-dim": "{violet-80}",
    "on-tertiary-fixed": "{violet-10}",
    "on-tertiary-fixed-variant": "{violet-30}",
    // Error — red
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — warm earthy cream (#fdf6e3 territory)
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{gray-90}",
    "on-surface-variant": "{gray-30}",
    "surface-tint": "{green-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines — warm forest gray
    outline: "{slate-50}",
    "outline-variant": "{gray-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — green: soft forest green on dark
        primary: "{green-80}",
        "on-primary": "{green-20}",
        "primary-container": "{green-30}",
        "on-primary-container": "{green-90}",
        "inverse-primary": "{green-40}",
        "primary-fixed": "{green-90}",
        "primary-fixed-dim": "{green-80}",
        "on-primary-fixed": "{green-10}",
        "on-primary-fixed-variant": "{green-30}",
        // Secondary — blue: muted teal-blue
        secondary: "{blue-80}",
        "on-secondary": "{blue-20}",
        "secondary-container": "{blue-30}",
        "on-secondary-container": "{blue-90}",
        "secondary-fixed": "{blue-90}",
        "secondary-fixed-dim": "{blue-80}",
        "on-secondary-fixed": "{blue-10}",
        "on-secondary-fixed-variant": "{blue-30}",
        // Tertiary — violet: soft purple
        tertiary: "{violet-80}",
        "on-tertiary": "{violet-20}",
        "tertiary-container": "{violet-30}",
        "on-tertiary-container": "{violet-90}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        // Error — red
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — warm dark forest (#2d353b territory)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{gray-80}",
        "surface-tint": "{green-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — forest gray
        outline: "{slate-60}",
        "outline-variant": "{zinc-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{green-22}",
        "primary-container": "{green-50}",
        "on-primary-container": "{green-100}",
        secondary: "{blue-22}",
        "secondary-container": "{blue-50}",
        "on-secondary-container": "{blue-100}",
        tertiary: "{violet-22}",
        "tertiary-container": "{violet-50}",
        "on-tertiary-container": "{violet-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{gray-22}",
        outline: "{slate-35}",
        "outline-variant": "{gray-50}",
      },
      "light-high-contrast": {
        primary: "{green-17}",
        "primary-container": "{green-30}",
        "on-primary-container": "{green-100}",
        secondary: "{blue-17}",
        "secondary-container": "{blue-30}",
        "on-secondary-container": "{blue-100}",
        tertiary: "{violet-17}",
        "tertiary-container": "{violet-30}",
        "on-tertiary-container": "{violet-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{gray-0}",
        outline: "{slate-17}",
        "outline-variant": "{gray-30}",
      },
      "dark-medium-contrast": {
        primary: "{green-87}",
        "on-primary": "{green-17}",
        "primary-container": "{green-60}",
        "on-primary-container": "{green-0}",
        "inverse-primary": "{green-30}",
        "primary-fixed": "{green-90}",
        "primary-fixed-dim": "{green-80}",
        "on-primary-fixed": "{green-10}",
        "on-primary-fixed-variant": "{green-30}",
        "surface-tint": "{green-80}",
        secondary: "{blue-87}",
        "on-secondary": "{blue-17}",
        "secondary-container": "{blue-60}",
        "on-secondary-container": "{blue-0}",
        "secondary-fixed": "{blue-90}",
        "secondary-fixed-dim": "{blue-80}",
        "on-secondary-fixed": "{blue-10}",
        "on-secondary-fixed-variant": "{blue-30}",
        tertiary: "{violet-87}",
        "on-tertiary": "{violet-17}",
        "tertiary-container": "{violet-60}",
        "on-tertiary-container": "{violet-0}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{gray-30}",
        "on-surface-variant": "{gray-87}",
        outline: "{slate-70}",
        "outline-variant": "{gray-60}",
      },
      "dark-high-contrast": {
        primary: "{green-95}",
        "on-primary": "{green-0}",
        "primary-container": "{green-80}",
        "on-primary-container": "{green-4}",
        "inverse-primary": "{green-30}",
        "primary-fixed": "{green-90}",
        "primary-fixed-dim": "{green-80}",
        "on-primary-fixed": "{green-10}",
        "on-primary-fixed-variant": "{green-30}",
        "surface-tint": "{green-80}",
        secondary: "{blue-95}",
        "on-secondary": "{blue-0}",
        "secondary-container": "{blue-80}",
        "on-secondary-container": "{blue-4}",
        "secondary-fixed": "{blue-90}",
        "secondary-fixed-dim": "{blue-80}",
        "on-secondary-fixed": "{blue-10}",
        "on-secondary-fixed-variant": "{blue-30}",
        tertiary: "{violet-95}",
        "on-tertiary": "{violet-0}",
        "tertiary-container": "{violet-80}",
        "on-tertiary-container": "{violet-4}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{gray-30}",
        "on-surface-variant": "{gray-100}",
        outline: "{slate-95}",
        "outline-variant": "{gray-80}",
      },
    },
  },
  order: ["color"],
});
