import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Gruvbox theme — M3 token variant.
 */
export default preset.define({
  id: "gruvbox",
  name: "Gruvbox",
  tokens: {
    // Chromatic palettes — remapped to gruvbox's 7 accent hues
    ...createM3ColorTokens("red", "#cc241d"),
    ...createM3ColorTokens("orange", "#d65d0e"),
    ...createM3ColorTokens("amber", "#d79921"),
    ...createM3ColorTokens("yellow", "#d79921"),
    ...createM3ColorTokens("lime", "#98971a"),
    ...createM3ColorTokens("green", "#98971a"),
    ...createM3ColorTokens("emerald", "#689d6a"),
    ...createM3ColorTokens("teal", "#689d6a"),
    ...createM3ColorTokens("cyan", "#689d6a"),
    ...createM3ColorTokens("sky", "#458588"),
    ...createM3ColorTokens("blue", "#458588"),
    ...createM3ColorTokens("indigo", "#458588"),
    ...createM3ColorTokens("violet", "#b16286"),
    ...createM3ColorTokens("purple", "#b16286"),
    ...createM3ColorTokens("fuchsia", "#b16286"),
    ...createM3ColorTokens("pink", "#b16286"),
    ...createM3ColorTokens("rose", "#cc241d"),
    // Neutral palettes — warm browns and grays
    ...createM3ColorTokens("slate", "#928374"),
    ...createM3ColorTokens("gray", "#928374"),
    ...createM3ColorTokens("zinc", "#928374"),
    ...createM3ColorTokens("neutral", "#ebdbb2"),
    ...createM3ColorTokens("stone", "#ebdbb2"),
    // Semantic roles — default to the light scheme
    // Primary — blue: main action color in gruvbox light
    primary: "{blue-40}",
    "on-primary": "{blue-100}",
    "primary-container": "{blue-90}",
    "on-primary-container": "{blue-10}",
    "inverse-primary": "{blue-80}",
    "primary-fixed": "{blue-90}",
    "primary-fixed-dim": "{blue-80}",
    "on-primary-fixed": "{blue-10}",
    "on-primary-fixed-variant": "{blue-30}",
    // Secondary — teal (aqua): strings, secondary elements
    secondary: "{teal-40}",
    "on-secondary": "{teal-100}",
    "secondary-container": "{teal-90}",
    "on-secondary-container": "{teal-10}",
    "secondary-fixed": "{teal-90}",
    "secondary-fixed-dim": "{teal-80}",
    "on-secondary-fixed": "{teal-10}",
    "on-secondary-fixed-variant": "{teal-30}",
    // Tertiary — violet (purple): keywords, special elements
    tertiary: "{violet-40}",
    "on-tertiary": "{violet-100}",
    "tertiary-container": "{violet-90}",
    "on-tertiary-container": "{violet-10}",
    "tertiary-fixed": "{violet-90}",
    "tertiary-fixed-dim": "{violet-80}",
    "on-tertiary-fixed": "{violet-10}",
    "on-tertiary-fixed-variant": "{violet-30}",
    // Error — red
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — warm cream neutrals at high tones
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{zinc-90}",
    "on-surface-variant": "{zinc-30}",
    "surface-tint": "{blue-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines — warm gray
    outline: "{zinc-50}",
    "outline-variant": "{zinc-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — orange: THE signature gruvbox dark accent
        primary: "{orange-80}",
        "on-primary": "{orange-20}",
        "primary-container": "{orange-30}",
        "on-primary-container": "{orange-90}",
        "inverse-primary": "{orange-40}",
        "primary-fixed": "{orange-90}",
        "primary-fixed-dim": "{orange-80}",
        "on-primary-fixed": "{orange-10}",
        "on-primary-fixed-variant": "{orange-30}",
        // Secondary — yellow: warm, prominent (classes, types)
        secondary: "{yellow-80}",
        "on-secondary": "{yellow-20}",
        "secondary-container": "{yellow-30}",
        "on-secondary-container": "{yellow-90}",
        "secondary-fixed": "{yellow-90}",
        "secondary-fixed-dim": "{yellow-80}",
        "on-secondary-fixed": "{yellow-10}",
        "on-secondary-fixed-variant": "{yellow-30}",
        // Tertiary — teal (aqua): cool counterpoint
        tertiary: "{teal-80}",
        "on-tertiary": "{teal-20}",
        "tertiary-container": "{teal-30}",
        "on-tertiary-container": "{teal-90}",
        "tertiary-fixed": "{teal-90}",
        "tertiary-fixed-dim": "{teal-80}",
        "on-tertiary-fixed": "{teal-10}",
        "on-tertiary-fixed-variant": "{teal-30}",
        // Error — red
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — warm dark browns (neutral at low tones)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{zinc-80}",
        "surface-tint": "{orange-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — warm gray
        outline: "{zinc-60}",
        "outline-variant": "{zinc-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{blue-22}",
        "primary-container": "{blue-50}",
        "on-primary-container": "{blue-100}",
        secondary: "{teal-22}",
        "secondary-container": "{teal-50}",
        "on-secondary-container": "{teal-100}",
        tertiary: "{violet-22}",
        "tertiary-container": "{violet-50}",
        "on-tertiary-container": "{violet-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{zinc-22}",
        outline: "{zinc-35}",
        "outline-variant": "{zinc-50}",
      },
      "light-high-contrast": {
        primary: "{blue-17}",
        "primary-container": "{blue-30}",
        "on-primary-container": "{blue-100}",
        secondary: "{teal-17}",
        "secondary-container": "{teal-30}",
        "on-secondary-container": "{teal-100}",
        tertiary: "{violet-17}",
        "tertiary-container": "{violet-30}",
        "on-tertiary-container": "{violet-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{zinc-0}",
        outline: "{zinc-17}",
        "outline-variant": "{zinc-30}",
      },
      "dark-medium-contrast": {
        primary: "{blue-87}",
        "on-primary": "{blue-17}",
        "primary-container": "{blue-60}",
        "on-primary-container": "{blue-0}",
        "inverse-primary": "{blue-30}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        "surface-tint": "{blue-80}",
        secondary: "{teal-87}",
        "on-secondary": "{teal-17}",
        "secondary-container": "{teal-60}",
        "on-secondary-container": "{teal-0}",
        "secondary-fixed": "{teal-90}",
        "secondary-fixed-dim": "{teal-80}",
        "on-secondary-fixed": "{teal-10}",
        "on-secondary-fixed-variant": "{teal-30}",
        tertiary: "{violet-87}",
        "on-tertiary": "{violet-17}",
        "tertiary-container": "{violet-60}",
        "on-tertiary-container": "{violet-0}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{zinc-87}",
        outline: "{zinc-70}",
        "outline-variant": "{zinc-60}",
      },
      "dark-high-contrast": {
        primary: "{blue-95}",
        "on-primary": "{blue-0}",
        "primary-container": "{blue-80}",
        "on-primary-container": "{blue-4}",
        "inverse-primary": "{blue-30}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        "surface-tint": "{blue-80}",
        secondary: "{teal-95}",
        "on-secondary": "{teal-0}",
        "secondary-container": "{teal-80}",
        "on-secondary-container": "{teal-4}",
        "secondary-fixed": "{teal-90}",
        "secondary-fixed-dim": "{teal-80}",
        "on-secondary-fixed": "{teal-10}",
        "on-secondary-fixed-variant": "{teal-30}",
        tertiary: "{violet-95}",
        "on-tertiary": "{violet-0}",
        "tertiary-container": "{violet-80}",
        "on-tertiary-container": "{violet-4}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{zinc-100}",
        outline: "{zinc-95}",
        "outline-variant": "{zinc-80}",
      },
    },
  },
  order: ["color"],
});
