import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Horizon theme — M3 token variant.
 */
export default preset.define({
  id: "horizon",
  name: "Horizon",
  reference: {
    // Chromatic palettes — Horizon's warm pink/peach/teal accents
    ...createM3ColorTokens("red", "#F43E5C"),
    ...createM3ColorTokens("orange", "#FAB795"),
    ...createM3ColorTokens("amber", "#FAC29A"),
    ...createM3ColorTokens("yellow", "#FAC29A"),
    ...createM3ColorTokens("lime", "#29D398"),
    ...createM3ColorTokens("green", "#27D797"),
    ...createM3ColorTokens("emerald", "#21BFC2"),
    ...createM3ColorTokens("teal", "#25B0BC"),
    ...createM3ColorTokens("cyan", "#59E1E3"),
    ...createM3ColorTokens("sky", "#26BBD9"),
    ...createM3ColorTokens("blue", "#26BBD9"),
    ...createM3ColorTokens("indigo", "#26BBD9"),
    ...createM3ColorTokens("violet", "#B877DB"),
    ...createM3ColorTokens("purple", "#B877DB"),
    ...createM3ColorTokens("fuchsia", "#EE64AC"),
    ...createM3ColorTokens("pink", "#E95378"),
    ...createM3ColorTokens("rose", "#E95378"),
    // Neutral palettes — cool dark with muted blue-gray
    ...createM3ColorTokens("slate", "#6C6F93"),
    ...createM3ColorTokens("gray", "#6C6F93"),
    ...createM3ColorTokens("zinc", "#2E303E"),
    ...createM3ColorTokens("neutral", "#1C1E26"),
    ...createM3ColorTokens("stone", "#6C6F93"),
  },
  system: {
    light: {
      // Primary — pink: cranberry, THE Horizon accent
      primary: "pink-40",
      "on-primary": "pink-100",
      "primary-container": "pink-90",
      "on-primary-container": "pink-10",
      "inverse-primary": "pink-80",
      "primary-fixed": "pink-90",
      "primary-fixed-dim": "pink-80",
      "on-primary-fixed": "pink-10",
      "on-primary-fixed-variant": "pink-30",
      // Secondary — violet: keywords, storage
      secondary: "violet-40",
      "on-secondary": "violet-100",
      "secondary-container": "violet-90",
      "on-secondary-container": "violet-10",
      "secondary-fixed": "violet-90",
      "secondary-fixed-dim": "violet-80",
      "on-secondary-fixed": "violet-10",
      "on-secondary-fixed-variant": "violet-30",
      // Tertiary — teal: functions
      tertiary: "teal-40",
      "on-tertiary": "teal-100",
      "tertiary-container": "teal-90",
      "on-tertiary-container": "teal-10",
      "tertiary-fixed": "teal-90",
      "tertiary-fixed-dim": "teal-80",
      "on-tertiary-fixed": "teal-10",
      "on-tertiary-fixed-variant": "teal-30",
      // Error — red
      error: "red-40",
      "on-error": "red-100",
      "error-container": "red-90",
      "on-error-container": "red-10",
      // Surfaces
      surface: "neutral-98",
      "on-surface": "neutral-10",
      "surface-dim": "neutral-87",
      "surface-bright": "neutral-98",
      "surface-container-lowest": "neutral-100",
      "surface-container-low": "neutral-96",
      "surface-container": "neutral-94",
      "surface-container-high": "neutral-92",
      "surface-container-highest": "neutral-90",
      "surface-variant": "slate-90",
      "on-surface-variant": "slate-30",
      "surface-tint": "pink-40",
      "inverse-surface": "neutral-20",
      "inverse-on-surface": "neutral-95",
      background: "neutral-98",
      "on-background": "neutral-10",
      // Outlines
      outline: "slate-50",
      "outline-variant": "slate-80",
      shadow: "neutral-0",
      scrim: "neutral-0",
    },
    dark: {
      // Primary — pink: bright cranberry on dark
      primary: "pink-80",
      "on-primary": "pink-20",
      "primary-container": "pink-30",
      "on-primary-container": "pink-90",
      "inverse-primary": "pink-40",
      "primary-fixed": "pink-90",
      "primary-fixed-dim": "pink-80",
      "on-primary-fixed": "pink-10",
      "on-primary-fixed-variant": "pink-30",
      // Secondary — violet: lavender keywords
      secondary: "violet-80",
      "on-secondary": "violet-20",
      "secondary-container": "violet-30",
      "on-secondary-container": "violet-90",
      "secondary-fixed": "violet-90",
      "secondary-fixed-dim": "violet-80",
      "on-secondary-fixed": "violet-10",
      "on-secondary-fixed-variant": "violet-30",
      // Tertiary — teal: functions
      tertiary: "teal-80",
      "on-tertiary": "teal-20",
      "tertiary-container": "teal-30",
      "on-tertiary-container": "teal-90",
      "tertiary-fixed": "teal-90",
      "tertiary-fixed-dim": "teal-80",
      "on-tertiary-fixed": "teal-10",
      "on-tertiary-fixed-variant": "teal-30",
      // Error — red
      error: "red-80",
      "on-error": "red-20",
      "error-container": "red-30",
      "on-error-container": "red-90",
      // Surfaces — cool dark (#1C1E26)
      surface: "neutral-6",
      "on-surface": "neutral-90",
      "surface-dim": "neutral-6",
      "surface-bright": "neutral-24",
      "surface-container-lowest": "neutral-4",
      "surface-container-low": "neutral-10",
      "surface-container": "neutral-12",
      "surface-container-high": "neutral-17",
      "surface-container-highest": "neutral-22",
      "surface-variant": "zinc-30",
      "on-surface-variant": "slate-80",
      "surface-tint": "pink-80",
      "inverse-surface": "neutral-90",
      "inverse-on-surface": "neutral-20",
      background: "neutral-6",
      "on-background": "neutral-90",
      // Outlines
      outline: "slate-60",
      "outline-variant": "zinc-30",
      shadow: "neutral-0",
      scrim: "neutral-0",
    },
  },
  roles: {},
});
