import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Kanagawa theme — M3 token variant.
 */
export default preset.define({
  id: "kanagawa",
  name: "Kanagawa",
  tokens: {
    // Chromatic palettes — Kanagawa's Japanese wave-inspired palette
    ...createM3ColorTokens("red", "#c34043"),
    ...createM3ColorTokens("orange", "#ffa066"),
    ...createM3ColorTokens("amber", "#dca561"),
    ...createM3ColorTokens("yellow", "#e6c384"),
    ...createM3ColorTokens("lime", "#98bb6c"),
    ...createM3ColorTokens("green", "#76946a"),
    ...createM3ColorTokens("emerald", "#7aa89f"),
    ...createM3ColorTokens("teal", "#6a9589"),
    ...createM3ColorTokens("cyan", "#a3d4d5"),
    ...createM3ColorTokens("sky", "#7fb4ca"),
    ...createM3ColorTokens("blue", "#7e9cd8"),
    ...createM3ColorTokens("indigo", "#2d4f67"),
    ...createM3ColorTokens("violet", "#957fb8"),
    ...createM3ColorTokens("purple", "#938aa9"),
    ...createM3ColorTokens("fuchsia", "#d27e99"),
    ...createM3ColorTokens("pink", "#d27e99"),
    ...createM3ColorTokens("rose", "#e46876"),
    // Neutral palettes — warm ink-tinted darks
    ...createM3ColorTokens("slate", "#54546d"),
    ...createM3ColorTokens("gray", "#727169"),
    ...createM3ColorTokens("zinc", "#363646"),
    ...createM3ColorTokens("neutral", "#1f1f28"),
    ...createM3ColorTokens("stone", "#c8c093"),
    // Semantic roles — default to the light scheme
    // Primary — blue (crystalBlue): the main accent
    primary: "{blue-40}",
    "on-primary": "{blue-100}",
    "primary-container": "{blue-90}",
    "on-primary-container": "{blue-10}",
    "inverse-primary": "{blue-80}",
    "primary-fixed": "{blue-90}",
    "primary-fixed-dim": "{blue-80}",
    "on-primary-fixed": "{blue-10}",
    "on-primary-fixed-variant": "{blue-30}",
    // Secondary — violet (oniViolet): keywords, special
    secondary: "{violet-40}",
    "on-secondary": "{violet-100}",
    "secondary-container": "{violet-90}",
    "on-secondary-container": "{violet-10}",
    "secondary-fixed": "{violet-90}",
    "secondary-fixed-dim": "{violet-80}",
    "on-secondary-fixed": "{violet-10}",
    "on-secondary-fixed-variant": "{violet-30}",
    // Tertiary — cyan (lightBlue): cool counterpoint
    tertiary: "{cyan-40}",
    "on-tertiary": "{cyan-100}",
    "tertiary-container": "{cyan-90}",
    "on-tertiary-container": "{cyan-10}",
    "tertiary-fixed": "{cyan-90}",
    "tertiary-fixed-dim": "{cyan-80}",
    "on-tertiary-fixed": "{cyan-10}",
    "on-tertiary-fixed-variant": "{cyan-30}",
    // Error — red (autumnRed)
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — warm parchment (lotusWhite territory)
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{gray-90}",
    "on-surface-variant": "{gray-30}",
    "surface-tint": "{blue-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines — warm muted gray
    outline: "{gray-50}",
    "outline-variant": "{gray-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — blue (crystalBlue): wave blue on sumi ink
        primary: "{blue-80}",
        "on-primary": "{blue-20}",
        "primary-container": "{blue-30}",
        "on-primary-container": "{blue-90}",
        "inverse-primary": "{blue-40}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        // Secondary — violet (oniViolet): purple keywords
        secondary: "{violet-80}",
        "on-secondary": "{violet-20}",
        "secondary-container": "{violet-30}",
        "on-secondary-container": "{violet-90}",
        "secondary-fixed": "{violet-90}",
        "secondary-fixed-dim": "{violet-80}",
        "on-secondary-fixed": "{violet-10}",
        "on-secondary-fixed-variant": "{violet-30}",
        // Tertiary — cyan (lightBlue): cool water tones
        tertiary: "{cyan-80}",
        "on-tertiary": "{cyan-20}",
        "tertiary-container": "{cyan-30}",
        "on-tertiary-container": "{cyan-90}",
        "tertiary-fixed": "{cyan-90}",
        "tertiary-fixed-dim": "{cyan-80}",
        "on-tertiary-fixed": "{cyan-10}",
        "on-tertiary-fixed-variant": "{cyan-30}",
        // Error — red (autumnRed)
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — deep sumi ink (#1f1f28 territory)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{gray-80}",
        "surface-tint": "{blue-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — warm fujiGray territory
        outline: "{gray-60}",
        "outline-variant": "{slate-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{blue-22}",
        "primary-container": "{blue-50}",
        "on-primary-container": "{blue-100}",
        secondary: "{violet-22}",
        "secondary-container": "{violet-50}",
        "on-secondary-container": "{violet-100}",
        tertiary: "{cyan-22}",
        "tertiary-container": "{cyan-50}",
        "on-tertiary-container": "{cyan-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{gray-22}",
        outline: "{gray-35}",
        "outline-variant": "{gray-50}",
      },
      "light-high-contrast": {
        primary: "{blue-17}",
        "primary-container": "{blue-30}",
        "on-primary-container": "{blue-100}",
        secondary: "{violet-17}",
        "secondary-container": "{violet-30}",
        "on-secondary-container": "{violet-100}",
        tertiary: "{cyan-17}",
        "tertiary-container": "{cyan-30}",
        "on-tertiary-container": "{cyan-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{gray-0}",
        outline: "{gray-17}",
        "outline-variant": "{gray-30}",
      },
      "dark-medium-contrast": {
        primary: "{blue-87}",
        "on-primary": "{blue-17}",
        "primary-container": "{blue-60}",
        "on-primary-container": "{blue-0}",
        "inverse-primary": "{blue-30}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        "surface-tint": "{blue-80}",
        secondary: "{violet-87}",
        "on-secondary": "{violet-17}",
        "secondary-container": "{violet-60}",
        "on-secondary-container": "{violet-0}",
        "secondary-fixed": "{violet-90}",
        "secondary-fixed-dim": "{violet-80}",
        "on-secondary-fixed": "{violet-10}",
        "on-secondary-fixed-variant": "{violet-30}",
        tertiary: "{cyan-87}",
        "on-tertiary": "{cyan-17}",
        "tertiary-container": "{cyan-60}",
        "on-tertiary-container": "{cyan-0}",
        "tertiary-fixed": "{cyan-90}",
        "tertiary-fixed-dim": "{cyan-80}",
        "on-tertiary-fixed": "{cyan-10}",
        "on-tertiary-fixed-variant": "{cyan-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{gray-30}",
        "on-surface-variant": "{gray-87}",
        outline: "{gray-70}",
        "outline-variant": "{gray-60}",
      },
      "dark-high-contrast": {
        primary: "{blue-95}",
        "on-primary": "{blue-0}",
        "primary-container": "{blue-80}",
        "on-primary-container": "{blue-4}",
        "inverse-primary": "{blue-30}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        "surface-tint": "{blue-80}",
        secondary: "{violet-95}",
        "on-secondary": "{violet-0}",
        "secondary-container": "{violet-80}",
        "on-secondary-container": "{violet-4}",
        "secondary-fixed": "{violet-90}",
        "secondary-fixed-dim": "{violet-80}",
        "on-secondary-fixed": "{violet-10}",
        "on-secondary-fixed-variant": "{violet-30}",
        tertiary: "{cyan-95}",
        "on-tertiary": "{cyan-0}",
        "tertiary-container": "{cyan-80}",
        "on-tertiary-container": "{cyan-4}",
        "tertiary-fixed": "{cyan-90}",
        "tertiary-fixed-dim": "{cyan-80}",
        "on-tertiary-fixed": "{cyan-10}",
        "on-tertiary-fixed-variant": "{cyan-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{gray-30}",
        "on-surface-variant": "{gray-100}",
        outline: "{gray-95}",
        "outline-variant": "{gray-80}",
      },
    },
  },
  order: ["color"],
});
