import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Monokai theme — M3 token variant.
 */
export default preset.define({
  id: "monokai",
  name: "Monokai",
  tokens: {
    // Chromatic palettes — Monokai's punchy, saturated syntax colors
    ...createM3ColorTokens("red", "#F92672"),
    ...createM3ColorTokens("orange", "#FD971F"),
    ...createM3ColorTokens("amber", "#E6DB74"),
    ...createM3ColorTokens("yellow", "#E6DB74"),
    ...createM3ColorTokens("lime", "#A6E22E"),
    ...createM3ColorTokens("green", "#A6E22E"),
    ...createM3ColorTokens("emerald", "#A1EFE4"),
    ...createM3ColorTokens("teal", "#A1EFE4"),
    ...createM3ColorTokens("cyan", "#66D9EF"),
    ...createM3ColorTokens("sky", "#66D9EF"),
    ...createM3ColorTokens("blue", "#66D9EF"),
    ...createM3ColorTokens("indigo", "#6A7EC8"),
    ...createM3ColorTokens("violet", "#AE81FF"),
    ...createM3ColorTokens("purple", "#AE81FF"),
    ...createM3ColorTokens("fuchsia", "#F92672"),
    ...createM3ColorTokens("pink", "#F92672"),
    ...createM3ColorTokens("rose", "#F92672"),
    // Neutral palettes — warm olive-gray (distinctive Monokai warmth)
    ...createM3ColorTokens("slate", "#75715E"),
    ...createM3ColorTokens("gray", "#75715E"),
    ...createM3ColorTokens("zinc", "#49483E"),
    ...createM3ColorTokens("neutral", "#272822"),
    ...createM3ColorTokens("stone", "#90908A"),
    // Semantic roles — default to the light scheme
    // Primary — pink/magenta: THE Monokai color (keywords, operators)
    primary: "{pink-40}",
    "on-primary": "{pink-100}",
    "primary-container": "{pink-90}",
    "on-primary-container": "{pink-10}",
    "inverse-primary": "{pink-80}",
    "primary-fixed": "{pink-90}",
    "primary-fixed-dim": "{pink-80}",
    "on-primary-fixed": "{pink-10}",
    "on-primary-fixed-variant": "{pink-30}",
    // Secondary — cyan: types, support functions
    secondary: "{cyan-40}",
    "on-secondary": "{cyan-100}",
    "secondary-container": "{cyan-90}",
    "on-secondary-container": "{cyan-10}",
    "secondary-fixed": "{cyan-90}",
    "secondary-fixed-dim": "{cyan-80}",
    "on-secondary-fixed": "{cyan-10}",
    "on-secondary-fixed-variant": "{cyan-30}",
    // Tertiary — violet: numbers, built-in constants
    tertiary: "{violet-40}",
    "on-tertiary": "{violet-100}",
    "tertiary-container": "{violet-90}",
    "on-tertiary-container": "{violet-10}",
    "tertiary-fixed": "{violet-90}",
    "tertiary-fixed-dim": "{violet-80}",
    "on-tertiary-fixed": "{violet-10}",
    "on-tertiary-fixed-variant": "{violet-30}",
    // Error — red (shares pink seed but semantically error)
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — warm olive-tinted
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{slate-90}",
    "on-surface-variant": "{slate-30}",
    "surface-tint": "{pink-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines — warm olive-gray
    outline: "{slate-50}",
    "outline-variant": "{slate-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — pink/magenta: hot pink keywords on dark olive
        primary: "{pink-80}",
        "on-primary": "{pink-20}",
        "primary-container": "{pink-30}",
        "on-primary-container": "{pink-90}",
        "inverse-primary": "{pink-40}",
        "primary-fixed": "{pink-90}",
        "primary-fixed-dim": "{pink-80}",
        "on-primary-fixed": "{pink-10}",
        "on-primary-fixed-variant": "{pink-30}",
        // Secondary — cyan: bright cyan types
        secondary: "{cyan-80}",
        "on-secondary": "{cyan-20}",
        "secondary-container": "{cyan-30}",
        "on-secondary-container": "{cyan-90}",
        "secondary-fixed": "{cyan-90}",
        "secondary-fixed-dim": "{cyan-80}",
        "on-secondary-fixed": "{cyan-10}",
        "on-secondary-fixed-variant": "{cyan-30}",
        // Tertiary — violet: purple constants
        tertiary: "{violet-80}",
        "on-tertiary": "{violet-20}",
        "tertiary-container": "{violet-30}",
        "on-tertiary-container": "{violet-90}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        // Error — red
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — warm olive-black (#272822 territory)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{slate-80}",
        "surface-tint": "{pink-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — olive comment gray
        outline: "{slate-60}",
        "outline-variant": "{zinc-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{pink-22}",
        "primary-container": "{pink-50}",
        "on-primary-container": "{pink-100}",
        secondary: "{cyan-22}",
        "secondary-container": "{cyan-50}",
        "on-secondary-container": "{cyan-100}",
        tertiary: "{violet-22}",
        "tertiary-container": "{violet-50}",
        "on-tertiary-container": "{violet-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{slate-22}",
        outline: "{slate-35}",
        "outline-variant": "{slate-50}",
      },
      "light-high-contrast": {
        primary: "{pink-17}",
        "primary-container": "{pink-30}",
        "on-primary-container": "{pink-100}",
        secondary: "{cyan-17}",
        "secondary-container": "{cyan-30}",
        "on-secondary-container": "{cyan-100}",
        tertiary: "{violet-17}",
        "tertiary-container": "{violet-30}",
        "on-tertiary-container": "{violet-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{slate-0}",
        outline: "{slate-17}",
        "outline-variant": "{slate-30}",
      },
      "dark-medium-contrast": {
        primary: "{pink-87}",
        "on-primary": "{pink-17}",
        "primary-container": "{pink-60}",
        "on-primary-container": "{pink-0}",
        "inverse-primary": "{pink-30}",
        "primary-fixed": "{pink-90}",
        "primary-fixed-dim": "{pink-80}",
        "on-primary-fixed": "{pink-10}",
        "on-primary-fixed-variant": "{pink-30}",
        "surface-tint": "{pink-80}",
        secondary: "{cyan-87}",
        "on-secondary": "{cyan-17}",
        "secondary-container": "{cyan-60}",
        "on-secondary-container": "{cyan-0}",
        "secondary-fixed": "{cyan-90}",
        "secondary-fixed-dim": "{cyan-80}",
        "on-secondary-fixed": "{cyan-10}",
        "on-secondary-fixed-variant": "{cyan-30}",
        tertiary: "{violet-87}",
        "on-tertiary": "{violet-17}",
        "tertiary-container": "{violet-60}",
        "on-tertiary-container": "{violet-0}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-87}",
        outline: "{slate-70}",
        "outline-variant": "{slate-60}",
      },
      "dark-high-contrast": {
        primary: "{pink-95}",
        "on-primary": "{pink-0}",
        "primary-container": "{pink-80}",
        "on-primary-container": "{pink-4}",
        "inverse-primary": "{pink-30}",
        "primary-fixed": "{pink-90}",
        "primary-fixed-dim": "{pink-80}",
        "on-primary-fixed": "{pink-10}",
        "on-primary-fixed-variant": "{pink-30}",
        "surface-tint": "{pink-80}",
        secondary: "{cyan-95}",
        "on-secondary": "{cyan-0}",
        "secondary-container": "{cyan-80}",
        "on-secondary-container": "{cyan-4}",
        "secondary-fixed": "{cyan-90}",
        "secondary-fixed-dim": "{cyan-80}",
        "on-secondary-fixed": "{cyan-10}",
        "on-secondary-fixed-variant": "{cyan-30}",
        tertiary: "{violet-95}",
        "on-tertiary": "{violet-0}",
        "tertiary-container": "{violet-80}",
        "on-tertiary-container": "{violet-4}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-100}",
        outline: "{slate-95}",
        "outline-variant": "{slate-80}",
      },
    },
  },
  order: ["color"],
});
