import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Night Owl theme — M3 token variant.
 */
export default preset.define({
  id: "night_owl",
  name: "Night Owl",
  tokens: {
    // Chromatic palettes — Night Owl's rich, accessible accents
    ...createM3ColorTokens("red", "#ff5874"),
    ...createM3ColorTokens("orange", "#F78C6C"),
    ...createM3ColorTokens("amber", "#ffcb8b"),
    ...createM3ColorTokens("yellow", "#ecc48d"),
    ...createM3ColorTokens("lime", "#c5e478"),
    ...createM3ColorTokens("green", "#c5e478"),
    ...createM3ColorTokens("emerald", "#7fdbca"),
    ...createM3ColorTokens("teal", "#7fdbca"),
    ...createM3ColorTokens("cyan", "#5ca7e4"),
    ...createM3ColorTokens("sky", "#82AAFF"),
    ...createM3ColorTokens("blue", "#82AAFF"),
    ...createM3ColorTokens("indigo", "#4373c2"),
    ...createM3ColorTokens("violet", "#c792ea"),
    ...createM3ColorTokens("purple", "#7e57c2"),
    ...createM3ColorTokens("fuchsia", "#c792ea"),
    ...createM3ColorTokens("pink", "#ff5874"),
    ...createM3ColorTokens("rose", "#ff5874"),
    // Neutral palettes — deep navy, cool blue-tinted
    ...createM3ColorTokens("slate", "#4b6479"),
    ...createM3ColorTokens("gray", "#637777"),
    ...createM3ColorTokens("zinc", "#1d3b53"),
    ...createM3ColorTokens("neutral", "#011627"),
    ...createM3ColorTokens("stone", "#5f7e97"),
    // Semantic roles — default to the light scheme
    // Primary — blue: functions, built-in constants
    primary: "{blue-40}",
    "on-primary": "{blue-100}",
    "primary-container": "{blue-90}",
    "on-primary-container": "{blue-10}",
    "inverse-primary": "{blue-80}",
    "primary-fixed": "{blue-90}",
    "primary-fixed-dim": "{blue-80}",
    "on-primary-fixed": "{blue-10}",
    "on-primary-fixed-variant": "{blue-30}",
    // Secondary — violet: keywords, control flow
    secondary: "{violet-40}",
    "on-secondary": "{violet-100}",
    "secondary-container": "{violet-90}",
    "on-secondary-container": "{violet-10}",
    "secondary-fixed": "{violet-90}",
    "secondary-fixed-dim": "{violet-80}",
    "on-secondary-fixed": "{violet-10}",
    "on-secondary-fixed-variant": "{violet-30}",
    // Tertiary — emerald: tags, operators
    tertiary: "{emerald-40}",
    "on-tertiary": "{emerald-100}",
    "tertiary-container": "{emerald-90}",
    "on-tertiary-container": "{emerald-10}",
    "tertiary-fixed": "{emerald-90}",
    "tertiary-fixed-dim": "{emerald-80}",
    "on-tertiary-fixed": "{emerald-10}",
    "on-tertiary-fixed-variant": "{emerald-30}",
    // Error — red
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — cool light
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{slate-90}",
    "on-surface-variant": "{slate-30}",
    "surface-tint": "{blue-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines
    outline: "{stone-50}",
    "outline-variant": "{slate-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — blue: bright function blue on deep navy
        primary: "{blue-80}",
        "on-primary": "{blue-20}",
        "primary-container": "{blue-30}",
        "on-primary-container": "{blue-90}",
        "inverse-primary": "{blue-40}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        // Secondary — violet: purple keywords
        secondary: "{violet-80}",
        "on-secondary": "{violet-20}",
        "secondary-container": "{violet-30}",
        "on-secondary-container": "{violet-90}",
        "secondary-fixed": "{violet-90}",
        "secondary-fixed-dim": "{violet-80}",
        "on-secondary-fixed": "{violet-10}",
        "on-secondary-fixed-variant": "{violet-30}",
        // Tertiary — emerald: teal tags/operators
        tertiary: "{emerald-80}",
        "on-tertiary": "{emerald-20}",
        "tertiary-container": "{emerald-30}",
        "on-tertiary-container": "{emerald-90}",
        "tertiary-fixed": "{emerald-90}",
        "tertiary-fixed-dim": "{emerald-80}",
        "on-tertiary-fixed": "{emerald-10}",
        "on-tertiary-fixed-variant": "{emerald-30}",
        // Error — red
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — very deep navy (#011627)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{stone-80}",
        "surface-tint": "{blue-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — muted teal-gray (comment territory)
        outline: "{gray-60}",
        "outline-variant": "{zinc-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{blue-22}",
        "primary-container": "{blue-50}",
        "on-primary-container": "{blue-100}",
        secondary: "{violet-22}",
        "secondary-container": "{violet-50}",
        "on-secondary-container": "{violet-100}",
        tertiary: "{emerald-22}",
        "tertiary-container": "{emerald-50}",
        "on-tertiary-container": "{emerald-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{slate-22}",
        outline: "{stone-35}",
        "outline-variant": "{slate-50}",
      },
      "light-high-contrast": {
        primary: "{blue-17}",
        "primary-container": "{blue-30}",
        "on-primary-container": "{blue-100}",
        secondary: "{violet-17}",
        "secondary-container": "{violet-30}",
        "on-secondary-container": "{violet-100}",
        tertiary: "{emerald-17}",
        "tertiary-container": "{emerald-30}",
        "on-tertiary-container": "{emerald-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{slate-0}",
        outline: "{stone-17}",
        "outline-variant": "{slate-30}",
      },
      "dark-medium-contrast": {
        primary: "{blue-87}",
        "on-primary": "{blue-17}",
        "primary-container": "{blue-60}",
        "on-primary-container": "{blue-0}",
        "inverse-primary": "{blue-30}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        "surface-tint": "{blue-80}",
        secondary: "{violet-87}",
        "on-secondary": "{violet-17}",
        "secondary-container": "{violet-60}",
        "on-secondary-container": "{violet-0}",
        "secondary-fixed": "{violet-90}",
        "secondary-fixed-dim": "{violet-80}",
        "on-secondary-fixed": "{violet-10}",
        "on-secondary-fixed-variant": "{violet-30}",
        tertiary: "{emerald-87}",
        "on-tertiary": "{emerald-17}",
        "tertiary-container": "{emerald-60}",
        "on-tertiary-container": "{emerald-0}",
        "tertiary-fixed": "{emerald-90}",
        "tertiary-fixed-dim": "{emerald-80}",
        "on-tertiary-fixed": "{emerald-10}",
        "on-tertiary-fixed-variant": "{emerald-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-87}",
        outline: "{stone-70}",
        "outline-variant": "{slate-60}",
      },
      "dark-high-contrast": {
        primary: "{blue-95}",
        "on-primary": "{blue-0}",
        "primary-container": "{blue-80}",
        "on-primary-container": "{blue-4}",
        "inverse-primary": "{blue-30}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        "surface-tint": "{blue-80}",
        secondary: "{violet-95}",
        "on-secondary": "{violet-0}",
        "secondary-container": "{violet-80}",
        "on-secondary-container": "{violet-4}",
        "secondary-fixed": "{violet-90}",
        "secondary-fixed-dim": "{violet-80}",
        "on-secondary-fixed": "{violet-10}",
        "on-secondary-fixed-variant": "{violet-30}",
        tertiary: "{emerald-95}",
        "on-tertiary": "{emerald-0}",
        "tertiary-container": "{emerald-80}",
        "on-tertiary-container": "{emerald-4}",
        "tertiary-fixed": "{emerald-90}",
        "tertiary-fixed-dim": "{emerald-80}",
        "on-tertiary-fixed": "{emerald-10}",
        "on-tertiary-fixed-variant": "{emerald-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-100}",
        outline: "{stone-95}",
        "outline-variant": "{slate-80}",
      },
    },
  },
  order: ["color"],
});
