import { createM3ColorTokens } from "../colors";
import preset from "../preset";

/**
 * Nord theme — M3 token variant.
 */
export default preset.define({
  id: "nord",
  name: "Nord",
  tokens: {
    // Chromatic palettes — mapped to Nord's muted Aurora + Frost hues
    ...createM3ColorTokens("red", "#bf616a"),
    ...createM3ColorTokens("orange", "#d08770"),
    ...createM3ColorTokens("amber", "#d08770"),
    ...createM3ColorTokens("yellow", "#ebcb8b"),
    ...createM3ColorTokens("lime", "#a3be8c"),
    ...createM3ColorTokens("green", "#a3be8c"),
    ...createM3ColorTokens("emerald", "#a3be8c"),
    ...createM3ColorTokens("teal", "#8fbcbb"),
    ...createM3ColorTokens("cyan", "#88c0d0"),
    ...createM3ColorTokens("sky", "#88c0d0"),
    ...createM3ColorTokens("blue", "#5e81ac"),
    ...createM3ColorTokens("indigo", "#81a1c1"),
    ...createM3ColorTokens("violet", "#b48ead"),
    ...createM3ColorTokens("purple", "#b48ead"),
    ...createM3ColorTokens("fuchsia", "#b48ead"),
    ...createM3ColorTokens("pink", "#bf616a"),
    ...createM3ColorTokens("rose", "#bf616a"),
    // Neutral palettes — cool blue-gray tinted (Polar Night)
    ...createM3ColorTokens("slate", "#434c5e"),
    ...createM3ColorTokens("gray", "#4c566a"),
    ...createM3ColorTokens("zinc", "#4c566a"),
    ...createM3ColorTokens("neutral", "#2e3440"),
    ...createM3ColorTokens("stone", "#3b4252"),
    // Semantic roles — default to the light scheme
    // Primary — cyan (nord8): THE signature Nord frost blue
    primary: "{cyan-40}",
    "on-primary": "{cyan-100}",
    "primary-container": "{cyan-90}",
    "on-primary-container": "{cyan-10}",
    "inverse-primary": "{cyan-80}",
    "primary-fixed": "{cyan-90}",
    "primary-fixed-dim": "{cyan-80}",
    "on-primary-fixed": "{cyan-10}",
    "on-primary-fixed-variant": "{cyan-30}",
    // Secondary — teal (nord7): the second frost accent
    secondary: "{teal-40}",
    "on-secondary": "{teal-100}",
    "secondary-container": "{teal-90}",
    "on-secondary-container": "{teal-10}",
    "secondary-fixed": "{teal-90}",
    "secondary-fixed-dim": "{teal-80}",
    "on-secondary-fixed": "{teal-10}",
    "on-secondary-fixed-variant": "{teal-30}",
    // Tertiary — violet (nord15): muted purple accent
    tertiary: "{violet-40}",
    "on-tertiary": "{violet-100}",
    "tertiary-container": "{violet-90}",
    "on-tertiary-container": "{violet-10}",
    "tertiary-fixed": "{violet-90}",
    "tertiary-fixed-dim": "{violet-80}",
    "on-tertiary-fixed": "{violet-10}",
    "on-tertiary-fixed-variant": "{violet-30}",
    // Error — red (nord11)
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — Snow Storm cool blue-gray neutrals
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{slate-90}",
    "on-surface-variant": "{slate-30}",
    "surface-tint": "{cyan-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines — cool blue-gray
    outline: "{slate-50}",
    "outline-variant": "{slate-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — cyan (nord8): frost blue on Polar Night
        primary: "{cyan-80}",
        "on-primary": "{cyan-20}",
        "primary-container": "{cyan-30}",
        "on-primary-container": "{cyan-90}",
        "inverse-primary": "{cyan-40}",
        "primary-fixed": "{cyan-90}",
        "primary-fixed-dim": "{cyan-80}",
        "on-primary-fixed": "{cyan-10}",
        "on-primary-fixed-variant": "{cyan-30}",
        // Secondary — teal (nord7): soft teal on dark
        secondary: "{teal-80}",
        "on-secondary": "{teal-20}",
        "secondary-container": "{teal-30}",
        "on-secondary-container": "{teal-90}",
        "secondary-fixed": "{teal-90}",
        "secondary-fixed-dim": "{teal-80}",
        "on-secondary-fixed": "{teal-10}",
        "on-secondary-fixed-variant": "{teal-30}",
        // Tertiary — violet (nord15): muted purple counterpoint
        tertiary: "{violet-80}",
        "on-tertiary": "{violet-20}",
        "tertiary-container": "{violet-30}",
        "on-tertiary-container": "{violet-90}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        // Error — red (nord11)
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — Polar Night cool blue-gray darks
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-80}",
        "surface-tint": "{cyan-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — cool blue-gray
        outline: "{gray-60}",
        "outline-variant": "{slate-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{cyan-22}",
        "primary-container": "{cyan-50}",
        "on-primary-container": "{cyan-100}",
        secondary: "{teal-22}",
        "secondary-container": "{teal-50}",
        "on-secondary-container": "{teal-100}",
        tertiary: "{violet-22}",
        "tertiary-container": "{violet-50}",
        "on-tertiary-container": "{violet-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{slate-22}",
        outline: "{slate-35}",
        "outline-variant": "{slate-50}",
      },
      "light-high-contrast": {
        primary: "{cyan-17}",
        "primary-container": "{cyan-30}",
        "on-primary-container": "{cyan-100}",
        secondary: "{teal-17}",
        "secondary-container": "{teal-30}",
        "on-secondary-container": "{teal-100}",
        tertiary: "{violet-17}",
        "tertiary-container": "{violet-30}",
        "on-tertiary-container": "{violet-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{slate-0}",
        outline: "{slate-17}",
        "outline-variant": "{slate-30}",
      },
      "dark-medium-contrast": {
        primary: "{cyan-87}",
        "on-primary": "{cyan-17}",
        "primary-container": "{cyan-60}",
        "on-primary-container": "{cyan-0}",
        "inverse-primary": "{cyan-30}",
        "primary-fixed": "{cyan-90}",
        "primary-fixed-dim": "{cyan-80}",
        "on-primary-fixed": "{cyan-10}",
        "on-primary-fixed-variant": "{cyan-30}",
        "surface-tint": "{cyan-80}",
        secondary: "{teal-87}",
        "on-secondary": "{teal-17}",
        "secondary-container": "{teal-60}",
        "on-secondary-container": "{teal-0}",
        "secondary-fixed": "{teal-90}",
        "secondary-fixed-dim": "{teal-80}",
        "on-secondary-fixed": "{teal-10}",
        "on-secondary-fixed-variant": "{teal-30}",
        tertiary: "{violet-87}",
        "on-tertiary": "{violet-17}",
        "tertiary-container": "{violet-60}",
        "on-tertiary-container": "{violet-0}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-87}",
        outline: "{slate-70}",
        "outline-variant": "{slate-60}",
      },
      "dark-high-contrast": {
        primary: "{cyan-95}",
        "on-primary": "{cyan-0}",
        "primary-container": "{cyan-80}",
        "on-primary-container": "{cyan-4}",
        "inverse-primary": "{cyan-30}",
        "primary-fixed": "{cyan-90}",
        "primary-fixed-dim": "{cyan-80}",
        "on-primary-fixed": "{cyan-10}",
        "on-primary-fixed-variant": "{cyan-30}",
        "surface-tint": "{cyan-80}",
        secondary: "{teal-95}",
        "on-secondary": "{teal-0}",
        "secondary-container": "{teal-80}",
        "on-secondary-container": "{teal-4}",
        "secondary-fixed": "{teal-90}",
        "secondary-fixed-dim": "{teal-80}",
        "on-secondary-fixed": "{teal-10}",
        "on-secondary-fixed-variant": "{teal-30}",
        tertiary: "{violet-95}",
        "on-tertiary": "{violet-0}",
        "tertiary-container": "{violet-80}",
        "on-tertiary-container": "{violet-4}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-100}",
        outline: "{slate-95}",
        "outline-variant": "{slate-80}",
      },
    },
  },
  order: ["color"],
});
