import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * One Dark theme — M3 token variant.
 */
export default preset.define({
  id: "one_dark",
  name: "One Dark",
  tokens: {
    // Chromatic palettes — One Dark's warm, vivid syntax hues
    ...createM3ColorTokens("red", "#e06c75"),
    ...createM3ColorTokens("orange", "#d19a66"),
    ...createM3ColorTokens("amber", "#e5c07b"),
    ...createM3ColorTokens("yellow", "#e5c07b"),
    ...createM3ColorTokens("lime", "#98c379"),
    ...createM3ColorTokens("green", "#98c379"),
    ...createM3ColorTokens("emerald", "#56b6c2"),
    ...createM3ColorTokens("teal", "#56b6c2"),
    ...createM3ColorTokens("cyan", "#56b6c2"),
    ...createM3ColorTokens("sky", "#61afef"),
    ...createM3ColorTokens("blue", "#61afef"),
    ...createM3ColorTokens("indigo", "#528bff"),
    ...createM3ColorTokens("violet", "#c678dd"),
    ...createM3ColorTokens("purple", "#c678dd"),
    ...createM3ColorTokens("fuchsia", "#c678dd"),
    ...createM3ColorTokens("pink", "#e06c75"),
    ...createM3ColorTokens("rose", "#be5046"),
    // Neutral palettes — cool blue-gray tinted
    ...createM3ColorTokens("slate", "#5c6370"),
    ...createM3ColorTokens("gray", "#4b5263"),
    ...createM3ColorTokens("zinc", "#5c6370"),
    ...createM3ColorTokens("neutral", "#282c34"),
    ...createM3ColorTokens("stone", "#828997"),
    // Semantic roles — default to the light scheme
    // Primary — blue: Hue 2, the function color
    primary: "{blue-40}",
    "on-primary": "{blue-100}",
    "primary-container": "{blue-90}",
    "on-primary-container": "{blue-10}",
    "inverse-primary": "{blue-80}",
    "primary-fixed": "{blue-90}",
    "primary-fixed-dim": "{blue-80}",
    "on-primary-fixed": "{blue-10}",
    "on-primary-fixed-variant": "{blue-30}",
    // Secondary — violet: Hue 3, keywords
    secondary: "{violet-40}",
    "on-secondary": "{violet-100}",
    "secondary-container": "{violet-90}",
    "on-secondary-container": "{violet-10}",
    "secondary-fixed": "{violet-90}",
    "secondary-fixed-dim": "{violet-80}",
    "on-secondary-fixed": "{violet-10}",
    "on-secondary-fixed-variant": "{violet-30}",
    // Tertiary — cyan: Hue 1, operators
    tertiary: "{cyan-40}",
    "on-tertiary": "{cyan-100}",
    "tertiary-container": "{cyan-90}",
    "on-tertiary-container": "{cyan-10}",
    "tertiary-fixed": "{cyan-90}",
    "tertiary-fixed-dim": "{cyan-80}",
    "on-tertiary-fixed": "{cyan-10}",
    "on-tertiary-fixed-variant": "{cyan-30}",
    // Error — red: Hue 5
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — cool blue-gray
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{slate-90}",
    "on-surface-variant": "{slate-30}",
    "surface-tint": "{blue-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines
    outline: "{slate-50}",
    "outline-variant": "{slate-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — blue: bright function blue on dark
        primary: "{blue-80}",
        "on-primary": "{blue-20}",
        "primary-container": "{blue-30}",
        "on-primary-container": "{blue-90}",
        "inverse-primary": "{blue-40}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        // Secondary — violet: purple keywords
        secondary: "{violet-80}",
        "on-secondary": "{violet-20}",
        "secondary-container": "{violet-30}",
        "on-secondary-container": "{violet-90}",
        "secondary-fixed": "{violet-90}",
        "secondary-fixed-dim": "{violet-80}",
        "on-secondary-fixed": "{violet-10}",
        "on-secondary-fixed-variant": "{violet-30}",
        // Tertiary — cyan: operators, regex
        tertiary: "{cyan-80}",
        "on-tertiary": "{cyan-20}",
        "tertiary-container": "{cyan-30}",
        "on-tertiary-container": "{cyan-90}",
        "tertiary-fixed": "{cyan-90}",
        "tertiary-fixed-dim": "{cyan-80}",
        "on-tertiary-fixed": "{cyan-10}",
        "on-tertiary-fixed-variant": "{cyan-30}",
        // Error — red
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — warm blue-gray darks (#282c34 territory)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{gray-30}",
        "on-surface-variant": "{slate-80}",
        "surface-tint": "{blue-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines
        outline: "{slate-60}",
        "outline-variant": "{gray-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{blue-22}",
        "primary-container": "{blue-50}",
        "on-primary-container": "{blue-100}",
        secondary: "{violet-22}",
        "secondary-container": "{violet-50}",
        "on-secondary-container": "{violet-100}",
        tertiary: "{cyan-22}",
        "tertiary-container": "{cyan-50}",
        "on-tertiary-container": "{cyan-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{slate-22}",
        outline: "{slate-35}",
        "outline-variant": "{slate-50}",
      },
      "light-high-contrast": {
        primary: "{blue-17}",
        "primary-container": "{blue-30}",
        "on-primary-container": "{blue-100}",
        secondary: "{violet-17}",
        "secondary-container": "{violet-30}",
        "on-secondary-container": "{violet-100}",
        tertiary: "{cyan-17}",
        "tertiary-container": "{cyan-30}",
        "on-tertiary-container": "{cyan-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{slate-0}",
        outline: "{slate-17}",
        "outline-variant": "{slate-30}",
      },
      "dark-medium-contrast": {
        primary: "{blue-87}",
        "on-primary": "{blue-17}",
        "primary-container": "{blue-60}",
        "on-primary-container": "{blue-0}",
        "inverse-primary": "{blue-30}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        "surface-tint": "{blue-80}",
        secondary: "{violet-87}",
        "on-secondary": "{violet-17}",
        "secondary-container": "{violet-60}",
        "on-secondary-container": "{violet-0}",
        "secondary-fixed": "{violet-90}",
        "secondary-fixed-dim": "{violet-80}",
        "on-secondary-fixed": "{violet-10}",
        "on-secondary-fixed-variant": "{violet-30}",
        tertiary: "{cyan-87}",
        "on-tertiary": "{cyan-17}",
        "tertiary-container": "{cyan-60}",
        "on-tertiary-container": "{cyan-0}",
        "tertiary-fixed": "{cyan-90}",
        "tertiary-fixed-dim": "{cyan-80}",
        "on-tertiary-fixed": "{cyan-10}",
        "on-tertiary-fixed-variant": "{cyan-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-87}",
        outline: "{slate-70}",
        "outline-variant": "{slate-60}",
      },
      "dark-high-contrast": {
        primary: "{blue-95}",
        "on-primary": "{blue-0}",
        "primary-container": "{blue-80}",
        "on-primary-container": "{blue-4}",
        "inverse-primary": "{blue-30}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        "surface-tint": "{blue-80}",
        secondary: "{violet-95}",
        "on-secondary": "{violet-0}",
        "secondary-container": "{violet-80}",
        "on-secondary-container": "{violet-4}",
        "secondary-fixed": "{violet-90}",
        "secondary-fixed-dim": "{violet-80}",
        "on-secondary-fixed": "{violet-10}",
        "on-secondary-fixed-variant": "{violet-30}",
        tertiary: "{cyan-95}",
        "on-tertiary": "{cyan-0}",
        "tertiary-container": "{cyan-80}",
        "on-tertiary-container": "{cyan-4}",
        "tertiary-fixed": "{cyan-90}",
        "tertiary-fixed-dim": "{cyan-80}",
        "on-tertiary-fixed": "{cyan-10}",
        "on-tertiary-fixed-variant": "{cyan-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-100}",
        outline: "{slate-95}",
        "outline-variant": "{slate-80}",
      },
    },
  },
  order: ["color"],
});
