import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Material Palenight theme — M3 token variant.
 */
export default preset.define({
  id: "palenight",
  name: "Material Palenight",
  tokens: {
    // Chromatic palettes — Material Theme Palenight syntax colors
    ...createM3ColorTokens("red", "#FF5370"),
    ...createM3ColorTokens("orange", "#F78C6C"),
    ...createM3ColorTokens("amber", "#FFCB6B"),
    ...createM3ColorTokens("yellow", "#FFCB6B"),
    ...createM3ColorTokens("lime", "#C3E88D"),
    ...createM3ColorTokens("green", "#C3E88D"),
    ...createM3ColorTokens("emerald", "#80CBC4"),
    ...createM3ColorTokens("teal", "#80CBC4"),
    ...createM3ColorTokens("cyan", "#89DDFF"),
    ...createM3ColorTokens("sky", "#89DDFF"),
    ...createM3ColorTokens("blue", "#82AAFF"),
    ...createM3ColorTokens("indigo", "#82AAFF"),
    ...createM3ColorTokens("violet", "#C792EA"),
    ...createM3ColorTokens("purple", "#BB80B3"),
    ...createM3ColorTokens("fuchsia", "#C792EA"),
    ...createM3ColorTokens("pink", "#F07178"),
    ...createM3ColorTokens("rose", "#FF5370"),
    // Neutral palettes — cool purple-blue tinted
    ...createM3ColorTokens("slate", "#676E95"),
    ...createM3ColorTokens("gray", "#4E5579"),
    ...createM3ColorTokens("zinc", "#303348"),
    ...createM3ColorTokens("neutral", "#292D3E"),
    ...createM3ColorTokens("stone", "#515772"),
    // Semantic roles — default to the light scheme
    // Primary — violet: THE palenight color (keywords, purple accent)
    primary: "{violet-40}",
    "on-primary": "{violet-100}",
    "primary-container": "{violet-90}",
    "on-primary-container": "{violet-10}",
    "inverse-primary": "{violet-80}",
    "primary-fixed": "{violet-90}",
    "primary-fixed-dim": "{violet-80}",
    "on-primary-fixed": "{violet-10}",
    "on-primary-fixed-variant": "{violet-30}",
    // Secondary — blue: functions, methods
    secondary: "{blue-40}",
    "on-secondary": "{blue-100}",
    "secondary-container": "{blue-90}",
    "on-secondary-container": "{blue-10}",
    "secondary-fixed": "{blue-90}",
    "secondary-fixed-dim": "{blue-80}",
    "on-secondary-fixed": "{blue-10}",
    "on-secondary-fixed-variant": "{blue-30}",
    // Tertiary — cyan: operators, types
    tertiary: "{cyan-40}",
    "on-tertiary": "{cyan-100}",
    "tertiary-container": "{cyan-90}",
    "on-tertiary-container": "{cyan-10}",
    "tertiary-fixed": "{cyan-90}",
    "tertiary-fixed-dim": "{cyan-80}",
    "on-tertiary-fixed": "{cyan-10}",
    "on-tertiary-fixed-variant": "{cyan-30}",
    // Error — red
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — cool purple-blue tinted
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{slate-90}",
    "on-surface-variant": "{slate-30}",
    "surface-tint": "{violet-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines
    outline: "{slate-50}",
    "outline-variant": "{slate-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — violet: soft purple keywords on blue-purple dark
        primary: "{violet-80}",
        "on-primary": "{violet-20}",
        "primary-container": "{violet-30}",
        "on-primary-container": "{violet-90}",
        "inverse-primary": "{violet-40}",
        "primary-fixed": "{violet-90}",
        "primary-fixed-dim": "{violet-80}",
        "on-primary-fixed": "{violet-10}",
        "on-primary-fixed-variant": "{violet-30}",
        // Secondary — blue: bright function blue
        secondary: "{blue-80}",
        "on-secondary": "{blue-20}",
        "secondary-container": "{blue-30}",
        "on-secondary-container": "{blue-90}",
        "secondary-fixed": "{blue-90}",
        "secondary-fixed-dim": "{blue-80}",
        "on-secondary-fixed": "{blue-10}",
        "on-secondary-fixed-variant": "{blue-30}",
        // Tertiary — cyan: operators, decorators
        tertiary: "{cyan-80}",
        "on-tertiary": "{cyan-20}",
        "tertiary-container": "{cyan-30}",
        "on-tertiary-container": "{cyan-90}",
        "tertiary-fixed": "{cyan-90}",
        "tertiary-fixed-dim": "{cyan-80}",
        "on-tertiary-fixed": "{cyan-10}",
        "on-tertiary-fixed-variant": "{cyan-30}",
        // Error — red
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — blue-purple tinted darks (#292D3E)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{gray-30}",
        "on-surface-variant": "{slate-80}",
        "surface-tint": "{violet-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — muted purple-blue
        outline: "{slate-60}",
        "outline-variant": "{gray-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{violet-22}",
        "primary-container": "{violet-50}",
        "on-primary-container": "{violet-100}",
        secondary: "{blue-22}",
        "secondary-container": "{blue-50}",
        "on-secondary-container": "{blue-100}",
        tertiary: "{cyan-22}",
        "tertiary-container": "{cyan-50}",
        "on-tertiary-container": "{cyan-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{slate-22}",
        outline: "{slate-35}",
        "outline-variant": "{slate-50}",
      },
      "light-high-contrast": {
        primary: "{violet-17}",
        "primary-container": "{violet-30}",
        "on-primary-container": "{violet-100}",
        secondary: "{blue-17}",
        "secondary-container": "{blue-30}",
        "on-secondary-container": "{blue-100}",
        tertiary: "{cyan-17}",
        "tertiary-container": "{cyan-30}",
        "on-tertiary-container": "{cyan-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{slate-0}",
        outline: "{slate-17}",
        "outline-variant": "{slate-30}",
      },
      "dark-medium-contrast": {
        primary: "{violet-87}",
        "on-primary": "{violet-17}",
        "primary-container": "{violet-60}",
        "on-primary-container": "{violet-0}",
        "inverse-primary": "{violet-30}",
        "primary-fixed": "{violet-90}",
        "primary-fixed-dim": "{violet-80}",
        "on-primary-fixed": "{violet-10}",
        "on-primary-fixed-variant": "{violet-30}",
        "surface-tint": "{violet-80}",
        secondary: "{blue-87}",
        "on-secondary": "{blue-17}",
        "secondary-container": "{blue-60}",
        "on-secondary-container": "{blue-0}",
        "secondary-fixed": "{blue-90}",
        "secondary-fixed-dim": "{blue-80}",
        "on-secondary-fixed": "{blue-10}",
        "on-secondary-fixed-variant": "{blue-30}",
        tertiary: "{cyan-87}",
        "on-tertiary": "{cyan-17}",
        "tertiary-container": "{cyan-60}",
        "on-tertiary-container": "{cyan-0}",
        "tertiary-fixed": "{cyan-90}",
        "tertiary-fixed-dim": "{cyan-80}",
        "on-tertiary-fixed": "{cyan-10}",
        "on-tertiary-fixed-variant": "{cyan-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-87}",
        outline: "{slate-70}",
        "outline-variant": "{slate-60}",
      },
      "dark-high-contrast": {
        primary: "{violet-95}",
        "on-primary": "{violet-0}",
        "primary-container": "{violet-80}",
        "on-primary-container": "{violet-4}",
        "inverse-primary": "{violet-30}",
        "primary-fixed": "{violet-90}",
        "primary-fixed-dim": "{violet-80}",
        "on-primary-fixed": "{violet-10}",
        "on-primary-fixed-variant": "{violet-30}",
        "surface-tint": "{violet-80}",
        secondary: "{blue-95}",
        "on-secondary": "{blue-0}",
        "secondary-container": "{blue-80}",
        "on-secondary-container": "{blue-4}",
        "secondary-fixed": "{blue-90}",
        "secondary-fixed-dim": "{blue-80}",
        "on-secondary-fixed": "{blue-10}",
        "on-secondary-fixed-variant": "{blue-30}",
        tertiary: "{cyan-95}",
        "on-tertiary": "{cyan-0}",
        "tertiary-container": "{cyan-80}",
        "on-tertiary-container": "{cyan-4}",
        "tertiary-fixed": "{cyan-90}",
        "tertiary-fixed-dim": "{cyan-80}",
        "on-tertiary-fixed": "{cyan-10}",
        "on-tertiary-fixed-variant": "{cyan-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-100}",
        outline: "{slate-95}",
        "outline-variant": "{slate-80}",
      },
    },
  },
  order: ["color"],
});
