import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Rosé Pine theme — M3 token variant.
 */
export default preset.define({
  id: "rose_pine",
  name: "Rosé Pine",
  reference: {
    // Chromatic palettes — Rosé Pine's 6 soft, desaturated accents
    ...createM3ColorTokens("red", "#eb6f92"),
    ...createM3ColorTokens("orange", "#f6c177"),
    ...createM3ColorTokens("amber", "#f6c177"),
    ...createM3ColorTokens("yellow", "#f6c177"),
    ...createM3ColorTokens("lime", "#9ccfd8"),
    ...createM3ColorTokens("green", "#9ccfd8"),
    ...createM3ColorTokens("emerald", "#31748f"),
    ...createM3ColorTokens("teal", "#31748f"),
    ...createM3ColorTokens("cyan", "#9ccfd8"),
    ...createM3ColorTokens("sky", "#9ccfd8"),
    ...createM3ColorTokens("blue", "#31748f"),
    ...createM3ColorTokens("indigo", "#31748f"),
    ...createM3ColorTokens("violet", "#c4a7e7"),
    ...createM3ColorTokens("purple", "#c4a7e7"),
    ...createM3ColorTokens("fuchsia", "#eb6f92"),
    ...createM3ColorTokens("pink", "#ebbcba"),
    ...createM3ColorTokens("rose", "#ebbcba"),
    // Neutral palettes — deep purple-tinted
    ...createM3ColorTokens("slate", "#524f67"),
    ...createM3ColorTokens("gray", "#6e6a86"),
    ...createM3ColorTokens("zinc", "#403d52"),
    ...createM3ColorTokens("neutral", "#191724"),
    ...createM3ColorTokens("stone", "#908caa"),
  },
  system: {
    light: {
      // Primary — violet (Iris): the brand purple
      primary: "violet-40",
      "on-primary": "violet-100",
      "primary-container": "violet-90",
      "on-primary-container": "violet-10",
      "inverse-primary": "violet-80",
      "primary-fixed": "violet-90",
      "primary-fixed-dim": "violet-80",
      "on-primary-fixed": "violet-10",
      "on-primary-fixed-variant": "violet-30",
      // Secondary — cyan (Foam): cool teal counterpoint
      secondary: "cyan-40",
      "on-secondary": "cyan-100",
      "secondary-container": "cyan-90",
      "on-secondary-container": "cyan-10",
      "secondary-fixed": "cyan-90",
      "secondary-fixed-dim": "cyan-80",
      "on-secondary-fixed": "cyan-10",
      "on-secondary-fixed-variant": "cyan-30",
      // Tertiary — pink (Rose): the namesake soft salmon
      tertiary: "pink-40",
      "on-tertiary": "pink-100",
      "tertiary-container": "pink-90",
      "on-tertiary-container": "pink-10",
      "tertiary-fixed": "pink-90",
      "tertiary-fixed-dim": "pink-80",
      "on-tertiary-fixed": "pink-10",
      "on-tertiary-fixed-variant": "pink-30",
      // Error — red (Love)
      error: "red-40",
      "on-error": "red-100",
      "error-container": "red-90",
      "on-error-container": "red-10",
      // Surfaces — warm purple-tinted (Dawn-inspired)
      surface: "neutral-98",
      "on-surface": "neutral-10",
      "surface-dim": "neutral-87",
      "surface-bright": "neutral-98",
      "surface-container-lowest": "neutral-100",
      "surface-container-low": "neutral-96",
      "surface-container": "neutral-94",
      "surface-container-high": "neutral-92",
      "surface-container-highest": "neutral-90",
      "surface-variant": "slate-90",
      "on-surface-variant": "slate-30",
      "surface-tint": "violet-40",
      "inverse-surface": "neutral-20",
      "inverse-on-surface": "neutral-95",
      background: "neutral-98",
      "on-background": "neutral-10",
      // Outlines — muted purple-gray
      outline: "gray-50",
      "outline-variant": "slate-80",
      shadow: "neutral-0",
      scrim: "neutral-0",
    },
    dark: {
      // Primary — violet (Iris): soft lavender on dark
      primary: "violet-80",
      "on-primary": "violet-20",
      "primary-container": "violet-30",
      "on-primary-container": "violet-90",
      "inverse-primary": "violet-40",
      "primary-fixed": "violet-90",
      "primary-fixed-dim": "violet-80",
      "on-primary-fixed": "violet-10",
      "on-primary-fixed-variant": "violet-30",
      // Secondary — cyan (Foam): light teal on dark
      secondary: "cyan-80",
      "on-secondary": "cyan-20",
      "secondary-container": "cyan-30",
      "on-secondary-container": "cyan-90",
      "secondary-fixed": "cyan-90",
      "secondary-fixed-dim": "cyan-80",
      "on-secondary-fixed": "cyan-10",
      "on-secondary-fixed-variant": "cyan-30",
      // Tertiary — pink (Rose): soft salmon warmth
      tertiary: "pink-80",
      "on-tertiary": "pink-20",
      "tertiary-container": "pink-30",
      "on-tertiary-container": "pink-90",
      "tertiary-fixed": "pink-90",
      "tertiary-fixed-dim": "pink-80",
      "on-tertiary-fixed": "pink-10",
      "on-tertiary-fixed-variant": "pink-30",
      // Error — red (Love)
      error: "red-80",
      "on-error": "red-20",
      "error-container": "red-30",
      "on-error-container": "red-90",
      // Surfaces — deep purple-tinted darks
      surface: "neutral-6",
      "on-surface": "neutral-90",
      "surface-dim": "neutral-6",
      "surface-bright": "neutral-24",
      "surface-container-lowest": "neutral-4",
      "surface-container-low": "neutral-10",
      "surface-container": "neutral-12",
      "surface-container-high": "neutral-17",
      "surface-container-highest": "neutral-22",
      "surface-variant": "slate-30",
      "on-surface-variant": "slate-80",
      "surface-tint": "violet-80",
      "inverse-surface": "neutral-90",
      "inverse-on-surface": "neutral-20",
      background: "neutral-6",
      "on-background": "neutral-90",
      // Outlines — muted purple-gray
      outline: "gray-60",
      "outline-variant": "slate-30",
      shadow: "neutral-0",
      scrim: "neutral-0",
    },
  },
  roles: {},
});
