import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Solarized theme — M3 token variant.
 */
export default preset.define({
  id: "solarized",
  name: "Solarized",
  tokens: {
    // Chromatic palettes — Solarized's 8 precisely engineered accents
    ...createM3ColorTokens("red", "#dc322f"),
    ...createM3ColorTokens("orange", "#cb4b16"),
    ...createM3ColorTokens("amber", "#b58900"),
    ...createM3ColorTokens("yellow", "#b58900"),
    ...createM3ColorTokens("lime", "#859900"),
    ...createM3ColorTokens("green", "#859900"),
    ...createM3ColorTokens("emerald", "#2aa198"),
    ...createM3ColorTokens("teal", "#2aa198"),
    ...createM3ColorTokens("cyan", "#2aa198"),
    ...createM3ColorTokens("sky", "#268bd2"),
    ...createM3ColorTokens("blue", "#268bd2"),
    ...createM3ColorTokens("indigo", "#268bd2"),
    ...createM3ColorTokens("violet", "#6c71c4"),
    ...createM3ColorTokens("purple", "#6c71c4"),
    ...createM3ColorTokens("fuchsia", "#d33682"),
    ...createM3ColorTokens("pink", "#d33682"),
    ...createM3ColorTokens("rose", "#dc322f"),
    // Neutral palettes — Solarized's unique blue-gray monotones
    ...createM3ColorTokens("slate", "#586e75"),
    ...createM3ColorTokens("gray", "#657b83"),
    ...createM3ColorTokens("zinc", "#586e75"),
    ...createM3ColorTokens("neutral", "#002b36"),
    ...createM3ColorTokens("stone", "#93a1a1"),
    // Semantic roles — default to the light scheme
    // Primary — blue: the workhorse accent in Solarized
    primary: "{blue-40}",
    "on-primary": "{blue-100}",
    "primary-container": "{blue-90}",
    "on-primary-container": "{blue-10}",
    "inverse-primary": "{blue-80}",
    "primary-fixed": "{blue-90}",
    "primary-fixed-dim": "{blue-80}",
    "on-primary-fixed": "{blue-10}",
    "on-primary-fixed-variant": "{blue-30}",
    // Secondary — cyan: links, constants
    secondary: "{cyan-40}",
    "on-secondary": "{cyan-100}",
    "secondary-container": "{cyan-90}",
    "on-secondary-container": "{cyan-10}",
    "secondary-fixed": "{cyan-90}",
    "secondary-fixed-dim": "{cyan-80}",
    "on-secondary-fixed": "{cyan-10}",
    "on-secondary-fixed-variant": "{cyan-30}",
    // Tertiary — violet: keywords, special
    tertiary: "{violet-40}",
    "on-tertiary": "{violet-100}",
    "tertiary-container": "{violet-90}",
    "on-tertiary-container": "{violet-10}",
    "tertiary-fixed": "{violet-90}",
    "tertiary-fixed-dim": "{violet-80}",
    "on-tertiary-fixed": "{violet-10}",
    "on-tertiary-fixed-variant": "{violet-30}",
    // Error — red
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — Solarized light uses base3 #fdf6e3 (warm cream)
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{slate-90}",
    "on-surface-variant": "{slate-30}",
    "surface-tint": "{blue-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines — the distinctive Solarized blue-gray
    outline: "{slate-50}",
    "outline-variant": "{slate-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — blue: bright blue on dark teal background
        primary: "{blue-80}",
        "on-primary": "{blue-20}",
        "primary-container": "{blue-30}",
        "on-primary-container": "{blue-90}",
        "inverse-primary": "{blue-40}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        // Secondary — cyan
        secondary: "{cyan-80}",
        "on-secondary": "{cyan-20}",
        "secondary-container": "{cyan-30}",
        "on-secondary-container": "{cyan-90}",
        "secondary-fixed": "{cyan-90}",
        "secondary-fixed-dim": "{cyan-80}",
        "on-secondary-fixed": "{cyan-10}",
        "on-secondary-fixed-variant": "{cyan-30}",
        // Tertiary — violet
        tertiary: "{violet-80}",
        "on-tertiary": "{violet-20}",
        "tertiary-container": "{violet-30}",
        "on-tertiary-container": "{violet-90}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        // Error — red
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — Solarized dark uses base03 #002b36 (deep teal-blue)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-80}",
        "surface-tint": "{blue-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines
        outline: "{gray-60}",
        "outline-variant": "{slate-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{blue-22}",
        "primary-container": "{blue-50}",
        "on-primary-container": "{blue-100}",
        secondary: "{cyan-22}",
        "secondary-container": "{cyan-50}",
        "on-secondary-container": "{cyan-100}",
        tertiary: "{violet-22}",
        "tertiary-container": "{violet-50}",
        "on-tertiary-container": "{violet-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{slate-22}",
        outline: "{slate-35}",
        "outline-variant": "{slate-50}",
      },
      "light-high-contrast": {
        primary: "{blue-17}",
        "primary-container": "{blue-30}",
        "on-primary-container": "{blue-100}",
        secondary: "{cyan-17}",
        "secondary-container": "{cyan-30}",
        "on-secondary-container": "{cyan-100}",
        tertiary: "{violet-17}",
        "tertiary-container": "{violet-30}",
        "on-tertiary-container": "{violet-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{slate-0}",
        outline: "{slate-17}",
        "outline-variant": "{slate-30}",
      },
      "dark-medium-contrast": {
        primary: "{blue-87}",
        "on-primary": "{blue-17}",
        "primary-container": "{blue-60}",
        "on-primary-container": "{blue-0}",
        "inverse-primary": "{blue-30}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        "surface-tint": "{blue-80}",
        secondary: "{cyan-87}",
        "on-secondary": "{cyan-17}",
        "secondary-container": "{cyan-60}",
        "on-secondary-container": "{cyan-0}",
        "secondary-fixed": "{cyan-90}",
        "secondary-fixed-dim": "{cyan-80}",
        "on-secondary-fixed": "{cyan-10}",
        "on-secondary-fixed-variant": "{cyan-30}",
        tertiary: "{violet-87}",
        "on-tertiary": "{violet-17}",
        "tertiary-container": "{violet-60}",
        "on-tertiary-container": "{violet-0}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-87}",
        outline: "{slate-70}",
        "outline-variant": "{slate-60}",
      },
      "dark-high-contrast": {
        primary: "{blue-95}",
        "on-primary": "{blue-0}",
        "primary-container": "{blue-80}",
        "on-primary-container": "{blue-4}",
        "inverse-primary": "{blue-30}",
        "primary-fixed": "{blue-90}",
        "primary-fixed-dim": "{blue-80}",
        "on-primary-fixed": "{blue-10}",
        "on-primary-fixed-variant": "{blue-30}",
        "surface-tint": "{blue-80}",
        secondary: "{cyan-95}",
        "on-secondary": "{cyan-0}",
        "secondary-container": "{cyan-80}",
        "on-secondary-container": "{cyan-4}",
        "secondary-fixed": "{cyan-90}",
        "secondary-fixed-dim": "{cyan-80}",
        "on-secondary-fixed": "{cyan-10}",
        "on-secondary-fixed-variant": "{cyan-30}",
        tertiary: "{violet-95}",
        "on-tertiary": "{violet-0}",
        "tertiary-container": "{violet-80}",
        "on-tertiary-container": "{violet-4}",
        "tertiary-fixed": "{violet-90}",
        "tertiary-fixed-dim": "{violet-80}",
        "on-tertiary-fixed": "{violet-10}",
        "on-tertiary-fixed-variant": "{violet-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-100}",
        outline: "{slate-95}",
        "outline-variant": "{slate-80}",
      },
    },
  },
  order: ["color"],
});
