import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Synthwave '84 theme — M3 token variant.
 */
export default preset.define({
  id: "synthwave",
  name: "Synthwave '84",
  tokens: {
    // Chromatic palettes — neon retro aesthetics
    ...createM3ColorTokens("red", "#fe4450"),
    ...createM3ColorTokens("orange", "#ff8b39"),
    ...createM3ColorTokens("amber", "#fede5d"),
    ...createM3ColorTokens("yellow", "#fede5d"),
    ...createM3ColorTokens("lime", "#72f1b8"),
    ...createM3ColorTokens("green", "#72f1b8"),
    ...createM3ColorTokens("emerald", "#72f1b8"),
    ...createM3ColorTokens("teal", "#36f9f6"),
    ...createM3ColorTokens("cyan", "#36f9f6"),
    ...createM3ColorTokens("sky", "#03edf9"),
    ...createM3ColorTokens("blue", "#03edf9"),
    ...createM3ColorTokens("indigo", "#495495"),
    ...createM3ColorTokens("violet", "#614D85"),
    ...createM3ColorTokens("purple", "#614D85"),
    ...createM3ColorTokens("fuchsia", "#ff7edb"),
    ...createM3ColorTokens("pink", "#fc28a8"),
    ...createM3ColorTokens("rose", "#fe4450"),
    // Neutral palettes — deep purple atmosphere
    ...createM3ColorTokens("slate", "#848bbd"),
    ...createM3ColorTokens("gray", "#848bbd"),
    ...createM3ColorTokens("zinc", "#2a2139"),
    ...createM3ColorTokens("neutral", "#262335"),
    ...createM3ColorTokens("stone", "#b6b1b1"),
    // Semantic roles — default to the light scheme
    // Primary — fuchsia: neon magenta, THE synthwave identity
    primary: "{fuchsia-40}",
    "on-primary": "{fuchsia-100}",
    "primary-container": "{fuchsia-90}",
    "on-primary-container": "{fuchsia-10}",
    "inverse-primary": "{fuchsia-80}",
    "primary-fixed": "{fuchsia-90}",
    "primary-fixed-dim": "{fuchsia-80}",
    "on-primary-fixed": "{fuchsia-10}",
    "on-primary-fixed-variant": "{fuchsia-30}",
    // Secondary — cyan: neon teal functions
    secondary: "{cyan-40}",
    "on-secondary": "{cyan-100}",
    "secondary-container": "{cyan-90}",
    "on-secondary-container": "{cyan-10}",
    "secondary-fixed": "{cyan-90}",
    "secondary-fixed-dim": "{cyan-80}",
    "on-secondary-fixed": "{cyan-10}",
    "on-secondary-fixed-variant": "{cyan-30}",
    // Tertiary — yellow: bright keywords
    tertiary: "{yellow-40}",
    "on-tertiary": "{yellow-100}",
    "tertiary-container": "{yellow-90}",
    "on-tertiary-container": "{yellow-10}",
    "tertiary-fixed": "{yellow-90}",
    "tertiary-fixed-dim": "{yellow-80}",
    "on-tertiary-fixed": "{yellow-10}",
    "on-tertiary-fixed-variant": "{yellow-30}",
    // Error — red
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-10}",
    // Surfaces — purple-tinted
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{slate-90}",
    "on-surface-variant": "{slate-30}",
    "surface-tint": "{fuchsia-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    // Outlines
    outline: "{slate-50}",
    "outline-variant": "{slate-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        // Primary — fuchsia: neon pink/magenta glow
        primary: "{fuchsia-80}",
        "on-primary": "{fuchsia-20}",
        "primary-container": "{fuchsia-30}",
        "on-primary-container": "{fuchsia-90}",
        "inverse-primary": "{fuchsia-40}",
        "primary-fixed": "{fuchsia-90}",
        "primary-fixed-dim": "{fuchsia-80}",
        "on-primary-fixed": "{fuchsia-10}",
        "on-primary-fixed-variant": "{fuchsia-30}",
        // Secondary — cyan: neon teal
        secondary: "{cyan-80}",
        "on-secondary": "{cyan-20}",
        "secondary-container": "{cyan-30}",
        "on-secondary-container": "{cyan-90}",
        "secondary-fixed": "{cyan-90}",
        "secondary-fixed-dim": "{cyan-80}",
        "on-secondary-fixed": "{cyan-10}",
        "on-secondary-fixed-variant": "{cyan-30}",
        // Tertiary — yellow: neon yellow keywords
        tertiary: "{yellow-80}",
        "on-tertiary": "{yellow-20}",
        "tertiary-container": "{yellow-30}",
        "on-tertiary-container": "{yellow-90}",
        "tertiary-fixed": "{yellow-90}",
        "tertiary-fixed-dim": "{yellow-80}",
        "on-tertiary-fixed": "{yellow-10}",
        "on-tertiary-fixed-variant": "{yellow-30}",
        // Error — red
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        // Surfaces — deep purple atmosphere (#262335)
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{slate-80}",
        "surface-tint": "{fuchsia-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        // Outlines — muted purple
        outline: "{slate-60}",
        "outline-variant": "{zinc-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{fuchsia-22}",
        "primary-container": "{fuchsia-50}",
        "on-primary-container": "{fuchsia-100}",
        secondary: "{cyan-22}",
        "secondary-container": "{cyan-50}",
        "on-secondary-container": "{cyan-100}",
        tertiary: "{yellow-22}",
        "tertiary-container": "{yellow-50}",
        "on-tertiary-container": "{yellow-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{slate-22}",
        outline: "{slate-35}",
        "outline-variant": "{slate-50}",
      },
      "light-high-contrast": {
        primary: "{fuchsia-17}",
        "primary-container": "{fuchsia-30}",
        "on-primary-container": "{fuchsia-100}",
        secondary: "{cyan-17}",
        "secondary-container": "{cyan-30}",
        "on-secondary-container": "{cyan-100}",
        tertiary: "{yellow-17}",
        "tertiary-container": "{yellow-30}",
        "on-tertiary-container": "{yellow-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{slate-0}",
        outline: "{slate-17}",
        "outline-variant": "{slate-30}",
      },
      "dark-medium-contrast": {
        primary: "{fuchsia-87}",
        "on-primary": "{fuchsia-17}",
        "primary-container": "{fuchsia-60}",
        "on-primary-container": "{fuchsia-0}",
        "inverse-primary": "{fuchsia-30}",
        "primary-fixed": "{fuchsia-90}",
        "primary-fixed-dim": "{fuchsia-80}",
        "on-primary-fixed": "{fuchsia-10}",
        "on-primary-fixed-variant": "{fuchsia-30}",
        "surface-tint": "{fuchsia-80}",
        secondary: "{cyan-87}",
        "on-secondary": "{cyan-17}",
        "secondary-container": "{cyan-60}",
        "on-secondary-container": "{cyan-0}",
        "secondary-fixed": "{cyan-90}",
        "secondary-fixed-dim": "{cyan-80}",
        "on-secondary-fixed": "{cyan-10}",
        "on-secondary-fixed-variant": "{cyan-30}",
        tertiary: "{yellow-87}",
        "on-tertiary": "{yellow-17}",
        "tertiary-container": "{yellow-60}",
        "on-tertiary-container": "{yellow-0}",
        "tertiary-fixed": "{yellow-90}",
        "tertiary-fixed-dim": "{yellow-80}",
        "on-tertiary-fixed": "{yellow-10}",
        "on-tertiary-fixed-variant": "{yellow-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-87}",
        outline: "{slate-70}",
        "outline-variant": "{slate-60}",
      },
      "dark-high-contrast": {
        primary: "{fuchsia-95}",
        "on-primary": "{fuchsia-0}",
        "primary-container": "{fuchsia-80}",
        "on-primary-container": "{fuchsia-4}",
        "inverse-primary": "{fuchsia-30}",
        "primary-fixed": "{fuchsia-90}",
        "primary-fixed-dim": "{fuchsia-80}",
        "on-primary-fixed": "{fuchsia-10}",
        "on-primary-fixed-variant": "{fuchsia-30}",
        "surface-tint": "{fuchsia-80}",
        secondary: "{cyan-95}",
        "on-secondary": "{cyan-0}",
        "secondary-container": "{cyan-80}",
        "on-secondary-container": "{cyan-4}",
        "secondary-fixed": "{cyan-90}",
        "secondary-fixed-dim": "{cyan-80}",
        "on-secondary-fixed": "{cyan-10}",
        "on-secondary-fixed-variant": "{cyan-30}",
        tertiary: "{yellow-95}",
        "on-tertiary": "{yellow-0}",
        "tertiary-container": "{yellow-80}",
        "on-tertiary-container": "{yellow-4}",
        "tertiary-fixed": "{yellow-90}",
        "tertiary-fixed-dim": "{yellow-80}",
        "on-tertiary-fixed": "{yellow-10}",
        "on-tertiary-fixed-variant": "{yellow-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{slate-30}",
        "on-surface-variant": "{slate-100}",
        outline: "{slate-95}",
        "outline-variant": "{slate-80}",
      },
    },
  },
  order: ["color"],
});
