import preset from "../preset";
import { createM3ColorTokens } from "../colors";

/**
 * Vesper theme — M3 token variant.
 */
export default preset.define({
  id: "vesper",
  name: "Vesper",
  reference: {
    // Chromatic palettes — Vesper's extremely minimal 3-color palette
    // Only peach (#FFC799), mint (#99FFE4), and salmon (#FF8080) exist
    ...createM3ColorTokens("red", "#FF8080"),
    ...createM3ColorTokens("orange", "#FFC799"),
    ...createM3ColorTokens("amber", "#FFC799"),
    ...createM3ColorTokens("yellow", "#FFC799"),
    ...createM3ColorTokens("lime", "#99FFE4"),
    ...createM3ColorTokens("green", "#99FFE4"),
    ...createM3ColorTokens("emerald", "#99FFE4"),
    ...createM3ColorTokens("teal", "#99FFE4"),
    ...createM3ColorTokens("cyan", "#99FFE4"),
    ...createM3ColorTokens("sky", "#99FFE4"),
    ...createM3ColorTokens("blue", "#99FFE4"),
    ...createM3ColorTokens("indigo", "#99FFE4"),
    ...createM3ColorTokens("violet", "#FFC799"),
    ...createM3ColorTokens("purple", "#FFC799"),
    ...createM3ColorTokens("fuchsia", "#FF8080"),
    ...createM3ColorTokens("pink", "#FF8080"),
    ...createM3ColorTokens("rose", "#FF8080"),
    // Neutral palettes — pure dark, nearly achromatic
    ...createM3ColorTokens("slate", "#A0A0A0"),
    ...createM3ColorTokens("gray", "#7E7E7E"),
    ...createM3ColorTokens("zinc", "#505050"),
    ...createM3ColorTokens("neutral", "#101010"),
    ...createM3ColorTokens("stone", "#8B8B8B"),
  },
  system: {
    light: {
      // Primary — orange (peach): THE vesper accent
      primary: "orange-40",
      "on-primary": "orange-100",
      "primary-container": "orange-90",
      "on-primary-container": "orange-10",
      "inverse-primary": "orange-80",
      "primary-fixed": "orange-90",
      "primary-fixed-dim": "orange-80",
      "on-primary-fixed": "orange-10",
      "on-primary-fixed-variant": "orange-30",
      // Secondary — green (mint): strings
      secondary: "green-40",
      "on-secondary": "green-100",
      "secondary-container": "green-90",
      "on-secondary-container": "green-10",
      "secondary-fixed": "green-90",
      "secondary-fixed-dim": "green-80",
      "on-secondary-fixed": "green-10",
      "on-secondary-fixed-variant": "green-30",
      // Tertiary — red (salmon): the third and final color
      tertiary: "red-40",
      "on-tertiary": "red-100",
      "tertiary-container": "red-90",
      "on-tertiary-container": "red-10",
      "tertiary-fixed": "red-90",
      "tertiary-fixed-dim": "red-80",
      "on-tertiary-fixed": "red-10",
      "on-tertiary-fixed-variant": "red-30",
      // Error — red (same palette, different role)
      error: "red-40",
      "on-error": "red-100",
      "error-container": "red-90",
      "on-error-container": "red-10",
      // Surfaces — clean, nearly achromatic
      surface: "neutral-98",
      "on-surface": "neutral-10",
      "surface-dim": "neutral-87",
      "surface-bright": "neutral-98",
      "surface-container-lowest": "neutral-100",
      "surface-container-low": "neutral-96",
      "surface-container": "neutral-94",
      "surface-container-high": "neutral-92",
      "surface-container-highest": "neutral-90",
      "surface-variant": "slate-90",
      "on-surface-variant": "slate-30",
      "surface-tint": "orange-40",
      "inverse-surface": "neutral-20",
      "inverse-on-surface": "neutral-95",
      background: "neutral-98",
      "on-background": "neutral-10",
      // Outlines
      outline: "gray-50",
      "outline-variant": "slate-80",
      shadow: "neutral-0",
      scrim: "neutral-0",
    },
    dark: {
      // Primary — orange (peach): warm accent on pure black
      primary: "orange-80",
      "on-primary": "orange-20",
      "primary-container": "orange-30",
      "on-primary-container": "orange-90",
      "inverse-primary": "orange-40",
      "primary-fixed": "orange-90",
      "primary-fixed-dim": "orange-80",
      "on-primary-fixed": "orange-10",
      "on-primary-fixed-variant": "orange-30",
      // Secondary — green (mint): strings
      secondary: "green-80",
      "on-secondary": "green-20",
      "secondary-container": "green-30",
      "on-secondary-container": "green-90",
      "secondary-fixed": "green-90",
      "secondary-fixed-dim": "green-80",
      "on-secondary-fixed": "green-10",
      "on-secondary-fixed-variant": "green-30",
      // Tertiary — red (salmon)
      tertiary: "red-80",
      "on-tertiary": "red-20",
      "tertiary-container": "red-30",
      "on-tertiary-container": "red-90",
      "tertiary-fixed": "red-90",
      "tertiary-fixed-dim": "red-80",
      "on-tertiary-fixed": "red-10",
      "on-tertiary-fixed-variant": "red-30",
      // Error — red
      error: "red-80",
      "on-error": "red-20",
      "error-container": "red-30",
      "on-error-container": "red-90",
      // Surfaces — near-black, minimal (#101010)
      surface: "neutral-6",
      "on-surface": "neutral-90",
      "surface-dim": "neutral-6",
      "surface-bright": "neutral-24",
      "surface-container-lowest": "neutral-4",
      "surface-container-low": "neutral-10",
      "surface-container": "neutral-12",
      "surface-container-high": "neutral-17",
      "surface-container-highest": "neutral-22",
      "surface-variant": "zinc-30",
      "on-surface-variant": "slate-80",
      "surface-tint": "orange-80",
      "inverse-surface": "neutral-90",
      "inverse-on-surface": "neutral-20",
      background: "neutral-6",
      "on-background": "neutral-90",
      // Outlines — minimal gray
      outline: "gray-60",
      "outline-variant": "zinc-30",
      shadow: "neutral-0",
      scrim: "neutral-0",
    },
  },
  roles: {},
});
