# Coverage on a pull request is informational.
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "condensed_header, diff, files"
  require_changes: true

# Coverage counts source files.
ignore:
  - "**/.dist"
  - "**/*.test.ts"
  - "**/test/**"
  - "examples/**"
