packages:
  - packages/untheme
  - packages/unocss-preset-untheme
  - packages/nuxt-untheme
  - examples/nuxt
catalog:
  "@nuxt/eslint-config": ^0.5.7
  "@nuxt/kit": ^3.13.2
  "@nuxt/schema": ^3.13.2
  "@nuxt/test-utils": ^3.14.3
  "@eslint/js": ^9.10.0
  "@types/eslint-config-prettier": ^6.11.3
  "@types/node": ^22.5.5
  "@vitest/coverage-v8": ^2.1.2
  changelogen: ^0.5.5
  eslint: ^9.12.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-prettier: ^5.2.1
  happy-dom: ^15.7.4
  nuxt: ^3.13.2
  prettier: ^3.3.3
  typescript: 5.5.4
  typescript-eslint: ^8.6.0
  unbuild: ^2.0.0
  vitest: ^2.1.2
  vue: ^3.5.12
