import { defineUnthemePreset } from "@untheme/kit";
import {
  tomato,
  tomatoDark,
  red,
  redDark,
  ruby,
  rubyDark,
  crimson,
  crimsonDark,
  pink,
  pinkDark,
  plum,
  plumDark,
  purple,
  purpleDark,
  violet,
  violetDark,
  iris,
  irisDark,
  indigo,
  indigoDark,
  blue,
  blueDark,
  cyan,
  cyanDark,
  teal,
  tealDark,
  jade,
  jadeDark,
  green,
  greenDark,
  grass,
  grassDark,
  brown,
  brownDark,
  orange,
  orangeDark,
  sky,
  skyDark,
  mint,
  mintDark,
  lime,
  limeDark,
  yellow,
  yellowDark,
  amber,
  amberDark,
  gold,
  goldDark,
  bronze,
  bronzeDark,
  gray,
  grayDark,
  mauve,
  mauveDark,
  slate,
  slateDark,
  sage,
  sageDark,
  olive,
  oliveDark,
  sand,
  sandDark,
} from "@radix-ui/colors";
import { createRadixColorTokens } from "./colors";

/**
 * The Radix UI preset.
 *
 * The base `tokens` map provides the full Radix Colors set — 31 scales (25
 * chromatic + 6 neutral), each as a light (`{scale}-{step}`) and dark
 * (`{scale}-dark-{step}`) 12-step palette — alongside Radix Themes radius,
 * spacing, typography, and shadow tokens, plus Radix's 12-step semantic roles
 * (accent and gray scales plus error, success, warning, and info status
 * colors) bound onto those palette tokens. The base defaults to the light
 * scheme; the `color` modifier's `dark` context remaps the roles onto the dark
 * scales.
 */
export const preset = defineUnthemePreset({
  id: "radix-ui",
  name: "Radix UI",
  tokens: {
    // Chromatic scales
    ...createRadixColorTokens("tomato", tomato, tomatoDark),
    ...createRadixColorTokens("red", red, redDark),
    ...createRadixColorTokens("ruby", ruby, rubyDark),
    ...createRadixColorTokens("crimson", crimson, crimsonDark),
    ...createRadixColorTokens("pink", pink, pinkDark),
    ...createRadixColorTokens("plum", plum, plumDark),
    ...createRadixColorTokens("purple", purple, purpleDark),
    ...createRadixColorTokens("violet", violet, violetDark),
    ...createRadixColorTokens("iris", iris, irisDark),
    ...createRadixColorTokens("indigo", indigo, indigoDark),
    ...createRadixColorTokens("blue", blue, blueDark),
    ...createRadixColorTokens("cyan", cyan, cyanDark),
    ...createRadixColorTokens("teal", teal, tealDark),
    ...createRadixColorTokens("jade", jade, jadeDark),
    ...createRadixColorTokens("green", green, greenDark),
    ...createRadixColorTokens("grass", grass, grassDark),
    ...createRadixColorTokens("brown", brown, brownDark),
    ...createRadixColorTokens("orange", orange, orangeDark),
    ...createRadixColorTokens("sky", sky, skyDark),
    ...createRadixColorTokens("mint", mint, mintDark),
    ...createRadixColorTokens("lime", lime, limeDark),
    ...createRadixColorTokens("yellow", yellow, yellowDark),
    ...createRadixColorTokens("amber", amber, amberDark),
    ...createRadixColorTokens("gold", gold, goldDark),
    ...createRadixColorTokens("bronze", bronze, bronzeDark),
    // Neutral scales
    ...createRadixColorTokens("gray", gray, grayDark),
    ...createRadixColorTokens("mauve", mauve, mauveDark),
    ...createRadixColorTokens("slate", slate, slateDark),
    ...createRadixColorTokens("sage", sage, sageDark),
    ...createRadixColorTokens("olive", olive, oliveDark),
    ...createRadixColorTokens("sand", sand, sandDark),
    // Pure tones — solid fills resolve their on-color contrast here
    white: "#ffffff",
    black: "#000000",
    // Radius
    "radius-1": "3px",
    "radius-2": "4px",
    "radius-3": "6px",
    "radius-4": "8px",
    "radius-5": "12px",
    "radius-6": "16px",
    "radius-full": "9999px",
    // Spacing
    "space-1": "4px",
    "space-2": "8px",
    "space-3": "12px",
    "space-4": "16px",
    "space-5": "24px",
    "space-6": "32px",
    "space-7": "40px",
    "space-8": "48px",
    "space-9": "64px",
    // Typography — font families
    "font-sans":
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    "font-mono": "'Menlo', 'Consolas', 'Roboto Mono', 'Courier New', monospace",
    // Typography — font sizes
    "font-size-1": "12px",
    "font-size-2": "14px",
    "font-size-3": "16px",
    "font-size-4": "18px",
    "font-size-5": "20px",
    "font-size-6": "24px",
    "font-size-7": "28px",
    "font-size-8": "35px",
    "font-size-9": "60px",
    // Typography — line heights
    "line-height-1": "16px",
    "line-height-2": "20px",
    "line-height-3": "24px",
    "line-height-4": "26px",
    "line-height-5": "28px",
    "line-height-6": "30px",
    "line-height-7": "36px",
    "line-height-8": "40px",
    "line-height-9": "60px",
    // Typography — letter spacing
    "letter-spacing-1": "0.0025em",
    "letter-spacing-2": "0em",
    "letter-spacing-3": "0em",
    "letter-spacing-4": "-0.0025em",
    "letter-spacing-5": "-0.005em",
    "letter-spacing-6": "-0.00625em",
    "letter-spacing-7": "-0.0075em",
    "letter-spacing-8": "-0.01em",
    "letter-spacing-9": "-0.025em",
    // Typography — font weights
    "weight-light": "300",
    "weight-regular": "400",
    "weight-medium": "500",
    "weight-bold": "700",
    // Shadows
    "shadow-1":
      "inset 0 0 0 1px rgb(0 0 0 / 4%), inset 0 1px 1px 0 rgb(0 0 0 / 4%)",
    "shadow-2": "0 0 0 1px rgb(0 0 0 / 4%), 0 1px 2px 0 rgb(0 0 0 / 8%)",
    "shadow-3":
      "0 2px 3px -1px rgb(0 0 0 / 8%), 0 1px 2px -1px rgb(0 0 0 / 8%)",
    "shadow-4":
      "0 8px 16px -4px rgb(0 0 0 / 12%), 0 2px 4px -2px rgb(0 0 0 / 8%)",
    "shadow-5":
      "0 12px 32px -8px rgb(0 0 0 / 16%), 0 4px 8px -4px rgb(0 0 0 / 8%)",
    "shadow-6":
      "0 24px 48px -12px rgb(0 0 0 / 24%), 0 8px 16px -8px rgb(0 0 0 / 12%)",
    // Semantic roles — default to the light scheme
    // Accent — indigo
    "accent-app-bg": "{indigo-1}",
    "accent-subtle-bg": "{indigo-2}",
    "accent-element": "{indigo-3}",
    "accent-element-hover": "{indigo-4}",
    "accent-element-active": "{indigo-5}",
    "accent-border-subtle": "{indigo-6}",
    "accent-border": "{indigo-7}",
    "accent-border-strong": "{indigo-8}",
    "accent-solid": "{indigo-9}",
    "accent-solid-hover": "{indigo-10}",
    "accent-text-subtle": "{indigo-11}",
    "accent-text": "{indigo-12}",
    "accent-contrast": "{white}",
    // Gray — slate
    "gray-app-bg": "{slate-1}",
    "gray-subtle-bg": "{slate-2}",
    "gray-element": "{slate-3}",
    "gray-element-hover": "{slate-4}",
    "gray-element-active": "{slate-5}",
    "gray-border-subtle": "{slate-6}",
    "gray-border": "{slate-7}",
    "gray-border-strong": "{slate-8}",
    "gray-solid": "{slate-9}",
    "gray-solid-hover": "{slate-10}",
    "gray-text-subtle": "{slate-11}",
    "gray-text": "{slate-12}",
    "gray-contrast": "{white}",
    // Status — error (red)
    "error-bg": "{red-3}",
    "error-border": "{red-7}",
    "error-solid": "{red-9}",
    "error-solid-hover": "{red-10}",
    "error-text": "{red-11}",
    // Status — success (green)
    "success-bg": "{green-3}",
    "success-border": "{green-7}",
    "success-solid": "{green-9}",
    "success-solid-hover": "{green-10}",
    "success-text": "{green-11}",
    // Status — warning (amber)
    "warning-bg": "{amber-3}",
    "warning-border": "{amber-7}",
    "warning-solid": "{amber-9}",
    "warning-solid-hover": "{amber-10}",
    "warning-text": "{amber-11}",
    // Status — info (blue)
    "info-bg": "{blue-3}",
    "info-border": "{blue-7}",
    "info-solid": "{blue-9}",
    "info-solid-hover": "{blue-10}",
    "info-text": "{blue-11}",
    // Globals
    background: "{slate-1}",
    panel: "{slate-2}",
    overlay: "{black}",
  },
  modifiers: {
    // Color scheme — the base tokens carry the light scheme, so `light` is
    // empty; `dark` remaps the semantic roles onto the dark scales.
    color: {
      light: {},
      dark: {
        // Accent — indigo
        "accent-app-bg": "{indigo-dark-1}",
        "accent-subtle-bg": "{indigo-dark-2}",
        "accent-element": "{indigo-dark-3}",
        "accent-element-hover": "{indigo-dark-4}",
        "accent-element-active": "{indigo-dark-5}",
        "accent-border-subtle": "{indigo-dark-6}",
        "accent-border": "{indigo-dark-7}",
        "accent-border-strong": "{indigo-dark-8}",
        "accent-solid": "{indigo-dark-9}",
        "accent-solid-hover": "{indigo-dark-10}",
        "accent-text-subtle": "{indigo-dark-11}",
        "accent-text": "{indigo-dark-12}",
        "accent-contrast": "{white}",
        // Gray — slate
        "gray-app-bg": "{slate-dark-1}",
        "gray-subtle-bg": "{slate-dark-2}",
        "gray-element": "{slate-dark-3}",
        "gray-element-hover": "{slate-dark-4}",
        "gray-element-active": "{slate-dark-5}",
        "gray-border-subtle": "{slate-dark-6}",
        "gray-border": "{slate-dark-7}",
        "gray-border-strong": "{slate-dark-8}",
        "gray-solid": "{slate-dark-9}",
        "gray-solid-hover": "{slate-dark-10}",
        "gray-text-subtle": "{slate-dark-11}",
        "gray-text": "{slate-dark-12}",
        "gray-contrast": "{white}",
        // Status — error (red)
        "error-bg": "{red-dark-3}",
        "error-border": "{red-dark-7}",
        "error-solid": "{red-dark-9}",
        "error-solid-hover": "{red-dark-10}",
        "error-text": "{red-dark-11}",
        // Status — success (green)
        "success-bg": "{green-dark-3}",
        "success-border": "{green-dark-7}",
        "success-solid": "{green-dark-9}",
        "success-solid-hover": "{green-dark-10}",
        "success-text": "{green-dark-11}",
        // Status — warning (amber)
        "warning-bg": "{amber-dark-3}",
        "warning-border": "{amber-dark-7}",
        "warning-solid": "{amber-dark-9}",
        "warning-solid-hover": "{amber-dark-10}",
        "warning-text": "{amber-dark-11}",
        // Status — info (blue)
        "info-bg": "{blue-dark-3}",
        "info-border": "{blue-dark-7}",
        "info-solid": "{blue-dark-9}",
        "info-solid-hover": "{blue-dark-10}",
        "info-text": "{blue-dark-11}",
        // Globals
        background: "{slate-dark-1}",
        panel: "{slate-dark-2}",
        overlay: "{black}",
      },
    },
  },
  order: ["color"],
});

export default preset;
