import { defineUnthemePreset } from "@untheme/kit";
import {
  blue,
  cyan,
  teal,
  green,
  gray,
  coolGray,
  warmGray,
  red,
  magenta,
  purple,
  orange,
  yellow,
} from "@carbon/colors";
import { createCarbonColorTokens } from "./colors";

/**
 * The Carbon preset.
 *
 * The base `tokens` map provides the full Carbon token set: the 12 IBM color
 * families (each a mode-independent 10-grade palette) plus white/black, the IBM
 * Plex type scale, the spacing scale, and motion easing/duration values, plus
 * Carbon's semantic roles bound by reference onto those palette tokens. The
 * base defaults to the **White** (light) scheme; the `color` modifier carries
 * the light and dark schemes, with `dark` remapping the roles onto **Gray 100**.
 *
 * The base pairs Carbon's two default themes — **White** (light) and **Gray
 * 100** (dark). The other official pairings (White/Gray 90, Gray 10/Gray 90,
 * Gray 10/Gray 100) ship as theme variants under `@untheme/carbon/themes`.
 */
export const preset = defineUnthemePreset({
  id: "white-g100",
  name: "Carbon",
  tokens: {
    // Color families — IBM Carbon palette (mode-independent 10-grade scales)
    ...createCarbonColorTokens("blue", blue),
    ...createCarbonColorTokens("cyan", cyan),
    ...createCarbonColorTokens("teal", teal),
    ...createCarbonColorTokens("green", green),
    ...createCarbonColorTokens("gray", gray),
    ...createCarbonColorTokens("cool-gray", coolGray),
    ...createCarbonColorTokens("warm-gray", warmGray),
    ...createCarbonColorTokens("red", red),
    ...createCarbonColorTokens("magenta", magenta),
    ...createCarbonColorTokens("purple", purple),
    ...createCarbonColorTokens("orange", orange),
    ...createCarbonColorTokens("yellow", yellow),
    // Pure tones — solid fills resolve their on-color contrast here
    white: "#ffffff",
    black: "#000000",
    // Typography — IBM Plex family stacks
    "font-sans":
      "'IBM Plex Sans', system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif",
    "font-mono":
      "'IBM Plex Mono', 'Menlo', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', Courier, monospace",
    "font-serif": "'IBM Plex Serif', 'Georgia', Times, serif",
    // Typography — type scale (size / line-height / weight / letter-spacing)
    "label-01-size": "0.75rem",
    "label-01-line-height": "1rem",
    "label-01-weight": "400",
    "label-01-letter-spacing": "0.02rem",
    "label-02-size": "0.875rem",
    "label-02-line-height": "1.125rem",
    "label-02-weight": "400",
    "label-02-letter-spacing": "0.01rem",
    "helper-text-01-size": "0.75rem",
    "helper-text-01-line-height": "1rem",
    "helper-text-01-weight": "400",
    "helper-text-01-letter-spacing": "0.02rem",
    "helper-text-02-size": "0.875rem",
    "helper-text-02-line-height": "1.125rem",
    "helper-text-02-weight": "400",
    "helper-text-02-letter-spacing": "0.01rem",
    "body-01-size": "0.875rem",
    "body-01-line-height": "1.25rem",
    "body-01-weight": "400",
    "body-01-letter-spacing": "0.01rem",
    "body-02-size": "1rem",
    "body-02-line-height": "1.5rem",
    "body-02-weight": "400",
    "body-02-letter-spacing": "0",
    "body-compact-01-size": "0.875rem",
    "body-compact-01-line-height": "1.125rem",
    "body-compact-01-weight": "400",
    "body-compact-01-letter-spacing": "0.01rem",
    "body-compact-02-size": "1rem",
    "body-compact-02-line-height": "1.375rem",
    "body-compact-02-weight": "400",
    "body-compact-02-letter-spacing": "0",
    "heading-01-size": "0.875rem",
    "heading-01-line-height": "1.125rem",
    "heading-01-weight": "600",
    "heading-01-letter-spacing": "0.01rem",
    "heading-02-size": "1rem",
    "heading-02-line-height": "1.375rem",
    "heading-02-weight": "600",
    "heading-02-letter-spacing": "0",
    "heading-03-size": "1.25rem",
    "heading-03-line-height": "1.75rem",
    "heading-03-weight": "400",
    "heading-03-letter-spacing": "0",
    "heading-04-size": "1.75rem",
    "heading-04-line-height": "2.25rem",
    "heading-04-weight": "400",
    "heading-04-letter-spacing": "0",
    "heading-05-size": "2rem",
    "heading-05-line-height": "2.5rem",
    "heading-05-weight": "400",
    "heading-05-letter-spacing": "0",
    "heading-06-size": "2.625rem",
    "heading-06-line-height": "3.146rem",
    "heading-06-weight": "300",
    "heading-06-letter-spacing": "0",
    "heading-07-size": "3.375rem",
    "heading-07-line-height": "4.047rem",
    "heading-07-weight": "300",
    "heading-07-letter-spacing": "0",
    // Spacing scale
    "spacing-01": "0.125rem",
    "spacing-02": "0.25rem",
    "spacing-03": "0.5rem",
    "spacing-04": "0.75rem",
    "spacing-05": "1rem",
    "spacing-06": "1.5rem",
    "spacing-07": "2rem",
    "spacing-08": "2.5rem",
    "spacing-09": "3rem",
    "spacing-10": "4rem",
    "spacing-11": "5rem",
    "spacing-12": "6rem",
    "spacing-13": "10rem",
    // Motion — duration
    "duration-fast-01": "70ms",
    "duration-fast-02": "110ms",
    "duration-moderate-01": "150ms",
    "duration-moderate-02": "240ms",
    "duration-slow-01": "400ms",
    "duration-slow-02": "700ms",
    // Motion — easing (productive + expressive)
    "easing-standard": "cubic-bezier(0.2, 0, 0.38, 0.9)",
    "easing-entrance": "cubic-bezier(0, 0, 0.38, 0.9)",
    "easing-exit": "cubic-bezier(0.2, 0, 1, 0.9)",
    "easing-expressive-standard": "cubic-bezier(0.4, 0.14, 0.3, 1)",
    "easing-expressive-entrance": "cubic-bezier(0, 0, 0.3, 1)",
    "easing-expressive-exit": "cubic-bezier(0.4, 0.14, 1, 1)",
    // Semantic roles — default to the White (light) scheme
    background: "{white}",
    "background-inverse": "{gray-80}",
    "layer-01": "{gray-10}",
    "layer-02": "{white}",
    "layer-03": "{gray-10}",
    "field-01": "{gray-10}",
    "field-02": "{white}",
    "text-primary": "{gray-100}",
    "text-secondary": "{gray-70}",
    "text-on-color": "{white}",
    "text-helper": "{gray-60}",
    "text-error": "{red-60}",
    "text-inverse": "{white}",
    "link-primary": "{blue-60}",
    "link-secondary": "{blue-70}",
    "link-visited": "{purple-60}",
    "border-subtle-00": "{gray-20}",
    "border-subtle-01": "{gray-30}",
    "border-strong-01": "{gray-50}",
    "border-inverse": "{gray-100}",
    "border-interactive": "{blue-60}",
    "icon-primary": "{gray-100}",
    "icon-secondary": "{gray-70}",
    "icon-on-color": "{white}",
    "icon-inverse": "{white}",
    "support-error": "{red-60}",
    "support-success": "{green-50}",
    "support-warning": "{yellow-30}",
    "support-info": "{blue-70}",
    focus: "{blue-60}",
    interactive: "{blue-60}",
  },
  modifiers: {
    // Color scheme — the base tokens carry the White (light) scheme, so `light`
    // is empty; `dark` remaps the semantic roles onto Carbon's Gray 100.
    color: {
      light: {},
      // Dark — Carbon "Gray 100" theme
      dark: {
        background: "{gray-100}",
        "background-inverse": "{gray-10}",
        "layer-01": "{gray-90}",
        "layer-02": "{gray-80}",
        "layer-03": "{gray-70}",
        "field-01": "{gray-90}",
        "field-02": "{gray-80}",
        "text-primary": "{gray-10}",
        "text-secondary": "{gray-30}",
        "text-on-color": "{white}",
        "text-helper": "{gray-40}",
        "text-error": "{red-40}",
        "text-inverse": "{gray-100}",
        "link-primary": "{blue-40}",
        "link-secondary": "{blue-30}",
        "link-visited": "{purple-40}",
        "border-subtle-00": "{gray-80}",
        "border-subtle-01": "{gray-70}",
        "border-strong-01": "{gray-60}",
        "border-inverse": "{gray-10}",
        "border-interactive": "{blue-50}",
        "icon-primary": "{gray-10}",
        "icon-secondary": "{gray-30}",
        "icon-on-color": "{white}",
        "icon-inverse": "{gray-100}",
        "support-error": "{red-50}",
        "support-success": "{green-40}",
        "support-warning": "{yellow-30}",
        "support-info": "{blue-50}",
        focus: "{white}",
        interactive: "{blue-50}",
      },
    },
  },
  order: ["color"],
});

export default preset;
