import { mkdir, rm, writeFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import { afterAll, describe, expect, it } from "vitest";

import type { Schema, Template } from "@untheme/schema";

import { defineSchema } from "@untheme/schema";

import { generate } from "../src/generate";
import { resolveKit } from "../src/resolve";
import { FIXTURES } from "./helpers";

const ROOT = fileURLToPath(FIXTURES);

/** Where the emitted modules are written to be imported back. */
const OUT = new URL("./.generated/emit/", import.meta.url);

afterAll(async () => {
  await rm(OUT, { recursive: true, force: true });
});

describe("generate", () => {
  it("emits the index, config and manifest modules with declarations", async () => {
    const output = await generate({ source: "./resolver.json" }, { cwd: ROOT });
    expect(output.outDir).toBe("untheme");
    expect(output.files.map((file) => file.path)).toEqual([
      "index.mjs",
      "index.d.mts",
      "config.mjs",
      "config.d.mts",
      "manifest.mjs",
      "manifest.d.mts",
    ]);
    for (const file of output.files) {
      expect(
        file.contents.startsWith(
          '// Generated by @untheme/kit from "fixture". Do not edit by hand.\n',
        ),
      ).toBe(true);
    }
  });

  it("declares explicit unions for the tokens, modifiers and contexts", async () => {
    const output = await generate({ source: "./resolver.json" }, { cwd: ROOT });
    const declarations = output.files.find(
      (file) => file.path === "index.d.mts",
    )!.contents;
    expect(declarations).toContain('\n  | "color.primary.600"');
    expect(declarations).toContain(
      'export type Modifier =\n  | "color"\n  | "density";',
    );
    expect(declarations).toContain(
      [
        "export type Mod = {",
        '  "color": { "light": Overrides; "dark": Overrides };',
        '  "density": { "default": Overrides; "compact": Overrides };',
        "};",
      ].join("\n"),
    );

    const config = output.files.find(
      (file) => file.path === "config.d.mts",
    )!.contents;
    expect(config).toContain(
      "export type Contract = UnthemeContract<Token, Mod>;",
    );
    expect(config).toContain("declare const config: UnthemeConfig<Contract>;");
  });

  it("declares only the contexts the config keeps", async () => {
    const output = await generate(
      {
        source: "./resolver.json",
        modifiers: { color: { contexts: ["dark"] } },
      },
      { cwd: ROOT },
    );
    const declarations = output.files.find(
      (file) => file.path === "index.d.mts",
    )!.contents;
    expect(declarations).toContain('  "color": { "dark": Overrides };');
    const index = output.files.find((file) => file.path === "index.mjs")!;
    expect(index.contents).not.toContain('"light"');
  });

  it("emits the manifest of the contexts the config keeps", async () => {
    const output = await generate(
      {
        source: "./resolver.json",
        modifiers: {
          color: { add: { dim: "./dim.json" }, contexts: ["dim", "dark"] },
          density: false,
        },
      },
      { cwd: ROOT },
    );
    const module = output.files.find((file) => file.path === "manifest.mjs")!;
    const literal = module.contents
      .split("export const manifest = ")[1]!
      .split(";\nexport default")[0]!;
    expect(JSON.parse(literal)).toEqual([
      {
        id: "color",
        name: "Color",
        contexts: [
          { id: "dim", name: "Dim" },
          { id: "dark", name: "Dark" },
        ],
      },
    ]);
    const declarations = output.files.find(
      (file) => file.path === "manifest.d.mts",
    )!.contents;
    expect(declarations).toContain(
      "export declare const manifest: readonly ModifierEntry[];",
    );
  });

  it("emits a never union and an empty structure without modifiers", async () => {
    const output = await generate(
      { source: "./base.json", name: "Base" },
      { cwd: ROOT },
    );
    const declarations = output.files.find(
      (file) => file.path === "index.d.mts",
    )!.contents;
    expect(declarations).toContain("export type Modifier = never;");
    expect(declarations).toContain("export type Mod = {};");
  });

  it("emits modules that import back to the resolved documents", async () => {
    const kit = await resolveKit({ source: "./resolver.json" }, { cwd: ROOT });
    const output = await generate({ source: "./resolver.json" }, { cwd: ROOT });
    await mkdir(OUT, { recursive: true });
    await writeFile(new URL("../.gitignore", OUT), "*\n");
    for (const file of output.files) {
      await writeFile(new URL(file.path, OUT), file.contents);
    }

    const keys = await import(
      pathToFileURL(fileURLToPath(new URL("index.mjs", OUT))).href
    );
    expect(keys.tokens).toEqual(Object.keys(kit.theme.tokens));
    expect(keys.modifiers).toEqual({
      color: ["light", "dark"],
      density: ["default", "compact"],
    });
    expect(keys.isToken("size.md")).toBe(true);
    expect(keys.isToken("size.xl")).toBe(false);
    expect(keys.isToken(7)).toBe(false);
    expect(keys.isModifier("density")).toBe(true);
    expect(keys.isModifier("toString")).toBe(false);

    const config = await import(new URL("config.mjs", OUT).href);
    expect(config.theme).toEqual(kit.theme);
    expect(config.input).toEqual(kit.input);
    expect(config.default).toEqual({ theme: kit.theme, input: kit.input });
    const schema: Schema<Template> = defineSchema(config.theme);
    schema.assert.theme(config.theme);
    schema.assert.input(config.input);
  });
});
