import preset from "../preset";

/**
 * Orange theme — Radix orange accent paired with the sand gray.
 */
export default preset.define({
  id: "orange",
  name: "Orange",
  reference: {},
  system: {
    light: {
      "accent-app-bg": "orange-1",
      "accent-subtle-bg": "orange-2",
      "accent-element": "orange-3",
      "accent-element-hover": "orange-4",
      "accent-element-active": "orange-5",
      "accent-border-subtle": "orange-6",
      "accent-border": "orange-7",
      "accent-border-strong": "orange-8",
      "accent-solid": "orange-9",
      "accent-solid-hover": "orange-10",
      "accent-text-subtle": "orange-11",
      "accent-text": "orange-12",
      "accent-contrast": "black",
      "gray-app-bg": "sand-1",
      "gray-subtle-bg": "sand-2",
      "gray-element": "sand-3",
      "gray-element-hover": "sand-4",
      "gray-element-active": "sand-5",
      "gray-border-subtle": "sand-6",
      "gray-border": "sand-7",
      "gray-border-strong": "sand-8",
      "gray-solid": "sand-9",
      "gray-solid-hover": "sand-10",
      "gray-text-subtle": "sand-11",
      "gray-text": "sand-12",
      background: "sand-1",
      panel: "sand-2",
    },
    dark: {
      "accent-app-bg": "orange-dark-1",
      "accent-subtle-bg": "orange-dark-2",
      "accent-element": "orange-dark-3",
      "accent-element-hover": "orange-dark-4",
      "accent-element-active": "orange-dark-5",
      "accent-border-subtle": "orange-dark-6",
      "accent-border": "orange-dark-7",
      "accent-border-strong": "orange-dark-8",
      "accent-solid": "orange-dark-9",
      "accent-solid-hover": "orange-dark-10",
      "accent-text-subtle": "orange-dark-11",
      "accent-text": "orange-dark-12",
      "accent-contrast": "black",
      "gray-app-bg": "sand-dark-1",
      "gray-subtle-bg": "sand-dark-2",
      "gray-element": "sand-dark-3",
      "gray-element-hover": "sand-dark-4",
      "gray-element-active": "sand-dark-5",
      "gray-border-subtle": "sand-dark-6",
      "gray-border": "sand-dark-7",
      "gray-border-strong": "sand-dark-8",
      "gray-solid": "sand-dark-9",
      "gray-solid-hover": "sand-dark-10",
      "gray-text-subtle": "sand-dark-11",
      "gray-text": "sand-dark-12",
      background: "sand-dark-1",
      panel: "sand-dark-2",
    },
  },
  roles: {},
});
