import { defineUnthemeConfig } from "untheme";
import { createM3ColorTokens } from "./colors";

/**
 * Material Design 3 theme factory.
 *
 * Reference tokens provide the full M3 token set: color palettes (Tailwind
 * family names as seeds), typography scales, shape radii, elevation shadows,
 * and motion easing/duration values. System tokens map color references to
 * semantic roles per light/dark mode following the M3 color system specification.
 */
export const defineM3Theme = defineUnthemeConfig({
  label: "Material 3",
  reference: {
    // Chromatic palettes
    ...createM3ColorTokens("red", "#ef4444"),
    ...createM3ColorTokens("orange", "#f97316"),
    ...createM3ColorTokens("amber", "#f59e0b"),
    ...createM3ColorTokens("yellow", "#eab308"),
    ...createM3ColorTokens("lime", "#84cc16"),
    ...createM3ColorTokens("green", "#22c55e"),
    ...createM3ColorTokens("emerald", "#10b981"),
    ...createM3ColorTokens("teal", "#14b8a6"),
    ...createM3ColorTokens("cyan", "#06b6d4"),
    ...createM3ColorTokens("sky", "#0ea5e9"),
    ...createM3ColorTokens("blue", "#3b82f6"),
    ...createM3ColorTokens("indigo", "#6366f1"),
    ...createM3ColorTokens("violet", "#8b5cf6"),
    ...createM3ColorTokens("purple", "#a855f7"),
    ...createM3ColorTokens("fuchsia", "#d946ef"),
    ...createM3ColorTokens("pink", "#ec4899"),
    ...createM3ColorTokens("rose", "#f43f5e"),
    // Neutral palettes
    ...createM3ColorTokens("slate", "#64748b"),
    ...createM3ColorTokens("gray", "#6b7280"),
    ...createM3ColorTokens("zinc", "#71717a"),
    ...createM3ColorTokens("neutral", "#737373"),
    ...createM3ColorTokens("stone", "#78716c"),
    // Typography — typeface references
    "font-brand": "Roboto, sans-serif",
    "font-plain": "Roboto, sans-serif",
    // Typography — display
    "display-large-size": "57px",
    "display-large-line-height": "64px",
    "display-large-weight": "400",
    "display-large-tracking": "-0.25px",
    "display-medium-size": "45px",
    "display-medium-line-height": "52px",
    "display-medium-weight": "400",
    "display-medium-tracking": "0px",
    "display-small-size": "36px",
    "display-small-line-height": "44px",
    "display-small-weight": "400",
    "display-small-tracking": "0px",
    // Typography — headline
    "headline-large-size": "32px",
    "headline-large-line-height": "40px",
    "headline-large-weight": "400",
    "headline-large-tracking": "0px",
    "headline-medium-size": "28px",
    "headline-medium-line-height": "36px",
    "headline-medium-weight": "400",
    "headline-medium-tracking": "0px",
    "headline-small-size": "24px",
    "headline-small-line-height": "32px",
    "headline-small-weight": "400",
    "headline-small-tracking": "0px",
    // Typography — title
    "title-large-size": "22px",
    "title-large-line-height": "28px",
    "title-large-weight": "400",
    "title-large-tracking": "0px",
    "title-medium-size": "16px",
    "title-medium-line-height": "24px",
    "title-medium-weight": "500",
    "title-medium-tracking": "0.15px",
    "title-small-size": "14px",
    "title-small-line-height": "20px",
    "title-small-weight": "500",
    "title-small-tracking": "0.1px",
    // Typography — body
    "body-large-size": "16px",
    "body-large-line-height": "24px",
    "body-large-weight": "400",
    "body-large-tracking": "0.5px",
    "body-medium-size": "14px",
    "body-medium-line-height": "20px",
    "body-medium-weight": "400",
    "body-medium-tracking": "0.25px",
    "body-small-size": "12px",
    "body-small-line-height": "16px",
    "body-small-weight": "400",
    "body-small-tracking": "0.4px",
    // Typography — label
    "label-large-size": "14px",
    "label-large-line-height": "20px",
    "label-large-weight": "500",
    "label-large-tracking": "0.1px",
    "label-medium-size": "12px",
    "label-medium-line-height": "16px",
    "label-medium-weight": "500",
    "label-medium-tracking": "0.5px",
    "label-small-size": "11px",
    "label-small-line-height": "16px",
    "label-small-weight": "500",
    "label-small-tracking": "0.5px",
    // Shape
    "shape-none": "0px",
    "shape-extra-small": "4px",
    "shape-small": "8px",
    "shape-medium": "12px",
    "shape-large": "16px",
    "shape-extra-large": "28px",
    "shape-full": "9999px",
    // Elevation
    "elevation-0": "none",
    "elevation-1":
      "0px 1px 2px 0px rgb(0 0 0 / 30%), 0px 1px 3px 1px rgb(0 0 0 / 15%)",
    "elevation-2":
      "0px 1px 2px 0px rgb(0 0 0 / 30%), 0px 2px 6px 2px rgb(0 0 0 / 15%)",
    "elevation-3":
      "0px 1px 3px 0px rgb(0 0 0 / 30%), 0px 4px 8px 3px rgb(0 0 0 / 15%)",
    "elevation-4":
      "0px 2px 3px 0px rgb(0 0 0 / 30%), 0px 6px 10px 4px rgb(0 0 0 / 15%)",
    "elevation-5":
      "0px 4px 4px 0px rgb(0 0 0 / 30%), 0px 8px 12px 6px rgb(0 0 0 / 15%)",
    // Motion — easing
    "easing-standard": "cubic-bezier(0.2, 0, 0, 1)",
    "easing-standard-decelerate": "cubic-bezier(0, 0, 0, 1)",
    "easing-standard-accelerate": "cubic-bezier(0.3, 0, 1, 1)",
    "easing-emphasized": "cubic-bezier(0.05, 0.7, 0.1, 1)",
    "easing-emphasized-decelerate": "cubic-bezier(0.05, 0.7, 0.1, 1)",
    "easing-emphasized-accelerate": "cubic-bezier(0.3, 0, 0.8, 0.15)",
    "easing-linear": "cubic-bezier(0, 0, 1, 1)",
    // Motion — duration
    "duration-short-1": "50ms",
    "duration-short-2": "100ms",
    "duration-short-3": "150ms",
    "duration-short-4": "200ms",
    "duration-medium-1": "250ms",
    "duration-medium-2": "300ms",
    "duration-medium-3": "350ms",
    "duration-medium-4": "400ms",
    "duration-long-1": "450ms",
    "duration-long-2": "500ms",
    "duration-long-3": "550ms",
    "duration-long-4": "600ms",
    "duration-extra-long-1": "700ms",
    "duration-extra-long-2": "800ms",
    "duration-extra-long-3": "900ms",
    "duration-extra-long-4": "1000ms",
  },
  modes: {
    light: {
      primary: "violet-40",
      "on-primary": "violet-100",
      "primary-container": "violet-90",
      "on-primary-container": "violet-30",
      "inverse-primary": "violet-80",
      "primary-fixed": "violet-90",
      "primary-fixed-dim": "violet-80",
      "on-primary-fixed": "violet-10",
      "on-primary-fixed-variant": "violet-30",
      secondary: "indigo-40",
      "on-secondary": "indigo-100",
      "secondary-container": "indigo-90",
      "on-secondary-container": "indigo-30",
      "secondary-fixed": "indigo-90",
      "secondary-fixed-dim": "indigo-80",
      "on-secondary-fixed": "indigo-10",
      "on-secondary-fixed-variant": "indigo-30",
      tertiary: "pink-40",
      "on-tertiary": "pink-100",
      "tertiary-container": "pink-90",
      "on-tertiary-container": "pink-30",
      "tertiary-fixed": "pink-90",
      "tertiary-fixed-dim": "pink-80",
      "on-tertiary-fixed": "pink-10",
      "on-tertiary-fixed-variant": "pink-30",
      error: "red-40",
      "on-error": "red-100",
      "error-container": "red-90",
      "on-error-container": "red-30",
      surface: "neutral-98",
      "on-surface": "neutral-10",
      "surface-dim": "neutral-87",
      "surface-bright": "neutral-98",
      "surface-container-lowest": "neutral-100",
      "surface-container-low": "neutral-96",
      "surface-container": "neutral-94",
      "surface-container-high": "neutral-92",
      "surface-container-highest": "neutral-90",
      "surface-variant": "zinc-90",
      "on-surface-variant": "zinc-30",
      "surface-tint": "violet-40",
      "inverse-surface": "neutral-20",
      "inverse-on-surface": "neutral-95",
      background: "neutral-98",
      "on-background": "neutral-10",
      outline: "zinc-50",
      "outline-variant": "zinc-80",
      shadow: "neutral-0",
      scrim: "neutral-0",
    },
    dark: {
      primary: "violet-80",
      "on-primary": "violet-20",
      "primary-container": "violet-30",
      "on-primary-container": "violet-90",
      "inverse-primary": "violet-40",
      "primary-fixed": "violet-90",
      "primary-fixed-dim": "violet-80",
      "on-primary-fixed": "violet-10",
      "on-primary-fixed-variant": "violet-30",
      secondary: "indigo-80",
      "on-secondary": "indigo-20",
      "secondary-container": "indigo-30",
      "on-secondary-container": "indigo-90",
      "secondary-fixed": "indigo-90",
      "secondary-fixed-dim": "indigo-80",
      "on-secondary-fixed": "indigo-10",
      "on-secondary-fixed-variant": "indigo-30",
      tertiary: "pink-80",
      "on-tertiary": "pink-20",
      "tertiary-container": "pink-30",
      "on-tertiary-container": "pink-90",
      "tertiary-fixed": "pink-90",
      "tertiary-fixed-dim": "pink-80",
      "on-tertiary-fixed": "pink-10",
      "on-tertiary-fixed-variant": "pink-30",
      error: "red-80",
      "on-error": "red-20",
      "error-container": "red-30",
      "on-error-container": "red-90",
      surface: "neutral-6",
      "on-surface": "neutral-90",
      "surface-dim": "neutral-6",
      "surface-bright": "neutral-24",
      "surface-container-lowest": "neutral-4",
      "surface-container-low": "neutral-10",
      "surface-container": "neutral-12",
      "surface-container-high": "neutral-17",
      "surface-container-highest": "neutral-22",
      "surface-variant": "zinc-30",
      "on-surface-variant": "zinc-80",
      "surface-tint": "violet-80",
      "inverse-surface": "neutral-90",
      "inverse-on-surface": "neutral-20",
      background: "neutral-6",
      "on-background": "neutral-90",
      outline: "zinc-60",
      "outline-variant": "zinc-30",
      shadow: "neutral-0",
      scrim: "neutral-0",
    },
  },
});
