import type { Config } from "untheme";
import { defineUnthemeConfig } from "untheme";
import { createM3ColorTokens } from "./colors";
import type { M3Ref, M3Sys } from "./types";

/**
 * Material Design 3 theme factory.
 *
 * Reference tokens provide a full spectrum of M3 tonal palettes using
 * Tailwind color family names as seeds. System tokens map them to semantic
 * roles per light/dark mode following the M3 color system specification.
 */
export const defineM3Theme = defineUnthemeConfig({
  label: "Material 3",
  reference: {
    // Chromatic palettes
    ...createM3ColorTokens("red", "#ef4444"),
    ...createM3ColorTokens("orange", "#f97316"),
    ...createM3ColorTokens("amber", "#f59e0b"),
    ...createM3ColorTokens("yellow", "#eab308"),
    ...createM3ColorTokens("lime", "#84cc16"),
    ...createM3ColorTokens("green", "#22c55e"),
    ...createM3ColorTokens("emerald", "#10b981"),
    ...createM3ColorTokens("teal", "#14b8a6"),
    ...createM3ColorTokens("cyan", "#06b6d4"),
    ...createM3ColorTokens("sky", "#0ea5e9"),
    ...createM3ColorTokens("blue", "#3b82f6"),
    ...createM3ColorTokens("indigo", "#6366f1"),
    ...createM3ColorTokens("violet", "#8b5cf6"),
    ...createM3ColorTokens("purple", "#a855f7"),
    ...createM3ColorTokens("fuchsia", "#d946ef"),
    ...createM3ColorTokens("pink", "#ec4899"),
    ...createM3ColorTokens("rose", "#f43f5e"),
    // Neutral palettes
    ...createM3ColorTokens("slate", "#64748b"),
    ...createM3ColorTokens("gray", "#6b7280"),
    ...createM3ColorTokens("zinc", "#71717a"),
    ...createM3ColorTokens("neutral", "#737373"),
    ...createM3ColorTokens("stone", "#78716c"),
  },
  modes: {
    light: {
      primary: "violet-40",
      "on-primary": "violet-100",
      "primary-container": "violet-90",
      "on-primary-container": "violet-30",
      "inverse-primary": "violet-80",
      "primary-fixed": "violet-90",
      "primary-fixed-dim": "violet-80",
      "on-primary-fixed": "violet-10",
      "on-primary-fixed-variant": "violet-30",
      secondary: "indigo-40",
      "on-secondary": "indigo-100",
      "secondary-container": "indigo-90",
      "on-secondary-container": "indigo-30",
      "secondary-fixed": "indigo-90",
      "secondary-fixed-dim": "indigo-80",
      "on-secondary-fixed": "indigo-10",
      "on-secondary-fixed-variant": "indigo-30",
      tertiary: "pink-40",
      "on-tertiary": "pink-100",
      "tertiary-container": "pink-90",
      "on-tertiary-container": "pink-30",
      "tertiary-fixed": "pink-90",
      "tertiary-fixed-dim": "pink-80",
      "on-tertiary-fixed": "pink-10",
      "on-tertiary-fixed-variant": "pink-30",
      error: "red-40",
      "on-error": "red-100",
      "error-container": "red-90",
      "on-error-container": "red-30",
      surface: "neutral-98",
      "on-surface": "neutral-10",
      "surface-dim": "neutral-87",
      "surface-bright": "neutral-98",
      "surface-container-lowest": "neutral-100",
      "surface-container-low": "neutral-96",
      "surface-container": "neutral-94",
      "surface-container-high": "neutral-92",
      "surface-container-highest": "neutral-90",
      "surface-variant": "zinc-90",
      "on-surface-variant": "zinc-30",
      "surface-tint": "violet-40",
      "inverse-surface": "neutral-20",
      "inverse-on-surface": "neutral-95",
      background: "neutral-98",
      "on-background": "neutral-10",
      outline: "zinc-50",
      "outline-variant": "zinc-80",
      shadow: "neutral-0",
      scrim: "neutral-0",
    },
    dark: {
      primary: "violet-80",
      "on-primary": "violet-20",
      "primary-container": "violet-30",
      "on-primary-container": "violet-90",
      "inverse-primary": "violet-40",
      "primary-fixed": "violet-90",
      "primary-fixed-dim": "violet-80",
      "on-primary-fixed": "violet-10",
      "on-primary-fixed-variant": "violet-30",
      secondary: "indigo-80",
      "on-secondary": "indigo-20",
      "secondary-container": "indigo-30",
      "on-secondary-container": "indigo-90",
      "secondary-fixed": "indigo-90",
      "secondary-fixed-dim": "indigo-80",
      "on-secondary-fixed": "indigo-10",
      "on-secondary-fixed-variant": "indigo-30",
      tertiary: "pink-80",
      "on-tertiary": "pink-20",
      "tertiary-container": "pink-30",
      "on-tertiary-container": "pink-90",
      "tertiary-fixed": "pink-90",
      "tertiary-fixed-dim": "pink-80",
      "on-tertiary-fixed": "pink-10",
      "on-tertiary-fixed-variant": "pink-30",
      error: "red-80",
      "on-error": "red-20",
      "error-container": "red-30",
      "on-error-container": "red-90",
      surface: "neutral-6",
      "on-surface": "neutral-90",
      "surface-dim": "neutral-6",
      "surface-bright": "neutral-24",
      "surface-container-lowest": "neutral-4",
      "surface-container-low": "neutral-10",
      "surface-container": "neutral-12",
      "surface-container-high": "neutral-17",
      "surface-container-highest": "neutral-22",
      "surface-variant": "zinc-30",
      "on-surface-variant": "zinc-80",
      "surface-tint": "violet-80",
      "inverse-surface": "neutral-90",
      "inverse-on-surface": "neutral-20",
      background: "neutral-6",
      "on-background": "neutral-90",
      outline: "zinc-60",
      "outline-variant": "zinc-30",
      shadow: "neutral-0",
      scrim: "neutral-0",
    },
  },
  roles: {},
} satisfies Config<M3Ref, M3Sys, never>);
