import { M3_TONES } from "./constant";

/** Union of all M3 tonal palette tone stops. */
export type M3Tone = (typeof M3_TONES)[number];

/** Union of all available M3 color palette names. */
export type M3Palette =
  | "red"
  | "orange"
  | "amber"
  | "yellow"
  | "lime"
  | "green"
  | "emerald"
  | "teal"
  | "cyan"
  | "sky"
  | "blue"
  | "indigo"
  | "violet"
  | "purple"
  | "fuchsia"
  | "pink"
  | "rose"
  | "slate"
  | "gray"
  | "zinc"
  | "neutral"
  | "stone";

/** Union of all M3 reference token keys. */
export type M3Ref = `${M3Palette}-${M3Tone}`;

/** Union of all M3 system token keys. */
export type M3Sys =
  | "primary"
  | "on-primary"
  | "primary-container"
  | "on-primary-container"
  | "inverse-primary"
  | "primary-fixed"
  | "primary-fixed-dim"
  | "on-primary-fixed"
  | "on-primary-fixed-variant"
  | "secondary"
  | "on-secondary"
  | "secondary-container"
  | "on-secondary-container"
  | "secondary-fixed"
  | "secondary-fixed-dim"
  | "on-secondary-fixed"
  | "on-secondary-fixed-variant"
  | "tertiary"
  | "on-tertiary"
  | "tertiary-container"
  | "on-tertiary-container"
  | "tertiary-fixed"
  | "tertiary-fixed-dim"
  | "on-tertiary-fixed"
  | "on-tertiary-fixed-variant"
  | "error"
  | "on-error"
  | "error-container"
  | "on-error-container"
  | "surface"
  | "on-surface"
  | "surface-dim"
  | "surface-bright"
  | "surface-container-lowest"
  | "surface-container-low"
  | "surface-container"
  | "surface-container-high"
  | "surface-container-highest"
  | "surface-variant"
  | "on-surface-variant"
  | "surface-tint"
  | "inverse-surface"
  | "inverse-on-surface"
  | "background"
  | "on-background"
  | "outline"
  | "outline-variant"
  | "shadow"
  | "scrim";
