import { defineUnthemePreset } from "@untheme/kit";
import { createM3ColorTokens } from "./colors";

/**
 * The Material Design 3 preset.
 *
 * The base `tokens` map provides the full M3 token set: color palettes
 * (Tailwind family names as seeds), typography scales, shape radii, elevation
 * shadows, and motion easing/duration values, plus the semantic roles bound
 * onto those palette tokens following the M3 color system specification. The
 * base defaults to the light scheme; the `color` modifier remaps the roles for
 * dark mode and for M3's medium- and high-contrast schemes in each mode (six
 * contexts: light/dark × standard/medium/high; fixed colors stay constant
 * across contrast per the M3 spec).
 */
export const preset = defineUnthemePreset({
  id: "material-3",
  name: "Material 3",
  tokens: {
    // Chromatic palettes
    ...createM3ColorTokens("red", "#ef4444"),
    ...createM3ColorTokens("orange", "#f97316"),
    ...createM3ColorTokens("amber", "#f59e0b"),
    ...createM3ColorTokens("yellow", "#eab308"),
    ...createM3ColorTokens("lime", "#84cc16"),
    ...createM3ColorTokens("green", "#22c55e"),
    ...createM3ColorTokens("emerald", "#10b981"),
    ...createM3ColorTokens("teal", "#14b8a6"),
    ...createM3ColorTokens("cyan", "#06b6d4"),
    ...createM3ColorTokens("sky", "#0ea5e9"),
    ...createM3ColorTokens("blue", "#3b82f6"),
    ...createM3ColorTokens("indigo", "#6366f1"),
    ...createM3ColorTokens("violet", "#8b5cf6"),
    ...createM3ColorTokens("purple", "#a855f7"),
    ...createM3ColorTokens("fuchsia", "#d946ef"),
    ...createM3ColorTokens("pink", "#ec4899"),
    ...createM3ColorTokens("rose", "#f43f5e"),
    // Neutral palettes
    ...createM3ColorTokens("slate", "#64748b"),
    ...createM3ColorTokens("gray", "#6b7280"),
    ...createM3ColorTokens("zinc", "#71717a"),
    ...createM3ColorTokens("neutral", "#737373"),
    ...createM3ColorTokens("stone", "#78716c"),
    // Typography — typeface references
    "font-brand": "Roboto, sans-serif",
    "font-plain": "Roboto, sans-serif",
    "weight-regular": "400",
    "weight-medium": "500",
    "weight-bold": "700",
    // Typography — display
    "display-large-font": "{font-brand}",
    "display-large-size": "57px",
    "display-large-line-height": "64px",
    "display-large-weight": "{weight-regular}",
    "display-large-tracking": "-0.25px",
    "display-medium-font": "{font-brand}",
    "display-medium-size": "45px",
    "display-medium-line-height": "52px",
    "display-medium-weight": "{weight-regular}",
    "display-medium-tracking": "0px",
    "display-small-font": "{font-brand}",
    "display-small-size": "36px",
    "display-small-line-height": "44px",
    "display-small-weight": "{weight-regular}",
    "display-small-tracking": "0px",
    // Typography — headline
    "headline-large-font": "{font-brand}",
    "headline-large-size": "32px",
    "headline-large-line-height": "40px",
    "headline-large-weight": "{weight-regular}",
    "headline-large-tracking": "0px",
    "headline-medium-font": "{font-brand}",
    "headline-medium-size": "28px",
    "headline-medium-line-height": "36px",
    "headline-medium-weight": "{weight-regular}",
    "headline-medium-tracking": "0px",
    "headline-small-font": "{font-brand}",
    "headline-small-size": "24px",
    "headline-small-line-height": "32px",
    "headline-small-weight": "{weight-regular}",
    "headline-small-tracking": "0px",
    // Typography — title
    "title-large-font": "{font-brand}",
    "title-large-size": "22px",
    "title-large-line-height": "28px",
    "title-large-weight": "{weight-regular}",
    "title-large-tracking": "0px",
    "title-medium-font": "{font-plain}",
    "title-medium-size": "16px",
    "title-medium-line-height": "24px",
    "title-medium-weight": "{weight-medium}",
    "title-medium-tracking": "0.15px",
    "title-small-font": "{font-plain}",
    "title-small-size": "14px",
    "title-small-line-height": "20px",
    "title-small-weight": "{weight-medium}",
    "title-small-tracking": "0.1px",
    // Typography — body
    "body-large-font": "{font-plain}",
    "body-large-size": "16px",
    "body-large-line-height": "24px",
    "body-large-weight": "{weight-regular}",
    "body-large-tracking": "0.5px",
    "body-medium-font": "{font-plain}",
    "body-medium-size": "14px",
    "body-medium-line-height": "20px",
    "body-medium-weight": "{weight-regular}",
    "body-medium-tracking": "0.25px",
    "body-small-font": "{font-plain}",
    "body-small-size": "12px",
    "body-small-line-height": "16px",
    "body-small-weight": "{weight-regular}",
    "body-small-tracking": "0.4px",
    // Typography — label
    "label-large-font": "{font-plain}",
    "label-large-size": "14px",
    "label-large-line-height": "20px",
    "label-large-weight": "{weight-medium}",
    "label-large-weight-prominent": "{weight-bold}",
    "label-large-tracking": "0.1px",
    "label-medium-font": "{font-plain}",
    "label-medium-size": "12px",
    "label-medium-line-height": "16px",
    "label-medium-weight": "{weight-medium}",
    "label-medium-weight-prominent": "{weight-bold}",
    "label-medium-tracking": "0.5px",
    "label-small-font": "{font-plain}",
    "label-small-size": "11px",
    "label-small-line-height": "16px",
    "label-small-weight": "{weight-medium}",
    "label-small-weight-prominent": "{weight-bold}",
    "label-small-tracking": "0.5px",
    // Shape
    "shape-none": "0px",
    "shape-extra-small": "4px",
    "shape-small": "8px",
    "shape-medium": "12px",
    "shape-large": "16px",
    "shape-large-increased": "20px",
    "shape-extra-large": "28px",
    "shape-extra-large-increased": "32px",
    "shape-extra-extra-large": "48px",
    "shape-full": "9999px",
    // Elevation
    "elevation-0": "none",
    "elevation-1":
      "0px 1px 2px 0px rgb(0 0 0 / 30%), 0px 1px 3px 1px rgb(0 0 0 / 15%)",
    "elevation-2":
      "0px 1px 2px 0px rgb(0 0 0 / 30%), 0px 2px 6px 2px rgb(0 0 0 / 15%)",
    "elevation-3":
      "0px 1px 3px 0px rgb(0 0 0 / 30%), 0px 4px 8px 3px rgb(0 0 0 / 15%)",
    "elevation-4":
      "0px 2px 3px 0px rgb(0 0 0 / 30%), 0px 6px 10px 4px rgb(0 0 0 / 15%)",
    "elevation-5":
      "0px 4px 4px 0px rgb(0 0 0 / 30%), 0px 8px 12px 6px rgb(0 0 0 / 15%)",
    // Motion — easing
    "easing-standard": "cubic-bezier(0.2, 0, 0, 1)",
    "easing-standard-decelerate": "cubic-bezier(0, 0, 0, 1)",
    "easing-standard-accelerate": "cubic-bezier(0.3, 0, 1, 1)",
    "easing-emphasized": "cubic-bezier(0.2, 0, 0, 1)",
    "easing-emphasized-decelerate": "cubic-bezier(0.05, 0.7, 0.1, 1)",
    "easing-emphasized-accelerate": "cubic-bezier(0.3, 0, 0.8, 0.15)",
    "easing-linear": "cubic-bezier(0, 0, 1, 1)",
    "easing-legacy": "cubic-bezier(0.4, 0, 0.2, 1)",
    "easing-legacy-decelerate": "cubic-bezier(0, 0, 0.2, 1)",
    "easing-legacy-accelerate": "cubic-bezier(0.4, 0, 1, 1)",
    // Motion — duration
    "duration-short-1": "50ms",
    "duration-short-2": "100ms",
    "duration-short-3": "150ms",
    "duration-short-4": "200ms",
    "duration-medium-1": "250ms",
    "duration-medium-2": "300ms",
    "duration-medium-3": "350ms",
    "duration-medium-4": "400ms",
    "duration-long-1": "450ms",
    "duration-long-2": "500ms",
    "duration-long-3": "550ms",
    "duration-long-4": "600ms",
    "duration-extra-long-1": "700ms",
    "duration-extra-long-2": "800ms",
    "duration-extra-long-3": "900ms",
    "duration-extra-long-4": "1000ms",
    // State — state-layer opacities
    "state-hover": "0.08",
    "state-focus": "0.12",
    "state-pressed": "0.12",
    "state-dragged": "0.16",
    // Semantic roles — default to the light scheme
    primary: "{violet-40}",
    "on-primary": "{violet-100}",
    "primary-container": "{violet-90}",
    "on-primary-container": "{violet-30}",
    "inverse-primary": "{violet-80}",
    "primary-fixed": "{violet-90}",
    "primary-fixed-dim": "{violet-80}",
    "on-primary-fixed": "{violet-10}",
    "on-primary-fixed-variant": "{violet-30}",
    secondary: "{indigo-40}",
    "on-secondary": "{indigo-100}",
    "secondary-container": "{indigo-90}",
    "on-secondary-container": "{indigo-30}",
    "secondary-fixed": "{indigo-90}",
    "secondary-fixed-dim": "{indigo-80}",
    "on-secondary-fixed": "{indigo-10}",
    "on-secondary-fixed-variant": "{indigo-30}",
    tertiary: "{pink-40}",
    "on-tertiary": "{pink-100}",
    "tertiary-container": "{pink-90}",
    "on-tertiary-container": "{pink-30}",
    "tertiary-fixed": "{pink-90}",
    "tertiary-fixed-dim": "{pink-80}",
    "on-tertiary-fixed": "{pink-10}",
    "on-tertiary-fixed-variant": "{pink-30}",
    error: "{red-40}",
    "on-error": "{red-100}",
    "error-container": "{red-90}",
    "on-error-container": "{red-30}",
    surface: "{neutral-98}",
    "on-surface": "{neutral-10}",
    "surface-dim": "{neutral-87}",
    "surface-bright": "{neutral-98}",
    "surface-container-lowest": "{neutral-100}",
    "surface-container-low": "{neutral-96}",
    "surface-container": "{neutral-94}",
    "surface-container-high": "{neutral-92}",
    "surface-container-highest": "{neutral-90}",
    "surface-variant": "{zinc-90}",
    "on-surface-variant": "{zinc-30}",
    "surface-tint": "{violet-40}",
    "inverse-surface": "{neutral-20}",
    "inverse-on-surface": "{neutral-95}",
    background: "{neutral-98}",
    "on-background": "{neutral-10}",
    outline: "{zinc-50}",
    "outline-variant": "{zinc-80}",
    shadow: "{neutral-0}",
    scrim: "{neutral-0}",
  },
  modifiers: {
    color: {
      light: {},
      dark: {
        primary: "{violet-80}",
        "on-primary": "{violet-20}",
        "primary-container": "{violet-30}",
        "on-primary-container": "{violet-90}",
        "inverse-primary": "{violet-40}",
        "primary-fixed": "{violet-90}",
        "primary-fixed-dim": "{violet-80}",
        "on-primary-fixed": "{violet-10}",
        "on-primary-fixed-variant": "{violet-30}",
        secondary: "{indigo-80}",
        "on-secondary": "{indigo-20}",
        "secondary-container": "{indigo-30}",
        "on-secondary-container": "{indigo-90}",
        "secondary-fixed": "{indigo-90}",
        "secondary-fixed-dim": "{indigo-80}",
        "on-secondary-fixed": "{indigo-10}",
        "on-secondary-fixed-variant": "{indigo-30}",
        tertiary: "{pink-80}",
        "on-tertiary": "{pink-20}",
        "tertiary-container": "{pink-30}",
        "on-tertiary-container": "{pink-90}",
        "tertiary-fixed": "{pink-90}",
        "tertiary-fixed-dim": "{pink-80}",
        "on-tertiary-fixed": "{pink-10}",
        "on-tertiary-fixed-variant": "{pink-30}",
        error: "{red-80}",
        "on-error": "{red-20}",
        "error-container": "{red-30}",
        "on-error-container": "{red-90}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-90}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-24}",
        "surface-container-lowest": "{neutral-4}",
        "surface-container-low": "{neutral-10}",
        "surface-container": "{neutral-12}",
        "surface-container-high": "{neutral-17}",
        "surface-container-highest": "{neutral-22}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{zinc-80}",
        "surface-tint": "{violet-80}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-20}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        outline: "{zinc-60}",
        "outline-variant": "{zinc-30}",
        shadow: "{neutral-0}",
        scrim: "{neutral-0}",
      },
      "light-medium-contrast": {
        primary: "{violet-22}",
        "primary-container": "{violet-50}",
        "on-primary-container": "{violet-100}",
        secondary: "{indigo-22}",
        "secondary-container": "{indigo-50}",
        "on-secondary-container": "{indigo-100}",
        tertiary: "{pink-22}",
        "tertiary-container": "{pink-50}",
        "on-tertiary-container": "{pink-100}",
        error: "{red-22}",
        "error-container": "{red-50}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-6}",
        "surface-dim": "{neutral-80}",
        "surface-container": "{neutral-92}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-87}",
        "on-surface-variant": "{zinc-22}",
        outline: "{zinc-35}",
        "outline-variant": "{zinc-50}",
      },
      "light-high-contrast": {
        primary: "{violet-17}",
        "primary-container": "{violet-30}",
        "on-primary-container": "{violet-100}",
        secondary: "{indigo-17}",
        "secondary-container": "{indigo-30}",
        "on-secondary-container": "{indigo-100}",
        tertiary: "{pink-17}",
        "tertiary-container": "{pink-30}",
        "on-tertiary-container": "{pink-100}",
        error: "{red-17}",
        "error-container": "{red-30}",
        "on-error-container": "{red-100}",
        "on-surface": "{neutral-0}",
        "surface-dim": "{neutral-80}",
        "surface-container-low": "{neutral-95}",
        "surface-container": "{neutral-90}",
        "surface-container-high": "{neutral-87}",
        "surface-container-highest": "{neutral-80}",
        "inverse-on-surface": "{neutral-100}",
        "on-surface-variant": "{zinc-0}",
        outline: "{zinc-17}",
        "outline-variant": "{zinc-30}",
      },
      "dark-medium-contrast": {
        primary: "{violet-87}",
        "on-primary": "{violet-17}",
        "primary-container": "{violet-60}",
        "on-primary-container": "{violet-0}",
        "inverse-primary": "{violet-30}",
        "primary-fixed": "{violet-90}",
        "primary-fixed-dim": "{violet-80}",
        "on-primary-fixed": "{violet-10}",
        "on-primary-fixed-variant": "{violet-30}",
        "surface-tint": "{violet-80}",
        secondary: "{indigo-87}",
        "on-secondary": "{indigo-17}",
        "secondary-container": "{indigo-60}",
        "on-secondary-container": "{indigo-0}",
        "secondary-fixed": "{indigo-90}",
        "secondary-fixed-dim": "{indigo-80}",
        "on-secondary-fixed": "{indigo-10}",
        "on-secondary-fixed-variant": "{indigo-30}",
        tertiary: "{pink-87}",
        "on-tertiary": "{pink-17}",
        "tertiary-container": "{pink-60}",
        "on-tertiary-container": "{pink-0}",
        "tertiary-fixed": "{pink-90}",
        "tertiary-fixed-dim": "{pink-80}",
        "on-tertiary-fixed": "{pink-10}",
        "on-tertiary-fixed-variant": "{pink-30}",
        error: "{red-87}",
        "on-error": "{red-17}",
        "error-container": "{red-60}",
        "on-error-container": "{red-0}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-30}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-17}",
        "surface-container-high": "{neutral-22}",
        "surface-container-highest": "{neutral-25}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-17}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{zinc-87}",
        outline: "{zinc-70}",
        "outline-variant": "{zinc-60}",
      },
      "dark-high-contrast": {
        primary: "{violet-95}",
        "on-primary": "{violet-0}",
        "primary-container": "{violet-80}",
        "on-primary-container": "{violet-4}",
        "inverse-primary": "{violet-30}",
        "primary-fixed": "{violet-90}",
        "primary-fixed-dim": "{violet-80}",
        "on-primary-fixed": "{violet-10}",
        "on-primary-fixed-variant": "{violet-30}",
        "surface-tint": "{violet-80}",
        secondary: "{indigo-95}",
        "on-secondary": "{indigo-0}",
        "secondary-container": "{indigo-80}",
        "on-secondary-container": "{indigo-4}",
        "secondary-fixed": "{indigo-90}",
        "secondary-fixed-dim": "{indigo-80}",
        "on-secondary-fixed": "{indigo-10}",
        "on-secondary-fixed-variant": "{indigo-30}",
        tertiary: "{pink-95}",
        "on-tertiary": "{pink-0}",
        "tertiary-container": "{pink-80}",
        "on-tertiary-container": "{pink-4}",
        "tertiary-fixed": "{pink-90}",
        "tertiary-fixed-dim": "{pink-80}",
        "on-tertiary-fixed": "{pink-10}",
        "on-tertiary-fixed-variant": "{pink-30}",
        error: "{red-95}",
        "on-error": "{red-0}",
        "error-container": "{red-80}",
        "on-error-container": "{red-4}",
        surface: "{neutral-6}",
        "on-surface": "{neutral-100}",
        "surface-dim": "{neutral-6}",
        "surface-bright": "{neutral-35}",
        "surface-container-lowest": "{neutral-0}",
        "surface-container-low": "{neutral-12}",
        "surface-container": "{neutral-20}",
        "surface-container-high": "{neutral-25}",
        "surface-container-highest": "{neutral-30}",
        "inverse-surface": "{neutral-90}",
        "inverse-on-surface": "{neutral-0}",
        background: "{neutral-6}",
        "on-background": "{neutral-90}",
        "surface-variant": "{zinc-30}",
        "on-surface-variant": "{zinc-100}",
        outline: "{zinc-95}",
        "outline-variant": "{zinc-80}",
      },
    },
  },
  order: ["color"],
});

export default preset;
