/**
 * Regenerates server/aurora/files.ts from @untheme/aurora's theme manifest and
 * folders: per theme, one lazy `import()` per file, each by its package path,
 * so the app's server bundler sees every file and loads one only when its
 * theme is requested. Run with `pnpm generate:themes`, then `pnpm format` from the repo root.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join, relative, sep } from "node:path";

const require = createRequire(import.meta.url);
const index = require.resolve("@untheme/aurora/themes/index.json");
const themes = dirname(index);
const manifest = JSON.parse(await readFile(index, "utf8"));

/** Every file under a theme folder, as sorted posix paths relative to it. */
const files = async (folder) => {
  const entries = await readdir(folder, {
    recursive: true,
    withFileTypes: true,
  });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
    .map((entry) => relative(folder, join(entry.parentPath, entry.name)))
    .map((path) => path.split(sep).join("/"))
    .sort();
};

const lines = [];
for (const { id } of manifest) {
  lines.push(`  ${JSON.stringify(id)}: {`);
  for (const path of await files(join(themes, id))) {
    const specifier = `@untheme/aurora/themes/${id}/${path}`;
    lines.push(
      `    ${JSON.stringify(path)}: () => import(${JSON.stringify(specifier)}, { with: { type: "json" } }),`,
    );
  }
  lines.push("  },");
}

await writeFile(
  new URL("../server/aurora/files.ts", import.meta.url),
  [
    "/**",
    " * Every aurora theme file, by theme id and path inside the theme's folder.",
    " * Generated by scripts/aurora.mjs from @untheme/aurora's theme manifest and",
    " * folders; regenerate with `pnpm generate:themes`, do not edit by hand.",
    " *",
    " * One lazy `import()` per file, each by its package path, so the app's",
    " * server bundler sees every file and loads one only when it is requested.",
    " */",
    'import type { Loader } from "./types";',
    "",
    "export const files: Record<string, Record<string, Loader>> = {",
    ...lines,
    "};",
    "",
  ].join("\n"),
);

console.log(`generated server/aurora/files.ts (${manifest.length} themes)`);
