import { describe, expect, it } from "vitest";

import { emit } from "../src/emit";

describe("emit", () => {
  it("renders a deterministic, importable configuration module", () => {
    const contents = emit(
      {
        theme: {
          id: "fixture",
          name: "Fixture",
          tokens: {
            "color.primary": {
              $type: "color",
              $value: {
                colorSpace: "srgb",
                components: [0, 0.5, 1],
                alpha: 1,
                hex: "#0080ff",
              },
            },
            "color.surface": { $type: "color", $value: "{color.primary}" },
          },
          modifiers: {
            color: {
              light: {},
              dark: { "color.surface": "{color.primary}" },
            },
          },
          order: ["color"],
        },
        themes: {
          ocean: { id: "ocean", name: "Ocean" },
        },
        input: { color: "light" },
      },
      "file:///tokens/resolver.json",
    );
    expect(contents).toBe(
      [
        "/**",
        " * Generated by @untheme/terrazzo from file:///tokens/resolver.json.",
        " * Do not edit by hand — regenerate from the token sources.",
        " */",
        `import type { Layer } from "untheme";`,
        "",
        `import { defineUnthemeConfig } from "untheme/config";`,
        "",
        "const config = defineUnthemeConfig({",
        "  theme: {",
        `    id: "fixture",`,
        `    name: "Fixture",`,
        "    tokens: {",
        `      "color.primary": {`,
        `        $type: "color",`,
        "        $value: {",
        `          colorSpace: "srgb",`,
        "          components: [",
        "            0,",
        "            0.5,",
        "            1,",
        "          ],",
        "          alpha: 1,",
        `          hex: "#0080ff",`,
        "        },",
        "      },",
        `      "color.surface": {`,
        `        $type: "color",`,
        `        $value: "{color.primary}",`,
        "      },",
        "    },",
        "    modifiers: {",
        "      color: {",
        "        light: {},",
        "        dark: {",
        `          "color.surface": "{color.primary}",`,
        "        },",
        "      },",
        "    },",
        "    order: [",
        `      "color",`,
        "    ],",
        "  },",
        "  input: {",
        `    color: "light",`,
        "  },",
        "});",
        "",
        "export const themes = {",
        "  ocean: {",
        `    id: "ocean",`,
        `    name: "Ocean",`,
        "  },",
        "} satisfies Record<",
        "  string,",
        "  Layer<typeof config.theme>",
        ">;",
        "",
        "export default config;",
        "",
      ].join("\n"),
    );
  });
});
