import preset from "../preset";
import { createM2ColorTokens } from "../colors";

/**
 * Ayu theme — M2 token variant.
 */
export default preset.define({
  id: "ayu",
  name: "Ayu",
  reference: {
    ...createM2ColorTokens("red", "#f07178"),
    ...createM2ColorTokens("orange", "#ff8f40"),
    ...createM2ColorTokens("amber", "#e6b450"),
    ...createM2ColorTokens("yellow", "#ffb454"),
    ...createM2ColorTokens("lime", "#aad94c"),
    ...createM2ColorTokens("green", "#aad94c"),
    ...createM2ColorTokens("emerald", "#95e6cb"),
    ...createM2ColorTokens("teal", "#95e6cb"),
    ...createM2ColorTokens("cyan", "#39bae6"),
    ...createM2ColorTokens("sky", "#59c2ff"),
    ...createM2ColorTokens("blue", "#59c2ff"),
    ...createM2ColorTokens("indigo", "#39bae6"),
    ...createM2ColorTokens("violet", "#d2a6ff"),
    ...createM2ColorTokens("purple", "#d2a6ff"),
    ...createM2ColorTokens("fuchsia", "#f29668"),
    ...createM2ColorTokens("pink", "#f07178"),
    ...createM2ColorTokens("rose", "#f07178"),
    ...createM2ColorTokens("slate", "#5a6673"),
    ...createM2ColorTokens("gray", "#5a6673"),
    ...createM2ColorTokens("zinc", "#404953"),
    ...createM2ColorTokens("neutral", "#0b0e14"),
    ...createM2ColorTokens("stone", "#667381"),
  },
  system: {
    light: {
      primary: "orange-500",
      "primary-variant": "orange-700",
      "on-primary": "neutral-50",
      secondary: "blue-500",
      "secondary-variant": "blue-700",
      "on-secondary": "neutral-50",
      background: "neutral-50",
      "on-background": "neutral-900",
      surface: "neutral-50",
      "on-surface": "neutral-900",
      error: "red-500",
      "on-error": "neutral-50",
    },
    dark: {
      primary: "orange-200",
      "primary-variant": "orange-700",
      "on-primary": "neutral-900",
      secondary: "blue-200",
      "secondary-variant": "blue-200",
      "on-secondary": "neutral-900",
      background: "neutral-900",
      "on-background": "neutral-50",
      surface: "neutral-900",
      "on-surface": "neutral-50",
      error: "red-200",
      "on-error": "neutral-900",
    },
  },
  roles: {},
});
