import preset from "../preset";
import { createM2ColorTokens } from "../colors";

/**
 * Dracula theme — M2 token variant.
 */
export default preset.define({
  id: "dracula",
  name: "Dracula",
  reference: {
    ...createM2ColorTokens("red", "#FF5555"),
    ...createM2ColorTokens("orange", "#FFB86C"),
    ...createM2ColorTokens("amber", "#FFB86C"),
    ...createM2ColorTokens("yellow", "#F1FA8C"),
    ...createM2ColorTokens("lime", "#50FA7B"),
    ...createM2ColorTokens("green", "#50FA7B"),
    ...createM2ColorTokens("emerald", "#50FA7B"),
    ...createM2ColorTokens("teal", "#8BE9FD"),
    ...createM2ColorTokens("cyan", "#8BE9FD"),
    ...createM2ColorTokens("sky", "#8BE9FD"),
    ...createM2ColorTokens("blue", "#6272A4"),
    ...createM2ColorTokens("indigo", "#6272A4"),
    ...createM2ColorTokens("violet", "#BD93F9"),
    ...createM2ColorTokens("purple", "#BD93F9"),
    ...createM2ColorTokens("fuchsia", "#FF79C6"),
    ...createM2ColorTokens("pink", "#FF79C6"),
    ...createM2ColorTokens("rose", "#FF5555"),
    ...createM2ColorTokens("slate", "#44475A"),
    ...createM2ColorTokens("gray", "#44475A"),
    ...createM2ColorTokens("zinc", "#6272A4"),
    ...createM2ColorTokens("neutral", "#282A36"),
    ...createM2ColorTokens("stone", "#44475A"),
  },
  system: {
    light: {
      primary: "violet-500",
      "primary-variant": "violet-700",
      "on-primary": "neutral-50",
      secondary: "pink-500",
      "secondary-variant": "pink-700",
      "on-secondary": "neutral-50",
      background: "neutral-50",
      "on-background": "neutral-900",
      surface: "neutral-50",
      "on-surface": "neutral-900",
      error: "red-500",
      "on-error": "neutral-50",
    },
    dark: {
      primary: "violet-200",
      "primary-variant": "violet-700",
      "on-primary": "neutral-900",
      secondary: "pink-200",
      "secondary-variant": "pink-200",
      "on-secondary": "neutral-900",
      background: "neutral-900",
      "on-background": "neutral-50",
      surface: "neutral-900",
      "on-surface": "neutral-50",
      error: "red-200",
      "on-error": "neutral-900",
    },
  },
  roles: {},
});
