import preset from "../preset";
import { createM2ColorTokens } from "../colors";

/**
 * Monokai theme — M2 token variant.
 */
export default preset.define({
  id: "monokai",
  name: "Monokai",
  reference: {
    ...createM2ColorTokens("red", "#F92672"),
    ...createM2ColorTokens("orange", "#FD971F"),
    ...createM2ColorTokens("amber", "#E6DB74"),
    ...createM2ColorTokens("yellow", "#E6DB74"),
    ...createM2ColorTokens("lime", "#A6E22E"),
    ...createM2ColorTokens("green", "#A6E22E"),
    ...createM2ColorTokens("emerald", "#A1EFE4"),
    ...createM2ColorTokens("teal", "#A1EFE4"),
    ...createM2ColorTokens("cyan", "#66D9EF"),
    ...createM2ColorTokens("sky", "#66D9EF"),
    ...createM2ColorTokens("blue", "#66D9EF"),
    ...createM2ColorTokens("indigo", "#6A7EC8"),
    ...createM2ColorTokens("violet", "#AE81FF"),
    ...createM2ColorTokens("purple", "#AE81FF"),
    ...createM2ColorTokens("fuchsia", "#F92672"),
    ...createM2ColorTokens("pink", "#F92672"),
    ...createM2ColorTokens("rose", "#F92672"),
    ...createM2ColorTokens("slate", "#75715E"),
    ...createM2ColorTokens("gray", "#75715E"),
    ...createM2ColorTokens("zinc", "#49483E"),
    ...createM2ColorTokens("neutral", "#272822"),
    ...createM2ColorTokens("stone", "#90908A"),
  },
  system: {
    light: {
      primary: "pink-500",
      "primary-variant": "pink-700",
      "on-primary": "neutral-50",
      secondary: "cyan-500",
      "secondary-variant": "cyan-700",
      "on-secondary": "neutral-50",
      background: "neutral-50",
      "on-background": "neutral-900",
      surface: "neutral-50",
      "on-surface": "neutral-900",
      error: "red-500",
      "on-error": "neutral-50",
    },
    dark: {
      primary: "pink-200",
      "primary-variant": "pink-700",
      "on-primary": "neutral-900",
      secondary: "cyan-200",
      "secondary-variant": "cyan-200",
      "on-secondary": "neutral-900",
      background: "neutral-900",
      "on-background": "neutral-50",
      surface: "neutral-900",
      "on-surface": "neutral-50",
      error: "red-200",
      "on-error": "neutral-900",
    },
  },
  roles: {},
});
