import preset from "../preset";
import { createM2ColorTokens } from "../colors";

/**
 * One Dark theme — M2 token variant.
 */
export default preset.define({
  id: "one_dark",
  name: "One Dark",
  reference: {
    ...createM2ColorTokens("red", "#e06c75"),
    ...createM2ColorTokens("orange", "#d19a66"),
    ...createM2ColorTokens("amber", "#e5c07b"),
    ...createM2ColorTokens("yellow", "#e5c07b"),
    ...createM2ColorTokens("lime", "#98c379"),
    ...createM2ColorTokens("green", "#98c379"),
    ...createM2ColorTokens("emerald", "#56b6c2"),
    ...createM2ColorTokens("teal", "#56b6c2"),
    ...createM2ColorTokens("cyan", "#56b6c2"),
    ...createM2ColorTokens("sky", "#61afef"),
    ...createM2ColorTokens("blue", "#61afef"),
    ...createM2ColorTokens("indigo", "#528bff"),
    ...createM2ColorTokens("violet", "#c678dd"),
    ...createM2ColorTokens("purple", "#c678dd"),
    ...createM2ColorTokens("fuchsia", "#c678dd"),
    ...createM2ColorTokens("pink", "#e06c75"),
    ...createM2ColorTokens("rose", "#be5046"),
    ...createM2ColorTokens("slate", "#5c6370"),
    ...createM2ColorTokens("gray", "#4b5263"),
    ...createM2ColorTokens("zinc", "#5c6370"),
    ...createM2ColorTokens("neutral", "#282c34"),
    ...createM2ColorTokens("stone", "#828997"),
  },
  system: {
    light: {
      primary: "blue-500",
      "primary-variant": "blue-700",
      "on-primary": "neutral-50",
      secondary: "violet-500",
      "secondary-variant": "violet-700",
      "on-secondary": "neutral-50",
      background: "neutral-50",
      "on-background": "neutral-900",
      surface: "neutral-50",
      "on-surface": "neutral-900",
      error: "red-500",
      "on-error": "neutral-50",
    },
    dark: {
      primary: "blue-200",
      "primary-variant": "blue-700",
      "on-primary": "neutral-900",
      secondary: "violet-200",
      "secondary-variant": "violet-200",
      "on-secondary": "neutral-900",
      background: "neutral-900",
      "on-background": "neutral-50",
      surface: "neutral-900",
      "on-surface": "neutral-50",
      error: "red-200",
      "on-error": "neutral-900",
    },
  },
  roles: {},
});
